### ISSUE TITLE
Const empty list returned for null DataType Lists

### ISSUE THREAD

**Issue by BrentM** [FlutterFlow/flutterflow-issues#1038]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This code is generated for a DateTime List in a FlutterFlow DataType:

```
    // "lastCheckedHistory" field.
    List<DateTime>? _lastCheckedHistory;
    List<DateTime> get lastCheckedHistory => _lastCheckedHistory ?? const []; // <<<< This shouldn't be a constant
    set lastCheckedHistory(List<DateTime>? val) => _lastCheckedHistory = val;
    void updateLastCheckedHistory(Function(List<DateTime>) updateFn) =>
        updateFn(_lastCheckedHistory ??= []);
    bool hasLastCheckedHistory() => _lastCheckedHistory != null;
```

When the field is read from Firebase, it returns an editable list but when Firebase returns null the getter gives a non editable list. This is very confusing and made worse by the getter not letting the user use their own null handling. Checking the "has" method works but isn't very idiomatic.

### Expected Behavior

The simple solution is to return a <T>[] instead of a constant empty list. It also might be good to just have the return on the field getter be nullable so the user can apply their own defaults. 

### Steps to Reproduce

1. Create a Datatype
2. include that datatype as a list field in a Collection
3. Use the field in a Custom function when the Firebase field is Null
5. Call the add List Method or otherwise try to modify the list. This will compile successfully but will fail silently (only an error on the console) in the Test environment when the custom function is called.

I'm not sure if this is reproduceable in the FF GUI but the inconsistency between a mutable empty list in the DB and the empty list constant given as a default for a null value is bound to cause problems at some point.

Reproducing this does NOT require a blank project but I can't seem to submit the issue without checking that box.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ol+fl2ItNtbxb+Kr+asFKpyQUC0wkaI0N18pBTTwYCIz0P+wMecjTflJvOdeHT2x2JVv9q3MJp9rTk+PPCuQHAASWG49xyblTEDzyQT67VYyVEKqSWHFDHZtVJEuV05mruiRDJuxZWF4k3U2YOOiRVg/dQ77tDTABBsiaNprVjE7hAi+6Xn0Jg1ZSfCvr

### Context

I'm modifying a list of DateTimes in a Datatype to timestamp when the user checks a field. The Action builder doesn't seem to let me edit a given list element so I'm doing this in Custom Functions.

I have a workaround in my project. Once I understood that the getter was giving an empty list constant I just made a mutable copy to work with.

### Visual documentation

This is an issue with Custom Functions and how they interact with List fields in DataTypes.
![Screenshot 2023-06-23 171450](https://github.com/FlutterFlow/flutterflow-issues/assets/952240/e511c1e8-af05-4116-acd9-7adc14dbd94e)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: All
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by agreaves** [comment]
Hey @BrentM! Thanks for submitting this bug report.

This is actually a rather tricky one, and when evaluating the pros and cons we definitely considered the issue you brought up before deciding on the current solution. We don't plan on updating this for the time being but I'll explain the reasoning behind it.

**Why Not Null**: Keeping the getter null, as you mentioned, is my next favorite option because everything works as expected when writing custom code (no surprises). However, it adds some significant complexity using it in the UI Builder (and even some when coding) because you now have to worry about null vs empty lists and iterating it becomes much more complicated (having to use conditional with the "Has Field" condition). So the logic here is to optimize for the (large) majority of use cases and assume that users using custom code will understand how to work with it (as you did).

**The _const_ issue**: There are a couple issues that require the default list to be `const`. The first, is that if it isn't, then the caller is accessing and modifying a list `[]` that isn't actually tied to the field: i.e. `List<DateTime> get lastCheckedHistory => _lastCheckedHistory ?? [];` would return an empty list instead of the `_lastCheckedHistory` field. To fix this, we return a `const []` to ensure that it is read-only and cannot be modified. If null, the field can still be set by setting it directly.

**Why not assign**: The only solution to the above is doing `List<DateTime> get lastCheckedHistory => _lastCheckedHistory ??= [];` instead, so that `lastCheckedHistory` is assigned in the process, so when you modify the list that is returned it's _actually_ updating the field. Unfortunately, this would mean that just by reading the field, we're modifying the `DataStruct`, which is undesirable. For example, `hasLastCheckedHistory()` would initially return `false` but `true` after simply reading the `lastCheckedHistory` field.

So unfortunately every solution is imperfect and has trade-offs, and we've gone with one that at least throws an error to alert the user (and doesn't fail silently), and only affects developers who are hopefully well equipped to work with it (like yourself).

Hope that explanation helps! Closing the issue for now (per our policy) but I'm happy to continue the thread and hear any ideas you may have, we're always happy to improve our custom code! 😁

**Comment by BrentM** [comment]
Now that you walk through the tradeoffs, this seems like the best of the imperfect solutions. Hopefully this discussion will help other people who are running into this. It's more a challenge of expectations not lining up with the implementation and this is a subtle issue. Once I figured out what was happening it was an easy fix. Thanks!
