### ISSUE TITLE
Manage content -->  provide horizontal scroll

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#106]
Flutterflow --> Open project --> Firebase --> Select collection --> Manage content --> 
https://app.flutterflow.io/cms/.......

30 fields in the document. 
Can see many fields on the right side. 

Had to reduce the chrome browser Zoom to 30% to view all fields. But that makes field names unreadable. 

Please provide a horizontal scroll to view all fields.

**Comment by hariprasadms** [comment]
Hi @palmdeskApp - Sorry for changing bug status. It's my keyboard keys jumping. 
I just checked this issue in my mac chrome browser, I can see that horizontal scroll is available when there are more fields in right side.

Can you please follow bugs template to add more details to this issue please. You can refer other issues as well. Once added all the details we can look into this issue. Thanks

**Comment by katherineqian** [comment]
Hi @palmdeskApp, 

Just to add on to @hariprasadms 's comment, we appreciate your bug submissions on the issue tracker and are happy to look into these issues. However, please follow the bug report template when you submit them (for this and other issues) so that our team has enough information investigate them. This is very important for us and we ask this of all users.

In case you were not able to find the template, I have included it here. Please edit your original submission to follow the template. Thank you very much!

# Issue Template
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.


## Expected behavior (required)
A clear and concise description of what you expected to happen.


## Current behavior (required)
What happens instead of the expected behavior.


## To Reproduce (required)
Please be detailed as possible here so we can help diagnose the issue. Issues cannot be accepted if they are too vague. For example, "project fails to build" could be better reported as: 
1. Create new page
2. Add container widget
3. Set width = 123
4. Click Run
5. Observe that project doesn’t build

Code can be included in this section if it is relevant to reproducing the bug. 

## Context (required)
How has this issue affected you? What are you trying to accomplish?


## Screenshots / recordings
If applicable, add screenshots to help explain your problem.

## Your environment
Include relevant details about the environment you experienced the bug in
* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by katherineqian** [comment]
This particular issue is actually not a bug: You should currently be able to scroll horizontally with a trackpad, or by holding the Shift key while scrolling if you are using a mouse. 

However, since other users have reported this as a problem too, we have added a bottom scrollbar and click-and-drag for horizontal scrolling on the Content Manager page. You should see an update to this in the app soon. 

Thanks for the report!

**Comment by luvlylavnder** [comment]
I was able to find this and figure out how to scroll but it would be way more intuitive to have a horizontal scrollbar. I see this was reported in 2022 and its now 2025. I realize that its not a bug but at least it would be nice if you would include a note somewhere on the page telling you how to scroll if there is no scroll bar.
