### ISSUE TITLE
Firestore Security Rule Mismatch FF Configuration

### ISSUE THREAD

**Issue by kawofong** [FlutterFlow/flutterflow-issues#1061]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, I have 1 collection `chat` and a subcollection `message` . For some reason, when I tried to redeploy the security rule, the `message` security rule doesn't obey what I have defined in FF.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/14829553/769248ae-0e44-470b-a4cf-d81e232cf28d)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/14829553/d6ac528d-df81-4c0a-b04c-aa04fc265f40)

### Expected Behavior

The security rule defined for `chats` collection should be the same as the security rule defined for `message` subcollection.

### Steps to Reproduce

I have not tried reproducing this issue in another project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Skufl0It2obgA+Kr9bcJR/ToUNkx/RYI3lOtqEBUcGJTqE4YDXOjASEhVXd+/TAl2Ilv8mmMypt7Vhob1GuQHAzGWf4hbyalqFAyWRnmQMIiLPs+OS2h7ONJWHkuV3MGZgBNBJupeS0Ig3zqmf9nKaADtJu/wOFU7M/GYBKnU+HiZAj+6Xn0Jg1ZSfCvr

### Context

Due to this error, I have to configured the Firestore security rule in Firebase, outside of FlutterFlow.

### Visual documentation

See current behavior

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Chrome Version 114.0.5735.133 (Official Build) (arm64)
- Operating system and version affected: MacOS 13.4
```

**Comment by victoriahuang1** [comment]
Hi @kawofong , I took a look and this is actually the expected behavior.

You will see that the `chats/{parent}/message/{document}` rules are what you defined.

In addition, we have the `/{path=**}/message/{document}` rule for the `message` subcollection, which has the same _read_ rules. This is purposefully there, and doesn't conflict with the other rules. It's needed for certain query patterns.

**Comment by flutterflowdevs** [comment]
@victoriahuang1 I think you have misunderstood the issue. 
Actually, the Issue is :
Rules are present in the flutterflow panel properly but when we deployed to Firebase the same rules were not reflected.
Please find the image below 
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/126557523/6ebddc4a-e604-45de-a7bf-7608f56e9c85)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/126557523/cd9fee47-4587-40f9-af39-0b724449514d)

**Comment by bulgariamitko** [comment]
@flutterflowdevs are you sure the rules are deployed?

**Comment by flutterflowdevs** [comment]
@bulgariamitko 
I have deployed multiple time even waited for 10 min but still result is same.

**Comment by bulgariamitko** [comment]
@flutterflowdevs  can you try to reproduce this in a brand new project?

**Comment by flutterflowdevs** [comment]
@bulgariamitko Let me try with new project and get back to for the same.
