### ISSUE TITLE
Tutorial step 4 doesn't work - cannot add Action

### ISSUE THREAD

**Issue by leecarlcooper** [FlutterFlow/flutterflow-issues#1085]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Cannot add action (to navigate to HomePage) in FlutterFlow MacOS v1.1.88 tutorial (step 4). Add action just shows a gray screen.

### Expected Behavior

Should have options for types of actions to add.

### Steps to Reproduce

1. follow the "build app in 5" tutorial and issue occurs in step 4/5.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8jfz812ofpE7aX6bu9agjgsG2Y5R600ttx+bw4bJJCvOpYUec/6P1JDTbDgSlVcJFmmp14dwMqOjvPpD+w3PQ2BRohg1KtUdjvwIT6WaY+TF7u8eHd8Ae9hBWKCyJ2nuR1SNftZL1IBwGaleti+YDLbJJDRCmowSq/LZO4=

### Context

Trying to complete the in-app tutorial

### Visual documentation

<img width="1894" alt="Screenshot 2023-07-07 at 11 58 50 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/8968430/89c698ff-dfb7-4baa-b277-c3421f69d76e">

### Environment

```markdown
- FlutterFlow version: v.1.1.88
- Platform: MacOS
- Browser name and version: (desktop version)
- Operating system and version affected: Ventura 13.4.1 (MacOS)
```

**Comment by hariprasadms** [comment]
Hi @leecarlcooper - Thanks for posting the issue. I can re-produce the issue. Thanks 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/6112429a-e4ee-4a78-91cc-2e60946db761

**Comment by paiameya** [comment]
I have copied the content from issue creator.
**Current Behavior**
Cannot add action (to navigate to HomePage) in FlutterFlow web version ( Chrome browser ) tutorial (step 4). Add action just shows a gray screen.

**Expected Behavior**
Should have options for types of actions to add.

**Steps to Reproduce**
follow the "build app in 5" tutorial and issue occurs in step 4/5.
Reproducible from Blank
 The steps to reproduce above start from a blank project.

**Context**
Trying to complete the in-app tutorial


**Visual documentation**
<img width="1439" alt="Screenshot 2023-07-17 at 8 56 17 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/55129904/fe6a098c-bee1-4b64-b206-c20977e0dbaf">

**Environment**
- FlutterFlow version: v.3.1
- Platform: MacOS
- Browser name and version: Chrome v114.0.5735.198
- Operating system and version affected: Monterey 12.6 (MacOS)

**Comment by MrReid1** [comment]
Anyone has find a fix for this? It still throws me errors upon creating actions for my pages.
