### ISSUE TITLE
Supabase Sign In

### ISSUE THREAD

**Issue by ndigacin** [FlutterFlow/flutterflow-issues#1161]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a user logs in, instead of taking the user to the logged in page, it sends the user to the entry page.

It does not take the user to the landing page. It behaves as if the log in is not successful.

### Expected Behavior

I expect the user to be sent to the logged in page after sign in

### Steps to Reproduce

Sign in using Supabase authentication

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESiMrq7YlgruIE+6rQcO16hQAkH1x/bZJEl9caRQgYfYz2EZoLPOr+VHFtTbCrd1VcBFql+Dkx3NrXifGWMPUFFy6eUoNoz5ZyWzn/Wl2uMpCqPpCKdH8nPNNWN26F0J2vrxFCHMdZZXAtw2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

This issue prevents me from publishing my app. Without a functionning authentication, the app is useless.

### Visual documentation

![Screenshot 2023-07-25 at 3 08 04 AM 1](https://github.com/FlutterFlow/flutterflow-issues/assets/116641569/02d8087d-1407-4bfa-893b-cd961d60c81b)

### Environment

```markdown
- FlutterFlow version: Most recent version
- Platform: Microsoft Edge, Desktop Beta Stand alone FF app
- Browser name and version:Microsoft Edge
- Operating system and version affected: Most recent
```

**Comment by sbis04** [comment]
Hey @ndigacin, thanks for reporting the issue! This looks like it's because of the way we handle authentication inside FlutterFlow.

It seems like you are trying to authenticate the user from the `cLogin` page but the entry page is set to `eBoardingPage`:

![Screenshot 2023-07-25 at 1 41 19 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/fc220980-2dc3-4ab5-adcd-4216f8d7b415)

We assume the login to be actually from the "Entry Page", but it looks like it's a different page for your use case. The easiest way to go around this issue is to convert the `cLogin` page to a component. Then inside the `eBoardingPage` wrap the page with a Stack widget and add the component. Now, instead of navigating to a different page when `Login` button is clicked, you can use a page variable to control the visibility of the component (using Conditional Visibility). Alternatively, it should also be possible to achieve this using the `ConditionalBuilder` widget.

We'll see if there's a way to improve our user authentication flow (or if the navigation issue can be solved), but for now this should be a good workaround!

**Comment by ndigacin** [comment]
Thx for replying @sbis04 . But I don’t think what you explain is the actual problem because I deployed the app dozens of times with the current setting and I never had any issue. The issue suddenly starts yesterday for no apparent reason. I also put the login page as entry page and it still didn’t solve the issue. I add navigation action after the sign in action, still the same issue. 

The workaround you suggest is very complicated for my limited knowledge with this software.

**Comment by MrRongoose** [comment]
Following here are this is newly occurring in my projects as well using Firebase Authentication. Using both Email and Google

**Comment by MrRongoose** [comment]
> Hey @ndigacin, thanks for reporting the issue! This looks like it's because of the way we handle authentication inside FlutterFlow.
> 
> It seems like you are trying to authenticate the user from the `cLogin` page but the entry page is set to `eBoardingPage`:
> 
> ![Screenshot 2023-07-25 at 1 41 19 PM](https://user-images.githubusercontent.com/43280874/255838547-fc220980-2dc3-4ab5-adcd-4216f8d7b415.png)
> 
> We assume the login to be actually from the "Entry Page", but it looks like it's a different page for your use case. The easiest way to go around this issue is to convert the `cLogin` page to a component. Then inside the `eBoardingPage` wrap the page with a Stack widget and add the component. Now, instead of navigating to a different page when `Login` button is clicked, you can use a page variable to control the visibility of the component (using Conditional Visibility). Alternatively, it should also be possible to achieve this using the `ConditionalBuilder` widget.
> 
> We'll see if there's a way to improve our user authentication flow (or if the navigation issue can be solved), but for now this should be a good workaround!

I'm using Firebase Auth. This workaround did not work for me. Login is done via Google or Email on Main Entry page but it doesn't forward to the Logged in Page. I know the auth is successful because if I manually navigate to a page in my app after logging in, it loads fine. If I hadn't logged in, it kicks me back to entry page

**Comment by MrRongoose** [comment]
This began working for me again as of very early this morning. Maybe today's update had it fixed already

**Comment by sbis04** [comment]
Yup, we did a couple of updates to Supabase! Thanks for letting me know that it's fixed for you!
