### ISSUE TITLE
New action Update email don't work

### ISSUE THREAD

**Issue by Perlo34** [FlutterFlow/flutterflow-issues#1162]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The new action to update email with firebase don't work

### Expected Behavior

I want to update the email of my user

### Steps to Reproduce

1. Create page
2. Enable firebase and auth
3. Add user to firebase
4. Add textfield and button to page 
5. Add action on button to edit email 
6. Choose textfield to new email
7. Test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OlMjf35dOpbxA+Kr9bfpV+TgXOWY1U4ZMitZxSko0fZfNGu4MPsneVFRuZrymdEFif1qZkmUK7PfqkvLhVO5fIS6sGd1E/7tqeALJTj6tM5CJBYeRfW1QGd5gGUCF1sK32hUlXeluSCxk2EyuefPLcB3DGb37OVY/PPK1KdeK2SrDX1iXc2URm05KZDPz

### Context

I want to update the email of my user directly in the app

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/136898815/8595f0c7-d5db-49e3-8b9a-4b5eef5a5ebd

### Additional Info

sorrry i need to post this quickly, so the description is short

### Environment

```markdown
- FlutterFlow version: 3.1 20 july
- Platform:web
- Browser name and version: brave 1.54
- Operating system and version affected: windows 11
```

**Comment by hariprasadms** [comment]
Hi @Perlo34 - Thanks for reporting the issue. You are checking the email update at firebase authentication. But updated email can change in authentication section after you logout and login to the app. It's because while updating authenticated user details through document reference, it is changed at document level but not at logged in user level. So logout and login and check your can see newly updated email listed in authentication section.

**Comment by Perlo34** [comment]
I found my error: I didn't think that the action directly modified the document, so I had also added an action modifying the document, so the update was only done at the document level.

**Comment by hariprasadms** [comment]
Thats great. I presume issue is resolved now. If so, please close the issue. Thanks

**Comment by Hitisha14** [comment]
Hi @Perlo34 , can you let me know how you have solved the issue ?

**Comment by sabatage3** [comment]
This doesn't work, I added an action to update the document after the update email action, then logged out and tried to log in again, but it won't let me log in since the authentication email is not updated, only in the document

**Comment by victoriahuang1** [comment]
@sabatage3 your issue may be related to #1588 , which is due to a breaking change from Firebase: https://stackoverflow.com/questions/77147854/firebase-please-verify-the-new-email-before-changing-email-auth-operation-not

**Comment by sabatage3** [comment]
> @sabatage3 your issue may be related to #1588 , which is due to a breaking change from Firebase: https://stackoverflow.com/questions/77147854/firebase-please-verify-the-new-email-before-changing-email-auth-operation-not

Thank you, I'll give it a try

**Comment by DhruvalGolakiya** [comment]
I'm getting same issue on click UpdateEmail with set updateEmail action I'm getting 400 error in console of identity error

" https://identitytoolkit.googleapis.com/v1/accounts:update?key=xxxx" POST 400 error

**Comment by Ryujinie** [comment]
Hi, I have the same issue, auth update email is not updating email field in authenticated users, just in my useraccount document, how to fix this?

**Comment by Diabelangelo** [comment]
I am facing same issue,above login and log out works however it's not a desired result,can you suggest something to solve the error rather than a walk around

**Comment by iGrits** [comment]
For others who might be facing this issue, here is how I resolved it. 

I had 2 actions:
1) Auth - Update Email
2) Backend Call - Update Document

I had both of these because I thought that was the logical thing to do. One action to update the actual auth email and another to update the user document.  Turns out, if you have the 'Update Document' one, that will make the 'Auth - Update Email' not work.  So just delete that action and only call the 'Auth - Update Email', it will then work and update in both spots!

FYI - In relation to the email enumeration, I have mine enabled in Firebase with the above working.
