### ISSUE TITLE
The filters cause the infinite scroll to bug in grid view

### ISSUE THREAD

**Issue by rayane69-crypto** [FlutterFlow/flutterflow-issues#1185]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I reported to the support team this bug, they told me to put it here. In a gridview with infinite scroll, when I filter the backend query, it loads, for example, the first 5 items, and then it gets stuck like that. 

![Capturepng](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/2d1ea5de-5b5d-4fae-85a9-f87d873bb2a8)
![Capture2](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/5de62e1a-0413-4fcd-a7df-efa484fd262b)

However, if I remove the filter, it continues to load, and the infinite scroll works fine.

### Expected Behavior

The infinite scroll works with filters in grid view, and I haven't tested the other widgets

### Steps to Reproduce

1- Create a new page.
2-Add a grid view.
3- Place an element inside the grid view.
4- Implement a backend query with infinite scroll and filter, for example, by quantity, and set the page size to 5 elements. The 5- backend query should return 10 elements initially, so it loads the other 5.
6- Test it, and you will notice a bug. "The cause of the problem is the filter. If you remove the filter, it works normally."

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ojcmB25NIxLVE7arqbcJV+CQ4JUh6aJ0zm8pBZzAaIrb1CLMqY8mnP1JuTuG+SghpMWGMp14ypvTIjYXpL/QENRaZGrZSz6lqSwyVfFO5MpeTF7mKXEZBGd5WJnWBy7WruyN4FNdfWEIj3GeIIe6yShbXQ++yOFQ8Sq/LZO4=

### Context

I'm trying to filter the data when it's requested, instead of fetching all the data, which could result in a huge amount of reading for Firestore.

### Visual documentation

link to the video 
https://www.veed.io/view/ec0ba92d-2245-4d88-8440-7f2bf5c145f5?panel=share

### Environment

```markdown
- FlutterFlow version: v3.1 (released July 27, 2023)
- Platform: MacOS
- Browser name and version: 115.0.5790.114
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by rayane69-crypto** [comment]
????

**Comment by kevintonb** [comment]
Hey @rayane69-crypto , I have tried to replicate the issue that you've mentioned following the reproducible steps that are outlined and was unable to do so. The Backend query in a GridView with filters works perfectly fine for me with or without infinite scroll. Can you please check if you have added all the necessary steps required to reproduce the issue? We also couldn't find any potential issues with the project that you've shared using the bug report code. Kindly add any additional steps or the bug report code with the issue visible along in this thread so that we can investigate this further. Or if you feel that this could be a project specific issue, please also feel free to share the bug report code of the project in which you're facing this issue in :)

**Comment by rayane69-crypto** [comment]
hello @kevintonb, I have just recreated the same thing, and it doesn't work on either Mac or Windows. I tried it on the ARC browser, but it also doesn't work on Safari, Google Chrome, Bing, or Opera. I've provided you with everything I have at my disposal.

**Comment by rayane69-crypto** [comment]
Someone else had the same problem but nothing.

https://github.com/FlutterFlow/flutterflow-issues/issues/947

**Comment by rayane69-crypto** [comment]
I tried filtering the list view using infinite scroll and encountered the same issue and another had the same problem : 
I think it comes from the indexing or the zone of our server, I don't know
https://github.com/FlutterFlow/flutterflow-issues/issues/1166

**Comment by sbis04** [comment]
Hey @rayane69-crypto, so sorry for this huge delay, I just noticed your community post. I tried reproducing the issue but wasn't able to. I looked into the project that you shared -- I believe currently whatever state the shared project is in, from there if I just add a Filter to the backend query I should have been able to reproduce this bug, right? (as you demonstrated in the community post).

I think it will be easier if you just update the project to a state where the bug is reproducible. Also, can you also show me how the data looks on the Firestore side (so that I can understand what the filtered query should actually return).

**Comment by rayane69-crypto** [comment]
hey @sbis04, I just did the same thing again, it doesn't work. 
![Capture d’écran 2023-08-15 à 12 46 45](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/8db0dc56-26af-49df-933f-f93f0e7ffad0)
![Capture d’écran 2023-08-15 à 12 45 34](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/048914bf-6fce-4b1d-a053-dc4a30c8adea)
![Capture d’écran 2023-08-15 à 12 36 08](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/6ef45e48-29af-47fa-bfc2-9ee2bbcb2d2b)
![Capture d’écran 2023-08-15 à 12 36 03](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/e3d805e0-0cde-44eb-8ea1-951a4999654d)
![Capture d’écran 2023-08-15 à 12 31 34](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/083e654a-90ef-477e-aee2-0caf5a307791)
![Capture d’écran 2023-08-15 à 12 45 24](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/6f39d778-45c8-4e75-9ba3-8632e9c0b20c)
![Capture d’écran 2023-08-15 à 12 35 52](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/dd998d98-a490-4c8f-8baa-5fc65334a872)
![Capture d’écran 2023-08-15 à 12 30 14](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/be824ed3-bdd2-45f8-b161-11e56b6f9fdf)

**Comment by rayane69-crypto** [comment]
I created a new project on flutterflow I have a new bug I can't continue the tests I have this, it's been almost 2 years since I create on flutterflow the first time I see this bug,
![Capture d’écran 2023-08-15 à 12 47 35](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/eca2fa41-50ac-404f-8641-0f9c7f59c722)

**Comment by rayane69-crypto** [comment]
👿

**Comment by rayane69-crypto** [comment]
@sbis04 @kevintonb @vishalagarwal2  The filter works fine, but when trying to filter an integer, it bugs out as in the example at the top.
Bug report code : ITESysmB35BgostG+rrucPpQhQIhNmY1bZMnktVxRR4dIq7xBLMyPMykZUNKTfG7eWNqJ2KInkYx7sLQkfPTEPkpGzWBUYhH0JVPEgyUUlGWacmnErmKX3BPL9hUBXaa5ra7uh0lBLduWFoE6k2pNq3qNleeY8aSfxBlZ7vfcPo=

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/62426733/1adc5d9e-13fc-4f3b-b911-8c5b17ed7baf)

**Comment by rayane69-crypto** [comment]
I just solved it. When using "greater than or equal to," it's necessary to sort the list first for the filter and infinite scroll to work. This wasn't mentioned anywhere, but at least I figured it out.
