### ISSUE TITLE
Action not trigger!

### ISSUE THREAD

**Issue by ckarmy** [FlutterFlow/flutterflow-issues#126]
I have a button that not working OnTap action! I try everithing but I can't make it work!
What can be the reason? Works on some items but not all!

![image](https://user-images.githubusercontent.com/10090783/201795676-c428faa1-9cd6-4d38-8cdd-08425e643387.png)

<img width="291" alt="image" src="https://user-images.githubusercontent.com/10090783/201795902-68f8d12b-b64e-4210-b8bf-4fc3ae4b760f.png">

**Comment by katherineqian** [comment]
Hi @ckarmy,

This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.

Thank you for your contribution!
