### ISSUE TITLE
stack widget error

### ISSUE THREAD

**Issue by Nuel-Agyei** [FlutterFlow/flutterflow-issues#1262]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Every time I try to make the stack 100% of the workarea it just goes blank

https://github.com/FlutterFlow/flutterflow-issues/assets/123364185/88fff9ef-031d-4bc5-9bc9-20850494a875

### Expected Behavior

The screen isn't supposed to go blank

### Steps to Reproduce

1. Create page 
2. Remove Appbar
3. Add Stack 
4. Make appbar 100%

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTkcrqx89gobxc+Kn+YMFVtCY4GUMdXOczitVEew4bCIj4PZohPeLOTFRtYMCzaH9YHVGggnEe0fDOvfDEUcA4ZDWVbJhHzqhccxPPbDiRRa3SPM+KOGhADZpUCUjE4buFnhBRCPFiR04l2VyuJt+uTT6Cf9qOYwx5e6fDbOY=

### Context

I can't continue my learning

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/123364185/aa59d58e-9e1d-49f1-9ea1-3b244ef7bc0c

### Environment

```markdown
- FlutterFlow version: 3.10.4 
- Platform: Web, Desktop
- Browser name and version: Brave
- Operating system and version affected: Windows 10
```

**Comment by wenkaifan0720** [comment]
Hi @Nuel-Agyei. This is because you are putting a widget that is of infinite height (i.e. the Stack) into a widget that also could be infinite height (i.e. the Column), so Flutter doesn't know how to render it. We generally catch those kind of errors but could have missed this situation. But I just want to let you know that this is not a bug on our end, but rather a restriction from the Flutter framework.

**Comment by Nuel-Agyei** [comment]
Hello @wenkaifan0720, OK thanks.
