### ISSUE TITLE
Pre-loading color not working as expected

### ISSUE THREAD

**Issue by stevey6404** [FlutterFlow/flutterflow-issues#1268]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have set the pre-loading colour to blue however when testing on iOS using TestFlight, it is showing orange on initial load.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/ff0f5c1a-f28e-41aa-a967-7b221bb31df1)

### Expected Behavior

Should be blue as expected on iOS.

Working on Android as expexted.

https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/7b9fa9ec-0ec1-40de-a844-49dfdf6d69cd

### Steps to Reproduce

1. Change pre-loading color to blue
2. Load onto iOS test flight

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfzcmA8c9grs9Y1r6JYMAwpCE4Q1McTIMziNZ+exUbfaL1Buw1eODSZVhDXdyraVNcJU2ajmAy7t7wjc7tFfQnIQmCGKk+yKp2djzOe2imacm1OqjpZXNRJ+ZPIH671KWRrRQnKbFsSEIZ22eyI+6vYB7DFOu/Zwh9f6PHaOI=

### Context

It is a new feature released however doesn't seem to be working as expected. 

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/25169810/d0817488-90e4-4690-aa44-6251a7803b56

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: iOS
- Browser name and version: Chrome Version 115.0.5790.171 
- Operating system and version affected: iOS 16.6
```

**Comment by webwurm** [comment]
I have also a problem with pre-loading color: As soon as I set it in my project and deploy to AppStore I get the error: 
```
Codemagic Deploy Output: Failed Step: Install pods
Because myproject depends on flutter_native_splash 2.3.1 which depends on image ^4.0.17, image ^4.0.17 is required. So, because myproject depends on image 4.0.15, version solving failed.
```
### Bug Report Code
IT4Wl8nl3891pbxH1rXuY+9VnjwWQ2Yha788msN+URA2GO/1OrYPQvj7PxFUcMe6d1Z9fWejkngX/Mr8idr+G/JfZBeqbNhx/5NIYQyVLX2Wb4S1Ea63b3dtGdxPf27D1pm7hRVTAPVpR04Y1GameuTIfCvsQ+/UDWtEOuaoXdeK2SrDX1iXc2URm05KZDPz

### Enviroment
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected: Windows 11 current build

**Comment by stevey6404** [comment]
Hi @kevintonb, I tested it on a new project and deployed to TestFlight and the problem isn't there for the colors specified. Do you know how I can resolve it for the project with the problem?

**Comment by stevey6404** [comment]
I've tried deleting my existing splash screen and then entering it again. However the pre-loading colour just doesn't seem to match. For example, I changed to a dark blue #142C44 and it turns out to be turquoise. I changed to orange but it's red...so I'm pretty stuck right now :/

**Comment by agreaves** [comment]
Hi @stevey6404, thanks for submitting the bug report. Like @kevintonb, I have not been able to reproduce this bug report, and as such am closing the issue for now.

However, my guess is that this is due to there being a Light Mode and Dark Mode version of your initial load splash color. I'm guessing that whichever one it is you're expecting, it's loading the other one. If you want to always show one color make sure to pick a color that is the same in Light vs Dark mode. Hope this helps!

**Comment by cartworthy** [comment]
I'm having this same issue! Except I'm trying to set mine to yellow and it's showing turquoise.

@agreaves I'm not using light mode or dark mode.

**Comment by brian-tempo** [comment]
I was just having the same issue, where for some users they'd see a flash of unexpected purple at app start up. Here's what was going on and what I did to fix:

- The users had Dark mode enabled in their iPhone settings.
- I did not have the "Dark Mode Theme" (See "Theme Settings" > "Colors" > "Dark Mode Theme") turned on, and in fact had never even looked at the dark mode color palette. 
- I had set the Splash screen pre-loading color ("Setting" > "App Assets" > "Splash") to the "Primary" color from my color palette, which happens to be a nice blue and what I was expecting all users to see.

It turns out that in the Dark Mode Theme the primary color was set to the purple color that users who had dark mode enabled were seeing. It was showing this even though I did not have the "Dark Mode Theme" turned on. **To fix, I simply changed the primary color in the dark mode theme to match the primary color from the light mode theme**. 

Under the hood, at least on iOS when the user has dark mode enabled in their iOS settings, it seems the dark mode theme color will be chosen even if the theme is disabled in the project.
