### ISSUE TITLE
Erratic UI behaviour in dynamic children object

### ISSUE THREAD

**Issue by ivantodorov78** [FlutterFlow/flutterflow-issues#1293]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://youtu.be/mtGnXB0WO0s

### Expected Behavior

Not glitch, see YT video 

### Steps to Reproduce

See YT video 

Project:

https://app.flutterflow.io/project/lumenosity-app-93r6hh?tab=widgetTree&page=Favorites

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

building a favorites list from a list associated with an authenticated user profile 

### Visual documentation

https://youtu.be/mtGnXB0WO0s

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: macOS
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by kevintonb** [comment]
Hey @ivantodorov78 , thank you for preparing the bug report. I have had a look at your project and noticed that there is a container within the ListView to which there is a Backend Query attached to. When the children are dynamically generated for the ListView there are new children rendered one by one in the Containers. And as these Containers have a backend query attached to them, they fetch data each time from Firebase and load before rendering. When loading, the loading indicator has a specific diameter of 512 px pushes away the children that are getting rendered out of the viewport, and when it finishes brings them back to visibility and causes them to load. This series of events causes the UI to look like it is stuttering in behaviour. I would suggest you to create a separate collection for favourite items, linked to the user references and generate children from a backend query and then assign variables to the child based on the backend query result as this would be the efficient way to go. This would also make sure the data is rendered once and will reduce data transmission cost in having a backend query on every dynamically generated child. If you face any other issues, please feel free to contact our support team over chat or through support@flutterflow.io. But since this isn't an issue within the platform itself I am closing this issue for now.

**Comment by ivantodorov78** [comment]
Hi Kevinton,

I'm following except the step where you suggest I create a separate collection for my favorite items. Do you mean a Firebase collection? Currently the Favorite Lumens are references stored in the user's favorite_lumens list and wondering how I query just those Lumens.

Thanks,

Ivan

___

*Ivan Todorov* | (310) 266-7533 | Calendar ( https://app.hubspot.com/meetings/ivantodorov/30m-1h-2h ) | LinkedIn ( https://www.linkedin.com/in/ivantodorov/ )
