### ISSUE TITLE
Hyphens not supported in JSON data anymore

### ISSUE THREAD

**Issue by JeromePS** [FlutterFlow/flutterflow-issues#1296]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

current API request returns a json with hyphens "-" and since the last update of FF, it's highlighted as an issue in the builder.

json previous data: $.gridT0-buy

json needs to be changed to: $.gridT0buy

### Expected Behavior

json data should work with hyphens so $.gridT0-buy should not return an error

### Steps to Reproduce

1. create api call
2. include api call in build
3. display api data such as "$.my-data"
4. error dispaly in project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4siMmB7ZNPn7xK1br+YMJ7/SUUJjt9a+cssct/cxQcB4j4PZoAf+LSYkltTsyzaHNEA02GuEMy3PzJuOH9JuwqKTqaGapayqgBdhPPbEeQR7aYBc+CfnB7O8dbfHaj0J6NpApSNsF0S05n7FyUP/CiQT+Cf9qOYwx5e6fDbOY=

### Context

my apis have hyphens in there and i'm unable to compile/publish until this error is fixed.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/137503473/aa03d478-ab1b-4260-82bd-dddd3f48828a)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: android/apple
- Browser name and version: chrome
- Operating system and version affected: windows 11
```

**Comment by YassinELY** [comment]
Hi All,

I get the same type of error when i try to use a JSON path that is ending on a number.

Yesterday this code was just working fine, when opening flutterflow today i got 20 errors all based around the same issue of the screenshots below.

This looks like the same issue as JeromePS is having.

<img width="1062" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/142539026/14de7259-f88c-4dfc-8276-7260f00c4e09">

<img width="1728" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/142539026/26ee70b0-1e29-4b2f-9b66-acc8710dda75">

**Comment by kiranetph** [comment]
The same applies to JSONpath with numbers. After the last update, my app reports 81 errors because of this change. 
To "fix" this from our side would require changing the original JSON file, which is impossible.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15226809/be6c0709-bca2-4c6b-99a2-f012b5109db1)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15226809/05509f34-1997-43be-a6e5-a1010281245c)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15226809/b68b5463-29dd-49a8-bf28-709a0de7e13c)

Please fix this bug.

It also relates to  issue  --> https://github.com/FlutterFlow/flutterflow-issues/issues/1296

**Comment by YassinELY** [comment]
Hi Flutter team, Are you guys working on this? Can we see the progress or actions that will be taken somewhere?

**Comment by j-mcq** [comment]
Is there an update on this? Would be great to have a fix. It all seems to work when running it locally.

**Comment by kiranetph** [comment]
@hariprasadms 
Is there any development on this issue?
Actually, there are several issues related to this bug and FF user can not continue with their projects affected by this problem since the bug was introduced more than 1 month ago. 
In our case, we don't have influence over the database structure and field names. 
We cannot continue with our project as long as JSON path will not allow numbers as element names.
