### ISSUE TITLE
Norwegian not being translated with Google

### ISSUE THREAD

**Issue by ampapplarsen** [FlutterFlow/flutterflow-issues#130]
## Expected behavior (required)
Translating fields to Norwegian

## Current behavior (required)
Norwegian language fields empty after translation action. Other languages OK.

## To Reproduce (required)
1. Add Norwegian as a language
2. Hit Translate All or Translate

## Context (required)
Trying to release my app in many languages.

## Your environment
* Version of FlutterFlow used: 1.1.18 
* Platform (e.g. Web, MacOS Desktop):  MacOS Desktop
* Browser name and version: Safari Version 15.6.1
* Operating system and version (desktop or mobile): MacOs 12.6

**Comment by ampapplarsen** [comment]
um, removing a major european language because what now?

**Comment by ampapplarsen** [comment]
![Screenshot 2022-11-16 at 14 46 27](https://user-images.githubusercontent.com/114226492/202197297-e26edeff-fe21-4e82-a403-724a30e31b08.png)

**Comment by Pepino-GR** [comment]
Convinced, set it as a bug.

**Comment by agreaves** [comment]
Hi @ampapplarsen! Thanks for the bug report. Currently FlutterFlow lists three different Norwegian languages (or dialects, forgive me as I'm not familiar). They are **Norwegian** (no), **Norwegian Bokmål** (nb), and **Norwegian Nynorsk** (nn). However, we have a bug where we are listing **Norwegian Bokmål** as simply **Norwegian**, so the two look identical and I'm guessing you chose **nb**. This will be fixed upon the next release!

Neither **nb** nor **nn** are not supported by Google translate, only **no** so please ensure you are using this one in your application. Since they look identical for now, try to add both and only keep the one that auto translates.
