### ISSUE TITLE
JSON Response is NULL after importing from Swagger

### ISSUE THREAD

**Issue by nick-chargely** [FlutterFlow/flutterflow-issues#1310]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Entire API group is broken due to a boolean being set in api_calls.dart file called 'returnBody'. There is no way to change this via the FlutterFlow app but after pulling the code and setting this value to true I validated this is the root of the issue. If this boolean is set to false then the jsonBody will be set to null in the api_manager.dart regardless if there is a value or not from the actual response body. 

### Expected Behavior

If there is a response is should be allowed through to be parse. Especially if there is handling in the endpoint and the code to parse it! This seems like a useless boolean

### Steps to Reproduce

1. go to api_calls.dart 
2. set the returnBody to false
3. you will now see all responses return null
4. you can confirm this via a listView - it will be empty

Within Flutter flow i believe you can reproduce it:
1. Access swagger.json file
2. import an api collection 
3. export the source code
4. navigate to api_calls.dart 
5. verify the returnBody is false

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcr1z4Z2xNtD0a6Jbe9alSQWMjsmULgZl+4acCs8GqLuPe0UWMzBUBFUOPHhd2NIfU6j8T4X/MrLud/qU8IrAEytc6Z61sxQZRbyfGagSrrRPoS3b0ZQBd1hI3KH4LeFmyJ5BMViLloS72CIHe+/d3bZGZu2NTJEMeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

It completely blocked my development for an entire week - I could not figure it out until i exported the code and looked through the flutter source code 

### Visual documentation

<img width="830" alt="Screenshot 2023-08-19 at 9 36 05 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/136842909/c5a7d529-2fa9-4cf6-acb1-b37941128263">
<img width="828" alt="Screenshot 2023-08-19 at 9 31 38 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/136842909/87f62bca-e02a-4c4d-abba-356f8b9dd05f">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: ios & android
- Browser name and version: chrome
- Operating system and version affected: all
```

**Comment by joshua-ffio** [comment]
Hi @nick-chargely ,

I have tried to reproduce the issue on my side and I am able to successfully get `returnBody: true` and able to get my swagger api results to load correct values. This behavior is currently working as intended because FlutterFlow is interpreting the response type during the swagger import based on the responses settings for the first 2xx code in your swagger.json for each endpoint configurations. If the configuration is set so that your content is of type application/json then returnBody will correctly set to true in the api code export.

Please use this for reference in regarding your swagger configuration: [https://swagger.io/docs/specification/describing-responses/](https://swagger.io/docs/specification/describing-responses/)

You might be able to get this to work post-import by adding the Content-Type: application/json header to your api configuration in FlutterFlow as well.

Because this ticket is unique to your current project and I am unable to reproduce using the steps provided, this ticket is considered a support request and will be closed. If you need more assistance after trying the steps I mentioned above, please use the chat support or contact support@flutterflow.io.

Thanks!
