### ISSUE TITLE
JsonPath failing to parse list to generate items with one item 

### ISSUE THREAD

**Issue by nick-chargely** [FlutterFlow/flutterflow-issues#1342]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When passing in a Json object to component which holds a list as child property the generate list is failing to resolve when there is one item in the list. Throwing null `Another exception was thrown: NoSuchMethodError: 'toList''

This was tested using the same object - it fails with one item but success with multiple.

This is using a basic - very simple statement and validated multiple times. 

### Expected Behavior

if there is one item in the list it still will pass a list but with one item in it NOT the single object.

### Steps to Reproduce

1. Create a component which holds a list within. 
2. Pass that Json object  (Example below) to the component as a parameter. 
3. Generate a list using the object (in this example you would generate using $.items or $.items[*].name
4. make child list item display the output ($.name or $)

This Fails:
{
"name": "test",
"description": "descriptionTest",
"items": [{
"name": "test",
"itemNumber": 0
}]
}

This works:
{
"name": "test",
"description": "descriptionTest",
"items": [{
"name": "test",
"itemNumber": 0
},{
"name": "test2",
"itemNumber": 2
}]
}

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlcr1z4Z2xNtD0a6Jbe9alSQWMjsmULgZl+4acCs9f5ToPJYQe8/6P0lCTs+9THxmfGacp14G/taKi9jDUsAnEE+sfqpk+s9AUgnyJTiuRZeTF7WafUckP5pjI0PF5MCRsBV4ItZpSGQX216QCvOsST3BNLL2PVQ8Sq/LZO4=

### Context

I am trying to send an object (from a webcall) into a component which holds a list of items to display. 

### Visual documentation

<img width="371" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/136842909/36dad623-0896-4f8a-987c-e4502e5f24f2">

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: iOS and Android
- Browser name and version: Chrome
- Operating system and version affected: all
```

**Comment by kevintonb** [comment]
Hey @nick-chargely , thank you for getting in touch with us. I have taken a look at the issue that you've mentioned here and appreciate you providing all necessary information. The issue seems to originate from the children generated from the Column in the stationCard component. I noticed that the children generated are served from a custom function (parsePlugListJsonFromJson) that returns a json object and does not have it's return type as a List. Enabling it to be a list will fix the issue for you. However as this is not a bug or an issue with Flutterflow itself, I am closing this issue for now. If you face any difficulties or similar challenges in the future, please feel free to contact our support team at support@flutterflow.io. We highly appreciate and thank you for creating a report, as these reports will help us improve the building experience of all our users.

**Comment by nick-chargely** [comment]
The custom function is a temporary solution to fix the problem. I obviously
prefer not to do it this way. Without this the bug is present. Just look at
the function, it shows the weirdness of the problem. Json in json out and
just grabs the plugs property... The problem present is for some reason the
jsonPath logic is returning a single object for that list when there is one
item. If I use basic json decode and grab is manually it works fine even
with dynamic return.

**Comment by ttjoonttkoon** [comment]
hey Nick, were you able to make this works? its a few months later and im encoutering exactly the same issue?

my json is from algolia search and it just wont parse. thanks
