### ISSUE TITLE
Switches Not Responding to Update Component State

### ISSUE THREAD

**Issue by kranium76** [FlutterFlow/flutterflow-issues#1344]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

 Basically I have 3 component State boolean variable which are  assigned to  3  Switch widget. 

When I update these Component State with Rebuild Current Component (using action flow ), switches doesn't reflect the right value.

### Expected Behavior

I have 3 switches

If I activate a switch and another switch is already activated, the latter must be deactivated.

Basically, it is not possible to activate several switches at the same time. 

### Steps to Reproduce

1.  Create a component with 3 switch
2. Create 3 component state for each switch
3. bind these component to each switch inital value
4. Create logic for toggle on : if one is toggle on , reset the other component state ( rebuild component )

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Ol8iAz4hgoctH176Jc/pV+TsUJlgnbZZMju5xaEo0G5fNG7UIec/4VEptXbC+TVc2fGeajnsK7s7XhtzIN/o5CzOYR4Bm/qtycg7hWnutV4SvEqi0VEZ8QdpKCBXD0MCFphZ+IvRvc1YB3U+DN96vVhfcNuPuNjMFD8iXIqzIjXPuQ0SLb3kNh1JWeC/v

### Context

I have a page that opens a bottom sheet containing a form to be filled in by the user

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/124464338/d814bcfe-b4a0-409a-bf84-7475bf5790f9)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Arc Version 1.4.1 (40966)
Chromium Engine Version 116.0.5845.96
- Operating system and version affected:
```

**Comment by MamadAsap** [comment]
Hi @kevintonb and @victoriahuang1 any news related to this issue ?

**Comment by aaronsegbedzi** [comment]
Yes, this is still a problem. When is this going to be fixed?

**Comment by kevintonb** [comment]
Hey @MamadAsap , thank you for getting in touch with us. The project seems to have authentication enabled with a huge number of other factors that make it difficult to test this issue in your project. It will be helpful to troubleshoot if you could create a new project and recreate the issue there and share the bug report code here. This will help us to isolate and identify the issue so that we can troubleshoot more effectively. Kindly share a new blank project with us with the bug reproduced.

**Comment by MamadAsap** [comment]
Hi @kevintonb sorry for that,  i have created a blank project **switch_bug** with the a component

**Comment by MamadAsap** [comment]
Hi @kevintonb and @victoriahuang1 any news related to this issue ?

**Comment by victoriahuang1** [comment]
Hi @MamadAsap , thanks for the update. I took a look at your project, and it seems like you are trying to update the switch values by updating the local component state variables, which are passed in as the "Switch initial value" for each switch. Is that correct?

If so, this is actually the expected behavior -- updating the "initial" value should _not_ update the _current_ value. The initial value, as the name suggests, is only meant to set the value for when the widget is first loaded.

**Comment by MamadAsap** [comment]
Hi @victoriahuang1 thank you for the update , so i have no way to update switch value depending of another switch value update ?

**Comment by victoriahuang1** [comment]
@MamadAsap that is correct. This is not a currently supported use case, but I just put out a PR to support it :)
Once the new code is deployed, you should be able to update your switches

**Comment by kranium76** [comment]
wow thank you @victoriahuang1 ! 🚀

**Comment by ge-king** [comment]
Any update on this?
