### ISSUE TITLE
"on Data Change" functionality does not "dispose" correctly

### ISSUE THREAD

**Issue by dasirra** [FlutterFlow/flutterflow-issues#1345]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have two screens A and B
- From A I can navigate to B.
- B is using the "on Data Change" functionality (what is a StreamBuilder with a Firestore StreamSubscription)

Well, I you navigate form A to B, then pop to A and then you trigger the "on Data Change" event, the StreamBuilder callback is called (even when you disposed B (we pop to A)) 

### Expected Behavior

Firestore listener Stream should be cancelled on B dispose method.

### Steps to Reproduce

1. Create page A
2. Create page B
3. Add "on Data Change" functionality to B.
4. Now go to A
5. Navigate to B from A
6. Pop to A from B
7. Trigger the "on Data Change" event

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wksrq249Jm9tF14SJcvlV/SY5Jk87apZMlcN+bEkbC5esPaYPXfikSEpWZ9+kTHxcL078uH4xwN3FkfzAA+UpH0mWR6JEwZN+YAvzVkGtV7KOCqmWZHZ8RN5JJVzH5JmK2CRRPtRpckJl20+EGPK8cCbZH7m3PEY7R/GHOqzLs3OqQ0SLb3kNh1JWeC/v

### Context

I'm trying to offer the user the possibility to go back from page B to A.

### Visual documentation

.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Android 11
- Browser name and version: Chrome
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @dasirra - Thanks for reporting the issue. The steps above described a bit confusing ( particularly when you say pop back to A). Need a bit more clarity about how you are navigating back to A, through click action, clicking back button or On page load and also what action you got in  "on Data Change" action. 

I did, however, test the steps by hitting the navigate back button and selecting the snackbar display action under the data change action and navigating from page B to A. On the debug and run mode or in terms of user experience, I don't see any issues. _I can confirm it is working as expected and no a bug._

Please share us images and a quick videos of any error or warnings you encounter. This could facilitate to speedup the investigation of the issue. Please let us know if the issue has already been resolved, and I'll close it. Thanks

**Comment by dasirra** [comment]
Hi @hariprasadms . Sure, I will try to explain it better.

Simplifying, what I say is that when you dispose a page containing a "on Data Change", the page is disposed but the associated "StreamSubscription" to the "on Data Change" doesn't. So, when the action that triggers the StreamSubscription occurs and you are out of the page (you disposed it), you can have errors specially if the StreamBuilder tries to call "setState" (tries to rebuild).

I solved the issue by adding a `_stream.cancel()` to the `onDispose` function in Flutter code, but I think this should be correctly handled by FF.

**Comment by hariprasadms** [comment]
Hi @dasirra - Thanks for the more details and appreciate your input to enhance the current design. 

I understand that you are suggesting an enhancement for the current design in the code. However there are no visible errors or issues around the user experience. If this is the case, I would suggest submit a feature request for the suggestion you are adding here. So that it can go to correct channel and team can consider your point. 

If you still think there is a visible error, create a blank project with issue setup details and share the bug report code. This can help to us to investigate the issue and come up with a solution.  

I can mark this issue as feature request / enhancement for the current design. This issue doesn't qualify for the issue tracker since it's specific to design and enhancement suggestion. The steps are not reproducible, and hence will be closed. Please use chat support or contact support@flutterflow.io for more help.

**Comment by MahmoudIsmail88** [comment]
after spending many hours , this problem still exists ! FF team , this should be an easy fix !
