### ISSUE TITLE
Instant Reload Doesn't Load in Background

### ISSUE THREAD

**Issue by dinasorz** [FlutterFlow/flutterflow-issues#1360]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Instant Reload Doesn't Reload in Background as it should, instead I must stay on the tab for a while for it to start loading, then I'm able to go back to other tabs, and when the progress bar is finished I must go to the tab again for a while for the application to finally show up and load!
I can't describe how much unproductive this is, as I'm forced to cut the productivity and just stare silently at a loading screen...

The waiting time for compiling and reloading are already too much unfortunately, and with the addition of that bug makes us feel each second of the slow progress

### Expected Behavior

For it to load in the background without having to open & stare at it, and when it finishes we just switch the tab and see our application without extra loadings

### Steps to Reproduce

-Instant Reload
-Switch to "other" tab
=It will not start loading until you switch back to the "instant reload" tab for a while.
-Switch back again to "other" tab
=When the progress bar finish, the app will not fully load until you switch back to the "instant reload" tab for a while.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ojPLlvJFIocte7q6JccBKjSQsHH5MB+ap0nlMpBazwbfe+uB4kqevfOTERBcMuhT3NIJ2eWp2oW0c2Lhd/+MBGPJeAzaYb7ZcycxfWw7gQkCVVL6nFJWgPHJ9GfxjN3GB06W7kRF+MBXfpYR3wM3VyMCvCybCzUQJzIPUUsDq/LZO4=

### Context

Slow productivity and breaking momentum

### Visual documentation

![a1](https://github.com/FlutterFlow/flutterflow-issues/assets/95580779/8e9a4f6b-6e47-47a5-bdbf-8e12becd01c4)
![a2](https://github.com/FlutterFlow/flutterflow-issues/assets/95580779/9549cb9b-5dab-40d5-83bf-f438d18c0039)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: PC
- Browser name and version: Chrome Version 116.0.5845.111
- Operating system and version affected: Windows 11
```

**Comment by SameerShahzad99** [comment]
@dinasorz Thank you for sharing, i was able to reproduce this problem on my end!

**Comment by joshua-ffio** [comment]
HI @dinasorz , Thank you for submitting this request. While we can understand this may be a slight inconvenience, this behavior is currently working as intended. During our testing, we found that if you open your test mode instance in a new browser window (as opposed to a tab) this should alleviate your issue as a workaround.

However, because this issue tracker is specifically for bug reports, we kindly ask you to submit a feature request through the in-app feature request tool. You can find it in the [“Help” menu inside of the FlutterFlow](https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.-help). This will help us keep track of and prioritize feature requests, ensuring we can continue to improve our product based on user feedback. We appreciate your understanding and look forward to hearing your ideas.

**Comment by anshunjain** [comment]
not sure how this is intended behavior. no web page in the world stops loading when you navigate away from it. this should be treated like a bug and resolved asap. Its a nuisance in development.
