### ISSUE TITLE
Scroll Bar not showing on Android devices (yet showing in run/test mode)

### ISSUE THREAD

**Issue by johnson407603** [FlutterFlow/flutterflow-issues#1361]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122502333/3b20c4fb-11f5-4399-9fdc-147de3f0b46b)
As shown on the screenshot, in run/test mode the scroll bar is showing, yet it's not showing in actual devices following deployment

### Expected Behavior

screenshot above is the expected behavior 

### Steps to Reproduce

Any scroll in my app has the same issue, not something that needs to be specifically reproduced

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeic/625NPn7xG7arMK8AwiQMwJ0QlUIInj+0bWRMhNbL1BIkAf8n7VEpLYte9fX9mPVeloHwC0s7KiNjpGPcnOU+rbbY//65XQTnLfz6tbJCoPoeCYEd7I9Fbf0yd5Kek3RVdKu52cV4f3GaYGfCdG3qCf9qOYwx5e6fDbOY=

### Context

To have the scrollbar shown so users know that there are more to exploreis

### Visual documentation

screenshot above

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected: Android (and possibly iOS)
```

**Comment by kevintonb** [comment]
Hey @johnson407603 , thank you for getting in touch. If you look at the generated code from Flutterflow for the scrollbar theme, you will notice that scroll bar has been enabled as a Material property [scrollbarTheme] for the whole app which activates a scrollbar for any scrollable widget in the app for the **Web** and **Desktop** platforms. In order to have a scrollbar activated for any scrollable widget in mobile, it will have to be wrapped around a **Scrollbar()** widget as a parent. So currently, the scrollbar will only be activated for web and desktop platforms as Flutterflow uses the scrollbarTheme property. So this not essentially a bug but an expected behaviour from the app. 

I'm adding some references to the scrollbar theme and the scrollbar widget from Flutter below:

[Scrollbar Widget](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scrollbar.dart)

[Scrollbar Theme](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/scrollbar_theme.dart)

If you would like to see this as a feature enabled for mobile, please raise a feature request to our engineering team.

I'm attaching a doc that guides you on how you can raise a feature request:

https://docs.flutterflow.io/getting-started/ui-builder/tool-bar#2.3-feedback
