### ISSUE TITLE
Count up timer duplicates value when other timers on page are reset

### ISSUE THREAD

**Issue by hplessis** [FlutterFlow/flutterflow-issues#1388]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We have multiple timers running in the project on the same page of which two of these timers (RunningTimer and GameTimer) are running at the same time. When stopping and resetting the GameTimer to to a specific value, the RunningTimer then also doubles in value. The RunningTimer is supposed to continue running and not stop or reset at any point. There are no code in the project that will reset the RunningTimer. I have created a new additional timer (testTimer) and added this below the RunningTimer in the same container and this showed the same response. i then moved the testTimer out of the container onto a different part of the page and the testTimer worked correctly while the RunningTimer still duplicated. Attached the widget code where the timers are contained

### Expected Behavior

On stopping and resetting the GameTimer to a specific value the RunningTimer should continue and not reset to double it's current value.

### Steps to Reproduce

I could not get the issue to reproduce outside of the project.
Attached the widget code containing the timers as well as the page code

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhcrl25NOseFF7q6JY+5oljkvH1McTZM3lOsYGA8aGLauO5ouP8/UaXdBT8+cfG9cJGCl+UgEwfCLiezqU+0nAAqef7V607VpWjzgeEeQMbaUPYeSQ3dREe5TJn7D14mFuBFRJbFaLy1m22GLcq3qNleeY8aSfxBlZ7vfcPo=

### Context

In the project the RunningTimer needs to continue running even if the other timers stop/start or change values.

### Visual documentation

Page and Widget Codes
[Scoring Page Code.txt](https://github.com/FlutterFlow/flutterflow-issues/files/12483989/Scoring.Page.Code.txt)
[PageRow Widget Code.txt](https://github.com/FlutterFlow/flutterflow-issues/files/12483990/PageRow.Widget.Code.txt)

Video showing issue
https://github.com/FlutterFlow/flutterflow-issues/assets/125641642/e3ea18da-bbd9-4363-8c2b-a9bfd58e6e80

### Additional Info

We added a work-around to this (got the current time from the RunningTimer and then reset the RunningTimer after the GameTimer was adjusted) in order to get past the issue.

### Environment

```markdown
- FlutterFlow version: V3.1 - Flutter 3.10.4 - Released August 28, 2023
- Platform: All platforms
- Browser name and version: All browsers
- Operating system and version affected: All OS's
```

**Comment by hariprasadms** [comment]
Hi @hplessis - Thanks for sharing the observation. I can confirm that I have tested timer widget with the above points you mentioned in the issue description. It is working as expected. This is **_not a bug_**.  See below. 

I advise making time widget components and using them over in pages. You can update components based on time intervals rather than the entire page. I hope it can answer can help you. 

https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/48ff824a-f1b4-48fe-be7d-149687cedcae

Because your project has more pages, it is unable to find the timer widgets you used on the page. If issue still persists, create a blank project with issue setup and update the issue with the details.
