### ISSUE TITLE
Dropdown-Widget doesn't show third line of text

### ISSUE THREAD

**Issue by jay-electronica** [FlutterFlow/flutterflow-issues#1398]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When typing a longer text in the Dropdown Widget that exceeds 2 lines, the text of the third line is simply cut-off.

### Expected Behavior

Should show all the text

### Steps to Reproduce

1. Create new page
2. Add Dropdown Widget
3. Type into Define Option Labels:
"Moderat 
(ca. 6 Std. - sitzende, wenig belastende Tätigkeit und viel Dehnung"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wiMjf35FOm8tF0L6JbsExqDwWGDs2apI7iusaaCs8GojnPO0ESs+lYldUcNO/TFViO2GGpHgX/Mrpi/zMFfdcCwSYbLZSwahMTBXMf3KlabK6Cr63b3EnO8dmGn6dy6S7vAlTCMFoV3A43TqDe+qiYAPvJZzsDW0aR+a4XdeK2SrDX1iXc2URm05KZDPz

### Context

held me up from continuing with my project

### Visual documentation

![Bildschirmfoto 2023-09-02 um 19 08 38](https://github.com/FlutterFlow/flutterflow-issues/assets/143325076/0542573e-12f3-4c5e-a662-13e44195e6a4)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: most recent versions of Chrome and Safari
- Operating system and version affected: macOS 13.5.1 Ventura
```

**Comment by hariprasadms** [comment]
Hi @jay-electronica - Thanks for reporting the issue. I can confirm that this is not a bug. This is as per design. The preview that you see is intended in order to keep the dropdown widget editor preview minimal and consistent with other widget types. However, the options with additional lines are visible as expected in test/run mode. You were given the ability to create a custom dropdown widget to suit your needs. I advise you to test a custom widget to see if that works for you. Thanks
