### ISSUE TITLE
Font Weight rendering not matching

### ISSUE THREAD

**Issue by priteshkumbhare** [FlutterFlow/flutterflow-issues#1399]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am using a custom font(Usual from Adobe). The font weight in Test Mode is much higher than that in Editor or Preview Modefont weight
<img width="1434" alt="Screenshot 2023-09-04 at 11 49 48 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/19405199/2101859c-2fce-4d5a-8148-6237d7afcedb">
Editor
<img width="1436" alt="Screenshot 2023-09-04 at 11 50 05 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/19405199/2a64b3f2-aa40-4cd7-8dca-ad9400d22a62">
Preview
<img width="1436" alt="Screenshot 2023-09-04 at 11 50 12 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/19405199/a3ad008c-9983-43d7-b037-3d02eb3b8e9d">
Test Mode (this has higher font weight)

### Expected Behavior

The font-weight in Test Mode should be same as that in Editor

### Steps to Reproduce

1. You can download Usual font for free from https://www.cufonfonts.com/font/usual
2. Write any text in the editor using Font Weight 300
3. Open Test Mode
4. You should see the Font Weight increased to around 500

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kzMrlvYtIvsdY7rrtbcZV9GEWG1w1TL07ttYbZxUjIuPtBJh+dsn4RxJoTfXhd0NhHFqj8WMepc70kfLDOuw3BymYRrk4zpdQcRXvc3q8R5SlO5aBe3d5M99TfVCY1JiRnghSVcZvS1Y512D7F9+RFj/YJ5+/Zwh9f6PHaOI=

### Context

The mismatch affects me as to counter this, I might have to use even lower font weight to compensate for this offser

### Visual documentation

Attached above

### Environment

```markdown
- FlutterFlow version: v3.1 - Flutter 3.10.4
- Platform: Web
- Browser name and version: Google Chrome Version 116.0.5845.140 (Official Build) (arm64)
- Operating system and version affected: MacOS Ventura 13.5.1
```

**Comment by agreaves** [comment]
Hi @priteshkumbhare, thank you for the bug report and relevant info!

This is actually due to a difference in the web rendering. We recently switched the FlutterFlow builder (including Preview mode) to use [CanvasKit](https://docs.flutter.dev/platform-integration/web/renderers) web rendering, which much more closely reflects what the application looks like on mobile. However, if your app does not use CanvasKit (an option present in the Platform Settings section), then fonts may look a bit different in Run/Test mode than what you see in the builder.

If you prefer the version in the builder, I suggest you switch to using CanvasKit for your application!

Sorry for the confusion in the meantime, we're aiming to update our documentation about this soon 🙂

**Comment by priteshkumbhare** [comment]
Thank you. Got it
