### ISSUE TITLE
Cannot use JSON path to compare with string variables ANYMORE.

### ISSUE THREAD

**Issue by EflexoftRD** [FlutterFlow/flutterflow-issues#1411]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/87630857/b7e12f5e-9df2-408d-8015-98e32aa697ab)
unable to use JSON custom path to compare it with a string.

### Expected Behavior

before the most recent update (as of 2nd Sept 2023) this feature was workign as expected.
we used to be able to set the custom path of the JSON (returned from an API call) in a comparison with a string.

### Steps to Reproduce

1. attempt to use a a json path in a conditional action comparing it with a string.
2. fail miserably, flips table because it used to work flawlessly.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESk8r6w4tgrttC16rccsJQhQIgQ0QnU7gnlO1ucx42B5DqBLMIY/T4R0NKTcOhfQtUDFSGnmcd/6HLkePhVvYpAEitQNhy0JVAFBbibFOjVIyoOruaZHBAP9FVJ2q75qW7rwpdBMhic3w66k6HNq3qNleeY8aSfxBlZ7vfcPo=

### Context

all of the projects i work on uses the comparison to do different actions so ALL of my projects now cant be run.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/87630857/980ec3fa-9204-462c-a76c-ff4013be7541)

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: flutterflow web
- Browser name and version: chrome 114.0.5735
- Operating system and version affected: windows 10 22H2
```

**Comment by gCharilaou** [comment]
I have the same issue. After couple of updates all the json data comparisons with text got invalid

**Comment by EflexoftRD** [comment]
@kevintonb @victoriahuang1 any update on this issue? can it be verified/reproduced?

**Comment by victoriahuang1** [comment]
Hi @EflexoftRD , thanks for the report. This is actually expected behavior caused by the lack of type inference on your JSON path -- we don't want the code to not be type safe, so we err on the side of caution when we don't know the type of the JSON path.

However, if you save the JSON path with its type information, then this should work. Please take a look [here](https://docs.flutterflow.io/data-and-backend/api-calls/api-calls-101#adding-json-path) for how to add JSON paths from test responses. You should then use the saved JSON path, rather than using a custom one in your action. The saved JSON path should have its type information.

**Comment by hypnotisttom** [comment]
Hi @victoriahuang1, I'm actually hitting this issue even though I'm using a saved JSON path.  It shows a string in the API tester, but when I go to use it, it says json, and as a result, I cannot compare it to a string value, due to the type-checking

![2023-10-13_17-14-02](https://github.com/FlutterFlow/flutterflow-issues/assets/9205055/9445f40c-2769-454c-9734-6133606071be)
![Screenshot 2023-10-13 at 5 13 23 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/9205055/ac395448-25c3-481a-81d7-544b253a457b)
![Screenshot 2023-10-13 at 5 12 50 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/9205055/34bad671-4066-4afc-bc96-4e3cfbf10588)

Am I doing something wrong?

**Comment by max-h-silverman** [comment]
I'm having this issue as well. Has anyone figured out a workaround?

**Comment by hypnotisttom** [comment]
@max-h-silverman, I worked around it by creating a function that takes the two string values and returns the boolean.  Then instead of using the comparison operator, I just call the function.  Hacky, but it works.

**Comment by max-h-silverman** [comment]
@hypnotisttom Cool yea that's what I ended up doing. Wish it didn't have to be like that but 🤷🏼‍♂️

**Comment by alturic** [comment]
Yea, I can't string compare anything anymore that I used to be able to.
