### ISSUE TITLE
Infinite Scroll Stops Loading with Greater Than Filter

### ISSUE THREAD

**Issue by rayane69-crypto** [FlutterFlow/flutterflow-issues#1435]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Two months ago, I reported a bug, but up until today, no action has been taken. I am reiterating my request in this message, hoping to receive a response.

The issue I'm facing is as follows: when I use the infinite scroll function in any widget with the backend filter (greater than or equal) or (less than or equal) and set it to display 2 documents at a time, the widget initially displays the 2 documents but then stops loading additional items, causing the iOS application to crash. This problem has a significant impact on those trying to create a Marketplace. I kindly request that you please consider the importance of this issue and address it as soon as possible. Thank you for your understanding and prompt response.

### Expected Behavior

When using the backend with infinite scroll, the filters work normally for integers

### Steps to Reproduce

1- Create a new page.
2- Add a grid view.
3- Place an element inside the grid view.
4- Implement a backend query with infinite scroll and a filter, for example, greater than or equal to 1 in quantity, and set the page size to 2 elements.
5- The backend query should initially return 10 elements to load the other 2.
6- Test it, and you will notice a bug. "The cause of the problem is the filter. If you remove the filter, it works normally."

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gjcmB25NIxLVE17Xyb+9VoCgUQzs+Rpc0sNtuTQIdCYDuBIYiaeD4X1htUuKrT39bKEWGkj4GpM7OveP9KvZeGwqtfLY9zJZAcT3KY3K/aovSC86eVkd8QO5PCXal0Ku7mhFdPu5YWk4H1Duqeui9aBfqNb37Zwh9f6PHaOI=

### Context

It's been 2 months since I've been waiting for this bug to be resolved, but nothing has happened. My goal is to create a marketplace, and if I don't implement infinite scroll, the document loading will be massive. To reduce this, I want it to display only products with a quantity greater than 1, with 20 documents loaded at a time instead of all at once

### Visual documentation

https://www.veed.io/view/ec0ba92d-2245-4d88-8440-7f2bf5c145f5?panel=share

### Additional Info

https://github.com/FlutterFlow/flutterflow-issues/issues/1185

### Environment

```markdown
- FlutterFlow version: v3.1 (released September 7, 2023)
- Platform: Mac Os
- Browser name and version: Arc 115.0.5790.114
- Operating system and version affected: macOS Ventura 13.4.1
```

**Comment by hariprasadms** [comment]
Hi @rayane69-crypto - Thanks for submitting the issue. I looked at the both the issue ( previous and current one).  In general, I would confirm that infinite scrolling is working as expected in most of the use cases. 

At this point, I presume it can be project specific issue. In your project we can't see the complete backend data and structure of the collection to understand filter criteria and why it is not returning the output as expected. Considering the nature of the issue and time required to investigate, I would advise you to contact the FF technical support team for help. They should be able to assist you in achieving the desired results and confirm if the problem is project-specific or not. 

Git issue repositories are primarily used to emphasise observations so that, compared to most use cases, we can say whether or not they are bugs.

**Comment by rayane69-crypto** [comment]
I just solved it. When using "greater than or equal to," it's necessary to sort the list first for the filter and infinite scroll to work. This wasn't mentioned anywhere, but at least I figured it out.
