### ISSUE TITLE
Auto Size option not available in DropDown Widget

### ISSUE THREAD

**Issue by nicopotgieter** [FlutterFlow/flutterflow-issues#1445]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As per email explanation to SAM
The DropDown widget only shows 3 lines inside the Option Labels. There is no option to allow for the more lines to be added.
The Text property does have an Auto Size for large amount of text, but the actual drop down selection does not have the option for Auto Size.

Please consider adding Auto Size to the DropDown selector

### Expected Behavior

To show more than 3 lines of data.

### Steps to Reproduce

N/A

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMn1z8pgoctF7r6JKflagmA5JUx8RIIomNZBaCorB5DoPZsUecmkM0RCQtOiY29ifFqakWoW0PDsv/PLA/kqaEyeGqJzysx2eA7KUjqgMaaTFJWvP3JCJ/5PIWa+1KaF2xF+AMRZWEFgwF2Aeem+QhbsHb7BIlgeD6/LZO4=

### Context

Will not be able to go live with app without this option. Buys investigating best solution for APP Building

### Visual documentation

N/A

### Additional Info

https://github.com/FlutterFlow/flutterflow-issues/assets/21144979/c4b8a0fc-a808-48c0-8a26-baac026bbe25

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Windows
- Browser name and version: Chrome Latest
- Operating system and version affected: WIN 11
```

**Comment by hariprasadms** [comment]
Hi @nicopotgieter - Thanks for reporting the issue. This is related to #1398 
I can confirm that this is not a bug. This is as per current design. The preview that you see is intended in order to keep the dropdown widget editor preview minimal and consistent with other widget types. 

However, you can raise this issue details as feature or existing feature enhancement request using _**_'Feature Request'_**_ form under help section. Also you were given the ability to create a custom dropdown widget to suit your needs. I advise you to try to create a custom widget to see if that works for you. Thanks

**Comment by nicopotgieter** [comment]
Hari

 

Than you for feedback and clarification.

The learning curve is steep as this is all very new to me. 

I will look into the developing of a Custom Widget.

 

😊

 

Nico
