### ISSUE TITLE
Textfield value disappears when switching page in a PageView when Autocomplete is ON

### ISSUE THREAD

**Issue by Torkilws** [FlutterFlow/flutterflow-issues#1446]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

(Only) When using Autocomplete in a TextField; after typing in text manually or selecting an autocomplete option and then switching page in a PageView and then going back to the page with TextField, the TextField value is no longer visible.

This issue is ONLY present when Autocomplete is enabled.

### Expected Behavior

Going back and fourth between pages with a TextField widget will keep the value inside the textfield.

### Steps to Reproduce

1. Create a page with 2+ pages
2. Add PageView
3. Add TextField to first page
4. Enable "Autocomplete" on TextField
5. Run
6. Type in text in TextField
7. Switch page and go back
8. TextField text is now gone

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESlMmA5c9goblH0LnqcMdqhQMjNlx7bZAnktV+WRMhfKr1EIYXOsj8YRNLYteqS1BcHmKKnkQ0097evt71FcY3GEmqf65S+ZRXQRXLVl6nMb62PZe8R3dBGcBQJlC/3KS3rBNAIuN0V3Al7WWtN/CdG3qCf9qOYwx5e6fDbOY=

### Context

This issue makes the Autocomplete feature unusable in my project. Which is a shame, cause it would be very useful.

### Visual documentation

Issue preview in my project:
https://github.com/FlutterFlow/flutterflow-issues/assets/15776477/459fe9f0-b475-4c42-96eb-104453f9dc1f

Issue preview in empty project:
https://github.com/FlutterFlow/flutterflow-issues/assets/15776477/0bf23995-017c-40bd-9246-28e9766e62fd

### Additional Info

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/15776477/7a143599-e9f3-45f3-a840-729d3a778ffa)

### Environment

```markdown
- FlutterFlow version: FlutterFlow version: v3.1 (released Sep. 7, 2023)
- Platform: Windows Desktop Web
- Browser name and version: Chrome Version 116.0.5845.180 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Home
```

**Comment by hariprasadms** [comment]
Hi @Torkilws - Thanks for submitting the issue. This behaviour what you are seeing is expected. The reason is when page view changes the page, page view widget rebuilds its widget. You can handle this using app-states and pageview's on-page change action.

**Comment by Torkilws** [comment]
How is this not a bug when this does NOT happen when Autocomplete is turned OFF ?

**Comment by Torkilws** [comment]
@hariprasadms This is how it looks when it is working (with Autocomplete on the TextField turned Off):
https://gyazo.com/6d0c57d57bfb2545f7dc59d5a5c509a8

What got from your message is that you mean all TextField values should be removed when a PageView page is changed, which makes no sense to me.

**Comment by wenkaifan0720** [comment]
Hi @Torkilws. When autocomplete is on, the textfield is not using a controller that stores its initial value, and when you switch pages in a page view, the auto complete text field gets rebuilt and the current text is lost. 

I have two workarounds for now: 1. use the TabBar widget instead and turn on keep tab state alive. PageView is really for displaying information and not interacted with. I would suggest you using the TabBar widget in this situation. 2. If you really want to use the PageView widget, I would suggest you create a string page state, set the initial value of the textfield to that widget state, and then add an onChanged action on the textfield that sets the page state to be the text of the textfield. This way you essentially create a page state that syncs with the textfield and it will not be lost when you switch pages in a PageView. 

I will also bring up the idea of adding keep state alive to the page view to our team. Since it is more like a feature request, I will close this issue for now. Thanks!

**Comment by Torkilws** [comment]
Thanks @wenkaifan0720 for the clarification. I was not aware that PageView is not designed to be interacted with, is this written somewhere? Replacing it with a TabBar will be troublesome as the PageView contains large amounts of data and systems. I will try with the page state variable approach.
