### ISSUE TITLE
RevenueCat "Null check operator used on a null value" (Grey screen)

### ISSUE THREAD

**Issue by janvanman** [FlutterFlow/flutterflow-issues#1449]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have configured RevenueCat pricing but I'm just getting a grey screen back. When running it locally in Android Studio, or directly on an Android device or iPhone, I get the message "Null check operator used on a null value". The RevenueCat setup and Android / iOS setup for subscriptions has been done correctly but I'm still not able to get the price strings back.  This is for displaying RevenueCat prices using RevenueCat > Current Offering > Package by identifier.  

### Expected Behavior

The price strings should display the value set up in RevenueCat.

### Steps to Reproduce

1. Create new page
2. Add a text element
3. Set the text element's value by clicking on the value setting link
4. Select the RevenueCat > Current Offering
5. In the popup, under Options, select "Package by identifier"
6. In the Package Identifier value, add a valid RevenueCat package name
7. Under Options, select Price String.
8. Run project on physical device

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehc+Az49On70A+ofhbu5F/AMxJ1gjbJ0vhNVxRgEbNZSrOqQTbuveRHdZUvWKTW9tfWKZnkEF0MLejvOXFe0qAweEQ5tywbl6aT3wcFuRRaagC5CgPnwlBp5UGBWb0MHU2SYnGMV0S10uig/GSw==

### Context

This issue is preventing me from displaying pricing and accepting payments for in app subscriptions.  The issue is holding up the app launch.  

### Visual documentation

![Screenshot 2023-09-13 092123](https://github.com/FlutterFlow/flutterflow-issues/assets/10946243/14aae108-e563-45fd-8f31-3cd90c9ae2be)
![Screenshot 2023-09-13 092028](https://github.com/FlutterFlow/flutterflow-issues/assets/10946243/b88f001a-5866-4b1f-ad19-b96c34fdd5fe)
![Screenshot 2023-09-13 092224](https://github.com/FlutterFlow/flutterflow-issues/assets/10946243/5400d0b9-57ee-462f-99a9-00faebe86869)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Android and iOS
- Browser name and version: Chrome 116.0.5845.187 (Official Build) (64-bit)
- Operating system and version affected: Android 11 RKQ1.200826.002 and iOS 16.4.1
```

**Comment by nathanwright17** [comment]
Saw the issue here too: https://github.com/FlutterFlow/flutterflow-issues/issues/1009

Been having the same issue after iOS App Review flagged the bug on my submission - with a gray screen of death showing when they tried to access the paywall on iPad. I ended up having to hard code the text prices with USD indicator because I couldn't fix it. It could be a slow connection issue between the parties? As I was only able to reproduce when accessing the paywall page quickly from app open, and it was occurring most on iPad (was using the latest iPad Pro 12.9inch) especially when using mobile hotspot.

I tried the pre-load option for Revenue Cat that Flutterflow has, but it took way too long for the app to open - always over 5 secs, sometimes even over 10 secs! And no pre splash or loading indicator, just a blank screen for that long before you even get to your splash image. So it wasn't an option.

Also having an issue with Revenue Cat subscription purchases taking a long time, over 8 secs, and another 5 sec delay after purchase confirmation. I've put in a message that pops up on purchase to let the user know it will take a while - hopefully it's enough to pass App Review since I can't do anything otherwise. They initially rejected it because they assumed it was a bug and that the loading indicator would be spinning indefinitely.

This is testing done on actual devices using Test Flight btw. I get the red screen auth issue error from the reported issue #1009 above when running in Test Mode - assuming due to Revenue Cat not working for web.

**Comment by coffeelydev** [comment]
I've spoken with RevenueCat's support regarding this iOS issue, and they've assured me that there are no issues on their end. It seems that the implementation in FlutterFlow might be the root of the problem. This is my top priority because I'm currently unable to bill my iOS users. 😞

**Comment by aemelyanovff** [comment]
@janvanman Thanks for reporting the issue. I can't say for certain without looking at your RevenueCat configuration, but most likely you set wrong package id.

The easiest way is to set it like this:
![Screenshot 2023-09-22 at 3 34 40 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/9c8cb505-c85a-4541-be88-db642713de95)

Alternatively, you can set package id like this:
![Screenshot 2023-09-22 at 3 36 18 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/0ec21458-0a6e-472d-b9d9-74f300319cea)

Note that if your RC configuration looks like this
![Screenshot 2023-09-22 at 3 37 00 PM](https://github.com/FlutterFlow/flutterflow-issues/assets/92294640/2172ffc7-fc57-4a05-9fa0-550a02ea0ada)
then the package id that you need to set in FlutterFlow is `$rc_weekly`, not `Weekly`.

I hope this helps!

Please reach out to FlutterFlow Support if you need further assistance.

**Comment by trevorFields** [comment]
This needs to be re-opened. the issues is: revenue_cat.offerings!.current!.annual!.identifier any time you are accessing revenue_cat, i have even check this in the logic, all kinds of different ways, is ff puts ! (even in logic checks), so you can't check that it is loaded.

in ff there is no way to check that "offerings" exist, it goes straight to picking an actual plan with !, so there is no way around this.

there needs to be ability to check if revenue cat is loaded yet.

**Comment by karansm97** [comment]
``` import 'package:purchases_flutter/purchases_flutter.dart';

/// packageOption: "weekly", "monthly", "threeMonth", or "annual"
Future<String> getPackagePriceString({
  required String packageOption,
}) async {
  try {
    // 1. Fetch your offerings
    final offerings = await Purchases.getOfferings();
    final current = offerings?.current;
    if (current == null) return '';

    // 2. Pick the right package
    Package? pkg;
    switch (packageOption) {
      case 'weekly':
        pkg = current.weekly;
        break;
      case 'monthly':
        pkg = current.monthly;
        break;
      case 'threeMonth':
        pkg = current.threeMonth;
        break;
      case 'annual':
        pkg = current.annual;
        break;
      default:
        pkg = null;
    }

    // 3. Return the localized price string or empty if missing
    return pkg?.storeProduct.priceString ?? '';
  } catch (e) {
    // swallow errors and return empty
    return '';
  }
}
```

Use this custom action in page load instead of flutterflow Revenue cat integration action. This fixed my issue. Flutterflows revenue cat integration code is incorrect and causes null check error.
@trevorFields is correct.
