### ISSUE TITLE
Special characters do not display correctly

### ISSUE THREAD

**Issue by hulohot** [FlutterFlow/flutterflow-issues#1456]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I need to show superscript text like this m<sup>3</sup>.

In Flutter I am able to do this with the command 'm\u00B3'.

But in FF, it appears that there is an extra '\\' character appended turning the string above into 'm\\\u00B3'.

### Expected Behavior

The string 'm\u00B3' should display as m<sup>3</sup>

### Steps to Reproduce

1. Create a new page
2. Add a text widget
3. Put any special character as the text value, such as 'm\u00B3' 
4. See the text displayed as 'm\u00B3' instead of m<sup>3</sup>

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fkufqxIt1j7xZ1rqBc8Iwgj8sJmY6RY0/m+0bURQgfIvqB+0qOsz7VxNJYsOGdwlIJFmj8XgK0qHGvuDuVsA3PgeVQ4Nez7pMVA/NcF+QbJCRDpGOYXZCQZ5QCU/H5raWmA9TKrBtLSRn2WDzAu6vThHbCZzvIEcBPf38B5LIo3i7LnjrDDtrwmNecCfn

### Context

Unable to show the text as expected.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/38847800/d40c9b06-95d2-472b-8eed-e45abdb0a6fd)

### Environment

```markdown
- FlutterFlow version: 3.1v
- Platform: Web
- Browser name and version: Chrome 116.0.5845.82
- Operating system and version affected: Ventura (MacOS) 13.4
```

**Comment by hulohot** [comment]
This can technically be bypassed by using a code expression, as seen here.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/38847800/21f1e72d-8169-448d-83af-419fd2c1b2c5)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/38847800/cc373824-517c-46e1-acb3-0844001feb01)

But that will not be sufficient for my workflow.

**Comment by hulohot** [comment]
Here is the code for that page after it has been downloaded.
```dart
child: Column(
  mainAxisSize: MainAxisSize.max,
  mainAxisAlignment: MainAxisAlignment.center,
  crossAxisAlignment: CrossAxisAlignment.center,
  children: [
    Text(
      'm\\u00B3',
      textAlign: TextAlign.start,
      style: FlutterFlowTheme.of(context).bodyMedium.override(
            fontFamily: 'Greycliff CF',
            fontSize: 50.0,
            useGoogleFonts: false,
          ),
    ),
    Text(
      "m\u00B3",
      style: FlutterFlowTheme.of(context).bodyMedium.override(
            fontFamily: 'Greycliff CF',
            fontSize: 50.0,
            useGoogleFonts: false,
          ),
    ),
  ],
),
```

**Comment by agreaves** [comment]
Hi @hulohot, thank you for the bug report! Unfortunately, strings in FlutterFlow are treated as literals, so at the moment we do not support passing in unicode characters directly into a String. This is primarily because it isn't always clear that a user is trying to use the `\` as a unicode character vs a literal `\` (which generally needs to be escaped with an additional `\` as you observed).

In theory we could try to do something clever / hacky and detect whether the string contains a unicode character (e.g. `\u00B3`) and then not escape the leading `\`, but this may or may not be best practice. At the very least it isn't available at the moment and would more be considered a feature request.

In the meantime, I would recommend creating a custom function to return `\u00B3` explicitly (or any other unicode character you like) and using that in a Combine Text to append it to any String that you need in the builder. Hope this works for you! Thanks again for the report.
