### ISSUE TITLE
Data Type can't be used in old Project as App State Type

### ISSUE THREAD

**Issue by JanikHalder** [FlutterFlow/flutterflow-issues#1457]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I wanted to change the App State Variables from JSON to Data Struct in an older project, but there I'm not able to select Data Type as the Data Type of the Variable.

This issue seems only to appear in some of my old projects.

![Bildschirmfoto 2023-09-15 um 09 09 39](https://github.com/FlutterFlow/flutterflow-issues/assets/95503532/a658eab1-8305-4817-bcfd-3916cedbf3cb)

### Expected Behavior

I guess it should be possible to select Data Type as in new projects.

### Steps to Reproduce

1. Create a Data Type
2. Create a new App State

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jcrq25VNsdtF+KryKPlFnmU5KVN7a40s0NV7aCosfZT2BLMcec/RVERoZNPkTXx6eFn8v2oW3N7ojuDuGu0CITeqftx8yJBMSQ/gZEalb6qRFJWgWnFCEp5WfXK436e3sxB/PrRYclIC3E6xfO+9TXPaH7rSOFUaDq/LZO4=

### Context

Changing my old App State Variables from JSON to Data Type.

### Visual documentation

![Bildschirmfoto 2023-09-15 um 09 09 39](https://github.com/FlutterFlow/flutterflow-issues/assets/95503532/75385c2e-211b-4a6a-a4f6-52bbb2ca4fb5)

### Additional Info

This issue just seems to appear in old projects.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by joshua-ffio** [comment]
Hi @JanikHalder, this issue is very similar to this issue: [Custom Data types disappeared from App State ? #962](https://github.com/FlutterFlow/flutterflow-issues/issues/962). Please try the solution in this ticket to see if it fixes your issue.

Additionally, because this issue seems to be unique to your specific project, this ticket is classified as a support request so I will be closing this ticket. If the solution mentioned in the link above does not fix your problem, please use chat support or contact support@flutterflow.io

Thank you!
