### ISSUE TITLE
False breaking crash/Ivalid action errors don't allow for any modification whatsoever 

### ISSUE THREAD

**Issue by Gavalakis** [FlutterFlow/flutterflow-issues#1460]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

At  some point my project could not be edited any more because anything I did returned a breaking error message like "a column can not be set to scrollable if it has an expanded child" which in my case doesnt  actually exist anywhere... It actually can be edited but if I click away from the page edit menu it reverts my last step (doesnt matter what it was)

### Expected Behavior

If I delete a random row or change text, it should remain as I changed it.

### Steps to Reproduce

I have no idea how it happened, just after deleting some backend stuff and adding youtube preview the whole thing begun to bug out more and more

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi/Lqw49Om9hE7s7uccBvnSQ7KW42aIJN0MpBZywgfZzzBLN/fPfQP0lDUtPmYHNtememp14K3M6OiN/hUPYBIRKZGaE6wbVQWw7yfGWgRZOTF7rhSXNTMJhNCkCx5J6rgyN4KrBhc04G7GC6P/OAbHfUQ4y3NXo8Sq/LZO4=

### Context

Creating a frontend concept of an application for an important university project.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/61183477/b206071c-8a4a-4cd7-a07b-93894ec84276)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform: Web
- Browser name and version: Brave and Microsoft edge
- Operating system and version affected:
```

**Comment by joshua-ffio** [comment]
Hi @Gavalakis, I've taken a look at your project and am unable to recreate any of the issues you have mentioned. This issue tracker is intended for general bugs that are applicable to all users, and because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support@flutterflow.io for further assistance. We appreciate your understanding.
