### ISSUE TITLE
Arrow keys in text fields navigate up and down layers

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#1461]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When focusing on a text field in FlutterFlow's inspector (right) menu, placing the cursor at the beginning and pressing the left arrow makes FF jump to another field. When pressing Cmd+Left (jump to beginning), chrome navigates to the previous page.
This makes FF absolutely unusable.

### Expected Behavior

Using arrows in text fields should not affect anything else but the text field.

### Steps to Reproduce

1. Create a text field
2. Click on "Text" in the right inspector menu to set the text
3. Press the left keyboard arrow.
4. Another layer gets selected
5. Press Cmd+Left
6. Chrome navigates back to the previous page.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0rNlud0wdCeKuOrMuYPSlUFRpYuqHTVFIJleimTkGwe/Fkez1LMJfCEyeQIQ5yJdxUxDjXj25MYyMDqmBdkRRO/JQGhSM1KeNmRNNNvh0WXAnwHGUId+ub3qCf9qOYwx5e6fDbOY=

### Context

Nothing to add

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/12573714/df746263-020d-47c8-ae6c-957446d963c5

### Environment

```markdown
- FlutterFlow version: 3.1 Sep 15
- Platform: Chrome
- Browser name and version: Chrome Version 116.0.5845.179 
- Operating system and version affected: MacOS
```

**Comment by jpollone** [comment]
I can confirm. I notice this when attempting to modify an object's name property with having to use the mouse. It appears intermittent.

For me, I notice this happens when attempting to rename a Row, but will then extend to other objects. I select a Row, click on the name property, tap left arrow to move to front of the property to rename, and the focus moves to other widgets.

I tested multiple clients listed below with the same issue. The work-around is to use the mouse to select and highlight the property.

### macOS 

#### Platforms
- Desktop client, Version 1.1.102 (1.1.102)
- Chrome , Version 117.0.5938.88 (Official Build) (arm64)
- Arc Version 1.8.1 (41651), Chromium Engine Version 116.0.5845.187

Also note that I rebooted and took the Apple TouchID keyboard out of the equation too.

**Comment by scharfschiesser** [comment]
Occurs for me too, MacOS Desktop version 1.1.103

**Comment by agreaves** [comment]
Hi @kium-one, thanks for the report! This is the same issue as #1475 and has since been fixed. 🙂

**Comment by kium-one** [comment]
Ps. there have been similar bugs these days that could have easily been caught before reaching production, which is disruptive for a huge amount of users. Is there a beta testing environment where we can try those features before they're released?
