### ISSUE TITLE
Icon Button Hover Fill Colour is Broken. Only one colour no matter the settings

### ISSUE THREAD

**Issue by chuggmuffin** [FlutterFlow/flutterflow-issues#1470]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/75537b3e133445e69a8eae4af7f55273

### Expected Behavior

https://www.loom.com/share/75537b3e133445e69a8eae4af7f55273

### Steps to Reproduce

https://www.loom.com/share/75537b3e133445e69a8eae4af7f55273

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WjuflvYt1xPVA1pDMKcBvmjw5JkQ8a+dIjsN+EBA3GIz1P7YPQvj7PxFUcO2iT2NpemGkpHgX/Mr5huH9KPcqNSmAbpRh+pF6SgLgJXOuRc2aBb63b2tTM8RTI3Kj0JmJuSVQWcB0WlIs2k+UHem+fDLfHqbQCzM4AOa4XdeK2SrDX1iXc2URm05KZDPz

### Context

https://www.loom.com/share/75537b3e133445e69a8eae4af7f55273

### Visual documentation

https://www.loom.com/share/75537b3e133445e69a8eae4af7f55273

### Additional Info

https://www.loom.com/share/75537b3e133445e69a8eae4af7f55273

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @chuggmuffin - Thanks for submitting the issue. I looked your project and widgets are in the page. I can confirm that the behaviour what you are seeing around fill colour and button hover style colour is as expected. When button hover style is enabled and colour code is same in the both places, on mouse hover it indicates there is a slight change in the colour. its the flutter material button widgets default behaviour. 

When you switch to a secondary background colour type, it looks like you have not rebuilt the project thats the reason you are not able to observe the colour change. 

_I can confirm that the issue is not a bug._

**Comment by chuggmuffin** [comment]
What does rebuilt the project mean?

I pressed the reload button multiple times.

**Comment by chuggmuffin** [comment]
Also, your explanation does not explain what happens with the last,
default button colour.

Please check again

**Comment by chuggmuffin** [comment]
Here's a video response.

Its a bug 100%

https://www.loom.com/share/ac82a7b82f124a07a96aeabf1e9291f6

**Comment by wenkaifan0720** [comment]
Hi @chuggmuffin. This is indeed a bug (or at least an unexpected behavior). IconButton, as a material widgets, will add an overlay tint color on top of itself when it is hovered/pressed, to emphasize that it has been hovered/pressed. Since we allow the user to explicitly set the hover color, I think it makes more sense to remove this overlay color (at least for the hovered state).  This fix should come in our next update. Thank you!

**Comment by chuggmuffin** [comment]
Fascinating!

Thank you for letting me know.

One of the strange joys I have taken while learning to program is seeing
the little quirks that pop up when features collide.

It's cool to know that Flutter itself added the feature but flutterflow has
to explicitly turn it off, vs turn it on.

Really neat!

Thanks for following up!

Brian
