### ISSUE TITLE
Screenshot Mode App Bar is too large

### ISSUE THREAD

**Issue by Fibn007** [FlutterFlow/flutterflow-issues#1485]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In Screenshot mode, I have my app bar size set to 5% of height and it is appearing like this:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/b6bfda8b-c6cc-4933-91d5-85b5449a8f5c)

### Expected Behavior

App Bar should be significantly smaller, like this:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/43394475/6d7c2274-1a78-444d-b8e3-76457fa69f6d)

### Steps to Reproduce

1. Create a new page with an app bar set to 5% of the screen height
2. Enter preview mode
3. Select the screenshot mode option
4. Select the page you created
5. View the incorrect app bar size

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48kvLlw4tNrsdG+KXydcFFmjgWQ187aLsVi+5tTUs8KOPcPZYETPTOTERtTfW4TQhIP02jkWoW0crRufz1LsEqC0iBfapI1qhMSQyXIT+hM76LFJWge3ZRM+5RCW6Yy7SJpB1+GMt1SGwb61yyDPO9QgTbJ4CzDFgsDq/LZO4=

### Context

Trying to grab screenshots for a new deployment and the images aren't 1:1 with my app.

### Visual documentation

Added in explanation of behavior

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Windows Desktop App
- Browser name and version: Chrome Version 116.0.5845.188 (Official Build) (64-bit)
- Operating system and version affected: Windows 10
```

**Comment by sbis04** [comment]
Hey @Fibn007, this is because AppBar by default uses the SafeArea to prevent the device notch and device status bar from overlapping any important UI elements present inside the AppBar. Even in the Builder, if you enable "Display Device", you will notice the AppBar having more height to accommodate the device notch (if any). Disabling "Display Device", toggles off the device safe area in the builder.

In screenshot mode, we enforce the safe area to maintain the authenticity of an actual app screenshot taken on a device and is required to satisfy the App Store and Play Store guidelines.

**Comment by sbis04** [comment]
Now we have enabled the safe area in the builder too to prevent this confusion. It should be available in the next update!
