### ISSUE TITLE
Animation issue

### ISSUE THREAD

**Issue by yunieskyaleman** [FlutterFlow/flutterflow-issues#1493]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When an animation in a widget is activated with "hide before animating" and a delay. The program run ok but when animated again (ej. when the page opens again) I get this error:

_AnimateState is a SingleTickerProviderStateMixin but multiple tickers were created.

That won't happen when I disable "hide before animating"

### Expected Behavior

Animate again while open the page again and again.

### Steps to Reproduce

Create a widget
Animate it
Check "hide before animating"
Set a delay. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wi87huJZOxLRC1aqNd+9VgjgXNlw6U5I7m8N9cAEYF5fmPbYPX/z4UBJoTbyndkFbfWCkgno1w8rMm9z1UPUBAAqeQIc/1s1iVjrdeF6lacjQDZGROGtuGshnI0vF1Kuv2SVQVfV2c1Ut7TqDfuyub3PaK4zUDFcnNeW1OpPXrgfuQ0SLb3kNh1JWeC/v

### Context

The page crash

### Visual documentation

<img width="305" alt="Screenshot 2023-09-20 at 9 25 12 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12021617/f90351a7-af7c-47b8-9e3a-f6880ede79ad">
<img width="434" alt="Screenshot 2023-09-20 at 9 26 19 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/12021617/5488b6a1-07f8-42ef-bdeb-9c88b736d444">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: iOS
- Browser name and version: Chrome 116.0.5845.187 (Official Build) (arm64)
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @yunieskyaleman - I did test the issue. but, not able to reproduce. The steps are not fully clear. And also above give project bug report code is not from blank project with issue steps setup. All these details.

Answer these please.
Create a widget - _What type of widget ?_
Animate it - _What type of animation ?_

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!
