### ISSUE TITLE
API is not displaying data in downloaded APK build

### ISSUE THREAD

**Issue by GillbertWong** [FlutterFlow/flutterflow-issues#1494]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

During the Run Test, all the features were working, and all data was displayed until when I built the APK and tested it in the mobile app, none of the APIs worked.

### Expected Behavior

It should be workable even when I build APK or IOS & IPA. 

### Steps to Reproduce

1. Build APK 
2. Login with URL "http://projectonesalesa01.ddns.net/CRMtest"
3. username: admin, Password: admin
4. click on Sales Inquiry 
5. Should have data displayed 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ohfLl8ZNPxLxY1pSJccBKjSQvHFA7a+c3jMpBZywgfZzzBLN/fPfQP09vTsilYAk/fVmMp14yw/T1ifLPKewqGwSWQKY5yc5XWwnzWluVVrmTF7qCOkZQGcRYCHK64Jivpgl+JthpcUZi3HGEHd6+f3TsO7rLDmowSq/LZO4=

### Context

The app is not workable.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/33408039/ed7ab758-8a26-4745-aa73-bcbb78b99301)

### Environment

```markdown
- FlutterFlow version: v10 (released Sep 21, 2023)
- Platform: mobile
- Browser name and version: Version 116.0.5845.188 (Official Build) (64-bit)
- Operating system and version affected: Window
```

**Comment by hariprasadms** [comment]
Thanks for submitting the issue @GillbertWong. Please update issue with project bug report code. Environment details are not fully clear. Platform says only Mobile. I assume it is Android mobile build.

**Comment by GillbertWong** [comment]
Hi Flutterflow,

May i know how do i update project bug report code cause is all the pages
which related to API calls.

Yeah is Android mobile build will edit the issue list later on.

Thanks
Best Regards

**Comment by hariprasadms** [comment]
To get project bug report code, goto any page widgets tree and right click then you can see the option. 

<img width="498" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/3a6ed041-1c89-4d72-9f49-719029a5a2c3">

**Comment by hariprasadms** [comment]
Hi, Thanks for updating the project report code. I have noticed you have not assigned the URL and Token states values in appstate where you are using those states in the request. That could be the issue. 

 However, when I tested with the downloaded apk and code I see the same issue you are experiencing. Looks like it is project specific issue.

Dev Note - 

- It works fine in FF web and debug run modes.
- its does not work in downloaded apk, local Androoid and iOS builds 
- It does not work in local web build. 
- The same end point works fine in postman.
- Stored app states are not appearing in downloaded code - _This is strange one as I can see other projects app state variables with its values can download with no issues._
- 
Postman response
<img width="1198" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/645da0f8-f270-4a77-b02a-019d3b574018">

**Comment by hariprasadms** [comment]
Hello, the dev team has looked into this issue and this is the update. 

**The reason why downloaded apk build is not able to fetch data from Api -** API calls made from Test Mode/Run Mode are routed through FF side of CORS proxy and calls made from APK/local web aren't. Hence your API end point looks like private end point and it needs a valid proxy channel to communicate to external world. This is something you should check at your end. 

Options to try,

- Firebase private Api.
- Check is there any proxy details for the end points you are using in the app.

I would suggest contact FlutterFlow support team to get more technical help. This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project, the issue is classified as a support request and will be closed.
