### ISSUE TITLE
AudioPlayer doesn't work in iOS 17

### ISSUE THREAD

**Issue by superkeven2020** [FlutterFlow/flutterflow-issues#1503]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

AudioPlayer doesn't work in iOS 17
https://docs.flutterflow.io/widgets-and-components/widgets/base-elements/audioplayer

We didn't change anything in our APP, however after we updated to iOS 17, the audio doesn't work.

### Expected Behavior

We expected the AudioPlayer work in iOS17.

### Steps to Reproduce

Simply run the AudioPlayer in iOS 17. You will find it doesn't work.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl+fl4otNxOFb14SJKsJommUvC2kcT5A709VuTQ4sCKL2O4kQdvWlVBZoON+6dFZYP0Smmj0FzMrohYXPA+0qFymrY6ZY/rpqEALMYD2ta5OBPaqCZUBBO8JMFWKAyqWk3BZ7ALZhWHAC31+AC9/LZCzDNOf4IlFISq/LZO4=

### Context

User can not use our main function in the app which have to run the audio player

### Visual documentation

no information 

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: ios
- Browser name and version: ios APP
- Operating system and version affected: ios17
```

**Comment by hariprasadms** [comment]
Hi @superkeven2020 - Thanks for posting the issue. When you says audio player is not working in iOS 17, is it not working on any of the latest iphone versions -  iPhone 12 to 14. Please confirm these details. 

In this instance I would suggest first reach FF support team for more help. This doesn't qualify for the issue tracker since it's specific to a version of phone device. Please use chat support or contact support@flutterflow.io. If they confirm it's an issue, you can come here we can start investigating the issue.  I hope it can help you. Thanks

**Comment by superkeven2020** [comment]
Hi Hari

I only tested on iPhone14 pro.
I believe this is not because the device, but because the version of iOS.
It was working on same device before I updated to iOS 17.

This is very urgent for us. We are losing customers.

Thank you.
Kai

On 22 Sep 2023, at 10:51, Hari ***@***.***> wrote:



Hi @superkeven2020<https://github.com/superkeven2020> - Thanks for posting the issue. When you says audio player is not working in iOS 17, is it not working on any of the latest iphone versions - iPhone 12 to 14. Please confirm these details.

In this instance I would suggest first reach FF support team for more help. This doesn't qualify for the issue tracker since it's specific to a version of phone device. Please use chat support or contact ***@***.******@***.***>. If they confirm it's an issue, you can come here we can start investigating the issue. I hope it can help you. Thanks

**Comment by hariprasadms** [comment]
Hi, I tested it on iOS 17.0 simulator. I can see there is platform exception. I can mark this as bug. Thanks

<img width="1387" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/f6de08f2-85f3-41b7-ad11-2bb7a72fc7f4">

**Comment by superkeven2020** [comment]
Thanks Hari
Please keep me in updated about when you can fix this bug.

Best regards
Kai

On 22 Sep 2023, at 14:23, Hari ***@***.***> wrote:



Hi, I tested it on iOS 17.0 simulator. I can see there is platform exception. I can mark this as bug. Thanks

[image]<https://user-images.githubusercontent.com/17435678/269949738-f6de08f2-85f3-41b7-ad11-2bb7a72fc7f4.png>

**Comment by superkeven2020** [comment]
Hi Hari
May I have update about this bug fixing?

**Comment by joshua-ffio** [comment]
Hi @superkeven2020 , we have looked into the issue and it seems like this turns out to be an issue with the Flutter pubdev package dependency for devices running iOS17 while trying to play audio in the base64 string format. In addition, the FlutterFlow AudioPlayer documentation does not mention support of this type of audio format. We apologize for this inconvenience, but unfortunately, this means it out of our hands to address this issue directly, as we never directly supported this usage. However, we will consider this type of format support as feature request when we start planning an update to the FlutterFlow AudioPlayer in the future. We appreciate your understanding.

**Comment by superkeven2020** [comment]
Hi @joshua-ffio This still not clear for me.
Who is responsible for fixing this issue? And any alternative audio player I can use?

**Comment by superkeven2020** [comment]
@joshua-ffio  Please reopen this case, This audio player is a part of the standard widget, please fix this issue , or remove from Flutterflow standard widget.

<img width="321" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/76756569/9fe208ea-a33f-4a5c-a2a0-9c0f6a044e49">
