### ISSUE TITLE
Reorderable ListView handles do not show in Mobile Web browsers

### ISSUE THREAD

**Issue by vguruv** [FlutterFlow/flutterflow-issues#1516]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Reorderable ListView Handles do not render in Mobile Web browsers

### Expected Behavior

Reorderable ListView handles should show in Mobile Web browsers, just like in desktop browsers.

### Steps to Reproduce

Create new page. 
Add ListView with text in a container, wrapped in column.
Publish to web - there is no handle visible for the rows in android or iOS browsers.
Example: https://app.flutterflow.io/project/reorder-issue-8cisor

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hvHlsIZ2sdtJ+KrUY8Axmjw5JWIlaI0zlOxBaCotCLbkOpgcf/fOYkRvZOHidG9qPmKj/GoW0PT9i9nxNsIBBEmeG91j+JYNYQvjQlqmV66hFJWgS2slP8VNGGqMyLTY2h15IuhZV3Bi1GaUFuSucHXqQpezIVcsDq/LZO4=

### Context

Reorder list view in web on mobile browsers

### Visual documentation

![Screenshot_20230924_124617_Chrome](https://github.com/FlutterFlow/flutterflow-issues/assets/3235596/f70013f4-ff3d-41d9-9be8-99a5d4dd3d47)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by agreaves** [comment]
Hi @vguruv, thank you for the bug report! This is actually the expected behavior of the Material [Reorderable ListView](https://api.flutter.dev/flutter/material/ReorderableListView/buildDefaultDragHandles.html). Drag handles are added on web and desktop, but not on mobile, where a drag is instead triggered by a long press.

I understand this is not documented or explained well, however, and I apologize for that. We're going to add more information in the tooltip in the next release, as well as in our documentation. Thanks!

**Comment by vguruv** [comment]
The space allocated to the drag icon is still blocked when the drag icon is invisible, resulting in a blank space where long-press-drag does not work. Do you want a separate new issue for this?
