### ISSUE TITLE
Not all Google Fonts are available in the app

### ISSUE THREAD

**Issue by ibadmore** [FlutterFlow/flutterflow-issues#1517]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Unable to use this google font: https://fonts.google.com/specimen/Unbounded

### Expected Behavior

Should be able to access all the google fonts

### Steps to Reproduce

try to add this google font to a project: https://fonts.google.com/specimen/Unbounded

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

1

### Context

Unable to use this google font: https://fonts.google.com/specimen/Unbounded

### Visual documentation

<img width="624" alt="Screenshot 2023-09-24 at 12 42 25 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/122062584/3cc6e031-23ff-4433-ba67-e45478b1f125">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by agreaves** [comment]
Hi @ibadmore, thanks for the report! The font you're referring to is a recent addition, so it's not currently present in the version of Google Fonts we are using, but we'll likely update the version of the package in the near future! This isn't a bug strictly speaking because In general, we can't always guarantee every font will be present, but we'll do our best to keep it up to date. Thanks!
