### ISSUE TITLE
Auth Update Email is not working

### ISSUE THREAD

**Issue by minashawky** [FlutterFlow/flutterflow-issues#1522]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I previously used to use the Auth Action "Update Email" to update the user auth email address when they request it. It seems this action is no longer working or updating the emails after FlutterFlow 4.0

### Expected Behavior

Once I request Update Email the email record of the user should be updated

### Steps to Reproduce

1. Create an Edit Profile Page that includes an email Text Field widget wrapped around a Form Validation
2. Set the Form to validate the email field is in a correct format
3. Add a "Save Profile" Button
4. In the "Save Profile" call "Backend Call" - "Update Document" and set the email field
5. Call the Auth Action "Update Email"
6. Call the Auth Action "Send E-Mail Verification Link"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sksrl7ZBItbxJ7qr+csZR/WE6OW55a4JFscsZa0kdB4joPLJ/OeP4VBdCTcOqd0NhHE2LjkgJ/t6NudrtFPY3GyiCbJhdyal6FAr/VXq8R5CzBaWoS0FCPJpYJkCc4cCRkBFvJftocngO21+UJt6yShXYN5+/Zwh9f6PHaOI=

### Context

I have users authorized by phone number + OTP... The following step is to create their profile (collecting their display name, email address, etc...). I wanted to add their email to their auth user account and ask the user to verify it.

### Visual documentation

<img width="1513" alt="Screenshot 2023-09-25 at 8 19 36 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6050173/30f4e729-b1db-4c72-8c35-f86ed91f0e12">

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome Version 117.0.5938.92 (Official Build) (arm64)
- Operating system and version affected: MacOs 13.5.2 (22G91)
```

**Comment by hariprasadms** [comment]
Hi @minashawky - Thanks for reporting the issue. Setup the issue in a blank project and share the bug report code. The above given bug code is not feasible as its a real project and got many pages. Can't locate the issue.

**Comment by minashawky** [comment]
Hi @hariprasadms ... Sure thing... I created a new project with three screens:

1. Phone auth
2. Phone verification (OTP)
3. Update Profile

The problem occurs in the "Save" button in the Update Profile.

You can login with the following credentials:

- +1 650 555 1234
- 123456

And here's the bug report code: IT4sk8nlz49OtbxA1872KPlR/CcQNjN+ar8escsZa0kdB4joPLJ/P+DCTFBpZO3nTXlhHEyYnnEzpKnej87xDcc7OgStRrZGyal6aQ/xf3q8R5CzBaWoS0FCPJpYJkCc4cCRkBFvJftocngO21+UJt6yShXYN5+/Zwh9f6PHaOI=

**Comment by hariprasadms** [comment]
Hi @minashawky - Thanks for setting up a project and providing details. I looked at the project, I can see that your are trying to update the email field during authentication flow. To update email field, it should be created first. As per authentication flow I do not see create user record action. Hence the error what you are seeing is expected. Instead of update action after form validation, add create action. Try this and let me know how it works.

**Comment by minashawky** [comment]
Thanks @hariprasadms for checking... Actually it used to work before and I have a live app with it working... Please note the following:

- The authentication flow ends after verifying the phone number OTP
- The following page "home_screen" the user is already authenticated
- Update email used to update the "auth" user record by adding the "email" record first before sending the request to verify the email... Screenshot attached is for a real user that I had in my current live app (my own user so its ok to share it here)

<img width="1201" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/6050173/8c55e696-47e5-4b95-aa14-693d4e0ed4b7">

My concern is that this used to work before and now its not. Keeping in mind that my business logic is to verify with a phone OTP first then update the client profile with his email, but I do not require his email for authentication anytime.

**Comment by hariprasadms** [comment]
Thanks for the details.

**Comment by Ren929** [comment]
@hariprasadms 
Any update on this? I think I have the same issue.

**Comment by tywil04** [comment]
In my app I just encountered an issue that when I update a users email, it updates the user record in Firestore, not the email used for authentication even though the method is for Firebase authentication??

**Comment by tywil04** [comment]
I think I have a similar issue.

I first encountered the issue on a large project of mine and I was able to replicate this issue on a blank project with Firebase.

The blank project used Firebase and had 3 pages. One page is a sign in page that contains a sign in with email form. The second page is contains a sign up with email form and the third page is a home page that has an update email form (TextField + Submit button, the button has the Update Email auth method and it is connected to the TextField).  

The issue is when updating the users email using the Update Email auth method, the user record in Firestore gets updated however the Firebase Authentication email doesn't change. [Heres a video of my blank project showing the issue.](https://github.com/FlutterFlow/flutterflow-issues/assets/68185249/9dceb3ad-651c-40ba-8a05-0d68855c2e65)

Is this the same issue or should I create a new issue?

**Comment by hariprasadms** [comment]
Hi @minashawky - I have tested email update action. I can confirm that it is working as expected. There will be a email verification email sent to new email address. Once email is verified, user can see new email address updated in FB authentication section. Have you followed this step ?

**Comment by minashawky** [comment]
Hi @hariprasadms ... I tried again now the test project. I can confirm the email was received yet if you check the action flow there should be an alert dialog afterwards which didn't show up. It means the action threw an exception. Can you please check again.

**Comment by RonaldSancho** [comment]
Any update on this?

**Comment by hariprasadms** [comment]
Please refer update email doc - https://docs.flutterflow.io/actions/actions/backend-database/firebase-authentication/update-email
