### ISSUE TITLE
Permissions error on log out

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#1525]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

User goes to settings page, then navigates to a sub page, on that sub page they click on log out button (auth logout). When the user lands on the login screen again, a firebase permission error shows up.
When inspecting the error, it seems like a single-time query that was on the settings page is concerned.

I didn't touch that project's area in a while. The only thing that changed was me enabling deeplinks. Not sure if that's related.

### Expected Behavior

Queries are disposed properly on log out.

### Steps to Reproduce

1. Create root page with a query that requires the user to be authenticated (firebase permissions)
2. Create sub page and navigate there
3. Place a log out button.
4. When the user logs out and goes to login page, an error is shown.
I didn't test on a blank project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0sd4bGA0dCJzuPLMQdvWlblBoQuarTAk3M0SmmmUH0/COioXiG8AoYC+ZUaF8+ZZMegKXJUW5a5OBEpO3dkB6EelMJ2qZ0MKJryVBIsB0SHga6mWPe+vIUXTAJLL2ImdISq/LZO4=

### Context

Just logging out.

### Visual documentation

 @firebase/firestore: Firestore (9.18.0): RestConnection RPC 'RunAggregationQuery' 0x174b2d61 failed with error:  {"code":"permission-denied","name":"FirebaseError"} URL:  [........] Error querying Instance of '_JsonQuery': FirebaseError: [code=permission-denied]: Missing or insufficient permissions.

### Environment

```markdown
- FlutterFlow version: 4.0 Sep 20
- Platform: Chrome
- Browser name and version: Chrome Version 116.0.5845.179 
- Operating system and version affected:  Mac 13.5.2 (22G91)
```

**Comment by SameerShahzad99** [comment]
The problem seems to be project-specific, you have not shared a blank project reproducing the problem.
From the first sight this seems to be due to your firebase rules, for further investigation, please reach out to the FlutterFlow support using live chat or email (support@flutterflow.io) so you could dig deeper into the issue!

**Comment by wemmick** [comment]
@SameerShahzad99 For what it's worth, I can replicate this. 

Steps for me - first (mysterious) version:

- Go to Sign In page and sign in
- Land on homepage. Homepage does a couple of queries that depend on the user being signed in, as it does for OP. 
- Hit Sign Out button
- Land on Sign in page
- See "insufficient permissions" error

So, I loosened up my permissions a little, and tried again.

Second (enlightening) version:
- Same steps, but on the last step (Sign in), the error changed to an error saying I needed to create a new index on my `cars` collection.  This was a little confusing, as my Sign In page has no queries from the `cars` collection.

I realized that it was retaining the `cars` collection from the Homepage, and an index was required because the user was no longer signed in, so it wasn't limiting its query to the user's cars (cars in the user's cars subcollection), but all cars.

If it helps, my `cars` query is happening as a Backend Query on a row that I use to display cards (each one with a `car`.) The query is one-time, and cached. It will typically return 1-4 documents.

After some searching in an attempt to debug this, it seemed like OP's bug report has pretty much the same issue/symptoms.  Hope this helps.  I don't have time right now to set up a blank project (deadline impending), but I'll try after the deadline. Happy to provide any other info about my project if helpful.
