### ISSUE TITLE
Generate children doesnt allow to use custom function

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#1532]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

ListView doesnt allow to use an API-CALL response in a custom function to pass it to "generate children"

### Expected Behavior

The generate children should allow to use api response in a custom function

### Steps to Reproduce

1. create a blank project
2. add a page
3. add a listView widget and make an api call (using backend query)
4. in generate children section, try to use a custom function that take the "Apicall response" as param
5. you will see that you cannot pass the api call response as param

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40zsnf25NPmMMA7aqNcsJV+T45JjM2beY71+traCotCLbkOpgcf/fOYkRWXdTjdGxUfU2gmWoW0+DFhvPAVsdcCzqsGd16yLoBVDrzeD+5VYSyFJWve3R5Bf1Qf1Sc56TYmxMmA7ZfLFY+wU6uBuSQfBHqQJzyCkQ8Da/LZO4=

### Context

Can not transform the api response (using a custom function) to display items in listview

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/9128a4ba-b397-4ec2-903f-4c3b5d2d884e)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/89469783/e8872f9a-7d73-4037-94bc-f05cb4527ac7)

### Additional Info

When you inspect the project, this is the only error

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Web
- Browser name and version: Chrome  117.0.5938.92
- Operating system and version affected: Win11
```

**Comment by nev-21** [comment]
Hi, please this will be consider as a bug?

**Comment by agreaves** [comment]
Hi @nev-21, apologies for missing this completely. In short, the issue is that you cannot pass an API through a custom function if infinite scroll is enabled. In order to fix this you can turn off "Enable Infinite Scroll" in the query, as it was not actually configured in the first place (just enabled).
<img width="302" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/7757399/51b66ee5-0479-40f5-ab75-53c26c37ddc1">

**Comment by nev-21** [comment]
Hi @agreaves, than you

But why is 
this not possible? the api response (json body, or modified by a jsonpath) should be allowed to be passed to a custom function (to modify, chage structure, add compute fields, etc.) and the custom function returns an array that can be used in generate children.

If I'm not wrong, before I put this issue I was using custom function to modify the backend-query response, and it was working

**Comment by thachjackson** [comment]
Any updates FFTeams? I'm facing it too. I need to enable "Enable Infinite Scroll" and if I dont use custom function to fix the json path array, the jsonpath will return an element {"key":"value"} instead of an array [{"key":"value"}] and it would cause this error in listview:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/82443959/77bb6ca3-d0af-4691-84d6-977aa173830d)
