### ISSUE TITLE
Custom Map widget is not showing on component although compiled successfully

### ISSUE THREAD

**Issue by InceptMvpDevelopers** [FlutterFlow/flutterflow-issues#1534]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm creating google map in flutter using flutter dependency google_maps_flutter: ^2.5.0 and change it according to FF. It is compiled successfully in FF but this widget is not showing in component. 

### Expected Behavior

After the custom widget is compiled successfully. The custom widget should be showing on the component or on the page.

### Steps to Reproduce

1. Add Google map keys in FF google map setting
2. Created custom map widget using flutter dependency google_maps_flutter: ^2.5.0.
3. Created component for adding the custom google map widget.
4. Added widget into the component. 
5. It is not showing on that component

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESifHf08pgobxF7ZPcc8BAhQMkQzM6bZI7ku1EdwEhfa7qOrAfds7OXFZLYteGTW5be1qZqzkDw9bni9nPDvUnGz+rR4RZzZRXQQHNeGKnR4SDBbWKQ3NBPJpNCHa91J+3rxRBC7BhLGQu3166ffCrG3qCf9qOYwx5e6fDbOY=

### Context

We are trying to build custom map because we want to show custom markers on the map.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/146105839/866d5476-8f2a-4be9-8cc7-a4aa8b0ad55e)
![screencapture-app-flutterflow-io-project-offy-mnbwcp-2023-09-26-19_49_29](https://github.com/FlutterFlow/flutterflow-issues/assets/146105839/42d8b843-c6a1-40f3-a098-2f90ebe8e9a2)

### Environment

```markdown
- FlutterFlow version: 3.10.4
- Platform: Web
- Browser name and version: Chrome 116.0.5845.188 
- Operating system and version affected: Windows 10
```

**Comment by SameerShahzad99** [comment]
I checked and I was unable to find that custom widget, also this does not seem to be a blank project with the issue reproduced, can you please reproduce this on a blank project and share the bug report code?

**Comment by InceptMvpDevelopers** [comment]
IT4Olc/qx89OxL1E7s+Bb/kwtDw5JjsnapZM0exhexMcG5PNG7UIec/4VEptXbC+TVc3ImaapGY1/v/IkvbIN8IqOQ+aY6461Lludj3gWkytMq3TPs2OVHR6MNpKCm3D3JiJpBB4PrJvc0IHwF+qCu6RbBHcJr22IW0RQcj/Jqf+o3/uQ0SLb3kNh1JWeC/v


I've created a separate project and implemented the Custom Google Map widget. This is the Bug Report Code of the component in which I use the custom Google map widget.

**Comment by InceptMvpDevelopers** [comment]
No, please do not close this issue. This issue is not resolved yet.

**Comment by joshua-ffio** [comment]
Hi @InceptMvpDevelopers , 

I did some looking into this issue and it seems like the issue is the `RenderRepaintBoundary.toImage()` usage in your custom widget, as it does not work on web. While debugging in your sample app, I can see the error:
```dart
Unsupported operation: toImage is not supported on the Web
```
See the following for more information.
 [https://github.com/flutter/flutter/issues/47721](https://github.com/flutter/flutter/issues/47721).

Therefore, from the FlutterFlow side we are not able to display anything because of this. Perhaps there is a workaround for web, but since this is not a general bug applicable to all users, debugging this falls out of the scope of the github tracker. If you have any further issues that fall within the FlutterFlow context on this custom widget, please reach out to chat support or contact support@flutterflow.io.

Thanks!
