### ISSUE TITLE
Issue with the Firebase Cloud Functions region

### ISSUE THREAD

**Issue by 8venturegit** [FlutterFlow/flutterflow-issues#1538]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a Cloud Function in the 'eur-west2' region. When FlutterFlow calls the function, it is located in the 'us' region, which causes an error.

### Expected Behavior

FlutterFlow should call the function in the correct region.

### Steps to Reproduce

1. Create a cloudfunction in region europe-west2
2. Call cloudfunction
3. The region is incorrect.
<img width="675" alt="Capture d’écran 2023-09-27 à 08 00 47" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140443940/aa926c92-2035-4eb2-897b-cb72dc85e79e">
<img width="454" alt="Capture d’écran 2023-09-27 à 07 59 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140443940/45b47a62-9869-493a-8ae7-ff7f7a85832f">
<img width="525" alt="Capture d’écran 2023-09-27 à 08 00 55" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140443940/8ef28556-537b-4216-b8c7-79981fe40aa6">

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sk871x4lIm+FY+Kr+bsBB/GEQG0N/a4I4scp/bxIgGIDzPOw+ZPXsbRdWYNOidFVqMESmmjkFpuzmkuHxFfo4AEyBGd1G1bhUdw3gQXKmQZOBPLWoWXFRJNxQJ3bFyLWzpiMnANJ1WWQM6l2IBe/ISh/ACb7jImdISq/LZO4=

### Context

I need to place the function in the "us" region for it to work.

### Visual documentation

<img width="454" alt="Capture d’écran 2023-09-27 à 07 59 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140443940/bc6bd645-6213-4f23-88f9-df960b8a8b5f">
<img width="675" alt="Capture d’écran 2023-09-27 à 08 00 47" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140443940/926dce40-d888-43f1-b87f-c612a29a16cc">
<img width="525" alt="Capture d’écran 2023-09-27 à 08 00 55" src="https://github.com/FlutterFlow/flutterflow-issues/assets/140443940/d37fa0e6-0240-46c5-ba87-9905b340fc25">

### Environment

```markdown
- FlutterFlow version: 4
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:  osX
```

**Comment by takashiff** [comment]
Hello, thank you for your bug report. This seems to be expected behavior based on Firebase's cloud functions documentation. Please see the following thread: https://github.com/firebase/firebase-tools/issues/842.
One way you could try to go around this issue is enabling CORS, although I cannot make any guarantees: https://stackoverflow.com/questions/42140247/access-control-allow-origin-not-working-google-cloud-functions-gcf. I would suggest looking through the above threads for a potential solution.

**Comment by takashiff** [comment]
Hello, thank you for your bug report. I apologize for the incorrect labelling of the bug. It has now been fixed and will be reflected in our next deploy.

**Comment by nicmohr25** [comment]
Hello, the bug is labeled as fixed but is the patch already deployed? 
Because I am still experiencing this issue.

**Comment by nicmohr25** [comment]
> Liar, still not working

I contact the support directly and they told me the bug was fixed but it’s not deployed yet.
Normally deployments are Thursdays which mean it’s either getting fixed today or with the next patch

**Comment by RizalSafwan** [comment]
im not sure when will flutterflow push the fix for now i found a temproady solution

find all ( FirebaseFunctions.instance ) and replace with ( FirebaseFunctions.instanceFor( app: FirebaseFunctions.instance.app, region: 'Replace-this-with-your-firesebase-region') )

this only works with if you're hosting outside of flutterflow
