### ISSUE TITLE
Some buttons stopped work after last FF update

### ISSUE THREAD

**Issue by atlas-wonami** [FlutterFlow/flutterflow-issues#1603]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After deploying version 4.0 of Flutter, we expected our application to run smoothly without any errors. Users should be able to click on various buttons within the application without encountering any issues.

We are experiencing with our application deployed on wonami-app.flutterflow.app. On the 26th of this month, we deployed our application and noticed that the like button on our home page is not functioning on both the test mode and on wonami-app.flutterflow.app. However, it is working as expected on [www.wonami.app](http://www.wonami.app/).

Despite reverting to the exact same version from the 26th, the issue persists on wonami-app.flutterflow.app. We have checked for any changes in the code that could affect the button's behavior and found nothing. This leads us to believe that there might be an issue from FlutterFlow's end that is causing a bug in the like button functionality on wonami-app.flutterflow.app.

### Expected Behavior

Like buttons working as before

### Steps to Reproduce

1- Run web publish
2- Attempt to click on various buttons within the application
3- The button dont call firebase properly 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gzMmAvJdOoeZE7aX6bu9Vo2UQJW1/aoc0st5Hd0gdCOPrBqQqZMnCSxJBYM/gaVNcMFab+Xwz7vzJidnPEfE4HxaVRqZHzs19WBfke2iuRbGbC7WednZ9IJlVIUiv1KSnrxJNIrFZcVID1Fy6Bt/JSgvDFOu/Zwh9f6PHaOI=

### Context

This bug has significantly impacted our ability to deploy our application for several days now. It is causing a critical disruption in our development process, and we are unable to provide our users with the latest updates and improvements.

### Visual documentation

Deploy after 4.0
![Captura de Tela 2023-10-06 às 15 24 13](https://github.com/FlutterFlow/flutterflow-issues/assets/113944529/953f47b9-4020-4ce2-a837-d1645963aff9)

Deploy before 4.0
![Captura de Tela 2023-10-06 às 15 25 13](https://github.com/FlutterFlow/flutterflow-issues/assets/113944529/92531c16-41ed-4ca3-8121-24371c7ddf7a)

Both have the same code

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: MacOS web
- Browser name and version:Chrome 117.0.5938.132
- Operating system and version affected: MacOS 14.0
```

**Comment by FrancoSernaglia** [comment]
I am having a very similar problem when uploading data to firebase. "Could not convert: Instance of LatLng" Before update 4.0 it was working fine. I created an issue for this too

**Comment by hariprasadms** [comment]
Hi @atlas-wonami - Thanks for submitting the issue. I looked at the project.So, I was unable to locate the issue page or button. Considering the nature of bug, we required a blank project with issue setup to investigate the issue. Please add the details and let us know. Thanks

**Comment by atlas-wonami** [comment]
In a blank project, it's working well. The issue is after 4.0 update in my project. We did not change anything related to this button recently, it just stopped working after the update. It's just what I know until now :(, but we are almost hundred percent sure that it's an FF bug. We've checked in an old Run versions of the project, and in these versions are working as expected, to make sure it's not our changes, we've reverted the project to these date to check if the buttons will back work, but it not work.

**Comment by hariprasadms** [comment]
Hi @atlas-wonami - Thanks for your response. In this instance i guess it could be project specific issue. I would suggest reach out FF technical support team for more help. They should be able assist you. Considering the wider status of the issue, I can confirm that FF functionality around the issue is working fine. Let us know if you could re produce the issue in blank project and share the details. We are happy to re investigate the issue. Thanks

**Comment by atlas-wonami** [comment]
We did this, but they closed our chat, we have a new chat opened, but no response, thats why we opened this bug, because the technical support are ignoring us :(

**Comment by hariprasadms** [comment]
This is a bit of challenging issue as it is not able to re produce at your end as well. However, I'm marking it as project specific.  I will let dev team to decide the status of it. Thanks

**Comment by atlas-wonami** [comment]
Ok, please try help us, we are counting on you, have no clue how to fix it, and its impacting us. Thanks

**Comment by atlas-wonami** [comment]
@hariprasadms do you have any update? We really need your help, because more buttons are not working, we cannot deploy any update to our customers, and we are stuck for more than 2 weeks with this problem

**Comment by atlas-wonami** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113944529/442b34b4-0d96-4ab2-bb43-0c2e133d1788)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113944529/e7c39bdd-35ec-4705-8eab-9d8899a07861)
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/113944529/c187b7a5-fb3d-4873-b78b-a30b5fd684ec)


All firebase update or create document stopped work, and we cannot create anything

**Comment by atlas-wonami** [comment]
We have observed that the counter increases only when we manually refresh the page. However, on wonami.app the counter increases and the button state changes in real-time. This behavior is consistent across all other buttons. This suggests that the issue is not related to requesting data from Firebase but is related to the real-time response from Firebase.

In other words, Firebase is not providing real-time query results, which is causing the error. However, on wonami.app, Firebase is responding correctly in real-time.

**Comment by atlas-wonami** [comment]
I need any kind of support, I got nothing in 3 weeks asking help :(

**Comment by atlas-wonami** [comment]
HI, IDK if FF changed something, but now, after a new deploy it´s possible update all docs, but it´s still impossible to create, the error remains

**Comment by atlas-wonami** [comment]
Hi,guys, do we have any news? We are stuck 1 month because this bug, we cannot do anything :(

**Comment by atlas-wonami** [comment]
Hi, any updates ? :(

**Comment by hariprasadms** [comment]
Hi @atlas-wonami - Sorry for my delayed response. Considering the nature of the issue. Its a bit challenging find out whats going on your project. I can follow up up with Dev team but not able to give ETA. Thanks

**Comment by atlas-wonami** [comment]
Hi, any news?

**Comment by atlas-wonami** [comment]
Hello?

**Comment by atlas-wonami** [comment]
Hello?

**Comment by glamourhammer** [comment]
@atlas-wonami I'm going to weigh in here because we have experienced this issue numerous times in our project and the behavior is not limited to the FF 4.0 update. Several updates in the past have resulted in the symptoms you are describing.

@hariprasadms @agreaves I suspect this will be very difficult to diagnose because, at least from our end, we have yet to identify any pattern to the unexpected behavior aside from observation thereof following FF updates.

Following updates, certain buttons and the Action Flows therein cease to function. In the most recent event (following an update to FF 4.0), an api call was no longer firing properly from the client. When testing the api in the FF api builder it functioned as expected. However, in test mode or production the client was neither calling the designated endpoint nor passing anything in the call: just null. Note that this code had not been touched in months, had been thoroughly tested and, prior to the update, was behaving as expected. The only change in the environment was the FF update.

As mentioned earlier the above is an example of behavior observed in the past and in no way an isolated event. While a non-solution, the only workaround we have found to date is to simply create a new button: note that copy/pasting an impacted button simply reproduces the same, undesired behavior. However, of equal importance is that a copy/paste of the Action(s) from within the corrupted button to a new button WILL resolve the issue. So, the root cause is likely to lay within the relationship between the action and the widget itself.

Hope that helps move this issue along because I would love to see a solution as it's cost our team many hours or head-scratching and wasted efforts.

**Comment by agreaves** [comment]
Hi @atlas-wonami, sorry for the slow response in getting to this issue. It was difficult to diagnose here since it was project specific. However, I now believe it's the same issue as #1582, which is now fixed and should be deployed in tomorrow's release. Thank you for your patience, and please let me know if for some reason the issue continues!
