### ISSUE TITLE
APK not downloading giving (Dart:html not found)

### ISSUE THREAD

**Issue by Dev-Muhammad-Junaid** [FlutterFlow/flutterflow-issues#1634]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img width="1390" alt="darthtmllibrary" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/5b64ce08-cba9-41c0-99a5-0e3fcb8ae2d5">

### Expected Behavior

Can't download APK for the project

### Steps to Reproduce

Simple Download APK on project, 0 errors

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kMmA8Y9Pxd9A7c/9bcdR/SI5KUw+RI0n0+1RaCosfZT2BLMcec/RVERtZOniYX9YIGaghWoW0MrGk/DLKe5fPT+aGdVP+M9MFBbKZH6hMoi4FJWgeUFCJ+hgI0fG5MCzqhFACPp2Wnct7Du2Feu9YHfaQrrVOm4wDq/LZO4=

### Context

Trying to download the project APK

### Visual documentation

<img width="1390" alt="darthtmllibrary" src="https://github.com/FlutterFlow/flutterflow-issues/assets/65047962/13c9b29d-eae1-4ad5-bfc8-773cdffc24de">

### Additional Info

.

### Environment

```markdown
- FlutterFlow version: v4.0 (released Sep 28,2023)
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected:  MacOS Sonoma
```

**Comment by Dev-Muhammad-Junaid** [comment]
Any update on this?

**Comment by sbis04** [comment]
Hey @Dev-Muhammad-Junaid, this is not a bug on our side rather it's happening because you are importing `import 'dart:html';` in one of the custom codes:

<img width="986" alt="Screenshot 2023-10-25 at 8 28 50 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/540c7db7-ca2e-4c0f-8b4c-4dc7bcd6bc5f">

If you are importing `dart:html` package inside any custom code, the app will only compile for web platform (that means it will work on Run/Test mode but APK build or native device build will fail)
