### ISSUE TITLE
Multiple API invocations on page load

### ISSUE THREAD

**Issue by the-digital-pro** [FlutterFlow/flutterflow-issues#1669]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Created a simple project which contains a column which has a GET API request associated. On application load two API calls are made. Duplicated the page and then navigated between the two. When the second page is loaded two API calls are also made. Navigate back to the first page and one 1 API call is made. I am pretty sure this was never a problem before.

### Expected Behavior

I would expect only 1 API invocation on each of the pages and would not expect any widget rebuild to cause an additional API call.

### Steps to Reproduce

1. Create a blank project and delete all widgets except the Column
2. Create an API call
3. Add the backend query to the Column
4. Test the application and review Google Chrome DEV tools.
5. You should see two API invocations.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz/Hqx89PvsdG1ZSJdcdVhiURJnkcTeUzlO1hdwwbI+OrBJoMZeLOYlBCSOqHfWNmAU388VIC3ML7iePUVvkFAxOrQKZ+/5NXUxDjVmOXRZClEZe8RXZ6QPFXGUiP4cGRpwhSPtNYZXgg2WeUO+Sub3qCf9qOYwx5e6fDbOY=

### Context

To keep API calls to a minimum as this could be costly. Cache Control would typically be applied but seams strange behaviour.  

### Visual documentation

Self explanatory steps to reproduce.

### Additional Info

Tried beta and get the same results.

### Environment

```markdown
- FlutterFlow version: 4 3.13.7
- Platform: Windows
- Browser name and version: Google Chrome 118.0.5993.72
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi @the-digital-pro - Thanks for reporting the issue. I can reproduce the issue. 

<img width="1390" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/6a27c0c3-141b-4430-b100-795eda0dd08f">

**Comment by victoriahuang1** [comment]
Hi @the-digital-pro , thanks for the report. I checked in with the team, and this is actually the current expected behavior. To avoid multiple API calls, please toggle the option to cache your queries.

<img width="285" alt="Screenshot 2023-10-25 at 2 39 05 PM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/16326980/175370ad-0cde-4cff-b1c7-86c4202563b6">

However, you are completely right that the default behavior to make a new request each time the page is rebuilt is not ideal. We will be putting this down as a feature improvement that we will work on.
