### ISSUE TITLE
intl is pinned to version 0.18.1 by flutter_localizations from the flutter SDK.

### ISSUE THREAD

**Issue by MikeYates** [FlutterFlow/flutterflow-issues#1681]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Everytime I compile a custom action it fails, even though the code is correct or it does not have any code.

### Expected Behavior

Code fails to compiled, error message shows up.

`Error: Failed running flutter pub get...
Note: intl is pinned to version 0.18.1 by flutter_localizations from the flutter SDK.`

### Steps to Reproduce

1. Add a new custom action
2. Save the custom action

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)
IT4ghvHqy5dNrsdb7aXqce9V/To6JmYgaIc0sd4bGA0dCJzuPLMQdvWkahJocN+gd1VtM0SmmnIDzPzPivPTO/cqaCiuc7pDzKV+cwnwXnO7QZOBBpeSY0BQBplgN2LD18GJrhVTPutqc04fw3GYfu/KXgnqQZDuImdISq/LZO4=-

### Context

Cannot create a custom action.

### Visual documentation

[Screnshot](https://imgur.com/a/awlFbwQ)

### Environment

```markdown
- FlutterFlow version: 4.0.2
- Platform: MacOs Desktop
- Browser name and version: -
- Operating system and version affected: MacOS High Sierra
```

**Comment by hariprasadms** [comment]
Hi @MikeYates - Thanks for submitting the issue. The error message indicates that there's a dependency conflict related to the intl package in your project. The error showing up because flutter_localizations package, which is part of the Flutter SDK, requires a specific version of the intl package (version 0.18.1 in this case). I can see that this has been working fine in other projects. It looks like specific to your project or user account. 

I would suggest, update issue with project bug report code so that we can download your project code and see whats going on inside. 

Also, check that you are working on up to date FlutterFlow version. Refresh your browser and see FlutterFlow portal is up to date.

**Comment by rssluca** [comment]
@MikeYates you can probably add `intl: ^0.18.1` to your action's `Pubspec Dependencies`.

**Comment by hariprasadms** [comment]
Hi @MikeYates - Are you still experiencing the issue?

**Comment by Abayjafton** [comment]
same problem

**Comment by Abayjafton** [comment]
Error running "flutter pub get" while checking custom widgets and actions. Please try again and if the problem persists fix pubspec dependencies.
Error: Failed running flutter pub get...
Note: intl is pinned to version 0.18.1 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because custom_widget depends on flutter_localizations from sdk which depends on intl 0.18.1, intl 0.18.1 is required.
So, because custom_widget depends on intl 0.18.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Try upgrading your constraint on intl: flutter pub add intl:^0.18.1

**Comment by wenkaifan0720** [comment]
Hi All. Could you provide a bug report code so I can further investigate the issue?

**Comment by MikeYates** [comment]
> Hi All. Could you provide a bug report code so I can further investigate the issue?

Updated with bug code

**Comment by MikeYates** [comment]
> Hi @MikeYates - Are you still experiencing the issue?

Yes, but I think I could get around it by opening it in chrome browser and ticking exclude compilation.

**Comment by wenkaifan0720** [comment]
Hi @MikeYates. The bug report code you provided doesn't seem to be valid.

**Comment by MikeYates** [comment]
> Hi @MikeYates. The bug report code you provided doesn't seem to be valid. Could you give me another one or just tell me the project id (from the url)? Right click on any widget on the widget tree and generate the bug report code.

I did generate from the widget tree, im not sure as the widget is not related to the bug.
porject-id: `repairdata-mc9ihi`

**Comment by wenkaifan0720** [comment]
I just compiled the two actions in your project (on web) and didn't see any issue. Could you update your mac app and try again?

**Comment by MikeYates** [comment]
> I just compiled the two actions in your project (on web) and didn't see any issue. Could you update your mac app and try again?

Web does work, I confirm this. Mac app does not.

**Comment by wenkaifan0720** [comment]
You need to update your mac app, the latest version is v4.1.0

**Comment by MikeYates** [comment]
> You need to update your mac app, the latest version is v4.1.0

Mine is at 4.0.2 (19) ? how do you update the mac app.
