### ISSUE TITLE
Carousel current index value is not updating on page change

### ISSUE THREAD

**Issue by sirian-m** [FlutterFlow/flutterflow-issues#1698]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The index of a carousel widget does not update when you swipe through a carousel widget, or when you use buttons with control carousel actions. 

### Expected Behavior

The index should automatically update on page change (both through a swipe and through the control action), and reflect this state on the rest of the page to use it in variables.

### Steps to Reproduce

1. New page
2. Add a carousel widget
3. Add a text widget
4. Set the text widget content to the current carousel index
5. Run/test the project
6. Swipe through items and see index not update (unless you randomly click somewhere on the carousel after)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXkcrl089NrtxE1qrqcsBaimQwFjMLa+cF0+1+FB4bC7LpPJkQfPTOZUNKQuLhSn9UJGej/X4d3M7TkoT1FMcBPgSqRYBb0JVASzviQl6nRcmmPqiefHJRFtNQGW6A5qaFsCNRKrdqdCUa7U6HNa3qNleeY8aSfxBlZ7vfcPo=

### Context

I have a carousel set from a variable list, and I want to change the opacity of the content based on if the index of the item is equal to the current carousel page. This does not work right now as it doesn't update.

### Visual documentation

Notice, only when I click that the index updates. This only works once though, clicking after that does nothing. Just like swiping.
https://github.com/FlutterFlow/flutterflow-issues/assets/109159237/79b71949-4d14-46c5-b666-c883e9013e08

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: All
- Browser name and version: Arc, 1.13.1 (42579). Chromium Engine Version 118.0.5993.88
- Operating system and version affected: MacOS 14.0
```

**Comment by joshua-ffio** [comment]
Hi @sirian-m , similar to #1014 , this current behavior is by design as we don't want to automatically rebuild the entire page every time the carousel moves. However, I will mark this down for a design review.

Currently the pageIndex is a state owned by the Carousel and does not assume it should rebuild the entire page on each carousel item change. If you would like to reflect updated values in other parts of your page, then you will need to use the `On Page Change` action on the carousel to rebuild the page so that your use of that variable is rebuilt with the update value.

Here is the relevant set-up and behavior.

![Screenshot 2023-10-24 at 9 55 29 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/141682285/9371b438-6797-4b1f-8f06-fa3559a85b08)

https://github.com/FlutterFlow/flutterflow-issues/assets/141682285/6b169906-7d9e-4b02-94d2-6d34b03f5933

**Comment by sirian-m** [comment]
Hi @joshua-ffio, thanks for clear explanation. That makes sense and I got it to work now indeed!
