### ISSUE TITLE
Not adding firebase project ID

### ISSUE THREAD

**Issue by CongoBeast** [FlutterFlow/flutterflow-issues#17]
I have been trying for several days to add a project id so that i can connect my firebase to flutterflow but it is not working, the button loads for a micro second then returns to origional no green check mark , i have followed all the instructions about how to connect and to enable permisions from my firebase so i dont know where the issue is.

**Comment by organicnz** [comment]
Hi mate,

Thank you for adding the issue. Could you add a little more detail? It would be great if you could edit this issue :)

Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.


## Expected behavior (required)



## Current behavior (required)



## To Reproduce (required)


Steps to reproduce the behavior:
1.
2.
3.
4.


## Context (required)



## Screenshots / recordings



## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):
