### ISSUE TITLE
Changes not saving

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#1727]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I worked on a different laptop for 1 day, then came back to the usual laptop (refreshed FF) and after a while realized that a lot of the changes aren't there, even though I had internet connection the whole time. Now it's really hard to figure out what got saved and what didn't.
How can I avoid this? How can I make sure all the changes are saved? Is there an indicator I missed?

### Expected Behavior

Autosaving work

### Steps to Reproduce

Probably use two tabs to simulate two laptops.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/lvJdOm99J1aX2de9VvCkQJmU1a5c0st4bGAsdGOvrBu0AfM/BPhdtTbTiaVNcf06aoFszw8Lzv+PTKvJcBzasQJRa/rVIEjz0e2i5bJOYOpC8Tmt9O8RXfEyw56evqwhCAMxfcVlg2Dm1fPOtQjPDFOu/Zwh9f6PHaOI=

### Context

Nothing special

### Visual documentation

Nothing to show

### Environment

```markdown
- FlutterFlow version: 4.0 Oct 26
- Platform: Chrome
- Browser name and version: Chrome Version 117.0.5938.132 
- Operating system and version affected: Mac OS 13.4.1 (c) (22F770820d)
```

**Comment by Coffee-Nerd** [comment]
My custom widgets and custom actions keep experiencing major regression as well, I can confirm this bug....
This has been happening since the latest update and is an absolute nightmare.

**Comment by Coffee-Nerd** [comment]
and it's not even for having two tabs open. I just built my apk, and when I looked at my code again it was reverted to pre-apk stuff. WHAT.

**Comment by hariprasadms** [comment]
Hi @Coffee-Nerd - Thanks for submitting the issue. I looked at your project. I can see there are changes are logged in project activity under collaboration sections. This indicates that your project got changes and has been time-stamped.  Since I can't seem to replicate the same behaviour in other projects, it seems like a project-specific issue. 

I would advise you to check the changes that have been logged in the project activity section, along with the date and time that the changes you believe are missing. If the activities are recorded but the project does not show those changes, than there may be a issues that required more investigation.

**Comment by agreaves** [comment]
Hi @Coffee-Nerd, can you also generate a Bug Report Code so I can further investigate? It can be from anywhere in the project.

**Comment by hariprasadms** [comment]
Due to inactive and no further details, closing the issue.
