### ISSUE TITLE
App bar - Button - Switch

### ISSUE THREAD

**Issue by palmdeskApp** [FlutterFlow/flutterflow-issues#173]
App Bar ---> Add switch button ---> Run/Test project --> switch action not working in Run/test mode.

**Comment by hariprasadms** [comment]
Hi, Could you please add more details to the issue. Please refer bug template and follow same formate to raise issues. Thanks

**Comment by palmdeskApp** [comment]
The switch button is added into App bar
The project is opened in Run mode
Can not operate switch button.

The same switch button is added to the page's main section. 
The project is opened in Run mode
Now switch button functions as expected.

Environment
Window 10, chrome browser.

**Comment by agreaves** [comment]
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.

([Example project when trying to reproduce steps](https://app.flutterflow.io/project/app-bar-switch-test-8f87dm))

If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce. In particular, a Bug Report Code would be required.

Thank you for your contribution!
