### ISSUE TITLE
logFirebaseAuthEvent throws an error with google auth.

### ISSUE THREAD

**Issue by simon-zhangmuye** [FlutterFlow/flutterflow-issues#1732]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

void logFirebaseAuthEvent(User? user, String method) {
  final isSignup = user!.metadata.creationTime == user.metadata.lastSignInTime;
  final authEvent = isSignup ? 'sign_up' : 'login';
  logFirebaseEvent(authEvent, parameters: {'method': method});
}

This is the code in analytics.dart in flutterflow
If I click google auth button, then navigate back. It will throw an error "user cannot be null". The App will crash.

### Expected Behavior

void logFirebaseAuthEvent(User? user, String method) {
  if (user != null) {
    final isSignup = user.metadata.creationTime == user.metadata.lastSignInTime;
    final authEvent = isSignup ? 'sign_up' : 'login';
    logFirebaseEvent(authEvent, parameters: {'method': method});
  }
}
Now I change the code to this.

### Steps to Reproduce

1. create a new project
2. enable google auth
3. enable google analytics
4. enable on Authentication
5. click google auth and navigate back
6. see error

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

user cannot be null

### Context

the app crashes

### Visual documentation

null

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by SameerShahzad99** [comment]
@simon-zhangmuye Can you please share a blank project with the issue reproduced, so I can test it?

**Comment by simon-zhangmuye** [comment]
@SameerShahzad99 This is not a blank project. You need to use google auth and connect with a firebase project.

**Comment by hariprasadms** [comment]
Hi @simon-zhangmuye - Due to inactivity in the issue, we presume the problem has been resolved with the latest FF updates. Hence, I am closing the issue. If the issue still persists, feel free to reopen or create a new one with all the required details along with project bug report code. Setting up a blank project with issue steps details can help to speed up the issue investigation. Please do the needful. Thanks

**Comment by hariprasadms** [comment]
Hi @simon-zhangmuye - Due to inactivity in the issue, we presume the problem has been resolved with the latest FF updates. Hence, I am closing the issue. If the issue still persists, feel free to reopen or create a new one with all the required details along with project bug report code. Setting up a blank project with issue steps details can help to speed up the issue investigation. Please do the needful. Thanks
