### ISSUE TITLE
Validating and uploading with csv file

### ISSUE THREAD

**Issue by FarheenAnsari-dev** [FlutterFlow/flutterflow-issues#174]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)
<adding data through csv file should be uploaded or if there is any error then display the same>

## Current behavior (required)
<adding data through csv file was working till 28th Nov 22 morning, after that its showing only process dialog>

## To Reproduce (required)

1.
2.
3.
4.

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

<img width="991" alt="Screenshot 2022-11-29 090520" src="https://user-images.githubusercontent.com/62877751/204451154-64f41713-28dc-4d34-8caa-63f10a524ef3.png">

**Comment by katherineqian** [comment]
Hi @FarheenAnsari-dev,

I cannot reproduce this bug. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance. There, you can provide more specific details on the CSV you are trying to upload.

If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.

Thank you for your contribution!
