### ISSUE TITLE
Recaptcha verification (during phone sign-in) takes to home screen instead of SMS code screen

### ISSUE THREAD

**Issue by Gintasz** [FlutterFlow/flutterflow-issues#1749]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After entering phone number, I am taken to recaptcha verification page. After that, on android, I'm taken to SMS code entrance page. However, on iOS I'm taken to home screen and it's not possible to complete sign in.

### Expected Behavior

I expect to be taken to SMS code entrance page after recaptcha verification

### Steps to Reproduce

Created new project on FF
Created new project on firebase
Added flutterflow user to firebase project, added service account user permission
Enabled email, phone, google sign in on firebase
Configured firebase with flutterflow project
Added enter phone & enter sms pages
Downloaded code, run locally on android, it works
Run locally on iphone, it's not possible to get to the sms code page because I'm always taken back to home page after recaptcha.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXi87lw5NInMRE+7X+cvpsr2MwFjsaU40V0tdTbw0jGLKuEJYMP+r+VBNaO8umY35AJVaWmngdwPzPvYb9Fe5dPUideINozqpUWwnNRluVVq6mPpGKfUZRGcFYC3KEy8HYpxBBKfVeS1Utw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

.

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/6189625/f1acfd8d-15b0-4261-a906-d6ae714144ff

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: iOS
- Browser name and version: Chrome
- Operating system and version affected: iOS
```

**Comment by Gintasz** [comment]
I enabled notifications, app check and now I don't get any recaptcha anymore... and I am taken straight to SMS page after entering phone. So this seemingly fixes the issue.

**Comment by hadeelsameh** [comment]
Hello, I am getting a similar issue. could you please specify which notifications you enabled? Also, you have enabled app check from firebase, FF, or both?

**Comment by hadeelsameh** [comment]
> I enabled notifications, app check and now I don't get any recaptcha anymore... and I am taken straight to SMS page after entering phone. So this seemingly fixes the issue.

Hello, I am getting a similar issue. could you please specify which notifications you enabled? Also, you have enabled app check from firebase, FF, or both?

**Comment by Gintasz** [comment]
@hadeelsameh I checked Enable notifications on FF (already had APN certificates uploaded to firebase, which is necessary for that), then enabled App Check in FF as well.

**Comment by hadeelsameh** [comment]
> @hadeelsameh I checked Enable notifications on FF (already had APN certificates uploaded to firebase, which is necessary for that), then enabled App Check in FF as well.

Thank you

**Comment by SameerShahzad99** [comment]
Thank you so much for reporting this bug, I can reproduce this issue on my end!

**Comment by WellDunDun** [comment]
@agreaves Hey Alex! I don't think this is resolved because I'm having the same issue but getting errors GoRouter:

`══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following StateError was thrown while dispatching notifications for GoRouterDelegate:
Bad state: No element

When the exception was thrown, this was the stack:
#0      _Array.last (dart:core-patch/array.dart:57:5)
#1      RouteMatchList.last (package:go_router/src/match.dart:305:34)
#2      _MyAppState.getRoute (package:navi/main.dart:126:67)
#3      _MyAppState.initState.<anonymous closure> (package:navi/main.dart:163:22)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:437:24)
#5      GoRouterDelegate._setCurrentConfiguration (package:go_router/src/delegate.dart:239:5)
#6      GoRouterDelegate.setNewRoutePath.<anonymous closure> (package:go_router/src/delegate.dart:199:18)
#7      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:43:39)
#8      GoRouterDelegate.setNewRoutePath (package:go_router/src/delegate.dart:195:14)
#9      _RouterState._processParsedRouteInformation.<anonymous closure> (package:flutter/src/widgets/router.dart:756:34)
#10     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:43:39)
#11     _RouterState._processRouteInformation (package:flutter/src/widgets/router.dart:748:8)
#12     _RouterState._handleRouteInformationProviderNotification (package:flutter/src/widgets/router.dart:765:5)
#13     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:437:24)
#14     GoRouteInformationProvider.notifyListeners (package:go_router/src/information_provider.dart:147:11)
#15     GoRouteInformationProvider._platformReportsNewRouteInformation (package:go_router/src/information_provider.dart:246:5)
#16     GoRouteInformationProvider.didPushRouteInformation (package:go_router/src/information_provider.dart:277:5)
#17     WidgetsBinding._handlePushRouteInformation (package:flutter/src/widgets/binding.dart:930:26)
<asynchronous suspension>
#18     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:42)
<asynchronous suspension>
#19     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:618:22)
<asynchronous suspension>

The GoRouterDelegate sending notification was:
  Instance of 'GoRouterDelegate'
════════════════════════════════════════════════════════════════════════════════════════════════════

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
#0      _Array.last (dart:core-patch/array.dart:57:5)
#1      RouteMatchList.last (package:go_router/src/match.dart:305:34)
#2      _MyAppState.getRoute (package:navi/main.dart:126:67)
#3      debugLogGlobalProperty.<anonymous closure> (package:navi/flutter_flow/debug_util.dart:144:63)
#4      debouncedDebugLogging.<anonymous closure> (package:navi/flutter_flow/debug_util.dart:92:47)
#5      EasyDebounce.fire (package:easy_debounce/easy_debounce.dart:54:31)
#6      main.<anonymous closure> (package:navi/main.dart:92:18)
#7      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
`

Happy holidays y'all!

**Comment by aaksa** [comment]
Also got this issue
