### ISSUE TITLE
UI Bug: Cannot scroll down Action Block list

### ISSUE THREAD

**Issue by JackWH** [FlutterFlow/flutterflow-issues#1750]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In FlutterFlow's macOS app, it's impossible to scroll down the list of Action Blocks if they extend beyond the bottom of the screen.

I've tried this in full screen and in windowed mode.

This is quite serious as I'm unable to make edits to any action blocks below the fold.

### Expected Behavior

We should be able to scroll down the list to access any Action Block.

### Steps to Reproduce

1. Open FlutterFlow for Mac
2. Ensure you have enough Action Blocks that they extend beyond the screen
3. Try to scroll down

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

This makes it impossible to edit any Action Blocks which appear below the fold.

### Visual documentation

![CleanShot 2023-10-31 at 21 04 14](https://github.com/FlutterFlow/flutterflow-issues/assets/627533/60d0176b-8f09-46ae-b32d-5eb98ce4e64b)

### Environment

```markdown
- FlutterFlow version: v4.0.2 — Flutter 3.10.4
- Platform: MacOS Desktop
- Browser name and version: N/A
- Operating system and version affected: macOS Sonoma 14
```

**Comment by JackWH** [comment]
@joshua-ffio Hi Joshua, bug report code is below:

```
IT4ozMmBw41grsNE7aXyKflahSQ6Jnp5ROcN1MpBazwbfe+uB4kqevfOTERWcObhS1FDelmJjWoW0vPIi9nhFvJcPReuRqJfz6hMZhXvWnGmV4SmFJWgWUdCHcJTG0Cu5La32xJBCPpeSXdn2VyyGtiWZAjZH772CzAeDa/LZO4=
```

Let me know if I can provide anything else that might help.

**Comment by joshua-ffio** [comment]
Hi @JackWH , I appreciate the help with the bug report code.

I tried in your project but I am able to scroll correctly using both a mouse wheel and the side scrollbar on the page all the way to the bottom.


https://github.com/FlutterFlow/flutterflow-issues/assets/141682285/99db10d3-bdf2-404b-970e-c4039d926649



I noticed in your first post, the video seems to have a bit different of a scroll behavior than what I am expecting, as the rest of the larger panel is staying static and only the inner list of actionblocks are scrolling down. This differs from what I am seeing because the entire panel scrolls (see video above).

Scrollbehaviors are sometimes hard to predict based on the device you are using to scroll, such as a trackpad, mousewheel, keys etc. How are you initiating the scrolling when you replicate this issue? Does this replicate if you click and drag the sidebar of the actions panel?

Thanks!

**Comment by JackWH** [comment]
@joshua-ffio Thanks for the followup, interesting to see your results! For context, I'm using a macOS Magic Trackpad to scroll. I can reproduce the same issue using a Magic Mouse as well.

After seeing your recording, I've found that if I initiate the scroll with my cursor over the "Actions / Action Blocks" buttons, the scroll begins successfully. However, once the scroll ends, it no longer lets me scroll back again. If I initiate the scroll with my cursor over one of the action blocks in the list, the scroll bug occurs immediately.

Good news though, I can successfully scroll by dragging the scrollbar — though it's worth noting it appears very narrow and low-contrast, I hadn't actually realised it was even there until seeing your video.

Here's a quick recording to demonstrate what I'm seeing now. The scroll starts successfully, but can't go back upwards, unless I grab for the narrow scrollbar instead:

![CleanShot 2023-11-01 at 19 20 54](https://github.com/FlutterFlow/flutterflow-issues/assets/627533/4dc2b3a9-38f8-458b-a5c8-2b91c4e1e748)

**Comment by takashiff** [comment]
Hi @JackWH, my apologies for the late follow-up. Have you experienced this issue in any other part of FlutterFlow? This information may help in narrowing down the root of this issue. Thanks!

**Comment by aemelyanovff** [comment]
Thanks for reporting the issue, @JackWH. It will be fixed in the next update.

**Comment by dantebgarcia** [comment]
I've got the same issue. Any update on when this will be fixed?
