### ISSUE TITLE
API not Run is marked Succeeded

### ISSUE THREAD

**Issue by dryprogrammer** [FlutterFlow/flutterflow-issues#1805]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

API not Run is marked Succeeded true

### Expected Behavior

API not Run should be marked Succeeded false

### Steps to Reproduce

Check Succeeded of API that is not run

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8kls/l6ot1pbxH+KrTbflviiAXMjs/aqxMmOt+bxIjF5TkEooTdvekV1pBYsyAewlAIVmjkn0y08rZueDpEfkoBAqAf4tq3boMEAzydz67VLKaOrWNPnNTN+JQJ2bD1rSrvgx9FPNtWl4GwziQC+qRYHLUH5DbO0YdI/yYKtrM+16jFnvNJiBsvyZecCfn

### Context

This has caused developer down time when using conditional logic based on API Succeeded, and required workarounds

### Visual documentation

Project:
https://app.flutterflow.io/project/bug-a-p-i-fail-is-success-52gd12

https://bugapinotrunissuceeded.flutterflow.app/
Click "Go"

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/40515415/b8773331-71a5-49a5-aa5e-304a30c8148f)

### Environment

```markdown
- FlutterFlow version: v4.0
- Platform: Web
- Browser name and version: Chrome 117.0.5938.88
- Operating system and version affected: Ubuntu 22.04.3 LTS
```

**Comment by dryprogrammer** [comment]
This issue is still ongoing

**Comment by agreaves** [comment]
Hi @dryprogrammer, thanks for the report! This is actually the intended behavior. In order to not result in a `null` value, we needed to choose one or the other for the default value of `succeeded` when the result it `null`.

The preferred method to do this is to use a condition based on whether the response is set:
<img width="306" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/7757399/d1b818d4-803b-406e-9001-6fbe22bfad0b">

and combine it either with a `Conditional Value` or `Multiple Condition` depending on your needs. Hope this helps! And apologies for any confusion, as well as for taking this long to respond.

**Comment by dryprogrammer** [comment]
Alex, I appreciate your reply.

I think succeeded == null should more intuitively imply False. I guess your intention was to design `Succeeded` in such a way that it could be used for the case where the API call failed, in which case I think a `Failed` property seems more suitably named. I guess my perception was that `Succeeded` would be used in the case where the API call succeeded, and False for the case where the API was not yet called.

Setting a second condition with ApiResult != null, seems like a practical workaround, but I feel that it creates a learning curve.

It's a small issue indeed, but I've found a few such scenarios where diving deep with FlutterFlow actually starts to lose productivity for the developer. IMHO, simple out-of-the-box intuitively predictable defaults with well documented gotchas and work-arounds would extend the productive range for FlutterFlow further.
