### ISSUE TITLE
"Deliver with sound" in manually trigger notificaiton do not work

### ISSUE THREAD

**Issue by kanatbkeeep** [FlutterFlow/flutterflow-issues#1833]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

"Deliver with sound" in manually trigger notificaiton do not work. Im trying to test push notification on my android device. When I manual send it, it come without any sound and vibration.

### Expected Behavior

I expect push notification with sound

### Steps to Reproduce

1. Go to project settings
2. Push notification
3. Manually Trigger Notifications
4. Turn on "Deliver with sound"
5. Send notificaiton

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gyfLlvYtNxLRE7qrcae9ajWUQNjI3a700st4bGAsdGOvrBu02Y/f8SxJoTdO6aVNcBVCjrGcx+tb8juLlNO4EHw+VGL5F+ZFiWzvOe2iuV8SbO7mCf3wnL9JRIECD1sOJkxEmKrd2LFlk1GeIIfCWTXbDBOu/Zwh9f6PHaOI=

### Context

-

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/79863395/6ab7130b-3026-4481-8469-c09425520ba1)

### Environment

```markdown
- FlutterFlow version: 4.0
- Platform: Mobile
- Browser name and version: Chrome 119.0.6045.124
- Operating system and version affected: Windows 11
```

**Comment by hariprasadms** [comment]
Hi, Apologies for the delayed response. Since the issue doesn't seem to be widespread and hasn't received further follow-up, it may have been inadvertently overlooked. Given the age of the issue, it's possible that it has been addressed in the latest FlutterFlow updates. Please verify if you are still encountering the problem, and if so, we can proceed with investigating it further. I've marked the issue status as _"waiting for user response"_ and will leave it open for the next 4 days before closing it. Thank you for your understanding.

**Comment by hariprasadms** [comment]
If the same issue persists, kindly create a new issue with additional details. Thank you!
