### ISSUE TITLE
Grey Screen when ordering ListView

### ISSUE THREAD

**Issue by Aewister** [FlutterFlow/flutterflow-issues#188]
## Expected behavior (required)
When setting the 'Ordering' filter for Backend Queries, the ListView should not show a grey screen.

## Current behavior (required)
When setting the 'Ordering' filter for Backend Queries, the ListView shows a grey screen.

## To Reproduce (required)
From: https://app.flutterflow.io/project/linkall-eqwit7
1. Go to the 'Deal Management' page in FlutterFlow.
2. Click the first ListView with Database query (see screenshot):
![Screen Shot 2022-12-02 at 10 33 00 PM](https://user-images.githubusercontent.com/109976278/205304301-564029f4-0900-4225-b8b4-93a5a9532cec.png)
3. Edit the Backend Query and set 'Ordering' by 'created_time'.
4. Run the project.
5. Go to the 'Deal Management' page by clicking '내 장바구니' (third icon from the left on the Nav Bar).
RESULT: Deal Management page shows as greyscreen.

## Context (required)
When users place go to the Deal Management page, they expect the orders they placed to be ordered in terms of when they were placed. Currently the results appear randomly ordered because 'Ordering by' is not possible.

## Your environment

* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web 
* Browser name and version: Chrome Version 107.0.5304.121
* Operating system and version (desktop or mobile): OSX Monterey

**Comment by wednesdei** [comment]
This issue happend to me as well, I thought it was my code, but it only happens when sorting by date/time.

**Comment by agreaves** [comment]
Thanks for the detailed bug report! Unfortunately, as it turns out you are running into a limitation of Firestore, where if you have an inequality filter ("<", ">", "!=", etc.) then your first Order By must be on the same field ([see docs](https://cloud.google.com/appengine/docs/legacy/standard/go111/datastore/query-restrictions#properties_used_in_inequality_filters_must_be_sorted_first)). We'll add an error message for when you try to add a query that breaks this rule, but unfortunately for now there's no way for us to allow this.

Thanks again!
