### ISSUE TITLE
Incorrect Kerning on JSON Path Response Previews

### ISSUE THREAD

**Issue by johnbhiggins7** [FlutterFlow/flutterflow-issues#193]
## Expected behavior 
String value returned from api should be properly kerned

## Current behavior 
Kerning value is too low.

## To Reproduce 
1. API call to https://swapi.dev/api/people
2. JSON Path $.results[:].created will show the value with incorrect kerning

## Context (required)
Aesthetics and readability, everything still works

## Your environment
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Chrome 107
* Operating system and version (desktop or mobile): Desktop

**Comment by agreaves** [comment]
Hey John 🙂! Thanks for the bug report! Unfortunately, this isn't due to kerning but an overflow issue in Flutter web itself. You'll notice it does not occur on MacOS desktop. In addition, when previewed using the button to the right it is at least displayed correctly. So although this is indeed a formatting issue there isn't a simple fix so we won't be fixing this in the foreseeable future.
