### ISSUE TITLE
SwipeableStack widget not available

### ISSUE THREAD

**Issue by orchard800** [FlutterFlow/flutterflow-issues#1934]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No SwipeableStack widget

### Expected Behavior

Access to the SwipeableStack widget

### Steps to Reproduce

look for SwipeableStack widget - discover its not there.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghc/1z4tPtbxa7aXycu9ahjgvG0AhU5c0sNobbxAjIoDoPJkUaeD7fk5pXdCqYAhlKEWKij8H+fznkYTtLPEnCyWdb65z+LhfEQ6XRlO/aoTSC6iKX0EkGZ9mfHKO0aeznhJBLs9sWloC22bzJN6RThLtQe76Zwh9f6PHaOI=

### Context

I need the swipeable stack widget as a core component of the app I'm building.

### Visual documentation

n/a

### Environment

```markdown
Project ID: stamp-card-raf2gd
FlutterFlow v4.0 released November 28, 2023
Flutter version is 3.13.7
Chrome 119.0.6045.159 (Official Build) (64-bit) 
Ubuntu 23.10
```

**Comment by orchard800** [comment]
If it's been discontinued, it should be removed from the documentation then 😁

**Comment by orchard800** [comment]
Good point @kiwimagic and thanks for pointing out the new pub.dev version!

**Comment by hariprasadms** [comment]
Hi r @orchard800 -Thanks for highlighting this point. Yes it the latest change as per new updates. Docs are being updated shortly. Sorry for the inconvenience.

**Comment by kiwimagic** [comment]
and just for future reference notes about my post above for anyone looking to add a custom package here are my research notes: and a caveat - this is from very brief googling so not saying I am 100% correct. There are definitely other swipable options on pub.dev so pls don't rely on my research only! for example https://pub.dev/packages/swipable_stack and to clarify the one used in FF I believe was https://pub.dev/packages/swipeable_card_stack that package was last updated since Oct 2021, this one https://pub.dev/packages/swipeable_cards_stack was taken from that original and further maintained - last update 10 months ago to incl null safety, then that one is tagged as discontinued and points to a replacement that seems? to be last updated 5 months ago https://pub.dev/packages/flutter_card_swiper

**Comment by wenkaifan0720** [comment]
Hi all. Yes we have replaced the old swipeable stack with this package: https://pub.dev/packages/flutter_card_swiper. And it should be available in our next update.
