### ISSUE TITLE
Chats are duplicating

### ISSUE THREAD

**Issue by boglexsoftware** [FlutterFlow/flutterflow-issues#194]
We've implemented native chat of FlutterFlow in our app and the app creates many duplicates of conversations. Will attach the screenshoot with issue: https://s3.eu-central-1.amazonaws.com/sonna.app/WhatsApp+Image+2022-11-17+at+15.17.44.jpeg

**Comment by agreaves** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.

Thank you!

(Apologies for the delayed response, there was a bug in the system and no one was initially assigned this bug)

**Comment by agreaves** [comment]
We've identified the problem and this should be fixed upon our next deploy!
