### ISSUE TITLE
AppSate Update in Custom widgets triggers ChangeNotifier in pages

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#1957]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently if you perform:  

    FFAppState().update(() {
        FFAppState().xxxxxxx = _currentValue;
    });

 then the ChangeNotifier is triggered in all pages (is there a way to remove it from a page?)... that is ok, but many times we only set the AppState as there is no return variable for a custom widget, meaning we get a lot of unnecessary page rebuilds (and backend calls).

### Expected Behavior

Would be good to have a method on the AppState, where the ChangeNotifier is not being triggered, ie.:

 FFAppState().updateNoRebuild(()

or be able to override on the pages within the app (as now we have page state App state shouldnt be used as much):
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/122821259/07e47f8d-fed0-45fc-99e7-77de5ce83996)

### Steps to Reproduce

n/a.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

na

### Context

i have custom widgets that are using FFAppState().update(() that are causing the ChangeNotifier to trigger in other pages.

### Visual documentation

n/a.

### Environment

```markdown
- FlutterFlow version: 3.17.3
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by OldFred2023** [comment]
Its stale because FF have failed to even look at the issue so far.

**Comment by OldFred2023** [comment]
nudge

**Comment by takashiff** [comment]
Hello @OldFred2023, my apologies for the late reply. Unfortunately, this looks like intended behavior with the way AppState is set up in FlutterFlow. Since AppState wraps the entire application, rather than just a single widget/page, when AppState is updated, the entire application is rebuilt accordingly. There is currently a solution in the works that should fix this issue for you, so once it has been released, I can follow up on this thread. However, I am currently unable to provide an ETA on said solution. Thank you for your patience!
