### ISSUE TITLE
FlutterFlow Version out of Date

### ISSUE THREAD

**Issue by bertke** [FlutterFlow/flutterflow-issues#2042]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

This issue has existed in the past and seemed resolved but has now resurfaced for me.  The Ipad version of FF is stuck at the 'Flutterflow version out of date' issue.  I have deleted/re-installed the ipad app and it has not resolved the issue.  I still have this issue from time to time on the mac but deleting and re-installing seems to fix that (although I would still call this a defect as well).  

### Expected Behavior

I would expect to be able to edit my project on my ipad after making changes in another version

### Steps to Reproduce

1) Create a new project on the ipad
2) edit on the mac version of FF
3) return to the ipad app and it will show this message

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESzM7l2IZgosNa1ZDubMBAhQMkQzM6bZI7ku1EdwEhfJznP+wXP8z4RxNLYte6f2w7EVL+8XwFpdbRiPLlUvcrHzCqbpRn/75XQQ3KQTiVVZuaBauOeGh7M+dYIFyG1p63uxV5ANttSiUB1FyYH/CdG3qCf9qOYwx5e6fDbOY=

### Context

Unable to work on my project using the ipad

### Visual documentation

Just the dialog would be relevant but it's the one that has the heading 'FlutterFlow Version out of Date' (with the only option being a button that says 'dashboard')

### Environment

```markdown
- FlutterFlow version: Latest ipad app version
- Platform: Ipad
- Browser name and version: NA (app)
- Operating system and version affected: Ipad OS latest
```

**Comment by agreaves** [comment]
Hi @bertke, sorry for the inconvenience here. Occasionally, due to App Store review the iPad app is a bit behind the web application. So this error occurs when you are editing a project both on iPad and on Web or MacOS. For now you'll need to stick to one of those two, but the updated iPad app should be approved and released soon.

**Comment by bertke** [comment]
Understood. Thank you for the quick response!!

**Comment by agreaves** [comment]
Latest version is released!

**Comment by duEuler** [comment]
> Hi @bertke, sorry for the inconvenience here. Occasionally, due to App Store review the iPad app is a bit behind the web application. So this error occurs when you are editing a project both on iPad and on Web or MacOS. For now you'll need to stick to one of those two, but the updated iPad app should be approved and released soon.


So, it's likely that the same issue is also occurring in the desktop version for Windows.

I've noticed that the project which wasn't edited on the web but was instead modified on the desktop worked fine. However, the project I'm simultaneously developing on Android and the web is currently locked with an error message, preventing any updates.

It would be incredibly helpful if the platform could display the specific version of the project that's causing the error, allowing for a direct comparison with the version used on the web. Additionally, I recommend including the "project version" and "development environment" in the snapshots. Currently, I'm unsure about the last point of editing and whether it was modified by Windows, the web, an iPad, a Mac, or Linux, which complicates reverting to the last stable version before the issue. I suspect the problem is a version incompatibility of the IDE used. As I've been working for days, it's not feasible to troubleshoot this now; I'll try reinstalling and wait for the next version of Windows to return to my previous working mode using Android Studio to compile the project. The Windows version was very good, but not being able to access the project renders it entirely useless and raises concerns for those intending to use it.

This addition would facilitate version management and the identification of potential incompatibilities between edits made on different platforms.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/36971433/05c23290-ebf3-4f1e-a519-4957d271bd9c)
