### ISSUE TITLE
When a user signs out, the Entry Page is not loaded.

### ISSUE THREAD

**Issue by siddharthadevops** [FlutterFlow/flutterflow-issues#207]
## Expected behavior (required)
When a user signs out, the Entry Page should be loaded.

## Current behavior (required)
When a user signs out, the Entry Page is not loaded.

## To Reproduce (required)
1. sign out a connected user.
2. call signOut()

### Bug Report Code
```
To fix the bug, please, replace the assignment of the variable initialUser from the current code: 

class _MyAppState extends State<MyApp> {
  Locale? _locale;
  ThemeMode _themeMode = FlutterFlowTheme.themeMode;
 ...
@override
  void initState() {
    super.initState();
    userStream = acimsocialFirebaseUserStream()
      ..listen((user) => initialUser ?? setState(() => initialUser = user));
```

To this:

```
 userStream = acimsocialFirebaseUserStream()
    ..listen((user) => setState(() => initialUser = user));

```
This way, each time the user is modified the initualUser variable will be set to the new value. 

## Context (required)
Every FlutterFlow app

**Comment by agreaves** [comment]
Hi @siddharthadevops, in FlutterFlow we automatically add a navigation to the Entry page if a "Sign Out" action is selected (unless the user adds a separate navigate action, or you are using Deep Linking and the user is on a page that requires authentication).

`initialUser` is only used to track whether to show the splash page, which is not typically shown when a user simply logs out. In order to  accomplish this, you'd want to navigate the user to a Splash Page upon sign out, which automatically redirects the user to another page after a few seconds.
