### ISSUE TITLE
Account not connected to internet?

### ISSUE THREAD

**Issue by tinrunje** [FlutterFlow/flutterflow-issues#2171]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Projects won't connect to the internet. They won't save, they won't run code expressions, they won't fetch Supabase schemas, even when projects are opened, the main FF dashboard won't load again (I have to close FF and re-run) and it actually won't open the support chat when a project is opened.

My internet works completely fine, I tried multiple different internet providers too (went to office, to friends place, parents place, tried connecting to mobile) and nothing worked.

Is this a problem with FF servers? However based on [https://status.flutterflow.io](https://status.flutterflow.io) everything seems operational.

### Expected Behavior

The project is connected to the internet.

### Steps to Reproduce

1. Create new page
2. Add a Text widget
3. Use the "Code Expression"
4. Put anything simple and tap on "Check Errors"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Can't generate, it just loads forever

### Context

Progress in my projects - add features and fix bugs.

### Visual documentation

I'll show a few things that load forever/time out:
Code expressions time out:

![Screenshot 2024-01-15 at 09 36 36](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b6c60d99-5f02-47a6-87ae-132ed196979c/dfba0f1b-4309-4ab2-bfdf-c418db1324c6?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNmM2MGQ5OS01ZjAyLTQ3YTYtODdhZS0xMzJlZDE5Njk3OWMvZGZiYTBmMWItNDMwOS00YWIyLWJmZGYtYzQxOGRiMTMyNGM2IiwiaWF0IjoxNzA3MTgxNTQwLCJleHAiOjMzMjc3NzQxNTQwfQ.bXEQxnlQWgbVTUCXZtEwvvE7jRsVLS7s7ORxuOfp5q8)

The FF chat loads indefinitely:

![Screenshot 2024-01-15 at 09 37 06](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a3e0ffbb-525b-45ce-9328-cef1be3aa3b4/2ab5f50c-af68-4d22-9dbd-994d2d9e04c3?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hM2UwZmZiYi01MjViLTQ1Y2UtOTMyOC1jZWYxYmUzYWEzYjQvMmFiNWY1MGMtYWY2OC00ZDIyLTlkYmQtOTk0ZDJkOWUwNGMzIiwiaWF0IjoxNzA3MTgxNTQwLCJleHAiOjMzMjc3NzQxNTQwfQ.MLq8EHqWBZfjRXo5nE726qBXlsTFXx7JH8BqiCRLGcI)

The bug report code generator runs forever (and finishes with error):

![Screenshot 2024-01-15 at 09 38 38](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4df11d12-8fed-4b5e-9633-a13b2c29d594/32a6ea23-d796-4d37-9162-559c905dd49a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80ZGYxMWQxMi04ZmVkLTRiNWUtOTYzMy1hMTNiMmMyOWQ1OTQvMzJhNmVhMjMtZDc5Ni00ZDM3LTkxNjItNTU5YzkwNWRkNDlhIiwiaWF0IjoxNzA3MTgxNTQwLCJleHAiOjMzMjc3NzQxNTQwfQ.FkX7iqc2bIIDL2CM5UOx7srXvWWkICOr2wO2KQnu33A)

Functions don't load:

![Screenshot 2024-01-15 at 09 40 27](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6711068e-09a3-486d-a713-59166c81ec11/148be2a9-f845-428c-bf88-3bd90c481657?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NzExMDY4ZS0wOWEzLTQ4NmQtYTcxMy01OTE2NmM4MWVjMTEvMTQ4YmUyYTktZjg0NS00MjhjLWJmODgtM2JkOTBjNDgxNjU3IiwiaWF0IjoxNzA3MTgxNTQwLCJleHAiOjMzMjc3NzQxNTQwfQ.TQ-pUqdGXSqcB0t9Lpd_mnvABNtb5epwzJmNrBg7OiY)

Trying to return to the dashboard from the project is just an infinite grey screen:

![Screenshot 2024-01-15 at 09 41 18](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/342ffaa6-f0d5-4d21-be2f-97332057fe26/9c2055fc-a820-406d-ba95-cabe377a33e4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zNDJmZmFhNi1mMGQ1LTRkMjEtYmUyZi05NzMzMjA1N2ZlMjYvOWMyMDU1ZmMtYTgyMC00MDZkLWJhOTUtY2FiZTM3N2EzM2U0IiwiaWF0IjoxNzA3MTgxNTQwLCJleHAiOjMzMjc3NzQxNTQwfQ.p0oJ4ggCgWEj1bRKEZiTHrkrjI8_H_GkA9xQdgH_zCc)

The domain is apparently not connected (although the project has been in production for 6months):

![Screenshot 2024-01-15 at 09 43 30](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e2608eab-e29e-4023-80e2-3d6752cf606a/8118f3a5-9997-4cbf-9b85-45e110f07cff?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMjYwOGVhYi1lMjllLTQwMjMtODBlMi0zZDY3NTJjZjYwNmEvODExOGYzYTUtOTk5Ny00Y2JmLTliODUtNDVlMTEwZjA3Y2ZmIiwiaWF0IjoxNzA3MTgxNTQwLCJleHAiOjMzMjc3NzQxNTQwfQ.2OkR1EnKQFyeX0RCDycLD9r1q8cQe798pq_ZsiF4QKg)

There are many more, but you get the point.

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: FlutterFlow v4.0 released January 12, 2024
- Platform: MacOS Desktop (tried web too)
- Browser name and version: Chrome Version 120.0.6099.216
- Operating system and version affected: macOS Sonoma 14.1
```

**Comment by hariprasadms** [comment]
Hi @tinrunje - Thanks for submitting the issue. It's strange to see your project not working despite a stable internet connection. 

To investigate further, I need a few more details:

* Have you tested the same steps in other projects? What is the issue status?
* Could you provide the project bug report code? This information is required to access your project.
* Try creating a brand new project and follow the same steps to see if you can reproduce the issue. If you can, please share the project bug report code for the new project. Thanks!

**Comment by tinrunje** [comment]
Hi @hariprasadms 
- Yeah. All projects on my account are acting the same. They just don't connect to the internet (I get the pop-up for internet access not available after a couple of min too).
- I would love to provide the bug report code ... it just doesn't get downloaded, it literally doesn't work.
- I've created a brand new project and I am experiencing the same exact issue (I tried with custom function and with creating a Code Expression). I am also unable to get the bug report code for this too. But I have made this demo project public so here's the link to that: https://app.flutterflow.io/project/bugtest-Oposms 

I also posted the issue here: https://community.flutterflow.io/ask-the-community/post/project-not-connected-to-internet-not-saving-2Ey3vddTWeKENPP 
P.S. this started happening last night (around 9PM GMT+1, Sunday 14.01.'24)

I am also attaching some screenshots:
![Screenshot 2024-01-15 at 11 53 07](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/9807b697-2e61-4e9d-a501-34827687849e)
![Screenshot 2024-01-15 at 11 53 34](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/865d3ad7-2dbd-46c0-95f1-23d87cb1548a)
![Screenshot 2024-01-15 at 11 54 50](https://github.com/FlutterFlow/flutterflow-issues/assets/52575319/c88d3832-f0a7-4fed-bb03-511f7b5284fe)

**Comment by tinrunje** [comment]
@hariprasadms I found out what breaks it - Code Expressions.
The project works completely fine until a Code Expression is opened, it then disconnects from the internet and nothing else works.

**Comment by gentleVirus** [comment]
I am experiencing the same problem. Exactly like @tinrunje described. To me it happens in short intervals (everything in the custom code are and code expression seem to trigger it nearly instant). I can do a few changes then suddenly I get the message "project save timed out". Then I get the same errors as described. And I can't publish  anymore. I switch tabs back and forth to the web publishing tab until the the project assets load again. Then problems stop for 2 or 3 Minutes and then start gain. Tested this on several devices. I also noticed that the whole browser connection (e.g. opening other websites) stops working as soon as the FlutterFlow problems occur. I know this sounds like it's a problem with my internet connection but at the same time the errors appear, all other devices in the network work fine. Also this only occurs when I use FlutterFlow and the time out starts, otherwise I can browse all day long and everything works perfectly. I only tested chrome so far. Could there be some connection between the the browser (chrome) and the time outs?

**Comment by gentleVirus** [comment]
I am experiencing the same problem. Exactly like @tinrunje described. To me it happens in short intervals (everything in the custom code are and code expression seem to trigger it nearly instant). I can do a few changes then suddenly I get the message "project save timed out". Then I get the same errors as described. And I can't publish  anymore. I switch tabs back and forth to the web publishing tab until the the project assets load again. Then problems stop for 2 or 3 Minutes and then start gain. Tested this on several devices. I also noticed that the whole browser connection (e.g. opening other websites) stops working as soon as the FlutterFlow problems occur. I know this sounds like it's a problem with my internet connection but at the same time the errors appear, all other devices in the network work fine. Also this only occurs when I use FlutterFlow and the time out starts, otherwise I can browse all day long and everything works perfectly. I only tested chrome so far. Could there be some connection between the the browser (chrome) and the time outs?

**Comment by gentleVirus** [comment]
I am experiencing the same problem. Exactly like @tinrunje described. To me it happens in short intervals (everything in the custom code are and code expression seem to trigger it nearly instant). I can do a few changes then suddenly I get the message "project save timed out". Then I get the same errors as described. And I can't publish  anymore. I switch tabs back and forth to the web publishing tab until the the project assets load again. Then problems stop for 2 or 3 Minutes and then start gain. Tested this on several devices. I also noticed that the whole browser connection (e.g. opening other websites) stops working as soon as the FlutterFlow problems occur. I know this sounds like it's a problem with my internet connection but at the same time the errors appear, all other devices in the network work fine. Also this only occurs when I use FlutterFlow and the time out starts, otherwise I can browse all day long and everything works perfectly. I only tested chrome so far. Could there be some connection between the the browser (chrome) and the time outs?

**Comment by tinrunje** [comment]
Thanks for sharing.
I can also confirm I tried on multiple devices... however, only on Mac devices (I don't have any Windows to test on).
I can also confirm that Code Expressions trigger this behaviour for me instantly, but it also sometimes gets triggered irrelevant of the Code Expressions.

**Comment by RoboduckNL** [comment]
Happens to me too at random moments in Google Chrome (Windows pc). Been working in Edge now and works perfectly fine. I can confirm what gentleVirus says, although I do not use any custom codes and code expressions. After working a couple of minutes it says the 'Project save timed out'. Super random, also cannot pinpoint why it happens. Worked fine for the last six months. Thanks anyone that's checking this issue!

**Comment by tinrunje** [comment]
@hariprasadms 
The issue does seem to be resolved for me since today in the morning.

**Comment by jpollone** [comment]
> @hariprasadms The issue does seem to be resolved for me since today in the morning.

I've been lucky and haven't seen this message the time I commented last. I'm still using the same macOS app version.

**Comment by jpollone** [comment]
At 10:24 ET on 21-JAN, the infamous "Project save timeout" error flashed. So, I attempted to return to the Project List and the FlutterFlow logo just spun.

- At the time, I was working on a page and switched to a different ConditionalBuilder context.
- Then I looked at the action associated with an icon.
- I think I was working between the multiple conditions since I restarted work at 09:56 ET.

I had not experienced this issue since my last encounter. And I am still using the same macOS app version.

**Comment by takashiff** [comment]
Hey folks, I believe this issue has been fixed recently, but please follow-up in this thread if you are still experiencing issues. Thanks

**Comment by fdelgadofocus** [comment]
I'm  experiencing te same issue

**Comment by fdelgadofocus** [comment]
It is not saving anything new on my project,
It was working pefectly 6 days ago then it stop saving changes

**Comment by fdelgadofocus** [comment]
I already checked everything , mac version, web version, windows version, etc. with no luck.
