### ISSUE TITLE
PageView: action onPageSwitch item Is considered as a list

### ISSUE THREAD

**Issue by fabienCambournac** [FlutterFlow/flutterflow-issues#2250]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I create actions on the onPageSwitch event of a PageView, the variable item type is a list instead of its true value.

### Expected Behavior

I'm expecting for the variable of the item to be the correct value.

### Steps to Reproduce

1. Create a new project.
2. Add a PageView.
3. Generate children from a variable.
4. Open the action flow editor on the event "on page swipe"
5. Create an action and observe that the item is not the correct type.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

PageView

### Context

I need the parameter to make an API call

### Visual documentation

![Capture d’écran 2024-01-26 à 15 59 46](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b8e7ee6f-e802-472c-85dd-a5b86dc0fd2d/5d7e6662-24f2-4a4a-945c-476b66af34c2?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iOGU3ZWU2Zi1lODAyLTQ3MmMtODVkZC1hNWI4NmRjMGZkMmQvNWQ3ZTY2NjItMjRmMi00YTRhLTk0NWMtNDc2YjY2YWYzNGMyIiwiaWF0IjoxNzA3MTU2Mzg0LCJleHAiOjMzMjc3NzE2Mzg0fQ.lTLWIzusIGchwe9Z6a_dZJ1rMryCwzpX8nz0-NWfm4k "=1614x")

![Capture d’écran 2024-01-26 à 16 00 13](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/de031c57-5603-4f10-8081-db88421c1030/83e26f23-5fc7-426e-8367-ac08c78dc851?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kZTAzMWM1Ny01NjAzLTRmMTAtODA4MS1kYjg4NDIxYzEwMzAvODNlMjZmMjMtNWZjNy00MjZlLTgzNjctYWMwOGM3OGRjODUxIiwiaWF0IjoxNzA3MTU2Mzg0LCJleHAiOjMzMjc3NzE2Mzg0fQ.he7Mqy7xpXwup8M5y0bGk1XtMvNYtmt1lf02j-sXoxw "=1495x")

![Capture d’écran 2024-01-26 à 16 00 22](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/2d268ff5-7705-4ff0-b6f5-ded8c3876709/fb074219-90ba-41a8-8dcb-4cc0c834d04e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yZDI2OGZmNS03NzA1LTRmZjAtYjZmNS1kZWQ4YzM4NzY3MDkvZmIwNzQyMTktOTBiYS00MWE4LThkY2ItNGNjMGM4MzRkMDRlIiwiaWF0IjoxNzA3MTU2Mzg0LCJleHAiOjMzMjc3NzE2Mzg0fQ.TFxWyYxhjikpr-M3YnFVp8j9wYQ73QOOHNeMpVmog0o "=1495x")

![Capture d’écran 2024-01-26 à 16 00 29](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/24bc5fa5-fc8a-4366-b27f-e3ace2e72ecd/8130e16b-28be-4947-aea2-e713f56aaf09?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yNGJjNWZhNS1mYzhhLTQzNjYtYjI3Zi1lM2FjZTJlNzJlY2QvODEzMGUxNmItMjhiZS00OTQ3LWFlYTItZTcxM2Y1NmFhZjA5IiwiaWF0IjoxNzA3MTU2Mzg0LCJleHAiOjMzMjc3NzE2Mzg0fQ.41YN4lh9520HFKgG9-ozIUByB3xSCyOeIYMxuBQ_W-I "=1495x")

### Additional Info

*No response*

### Environment

```
- FlutterFlow version: v4.1 (released January 25)
- Platform: Web
- Browser name and version: Chrome 120.0.6099.234
- Operating system and version affected: macOS 14.2.1
```

**Comment by fabienCambournac** [comment]
Why am I getting no feedback? It's been a month since I created this ticket!

**Comment by rzambroni** [comment]
Hey @fabienCambournac, sorry about the delay in the answer, we are trying to get up to speed with everything. Are you still experiencing this problem? if so, do you mind sharing the bug report code of the example project above? Thanks!

**Comment by fabienCambournac** [comment]
Hey @rzambroni
Yes, I still have this issue. I can't get an error code because the interface is mistaken about the expected variable type (it's defined as a List). I've created a project with the issue (test-page-view-bug-5l8oto). If you try to set the value in the "on page swipe" event action, you'll see that it's impossible.
<img width="1459" alt="Capture d’écran 2024-04-12 à 17 41 37" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40824967/b76bf98b-5b53-4619-a201-e9ff3a426912">
<img width="1459" alt="Capture d’écran 2024-04-12 à 17 41 42" src="https://github.com/FlutterFlow/flutterflow-issues/assets/40824967/842d46e3-485c-46d2-8dd0-16688c075d45">

**Comment by rzambroni** [comment]
Hey @fabienCambournac, if i understand correctly, you are trying to save the index of the selected page into the variable "numberSelected" after the On Page Swipe event. Have you tried using the Widget State -> PageView Current index variable?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/53f11057-c935-4414-a596-978f7b34f8b0/ea9feac0-50d5-46cd-8223-724d14433d92?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81M2YxMTA1Ny1jOTM1LTQ0MTQtYTU5Ni05NzhmN2IzNGY4YjAvZWE5ZmVhYzAtNTBkNS00NmNkLTgyMjMtNzI0ZDE0NDMzZDkyIiwiaWF0IjoxNzEzMjAwODQ1LCJleHAiOjMzMjgzNzYwODQ1fQ.jNwOvIjeotGjgcpeqB9acu14TcTkcZ_XiGhaeopBoh0 " alt="image.png" width="1156" height="782" />

**Comment by fabienCambournac** [comment]
Hey @rzambroni, for the example, I chose to use a number, but I don't want the index. In my actual project, I have an object. So, when it comes to number item, it's not supposed to return the list of page views but rather the current item.

**Comment by ignalauret** [comment]
Hi @fabienCambournac, I am now checking your issue. I understand that you are trying to generate pages from a list of objects (lets say of type PageModel) and then use the selected PageModel when the page is swiped.<br>To achieve this, you are in the right track, but sadly you can't do really complex things on just one action, you need to break it into multiple actions. <br>You would need to add to the Page State a PageModel variable (in my case it's *selectedColor)* and then set that variable, using the "item at index" option, combined with the "Specific Index" and selecting the current index of the PageView, that you will find it under "Widget State".<br>From there, you will have in your variable the updated value, and you can create more actions after to use that new value for whatever you want. 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/432f9a43-07e2-4b99-8c09-4ddc1febad6c/d9e0dfa5-2f48-47b5-963a-b70a6c174029?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80MzJmOWE0My0wN2UyLTRiOTktOGMwOS00ZGRjMWZlYmFkNmMvZDllMGRmYTUtMmY0OC00N2I1LTk2M2EtYjcwYTZjMTc0MDI5IiwiaWF0IjoxNzEzMjk5NzA5LCJleHAiOjMzMjgzODU5NzA5fQ.jK5zHX8GmCs63bZ0a_z0BE0hm7LQRz-wQwo4qiFRRJ4 " alt="Screenshot 2024-04-16 at 5.30.35 PM.png" width="1302" height="723" />

Hope it was clear, if you need any more help please feel free to contact our Customer Support, they will be happy to help you. <br>I'm going to close this issue because it's not a bug on the FlutterFlow platform. If you still think there is an issue here, please let me know.<br>Have a great day!

**Comment by rzambroni** [comment]
Closing this issue since we haven't heard back from you, thanks!
