### ISSUE TITLE
Unable to load FlutterFlow run mode links in browsers not previously logged into FlutterFlow development studio

### ISSUE THREAD

**Issue by tim-weisbrod** [FlutterFlow/flutterflow-issues#2300]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I'm in a browser where I have been in the development studio I can start and run one of the run URLs for my app. This works whether I have previously logged into my app or not.

However, when I open that link in a fresh incognito session, or a different browser, or when someone opens it on a different machine, it gets stuck on a dark screen with a spinning circle around a pulsating Flutter Flow logo & never loads the app. In the developer console I see the following error.

Exception while loading service worker: Error: prepareServiceWorker took more than 4000ms to resolve. Moving on.
at flutter.js?1705313859:48:11
(anonymous) @ flutter.js?1705313859:368

If in that new incongito session / other browser, I then login to the the Flutter development studio, and then retry the link it does work.

I had a long thread with Barry from the support team about this, who asked me to log the issue here. He said:

It seems something related to the FlutterFlow editor session authentication is carrying over to allow run mode URLs to properly initialize even after normal app log out.
But fully anonymous browsers break since they lack that auth association. This implies the apppreview links have some coupling to editor access not yet stripped when shared publicly.
I reproduced the same behavior you outlined during my own testing across chrome profiles. Definitely an area we can improve avoiding that hidden dependency.

### Expected Behavior

The run mode link will load the app successfully, even in a browser that was not used previously to login to the FlutterFlow development studio.

### Steps to Reproduce

Start new incognito session
Load a run mode URL

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si/LlvI92m9tK0L6JdflB/SQQJmI3U5Iwscp/bxIgGIDzPOw+ZPWlbkxvTu2idwlcOESmml4Jp97HhoXXDO5eNU2cfYB4yLt2cAvicHiue5OBDKWWW3JTJ/tjfmXD5MKzuxQnGNFuckIHw16MfdmsSgPdNYzwImdISq/LZO4=

### Context

It has stopped us from being able to share run mode links

### Visual documentation

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/6daf0d62-35b3-4964-8e1b-7c69b6c8eb83/a59a023c-198d-41ed-bb55-ed425c8b490d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82ZGFmMGQ2Mi0zNWIzLTQ5NjQtOGUxYi03YzY5YjZjOGViODMvYTU5YTAyM2MtMTk4ZC00MWVkLWJiNTUtZWQ0MjVjOGI0OTBkIiwiaWF0IjoxNzA3MTYxMDc5LCJleHAiOjMzMjc3NzIxMDc5fQ.YnfKWwguV0pPpcM3x2kF_L1rOPc1yQ8QTZG6LK_wq6I)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Flutter version: 3.13.7
- Platform: Web
- Browser name and version: Chrome 121.0.6167.140 & Edge 122.0.2365.8
- Operating system and version affected: Windows 11 Pro 23H2 Build 22635.3139
```

**Comment by sbis04** [comment]
Hi @tim-weisbrod, sorry for the inconvenience that you are facing. But this is an expected behavior. Currently, our Run mode links are only accessible to the users having access to the project. You can get more information from the tooltip present inside the "Test, Run & Publish" dialog:

<img width="461" alt="Screenshot 2024-02-06 at 10 07 03 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/bfbc29c4-9823-4b9a-979b-56bc303496fa">

If the project is publicly accessible then any user can access the Run mode link even if they are not logged in. But just to note, anyone can then clone your entire project. You can make a project public from here:

<img width="534" alt="Screenshot 2024-02-06 at 10 12 45 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/43280874/872f9e8f-2e7f-4f81-8a82-01f8a419a0b1">
