### ISSUE TITLE
I get an error when I go to a new screen

### ISSUE THREAD

**Issue by jorjik** [FlutterFlow/flutterflow-issues#2365]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When switching from the MyTrips screen to TripPageV2, an error is displayed.

### Expected Behavior

there should be no error

### Steps to Reproduce

1. watch the video below 2) use the link
   [https://app.flutterflow.io/run/RhMyRRbWDCuMCpyIAUEP](https://app.flutterflow.io/run/RhMyRRbWDCuMCpyIAUEP)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4slsn1zIt1m/VY+Kr2ccBr/Sg7C0AjU4Eascp/bxIgGIDzPOw+ZPWkTFNCYMerY2xAPkSmml0HwNqOjuDLNPdePTaAbrp+/8x+TAHNfEOma5OBDJeeOGsmHe5jCX3D37WjnhBRLthoL1Jg6jmMJO69Xj/qO5f6IndISq/LZO4=

### Context

I want to see detailed information about the "trip"

### Visual documentation

video [https://somup.com/cZnqI1pttE](https://somup.com/cZnqI1pttE)
error [https://i.imgur.com/E2Ia85S.png](https://i.imgur.com/E2Ia85S.png)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1
- Platform: web
- Browser name and version: yandex-browser 23
- Operating system and version affected: windows 10
```

**Comment by hariprasadms** [comment]
Hi @jorjik, Thank you for submitting the issue. The provided steps are not comprehensive enough for us to fully understand the problem. Additionally, we need more information about where the issue is located within your project, such as the page name and relevant data details. Without these details, it's challenging for us to accurately diagnose the problem. Please update the issue with these additional details. Thank you!

**Comment by jorjik** [comment]
https://app.flutterflow.io/run/6O5bGonctFcsrmF4NngL

log in via SMS, fill in your profile
choose a destination:
from - odessa
where to - moldova
select icon - passenger
click the find trip button
* as a result there will be one card
** pressing it will cause an error

**Comment by hariprasadms** [comment]
Hi @jorjik - Thank you for providing futher details. Since the login requires a phone number with a specific code, I'm unable to log in using a UK number. Consequently, I can't access the app to investigate the issue. While I've looked at the project pages, the **CreateTripe** and **TripPageV2** page doesn't provide sufficient information about the error.

Could you please share test login credentials with me? This will enable me to log in and examine the app, allowing me to better understand the issue and provide assistance. Thank you.

**Comment by jorjik** [comment]
send email to [hari@flutterflow.io](mailto:hari@flutterflow.io)

**Comment by hariprasadms** [comment]
Hi @jorjik - No details received through email. Please re-send it. Thanks

**Comment by jorjik** [comment]
re-send it

**Comment by hariprasadms** [comment]
Hi @jorjik - Not received details through email yet.

**Comment by jorjik** [comment]
![tel-for-test](https://github.com/FlutterFlow/flutterflow-issues/assets/116784/6e514db4-342b-4e93-af4f-c5bc85e01074)
p.s. you can use any mobile number - it does not have to be +3

**Comment by hariprasadms** [comment]
Hi @jorjik - Thank you for investigating the steps outlined. Upon logging in to review the process you described, I observed that the error displayed on the browser console does not provide sufficient information. Upon examining the createTrip page, I noticed that there is a container with a collection reference query, along with a click action associated with it. I suspect that this configuration might be causing the issue.

My suggestion would be to try mapping the data document fields and then attempting the operation again. However, please note that this is a high-level suggestion. Based on the configurations observed, it appears that the issue is more related to the configuration on your end rather than being a bug. If you need futher more help, reach FF support team. I hope it can help you. Thanks 

<img width="1511" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/8110121c-68e5-4066-b43c-e4e23c6f97ee">
