### ISSUE TITLE
Null values in Run Mode with authentication 

### ISSUE THREAD

**Issue by Josefpa** [FlutterFlow/flutterflow-issues#239]
How to reproduce:

Create a home page that required authentication
have a backend query within that 
(the user in the test/run mode has already logged in)

that queries a document from reference which is within the authentication/user document that has a values that the page depends on:

For example user photos collection that has a reference in the user collection and i want to load an image from the photos collection on the page 

Works on initial load, but when you instantly reload 
You will get this error:

After reloading like ~20 times it sometimes works

but mostly you have to restart session

![image](https://user-images.githubusercontent.com/67612575/208231240-6416a2b7-8050-4295-ba38-5e34c4934536.png)
![image](https://user-images.githubusercontent.com/67612575/208231264-140e830a-a87c-4968-8e2e-c0f11eaab613.png)

I don't think this will help since the bug in the issue tab is that the custom code has to be compiled even though it is and the run works perfectly with the new code 
![image](https://user-images.githubusercontent.com/67612575/208231437-52b8eec9-5394-430c-992d-183e7ee3ad74.png)

ITFfhefqwItIn7wG15SIY+xWgmU4C1McTZM3lOsYGBAjG5CoPOwhdeD+aXdeZ9DiY347AFSajToezPTTvdjPCPEBBEmrGZ82k/UwKlCvHAM=

**Comment by agreaves** [comment]
Hi @Josefpa, this is actually due to the backend query you have in the main column in the HomePage. It's looking for a field in the User Document that is not necessarily there (the user link). When this field is not populated (as is the case when a user first signs up) you will get an error because we are trying to make a query on a null Document Reference. To prevent this, you can add conditional visibility to your widget so that it only appears if the reference you set from a variable "Exists or Is Not Empty".

The only other explanation (if this does not fix the problem) is that this is the same issue as #199, so you can also look for updates to that issue. For now, I'm closing this as either fixed or a duplicate.
