### ISSUE TITLE
Persistent AppState (List JSON) Not Saving on App Restart in FlutterFlow

### ISSUE THREAD

**Issue by ckarmy** [FlutterFlow/flutterflow-issues#2413]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am experiencing an issue in my FlutterFlow project where a persistent AppState (List JSON) is not being saved as expected. This AppState is generated through a custom action, which is triggered by a button. The action populates the app successfully and operates as intended during the session. However, the problem arises when I close the app and then reopen it; the supposed persistent variable does not retain its data.

### Expected Behavior

The app state keep the data

### Steps to Reproduce

* open the project [https://app.flutterflow.io/project/test-4ztdzk](https://app.flutterflow.io/project/test-4ztdzk)
* press "generate JSON" button many times
* restart the app and the list is empty

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89got8G0LrqL8J6hQAkH1x/bZJEl9cbVQ0dJZTkPbQEZ+r+VGtBTcOEeFZqG1WagmUe0cmOjePDJ8IEJkyWeINoyYdqQw/vXk2geJSVOpbhdEZ5PJpRIXbA07a32Ql4CNttSXg+w2z/cq3qNleeY8aSfxBlZ7vfcPo=

### Context

reuse data in a app state

### Visual documentation

![Captura de pantalla 2024-02-29 a la(s) 15 27 16](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f375dcf9-5a70-4c31-8c23-9225a7e9c7cd/d6db9911-234b-4457-bdac-82fc2306f997?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMzc1ZGNmOS01YTcwLTRjMzEtOGMyMy05MjI1YTdlOWM3Y2QvZDZkYjk5MTEtMjM0Yi00NDU3LWJkYWMtODJmYzIzMDZmOTk3IiwiaWF0IjoxNzA5NjQ4Njg2LCJleHAiOjMzMjgwMjA4Njg2fQ.cbbomn0eDznirIvyJfsuE6uJr7wbur_r4EbYAAqjeiQ)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1
- Platform: All
- Browser name and version: Chrome Versión 120.0.6099.129 (Build oficial) (arm64)
- Operating system and version affected: Sonoma 14.2
```

**Comment by hariprasadms** [comment]
Hi @ckarmy - Thank you for bringing up the issue. The reproducible steps provided are a bit confusing. After reviewing your project, I noticed that you have an app state created, but there is no JSON data inputted into it. In this scenario, the app state will remain empty when accessed during the build run. Is this what you are experiencing, or is there something else happening? Please provide clearer steps to describe the issue, as this will help us triage the problem more efficiently. Thank you.

**Comment by ckarmy** [comment]
Thanks @hariprasadms for the reply. The JSON is created via custom code when you click on the button "Geneterate JSON". But noyt retain the data...

The code:

```
Future json() async {
  FFAppState().update(() {
    List<Map<String, dynamic>> item = [];

    item.add({"test": "test"});

    FFAppState().ItemsJson.add(item[0]);
  });

  print(FFAppState().ItemsJson);
}
```

**Comment by ckarmy** [comment]
@hariprasadms, I've noticed that the error occurs when the secure persisted fields option is checked. When this option is selected, the variable (JSON List) is not saved.
<img width="296" alt="Captura de pantalla 2024-03-05 a la(s) 11 15 29" src="https://github.com/FlutterFlow/flutterflow-issues/assets/10090783/615e11f9-1e8e-422e-8f12-02d2fe5cb1ba">

**Comment by rzambroni** [comment]
hi @ckarmy, thanks for the report! I did the same example but instead of using your custom action i implemented the same behavior by utilizing the App State Change actions provided by FlutterFlow and it is working as expected.  The state json list saved on the app state is persisted correctly even when the app is restarted. <br><br>Although it seems like your custom action is adding the items to the json on screen correctly i'm not sure if it is updating the state correctly. <br>I would recommend using the feature provided by FlutterFlow for this particular use-case. <br><br>Thanks!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/bdb09888-36e2-4e7b-9647-cdbf6ee484ab/73a77611-939b-4161-a102-2308b5709252?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZGIwOTg4OC0zNmUyLTRlN2ItOTY0Ny1jZGJmNmVlNDg0YWIvNzNhNzc2MTEtOTM5Yi00MTYxLWExMDItMjMwOGI1NzA5MjUyIiwiaWF0IjoxNzEyOTQxMjAxLCJleHAiOjMzMjgzNTAxMjAxfQ.RRw0H1pDo8d0nVYUYzuPbpMtTRHdh49hc-fN-pE2dDA " alt="image.png" width="1507" height="918" />

**Comment by mirhec** [comment]
Hi @rzambroni,

do you want to say that it is not supported to change the app state by using custom actions? This is a huge issue for us, because we have quite complex api calls and need / want to execute them in custom actions. The response should be stored persistently in the app state. If this is not possible, we need to think about another solution, because it is a nogo for us to migrate every custom action logic to FlutterFlows API functionality.

**Comment by rzambroni** [comment]
Hi @mirhec,

Apologies for any confusion! You’re absolutely right that changing an appState variable is supported through custom actions. However, we are unable to provide support for every custom action that users create and implement. In some instances, the specific use case may not require a custom action and could be implemented more reliably through the FlutterFlow UI, reducing the potential for errors.

If you're facing any issues, I recommend opening a new ticket with detailed replication steps. If possible, including a blank project where the issue can be reproduced would greatly assist in speeding up the troubleshooting process.

Thanks for your understanding!
