### ISSUE TITLE
Screen freezes on black after opening some pages in my project

### ISSUE THREAD

**Issue by felipecasali** [FlutterFlow/flutterflow-issues#2426]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

FlutterFlow goes to a black screen when I open some pages in my project.

### Expected Behavior

Open normally the pages

### Steps to Reproduce

Open the Home page in Minha Obra project.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gi8rlvJB1pbxG7ZPyce9V+Sk4NkQlbJc0sNobbxAjIoDoPJkUaeD4dktWcN/kTQhPKEWJpEQCwNLNiIfpVMEFBzSdUb5P+Mx1VQzdRlG/aoTUDc+rPHxCHdxUJnav35+FvxVSJs5iLHwi3Ga1N/KuSi3YJ4/7Zwh9f6PHaOI=

### Context

I can't edit the main pages in my project.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/11812375/05822ac7-5f59-46e8-a5ea-12c0a3bb2c46](https://github.com/FlutterFlow/flutterflow-issues/assets/11812375/05822ac7-5f59-46e8-a5ea-12c0a3bb2c46)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.13.7
- Platform: MacOs
- Browser name and version: Chrome
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @felipecasali - Thank you for submitting the issue. In the recorded video, it's not clear when exactly the screen goes blank—whether it's upon clicking, navigation, or another action. Could you please provide the exact steps when you observe this behavior? This additional information would be helpful. Thank you.

**Comment by felipecasali** [comment]
Hi Hari,

The issue happens as soon as I click on some pages like Home,
HomeResponsavel... now I've realized that it happens only in Chrome.
I could open the project normally in Safari.

Felipe Casali
11-97084-3096

**Comment by leoleo-s** [comment]
I noticed it in my apps too. This happens every time you insert an image widget or turn on the "add background widget" on the appBar.

**Comment by hariprasadms** [comment]
Hi @felipecasali - I have verified your project thoroughly and navigated through all the pages multiple times, but I haven't encountered any issues on my end. Since you mentioned that the problem occurs only on the Chrome browser, it's possible that it's related to some browser extensions. However, I'm not certain. Could you try accessing the project in Chrome's incognito mode and see if you see the same behavior there?

**Comment by JorgeABP** [comment]
Hi, I've been leading with the same problem since yesterday at the evening. I tried to open my projects with chrome in the normal way and in incognito and the problem persist (black screen). I opened my project in Safari and it works but in a very slow motion. I'm using MacOs Ventura 13.1

**Comment by zetabrands** [comment]
I too am experiencing this in Chrome. It's maddening. Woke up the next day, did a refresh, and suddenly it auto-refreshes to a blank screen like OP. 

I dont have to take any action, just open the project and a few seconds later it's going to refresh and lock out. I turn off hardware acceleration in chrome, the problem goes away, but it becomes unusably slow. 

I verified by grabbing a laptop and going to the same site, working fine in that computer's chrome. Reinstalled chrome, removed all settings from original computer, problem still exists. I also tried Safari like OP and I could open it, but it's so slow to work with in there. 

It's incredibly frustrating because it's not something happening universally. Why on earth my one laptop running chrome works fine, while the one I've been working on daily for a year overnight suddenly can't load app.flutterflow.com despite fully reinstalling chrome, going incognito, etc.

**Comment by jlsimmo** [comment]
I have exactly the same issue. Only some screens do it. Only in chrome.

**Comment by deliChips** [comment]
I'm another one with this issue, I tried accessing a page I have not worked on for weeks, its been loading fine during testing though. Tried opening in the Flutterflow builder and it turns black/crashes. Chrome console is showing memory issues from what I gather.

**Comment by smplfy** [comment]
Running into the same issue here as well. Only a specific page. Only in Chrome on MacOS.

**Comment by takashiff** [comment]
Hi all, thank you for the reports. There's currently an issue with [Flutter shaders rendering on Chrome](https://github.com/flutter/flutter/issues/140504). The following steps may help to temporarily work around this issue:

- Go To chrome://flags/
- Search for "Out-of-process 2D canvas rasterization" and enable the flag
- Relaunch the chrome browser

Thanks

**Comment by jlsimmo** [comment]
Thank you! That’s fixed the problem for me. JohnOn 6 Mar 2024, at 19:47, takashiff ***@***.***> wrote:﻿
Hi all, thank you for the reports. There's currently an issue with Flutter shaders rendering on Chrome. The following steps may help to temporarily work around this issue:

Go To chrome://flags/
Search for "Out-of-process 2D canvas rasterization" and enable the flag
Relaunch the chrome browser

Thanks

**Comment by takashiff** [comment]
@jlsimmo That's great to hear! Thanks for letting me know
