### ISSUE TITLE
Run Time error - checkgroup set all

### ISSUE THREAD

**Issue by havle** [FlutterFlow/flutterflow-issues#248]
![image](https://user-images.githubusercontent.com/4477733/208639585-a0caf318-b0f3-4421-9fdf-dc2daf4355fa.png)

When using the set all for Checkbox group this error appeared in run time
Error: Command failed: flutter build web  --web-renderer html --no-pub --no-version-check
Target dart2js failed: Exception:
lib/setting_user_new/setting_user_new_widget.dart:811:65:
Error: The getter 'siteCheckboxCompanySiteRecordList' isn't defined for the class '_SettingUserNewWidgetState'.
 - '_SettingUserNewWidgetState' is from 'package:instask/setting_user_new/setting_user_new_widget.dart' ('lib/setting_user_new/setting_user_new_widget.dart').
                                                                siteCheckboxCompanySiteRecordList
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by agreaves** [comment]
Thanks for the bug report! This is because the widget that has the Select All action does not have access to the options that populate the Checkbox Group, since these come from a Backend Query on the Checkbox Group itself. We have added a project error for when this is the case.

In order to fix, make sure to set the Backend Query on a widget that contains both the Checkbox Group and the widget that is performing the Select All action.
