### ISSUE TITLE
OpenAI TTS web bug

### ISSUE THREAD

**Issue by ozzymen** [FlutterFlow/flutterflow-issues#2530]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When having a conversation with my gpt assistant. my speech to text and everything else works fine. The only thing that does not work is the TTS from OpenAI. The chat gives me a response but no voice is played. I did some research and came to the conclusion that it may be due to autoplay restrictions on google chrome require permission before letting a page autoplay. However, i find this weird because the Flutter TTS seems to work. would love to see if there is a way to get this fixed

### Expected Behavior

I speak to chat assistant, it responds with OpenAI set voice

### Steps to Reproduce

1. set up any chatbot
2. set up openai TTS via custom actions
3. set an action chain to play openai tts with chatbot's response
4. play.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

unknown

### Context

trying to write a sales training bot, it wont be effectives on web if user cannot hear a voice talking to them

### Visual documentation

---

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform:Flutter web browser
- Browser name and version: chrome
- Operating system and version affected: --
```

**Comment by hariprasadms** [comment]
Hi @ozzymen -Thank you for submitting the issue. Upon reviewing the expectations outlined in the issue details, it appears to be more specific to the functionality you are utilizing with a third-party service. In such cases, the FlutterFlow support team should be the primary contact for further assistance. If they confirm that there is an issue with FlutterFlow's basic features, we will investigate the issue here. Please reach out to the FlutterFlow support team. Thank you.

**Comment by ozzymen** [comment]
I already did and they sent me to you?? Do you at least have any potential fixes?Best,On Mar 15, 2024, at 4:37 AM, Hari ***@***.***> wrote:﻿
Hi @ozzymen -Thank you for submitting the issue. Upon reviewing the expectations outlined in the issue details, it appears to be more specific to the functionality you are utilizing with a third-party service. In such cases, the FlutterFlow support team should be the primary contact for further assistance. If they confirm that there is an issue with FlutterFlow's basic features, we will investigate the issue here. Please reach out to the FlutterFlow support team. Thank you.

**Comment by leighajarett** [comment]
Oh no, that's so frustrating. So sorry about that! We're looking into this issue, thanks so much for your patience

**Comment by leighajarett** [comment]
Hi there! We looked into this some more and I'm not sure how much we can do beyond warn users before building for web. 

It looks like something that Chrome (and many other major browsers) do - intentionally block audio without interaction to prevent random webpages from playing noise out of nowhere. [https://stackoverflow.com/questions/49930680/how-to-handle-uncaught-in-promise-domexception-play-failed-because-the-use?rq=2](https://stackoverflow.com/questions/49930680/how-to-handle-uncaught-in-promise-domexception-play-failed-because-the-use?rq=2)

**Comment by ozzymen** [comment]
Yes I’ve talked about this with you guys and have been trying to find a work around for about a month now. On Apr 10, 2024, at 7:11 AM, Leigha Jarett ***@***.***> wrote:﻿
Closed #2530 as not planned.

**Comment by leighajarett** [comment]
I think the fix would just be for you to change the design of your app since this is not how browsers want web apps to behave

**Comment by ozzymen** [comment]
Okay can you connect me to some engineer or somebody more qualified to answer this question? You’re handling this horribly and it’s clear you’re trying to do the bare minimum to solve this issue. I already mentioned multiple times that Google chrome isn’t allowing and asked if there were any solutions including different ways to code/design.Please connect me to somebody who knows what they are doing. On Apr 10, 2024, at 10:57 AM, Leigha Jarett ***@***.***> wrote:﻿
I think the fix would just be for you to change the design of your app since this is not how browsers want web apps to behave

**Comment by leighajarett** [comment]
Sorry that you're frustrated.

I don't have your project ID to see how you designed this action because you didn't specify the bug code when creating this issue. Also, the steps are unclear so I cannot recreate from a blank project. Without that information it's not possible for me to tell you how to redesign your own application. 

Since the browser doesn't want you to play noise without a user action, I would suggest that you ensure the sound is only triggered based on some specific user action. Once again, without looking at your project in detail, it's impossible for me to recommend a specific next step.

I'm sorry you didn't have luck with the support team - that's unfortunate and I will bring that feedback back to our team! However, this issue tracker is meant for bugs that are reproducible from a blank project. This is not a forum for advice on re-architecting your app. 

Sorry again that this isn't the answer you were hoping for.
