### ISSUE TITLE
FF generates the codes inconsistently.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#256]
## Expected behavior (required)

- Consistent behavior based on the Action Output variable

## Current behavior (required)

- When I add two Conditional Visibility widgets, FF generates the code inconsistently and produce `Null check operator used on null value`.

## To Reproduce (required)

1. Create an custom action that returns false.
2. Add the action on `OnPageLoad`
3. Save the output as `canCreate` variable name.
4. Add two Conditional Widgets in a column with `canCreate` as its conditional variable.
5. Set the visibility true to the first Conditional Visibility Widget.
6. Set the visibility false to the second Conditional Visibility widget.

And you will see some similar codes like below.

```
Column(
  mainAxisSize: MainAxisSize.max,
  children: [
    if (canCreate ?? true) ...
    if (!canCreate!) ..
  ]
```

The problem on the code above is that;

- The first code is safe with null value error.
- The second code produces `null check operator used on a null value`.

Either the two codes use `null check operator` or not. Not mixing like one use `null check operator` and the other does not.

The two are inconsistent and that makes difficult to build app.

I wish the second code would be `if ( canCreate ?? false )`.

This goes similar to the integer type action variable.

If I put `Greater Than` 0, it will produce `if (canCreate! > 0)` where it uses `null check operator`,
If I put `Equal To` 0, it will produce `if (canCreate == 0)` where it does not use `null check operator`.

### Bug Report Code

ITFXjefluJN2rtxE0ZCMLMBWliEwFjMLa+cF0+1+FB4gGKKvBKQMduP8X0NKTf2lfHNMPWCWjT8K/+jQjoT9E8FeOk+sfKE7k/UwKlCvHAM=

**Comment by agreaves** [comment]
Hi @thruthesky, this default behavior is by design in order to save users a bit of trouble. In reality, users should determine default values themselves, but we apply `?? true` in order to catch cases where they don't. This is much harder to do when negating the entire value.

However, we've now added an explicit "Default Value" for boolean conditions so that you can always set what value to default to when null. This will be available upon our next deploy! Thanks for the feedback 🙂

**Comment by thruthesky** [comment]
@agreaves Thank you :)
