### ISSUE TITLE
issue since recent update on apple tablet - blank page on load

### ISSUE THREAD

**Issue by dspelmandev** [FlutterFlow/flutterflow-issues#2646]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My app is failing to load on an IOS Ipad. It had been working fine previous to the recent update. 

### Expected Behavior

The app should load to the auth page or the select menu page. 

### Steps to Reproduce

1. visit https://cdsobsession.flutterflow.app/ on IOS Ipad. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wlefl2ItPj7xd7qrucvpvijoUCDs1aJI70cFEQis8GZT0B4kcYs+kfklUcNTndGxAf2CKjT4X/MnFvd+SVMIoJgqCfbpezLpAVgv/UlOtWrXSCb63b0d5NNFUChW/1re3iCN4KsludGdk7Ey2Ju6vFyvtHuOxOzM7AeaoXdeK2SrDX1iXc2URm05KZDPz

### Context

Customers are unable to access the app. 

### Visual documentation

![IMG_D566F602BDD3-2](https://github.com/FlutterFlow/flutterflow-issues/assets/165904697/fc2d92c7-c009-4a2e-87e7-3198860dbed1)

### Environment

```markdown
- FlutterFlow version: V4.1
- Platform: MacOS Ipad, Web Safari and Chrome
- Browser name and version: Safari
- Operating system and version affected: Ipad Air 12.5.7
```

**Comment by faroukdubai2** [comment]
Blank White Screen Issue on App Launch

Description:
Upon launching the app, users are greeted with a blank white screen instead of the expected content. This issue persists consistently, impacting the user experience negatively. 

Steps to Reproduce:
1. Launch the app on any supported device.
2. Observe the screen upon app launch.



Actual Behavior:
Upon launch, the app displays a blank white screen, providing no indication of progress or loading activity.
![Screenshot-0403-155753](https://github.com/FlutterFlow/flutterflow-issues/assets/157837108/bd97a426-345a-4258-80a6-745a0d6a0780)


This issue severely impacts the user experience and needs urgent attention.

**Comment by bozzoleandro** [comment]
Hi @dspelmandev, I'm able to open an app in an iOS device, are you still experiencing the same issue?

**Comment by gutomec** [comment]
I am having the same problem! The web version of my app, generated by Flutterflow, stays completely blank for 15 seconds before opening the splash page set to appear for 2 seconds, and only then does it enter my app. This really creates a horrible user experience, causing users to abandon the app thinking it has a problem.

**Comment by bozzoleandro** [comment]
Hi @dspelmandev, are you still experiencing the issue? Tested on several iOS devices and works ok for me. @gutomec, can you please create a new blank project with the issue that you're having and send me the bug report code?
