### ISSUE TITLE
Windows version overwrites project with a cached/older version when opened after editing in browser

### ISSUE THREAD

**Issue by Dbrrohof** [FlutterFlow/flutterflow-issues#2744]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When opening a project in the Windows application, then editing it in the browser, and then later opening the windows app, it will not refresh the project but instead overwrite the cloud save with and older version. Snapshots of my project confirmed this when comparing custom code.

### Expected Behavior

Windows version should ALWAYS fetch latest version from cloud before opening.

### Steps to Reproduce

1. Open a project on Windows application
2. Close application and open project in the browser (you can also try to keep the application open to see if that will reproduce the bug)
3. Edit some custom code in the browser
4. Close down all instaces of flutterflow both browser and windows app
5. Reopen windows app and see the custom code you have changed in the browser be gone

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40zMmBw41OxdsA+KryKPlFnmU5JUN6ao07mO5raCosfZT2BLMcec/RVERBZ7S6THxtM2CKnWoW0PT6uOLhVuwqCxCYQbpx+qgIWDvxVj2tM5CIFJWvPXR9M9pRfEfF34mFgRNvCNhqLndk2DuMf9+ySg3aJIf1ITEsDq/LZO4=

### Context

Reverting back to old code is not nice.

### Visual documentation

Did not get any images in time

### Environment

```markdown
- FlutterFlow version:  v4.1.34+
- Platform: Browser + Windows App
- Browser name and version: Chrome Version 123.0.6312.123 (Officiel version) (64-bit)
- Operating system and version affected: Windows 11 Home 23H2 22631.3447
```

**Comment by paulperez-dev** [comment]
Hi @Dbrrohof, thanks for your report! I was not able to replicate your issue. I created a new project from Windows app, added a custom function and closed the app. Then I opened the same project on the web and edited the custom code. After closing the tab and opening the desktop app, the remote changes were there after a moment (maybe it was syncing). The web version wasn't overridden.<br><br>Can you please share a more detailed step by step? Maybe a video recording (it helps a lot).

**Comment by GoCloudToday** [comment]
@paulperez-dev I am having the exact same issue and could replicate as well. See on the screenshot my new projects side by side:
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/121566690/777421ce-0bbf-42cd-b5f4-bb9d7e071871)
You can see the web one has v2, the desktop is still on v1, even though I have not had the desktop app open during the web change and save to v2.
If I close the desktop app and reopen it will with the correct, now v2 version. This is especially annoying as sometimes when developing I am not saving a new version but just using the web version to make some custom code edits (the Desktop version still does not offer the same experience) and then wanting to return to the desktop, needing to remember this refresh, otherwise I might override my changes. 
I also did a bug report code, not sure if that helps:

ITFTz/Hqx89hosRK+Kn9LMdvpCkRCUMdXOczitVEew4bCIj4OpkAe8n7M1FocMSzaHxmI079kng0pKHNuPLlJPQFEzqZRtVTz81LExPPbEOtM7ayBqjpYkEkO/1jCH6H1pinmQlCGPtic1IZ2l6qO9+9Fj6Cf9qOYwx5e6fDbOY=

**Comment by Dbrrohof** [comment]
> Hi @Dbrrohof, thanks for your report! I was not able to replicate your issue. I created a new project from Windows app, added a custom function and closed the app. Then I opened the same project on the web and edited the custom code. After closing the tab and opening the desktop app, the remote changes were there after a moment (maybe it was syncing). The web version wasn't overridden.Can you please share a more detailed step by step? Maybe a video recording (it helps a lot).

Hi @paulperez-dev, Just as @GoCloudToday mentioned and provided great details and screenshots, thats the excact issue we are facing. I could indeed go and force this multiple times, but i hope that you have enough material from this thread. Otherwise do let me know.

**Comment by Dbrrohof** [comment]
Hi @paulperez-dev just wanted to mention that this keeps happening for me - so bad at this point, that i have chosen to uninstall the windows version since it reverts to older versions and this is not optimal. Please tag me and let me know once this issue has been fixed, so that i again can use the windows version (already miss local run ... )

**Comment by rzambroni** [comment]
Hey @dbrrohof & @GoCloudToday, 

I was able to replicate the issue and will send it to the team so they can take a look. <br>Thanks for the report.

**Comment by vinayakagw** [comment]
Any update on a fix for this?
