### ISSUE TITLE
Checkbox is not updated on listview or column with backed query

### ISSUE THREAD

**Issue by hchehab** [FlutterFlow/flutterflow-issues#2768]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a list view with backend query(supbase), the list view has rows with text, double and Boolean fields, The backend query filter based on dropdown. When I select a dropdown value, the list view show the correct rows, however, if I deselect some rows and then reset the dropdown and reselect the drop down the list view checkbox is not showing the correct value. I was able to reproduce this behavior again and again.

### Expected Behavior

Checkbox should reflect the result of the backend query

### Steps to Reproduce

I made the project public at [https://app.flutterflow.io/project/test-ehy4ca](https://app.flutterflow.io/project/test-ehy4ca)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89godtf0anqc/pQhQIkQ2IjUOcJi+0aSR42F7auE+0XPsj8S0NKTMvgfH9UKEyLmloBzNXFv9nPLvAqAxGafo8/0JVAZTnhTk+7R6a0C86aOHElHppRfW665p+K2hN4CPFpdUFn72GTNq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am not getting the correct checkbox value in my list view

### Visual documentation

[https://app.flutterflow.io/project/test-ehy4ca](https://app.flutterflow.io/project/test-ehy4ca)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: v4.1.34+
- Platform: Windows
- Browser name and version: Chrome Version 123.0.6312.122
- Operating system and version affected: Windows 10 Pro
```

**Comment by ignalauret** [comment]
Hey @hchehab thanks for your report. Are this Checkboxes set locally, or should they be reflecting a boolean attribute of your saved model from Supabase?<br>In case they are set locally, then it's expected that they clean up after changing the dropdown, since the widget is rebuilding and going back to the default state you gave to the Checkboxes.<br>If they are showing a field from you document, then you need to make sure the checkbox is updating the field on the document when changing, and you are not just setting the value to start with the boolean on the document. You need to add an extra action to the CheckBox to update the document field when the CheckBox value is updated. If not, when you reload the query the checkboxes are going to go back to the value the field has in the Document on Supabase, that hasn't changed.<br>If you have already done this and you still think there is a bug, please give me the steps to reproduce it from a Blank project so I can test it. <br>Hope I was helpful, have a great day!

**Comment by ignalauret** [comment]
I'm closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
