### ISSUE TITLE
When I delete items one by one using a delete action via a listTile with swipableActionWidget the screen crashes

### ISSUE THREAD

**Issue by PaulHolsters** [FlutterFlow/flutterflow-issues#277]
**Reproducing the problem:**
1. Create a page with a listView 
2. Use a listTile with slidableActionWidget as the child
![image](https://user-images.githubusercontent.com/88238734/209482724-4b0c37bf-2b1e-4c89-a4b1-ce7ded6dced9.png)
3. Attach a db query (api call) to it (or do this in a component higher up the tree like a homepage component)
![image](https://user-images.githubusercontent.com/88238734/209482759-9839e19a-b5d1-4346-8604-8289746c0dd7.png)
4. Use the response to generate children for the listView.
![image](https://user-images.githubusercontent.com/88238734/209482772-9122be42-a322-4a77-b9a1-2364ba97aa81.png)
5. connect an API call to a delete action in the slidableActionWidget that wil delete the item from the list
![image](https://user-images.githubusercontent.com/88238734/209482793-ddd52499-3539-4cb4-adfa-82ad264ba131.png)
![image](https://user-images.githubusercontent.com/88238734/209482817-d39b0d38-7ed1-427d-bf27-0130e2697b20.png)
6. **test the implementation by doing the following:**
=>make sure you have like **10** items in the list
=> start deleting them one after the other.
![image](https://user-images.githubusercontent.com/88238734/209483687-073d37c7-3619-4e1c-8d04-b44c69e1cbe7.png)
=> Around 3 to 7 items deleted you will get this error:
![image](https://user-images.githubusercontent.com/88238734/209482707-68dc2a27-2dee-4962-a15d-4f37c3d141ce.png)

**Comment by agreaves** [comment]
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and we have not been able to reproduce this issue with the provided steps, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.

If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce. Adding a Bug Report Code would be extremely helpful as well.

Thank you for your contribution!

**Comment by PaulHolsters** [comment]
Thanks.
