### ISSUE TITLE
Community profile update and login is buggy

### ISSUE THREAD

**Issue by unibum** [FlutterFlow/flutterflow-issues#2772]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When in community, I change name, update/save, names update correctly in my previous posts.. log out, try to login using FF creds and tells me error and that I should reset password.. (also not there is no password reset link either on page).
Go to FF, login works fine, click community, new page opens, old name appears!!

### Expected Behavior

Update name persists.
login into FF community also works using FF creds

### Steps to Reproduce

When in community, I change name, update/save, names update correctly in my previous posts.. log out, try to login using FF creds and tells me error and that I should reset password.. (also not there is no password reset link either on page).
Go to FF, login works fine, click community, new page opens, old name appears!!

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

NA

### Context

Change name in FF community to be more anonymous when creating questions.. by default it pulls through FF info.. prefer prompted to create profile on FF Community to start with..

### Visual documentation

![FFCommunitylogin](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9eb87fe9-11dc-4e00-a737-55238dddf245/5259c2c6-866d-43f3-9f3b-75a4b338db61?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ZWI4N2ZlOS0xMWRjLTRlMDAtYTczNy01NTIzOGRkZGYyNDUvNTI1OWMyYzYtODY2ZC00M2YzLTlmM2ItNzVhNGIzMzhkYjYxIiwiaWF0IjoxNzEzNTg3MDYxLCJleHAiOjMzMjg0MTQ3MDYxfQ.hb0Ip411SuTm8W_JISx2riWtQ4LBsa60yavefx8kNnY)

### Additional Info

![FFCommunitylogin](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/72cac29d-4799-43f7-b21f-9870ec229244/52b28411-2189-44e3-9a6b-82d0c13235ea?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83MmNhYzI5ZC00Nzk5LTQzZjctYjIxZi05ODcwZWMyMjkyNDQvNTJiMjg0MTEtMjE4OS00NGUzLTlhNmItODJkMGMxMzIzNWVhIiwiaWF0IjoxNzEzNTg3MDYxLCJleHAiOjMzMjg0MTQ3MDYxfQ.cxAsSmueAE0L-e5zQagP8viRM3sKVU-\_CSUFsw5dHxs)

### Environment

```markdown
- FlutterFlow version: all
- Platform: web
- Browser name and version: chrome latest
- Operating system and version affected: win 11
```

**Comment by rzambroni** [comment]
Hey there, we are going to the profile update bug you are mentioning. But, in regards to the reset password you can use the "Forgot your password?" link. It is visible in your screenshot.

**Comment by unibum** [comment]
Thanks.. brain fog on my part sorry,, I didnt associate password reset with password recovery.. I guess it makes sense to forget password means you have to reset it...................................................... my bad

**Comment by unibum** [comment]
Just to clarify, my FF password wasnt working in FF Community.. but did work back in FF which let me then click back into community as logged in.. so under why I was getting password reset message in first instance

**Comment by PoojaB26** [comment]
Hey @unibum, unless you add a password to your community account, you cannot use the FF email & password because we don't share your credentials with other services. So to make sure, you can log in through email password, you will have to login via https://app.flutterflow.io/community first (you can skip it now because you have already logged in before once, this is only for first timers) and then log out, and do forget password, and use the same email as FF account. 
Once you set your new password, you can log in via email-password again. 

About the username update, if you enter community again from FlutterFlow, the name will reset again to your profile name from FlutterFlow because your profile name is shared with community for now. We can make this experience better in the future but for now, you can directly change the name in FlutterFlow account and on entering community from FF, it will take the new profile name. Let me know if that works?

**Comment by unibum** [comment]
Hi, yes that seemed to work.
not very intuitive though.. much easier if there was a password reset in profile panel.. you have email box which user can change, easier if they can change/add password and it sets for just community (not impact FF password).
