### ISSUE TITLE
Difficulty in Closing Date Picker After Selection in FlutterFlow

### ISSUE THREAD

**Issue by DavydBA** [FlutterFlow/flutterflow-issues#2786]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have implemented a date picker to allow users to select a date in a TextField item. However, the date picker remains open after choosing a date even if I click on another part of the screen.

### Expected Behavior

After the date is selected I can close the date picker by clicking on another part of the screen.

### Steps to Reproduce

1. Create a new page.
2. Add a 'TextField' widget.
3. Add Action 1 for this TextField item ('On Focus Change' tab): Date/Time Picker (any properties).
4. Add Action 2 for this TextField item ('On Focus Change' tab): Set Form Field: Widget State - TextField item

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c8bc58fd-1f12-40f1-9d55-4c5be6dc5a72/6046bdfd-b26d-45b2-bfb4-e645a6adaf10?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jOGJjNThmZC0xZjEyLTQwZjEtOWQ1NS00YzViZTZkYzVhNzIvNjA0NmJkZmQtYjI2ZC00NWIyLWJmYjQtZTY0NWE2YWRhZjEwIiwiaWF0IjoxNzEzODA0MjY3LCJleHAiOjMzMjg0MzY0MjY3fQ.8eJYssgvcvLIlrVXuPwAcOWQmUJjP-uDJak3vvcYYxA)

1. Run the app in Test Mode.
2. Select the TextField item and choose the date.
3. Confirm the selected date.
   The date picker won't be closed.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki8mAvJNJpbxb0KrtbexWnikvQ0N6TL03t9VxSUgrIrbyPJkUaff4XFNCZMjjTQl5KEWIkTgHwcrvkobUUME6YDmAbqJSyJN9Ww3hVjm/aoSIPKuwVnZCJ9pQCX7E0piJrSZ4OtpeV0YlwDuqHumyYDftQof7Zwh9f6PHaOI=

### Context

I can't use the desired element type (TextField) to implement date selection logic.

### Visual documentation

[https://github.com/FlutterFlow/flutterflow-issues/assets/118316141/c68f68f1-4f19-4631-8471-c5e597b6b591](https://github.com/FlutterFlow/flutterflow-issues/assets/118316141/c68f68f1-4f19-4631-8471-c5e597b6b591)

### Additional Info

*No response*

### Environment

```markdown
- FlutterFlow version: 4.1.34+ (Flutter 3.19.1)
- Platform: Web
- Browser: Google Chrome Version 124.0.6367.60 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro 23H2 22631.3447
```

**Comment by rzambroni** [comment]
Hi @DavydBA, thank you for your report. The issue you're experiencing is caused by the use of actions during the "On Focus Change" event. Unfortunately, the behavior you're aiming for cannot be achieved through this event. To accomplish this, One common practice is to place a button adjacent to the TextField, which triggers the DatePicker action "On Tap" instead , as the TextField widget alone does not support this functionality. There are various [posts](https://community.flutterflow.io/widgets-and-design/post/the-perfect-datepicker-PweZmrcQAGV4VwT) on the community page that discuss the approaches. Hope that helps!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/be8a8ebd-a651-43ae-8b8b-594d6829a9a3/f6028d63-8544-4551-98a0-f7fcf2b6bfd5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iZThhOGViZC1hNjUxLTQzYWUtOGI4Yi01OTRkNjgyOWE5YTMvZjYwMjhkNjMtODU0NC00NTUxLTk4YTAtZjdmY2YyYjZiZmQ1IiwiaWF0IjoxNzEzODA2NjUzLCJleHAiOjMzMjg0MzY2NjUzfQ.1O4I2NgJP9oqE4vf-3J_85zvZ9OWNvQ964HmPgiSVos " alt="image.png" width="348" height="88" />

**Comment by DavydBA** [comment]
Hey [rzambroni](https://github.com/rzambroni),
There's a good option there. I came up with another idea of combining a text item and an icon button.
We can close this issue.
Thanks a lot!
