### ISSUE TITLE
JSON path don't find by API call 

### ISSUE THREAD

**Issue by rmiagn** [FlutterFlow/flutterflow-issues#2810]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I test my API, the JSON path for the data "battery.level" is not recognized and displays "null," even though it recognizes the other data.

### Expected Behavior

The "response preview" should display "51", not "null".

### Steps to Reproduce

1. Access to API call "LongitudeLatitude"
2. Response and test
3. "Test API call"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hfHlx85Pm9hE18/ubMJV9Sk5JUQ1R4IRmtZRaCosfZT2BLMcec/RVERtTcOod2x6IU2j/GoW0M7pufzXDcBcHAqsbp8+ypZ1WgnKbEOiVLaMFJWgZHN8Hd9PI0Ck3MO32B5APfpaV3ss70+IfNmiSinbGJz1Dm4SD6/LZO4=

### Context

I'm looking to display this data to the end user.

### Visual documentation

<img width="925" alt="Capture d’écran 2024-04-25 à 22 46 04" src="https://github.com/FlutterFlow/flutterflow-issues/assets/168136826/976b6d53-664b-4135-a7ec-69dfec546c9a">

### Environment

```markdown
- FlutterFlow version: v3.1 
- Platform:
- Browser name and version: mac
- Operating system and version affected:
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by rzambroni** [comment]
Hey @rmiagn, to test this correctly I might need to have access to your project, can you provide a bug report code? <br><br>By the look of it, because the telemetry object is inside an array you might be missing an index indicator, something like:

```
$.result[0].telemetry.batter.level
```

<br>Could that be the case? <br><br>Thanks.

**Comment by rmiagn** [comment]
The bug report code is insert on ticket. But the problem is on API call

**Comment by rzambroni** [comment]
found the problem, the path is getting confused by the "battery.level" variable having a dot, like it is trying to acces an inner variable called "level" inside "battery" rather than the variable called "battery.level". 

In those cases you can define the json path like this: (see screenshot)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/975a24c9-0ad0-477b-849d-e41ba3a1342c/035a2bc9-a4bd-4e04-a5e6-f680b6535b7d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NzVhMjRjOS0wYWQwLTQ3N2ItODQ5ZC1lNDFiYTNhMTM0MmMvMDM1YTJiYzktYTRiZC00ZTA0LWE1ZTYtZjY4MGI2NTM1YjdkIiwiaWF0IjoxNzE0MDgzMzYwLCJleHAiOjMzMjg0NjQzMzYwfQ.qWMAOCyLHuW9H1NwbfGRBL_nAdOA5WXyE61oDbMEs9Q " alt="image.png" width="1171" height="463" />

**Comment by rmiagn** [comment]
You are great rzambroni ! Thank you very much :)
