### ISSUE TITLE
Able to save data in Firestore via debug, but Firestore rule state 'Write' - 'No One'

### ISSUE THREAD

**Issue by vengoran** [FlutterFlow/flutterflow-issues#2827]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Data is getting stored in Firestore database but the rules states 'Write' - 'No One'
[FlutterFlow to Firestore Issue.docx](https://github.com/FlutterFlow/flutterflow-issues/files/15141067/FlutterFlow.to.Firestore.Issue.docx)

### Expected Behavior

Data should not be stored in Firestore as per the Flutterflow document

### Steps to Reproduce

1. Run the app in test mode
2. Add a note and save the note

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfismB25NgoctH176JcsJvuCAvJmEcTIMziNZ+exUbfaL1BqQMfMjSYVhtUtOgaVNcC06jrD4Jwa3whYXuVvU5ExKdQa5SzpZybAzee2iWV4ysC7q8PmskL+lTIXHG08GFkBBCPuNYLEJh6173G9yXEzDDFOu/Zwh9f6PHaOI=

### Context

Standard functionality not working as expected

### Visual documentation

[FlutterFlow to Firestore Issue.docx](https://github.com/FlutterFlow/flutterflow-issues/files/15141071/FlutterFlow.to.Firestore.Issue.docx)

### Environment

```markdown
- FlutterFlow version: 4.1.45
- Platform: Flutterflow
- Browser name and version: Firefox
- Operating system and version affected: NA
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @vengoran thanks for your report. First of all, I can see you are confusing the **Write** permission with the **Create** permission.<br>From the [Docs](https://docs.flutterflow.io/data-and-backend/firebase/firestore-database-cloud-firestore/firestore-rules): 

* **Create:** Allow users to create a new document inside the collection.


* **Write:** Allow users to update a document of a collection.

I can see that in your project you have Create enabled for "Everyone", so it's correct that you are able to create documents from your app. <br>However, I also tried setting this Create to "No One" on a project I created to replicate your issue, and I was still able to create documents. This was because my project was new, so I had a "Test Rule" inside my Firestore rules that allowed every interaction with my DB until certain date next month. <br>So, please make sure to disable the **Create** flag instead of the Write flag, and also remove the "Test Rule" if you have it. <br>Hope I was helpful, I'm closing this issue because I don't see any bug here. If you still think there is a bug, please let me know. <br>Have a great day!
