### ISSUE TITLE
Place Picker is causing a cors error

### ISSUE THREAD

**Issue by alfonsoterron** [FlutterFlow/flutterflow-issues#2891]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

- Click on an out-of-the-box place picker
- Add any address
- No address is retrieved
- A cors error is thrown by Google Maps API endpoint 

### Expected Behavior

- Click on an out-of-the-box place picker
- Add any address
- List the predicted addresses
- Pick one
- Get the address from the Place Picker

### Steps to Reproduce

1. Go to [https://test-place-picker-gxk2vf.firebaseapp.com/](https://test-place-picker-gxk2vf.firebaseapp.com/)
3. Click in the Place Picker button
4. Enter any address

### Reproducible from Blank

- This is a blank project where the issue is replicable.
- [https://test-place-picker-gxk2vf.firebaseapp.com/](https://test-place-picker-gxk2vf.firebaseapp.com/)

### Bug Report Code (Required)

IT4Oz/Hqx89grs9D7ar2de9ajiAsQ34jarxMjOpuUgEdIoPNGJgEfPTBSE5ZTem4TwlYMFv8oH4dzNLJvc7hVOQHAw6ZGqJ/1rViVgLMZD26MpvWPJasPXN6Bf5RJEuV0aurhxBCGPBocWRg7U2UP9yXHyvvJu6xDUQ3D/GXLt7Do3yGAi+6Xn0Jg1ZSfCvr

### Context

- This issue is on the Production environment
- We launched our app one week ago, and no issues reported till this morning
- This issue keeps on hold users on uploading products.

### Visual documentation

<img width="1440" alt="Screenshot 2024-05-11 at 12 20 12 AM" src="https://github.com/FlutterFlow/flutterflow-issues/assets/35768391/ac85f802-13fa-4589-872d-0a634163ce02">

### Environment

```markdown
- FlutterFlow version: v4.1.49+
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Macbook Pro m1 Sonoma Version 14.2.1 (23C71)
```

### General

- [ ] I was collaborating with other users in the same project prior to the data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly before data loss
- [ ] A crash or other bug occurred before data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using Flutterflow from multiple devices
- [ ] I was using Flutterflow from multiple platforms (e.g. both web and MacOS Desktop apps)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by msusviela** [comment]
Hi @alfonsoterron - Thanks for submitting the issue. I've taken a look at your project, but with a lot going on, it's challenging to pinpoint the issue. Given the nature of the problem you're highlighting, we need a blank project with the issue steps set up in it. Without these details, it might be a bit challenging for us to investigate the issue. Please provide the required information. If the issue is already resolved for you, please feel free to close the issue. Thanks!

**Comment by alfonsoterron** [comment]
Hi @msusviela ,

Please check my edit, I've created a blanc project and replicated the issue.

Let me know about anything where I may help.

I look forward to hearing back from you.

Thank you.

**Comment by msusviela** [comment]
Thanks @alfonsoterron. Could you provide us with the Steps to Reproduce to reproduce from blank from our side?

**Comment by alfonsoterron** [comment]
@msusviela , 

1. Create a blank project
2. Set up a Firebase project following the documentation instructions
3. Set up a Google Map Web API Key following the documentation instructions
4. Deploy the web app to Firebase following documentation instructions (https://test-place-picker-gxk2vf.firebaseapp.com/)
5. Deploy to FlutterFlow preview domain (https://test-place-picker-gxk2vf.flutterflow.app/)

The PlacePicker will work without issues in the flutterflow.app preview domain but will not work in the firebaseapp.com domain.

Let me know if you need more details.

Thanks.

**Comment by msusviela** [comment]
Hey @alfonsoterron, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by alfonsoterron** [comment]
Hi @msusviela, is there a chance you share the Credentials API Key configuration?

I am using the created by the FlutterFlow project.

Thank you.

**Comment by AKRehmanKhan** [comment]
Hey I am facing the same issue has anyone resolved it? Flutter Flow place pickers gives cores issue while publishing on our own custom domain
