### ISSUE TITLE
Firestore Data Manager not fuctioning properly

### ISSUE THREAD

**Issue by MemoriaM1** [FlutterFlow/flutterflow-issues#2899]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

![Screenshot 2024-05-13 000134](https://github.com/FlutterFlow/flutterflow-issues/assets/169633835/9783a20d-af08-4e38-875f-4a3dd3f18ae4)

The circle just keep on turning and turning and no content and showing

### Expected Behavior

should be showing all the data content

### Steps to Reproduce

1. go to firestore
2. manage content
3.and the firestore data manager pop up
4. the circle keep on spinning and no content showing

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki/HluIlPm+FY+KqIbflWlSkRQ1h6TLJEoetxc0gbfe/4PLQPPuCkaRZoZOKzaH9AJWGIkj4F0MGNj/HTCOwnNQesf4c6+ZBIVBPPbEeiaKqRDcySOWgkL8BXJhW60Z2noglRAMhsWl4C6meQCN6RHj6Cf9qOYwx5e6fDbOY=

### Context

I can't continue inputting the necessary data to run the app

### Visual documentation

![Screenshot 2024-05-13 000134](https://github.com/FlutterFlow/flutterflow-issues/assets/169633835/09cb1714-645a-4d35-a775-ff39f7a8572d)

### Environment

```markdown
- FlutterFlow version: 4.1.49
- Platform: Web
- Browser name and version: Chrome 124.0.6367.157
- Operating system and version affected: none
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by hariprasadms** [comment]
Hi @MemoriaM1, Thank you for bringing up the issue. Are you still experiencing the issue?
 I've reviewed your project settings related to Firebase setup, and everything appears to be in order. However, the loading issue you're encountering with the Firestore CMS content data might be from incorrect deployment of Firestore rules and possibly FlutterFlow's access to the project.

Since we don't have access to your Firebase project directly, I recommend checking the access permissions for the user firebase@flutterflow.io in your project settings (see below). Additionally, regenerating the configuration files might also resolve the issue.

Let us know if this helps.

<img width="955" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/17435678/86cd38ce-60a6-4bed-af60-5a242f42a3df">

**Comment by MemoriaM1** [comment]
Thanks, it worked. you guys are awesome. thank you

**Comment by hariprasadms** [comment]
Great to hear that it's working for you now! Don't hesitate to submit any further issues if you find them. Thanks for your valuable contributions.

**Comment by MemoriaM1** [comment]
Hi Hariprasdms I have found the problem persist. Can you please check again? 

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/169633835/afe34852-2d09-41aa-974b-c7f25b269ba9)
