### ISSUE TITLE
greyed out cards in a long scroll page

### ISSUE THREAD

**Issue by danyzeus** [FlutterFlow/flutterflow-issues#2911]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In the news and updates page, when I click on the comprehensive plan, I go into subtitles page. There are a lot of cards for the comprehensive plan, so when I scroll through, somewhere in the middle there starts a greyed out screen.
<img width="1800" alt="Screenshot 2024-05-14 at 14 37 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/92539565/790e2477-5c37-4d98-8d59-474068e7d36f">

### Expected Behavior

Why does the card color get greyed out? i want it to remain white like the first several cards

### Steps to Reproduce

I tried changing the card color for the component but it still appears greyed out half way through the subtitle page

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTi87huJZOsbRa+KrMdvpsoDgUGUMcWOdEl+tuZwgbIoznBuwiPc77VFJpZ+bgaVNcH2GjkToypN2KkoTXLPICHzqtGrZj1bhycwrke2i6RrKmEsyNPHQlGfNWf2qM0KSonh1dLsttLHNl3zmQfN6UYBLDFOu/Zwh9f6PHaOI=

### Context

Greyed out screen is hard to read as the text itself is grey and meant to be read on a white background

### Visual documentation

<img width="1800" alt="Screenshot 2024-05-14 at 14 37 43" src="https://github.com/FlutterFlow/flutterflow-issues/assets/92539565/fec3bb64-3dff-4258-8a40-77bf227e3db8">

### Environment

```markdown
- FlutterFlow version: latest May 14, 2024
- Platform: web app deployment
- Browser name and version: chrome
- Operating system and version affected: mac os
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by ignalauret** [comment]
Hey @danyzeus thanks for your report. I think your issue here is that you have a ListView with the Column generating the Dynamic children inside. I would suggest you to remove the column, and just have the ListView generate the children instead. 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/afeff903-3da5-41bf-bacd-d51bbde45c12/f6dd4dc9-5cdb-4f7c-8dab-a0bcf9e011d9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hZmVmZjkwMy0zZGE1LTQxYmYtYmFjZC1kNTFiYmRlNDVjMTIvZjZkZDRkYzktNWNkYi00ZjdjLThkYWItYTBiY2Y5ZTAxMWQ5IiwiaWF0IjoxNzE1NzQwNDQ4LCJleHAiOjMzMjg2MzAwNDQ4fQ._L6wA2LisMzpWTI5aQLuZ-P1AQj4yuyEssJpgzZkTkw " alt="Screenshot 2024-05-14 at 11.31.15 PM.png" width="250" height="135" />

Sadly, I can't be of much help here because this seems like a misconfigured UI and not a bug. If you need any help, please feel free to contact our Customer Support team, they will be much more helpful than me and are going to guide you on building the UI you are looking for. <br>If you still think there is a Bug here, please let me know, Have a great day!
