### ISSUE TITLE
TextField initial value doesn't change from variable once it's set. (problem when using Firestore Streams)

### ISSUE THREAD

**Issue by MauruschatM** [FlutterFlow/flutterflow-issues#2917]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a component with TextFields inside. If the parameters of the component change, the initial values of the TextFields don't change. Since it's a component, it's hard to update via action from the page. And you can't know it sometimes when using Firestore Streams!

Also, it's a general issue, that the initial values can't change dynamically.

### Expected Behavior

TextFields should change their initial value, when the variable changes. Just like with the placeholder or label.

### Steps to Reproduce

1. Create a page
2. Create a component (with string parameter and a TextField inside)
3. Set initial value of the TextField to the parameter
4. Update the parameter from the page. (could be with firestore)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4gz8rluYtOoctJ0LrUbO9V9SQsQm55aK00st4bGAsdGOvrBu0AfuLSSFFpXsTnaVNcC2K0oE4epPDMi9nPKvYBA0+Vbqp//7piYD30e2iibLKsPJCgenZDN+BmGkyB0raw3AklPuNZcVYc62GMJOqQZz3DFOu/Zwh9f6PHaOI=

### Context

I have a list of items and a single component to edit the items. Since the initial value doesn't change when selecting a different item, you have to create a list of that component for every item and conditionally displaying just one.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/60385231/16e9d08c-8567-4e1d-9c5c-8ccf57889524)

Furthermore the values have to change by the Firestore collection Stream. I have a table with calculated data and it should be displayed correctly in order for the user to change the right values.

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/60385231/c2b4ba6e-ec9e-4281-a9e6-478ac6b2fd08)

### Environment

```markdown
- FlutterFlow version: v4.1.52
- Platform: Web, ...
- Browser name and version: Chrome, Edge, ...
- Operating system and version affected: Windows 10, Windows 11, ...
```

### General

- [ ] I was collaborating with other users in the same project prior to data loss
- [ ] I navigated between different project views leading up to data loss
- [ ] The UI was running very slowly prior to data loss
- [ ] A crash or other bug occurred prior to data loss
- [ ] Data was not saved in a snapshot
- [ ] I was using flutterflow from multiple devices
- [ ] I was using flutterflow from multiple platforms (e.g. both web and MacOS Desktop app)

### Relative to the time the changes were made, data was lost within

- [ ] 1 minute
- [ ] 1 hour
- [ ] 1 day
- [ ] 1 week

### When following my steps to reproduce, data loss happens

- [ ] ~100% of the time
- [ ] ~50% of the time
- [ ] ~10% of the time
- [ ] ~1% of the time
- [ ] Very rarely or only encountered once

**Comment by MauruschatM** [comment]
Just noticed that the behavior does make sense. Because you don't want the user to be interrupted while writing.

But then you would need an Action Event like "On component change" or in the TextField "on initial variable change"
Best solution would be to update the initial value when the user doesn't have the focus on that field.

**Comment by MauruschatM** [comment]
If you have another solution, it would be great.

**Comment by ignalauret** [comment]
Hey @MauruschatM thanks for your report. The Flutter Text Field doesn't update it's value when the Initial Value parameter changes. So on FF to change a TextField value you need to use "Set Form Field" action. <br>If you use this action, you will see your text fields differentiated by name, so you can identify which one to choose (if you are using the same component multiple times), like your_component -> TextField_1, your_component -> TextField_2, etc.<br>I hope I was helpful. If you need more help with your text fields, please feel free to contact our Customer Support, they will be able to help you more than me. For now, closing this issue because it's not a bug on FF. If you still think there is a bug here, please let me know. <br>Have a great day!

**Comment by MauruschatM** [comment]
> Hey @MauruschatM thanks for your report. The Flutter Text Field doesn't update it's value when the Initial Value parameter changes. So on FF to change a TextField value you need to use "Set Form Field" action. If you use this action, you will see your text fields differentiated by name, so you can identify which one to choose (if you are using the same component multiple times), like your_component -> TextField_1, your_component -> TextField_2, etc.I hope I was helpful. If you need more help with your text fields, please feel free to contact our Customer Support, they will be able to help you more than me. For now, closing this issue because it's not a bug on FF. If you still think there is a bug here, please let me know. Have a great day!

@ignalauret Thanks for your answer. How would you do that with Firestore Streams then?

**Comment by ametaplus** [comment]
I keep having the same problem: When loading a document from Firestore in an Action on page load and then setting a PageState with it, it doesn't update the textfield's initial-value with it - which is weird, since it works with basically all other widgets. Maybe textfields can have a setting if they should be updated automatically or not when tied to a State-variable? Or at least (slightly different topic) the "Set Form Field"-action should be combined like the "set Page State", so that I don't have 15 "Set form field"-actions when loading something into textfields, but only 1 with 15 fields.
