### ISSUE TITLE
Using a Lottie Animation stored on Firebase Storage is not recognized

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#294]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Load the Lottie Animation

## Current behavior (required)

Nothing happens, doesn't load the animation

## To Reproduce (required)

1. Add a Lottie Animation
2. Select network as source and in the path paste the URL from the Firebase Storage
3. Build the project and doesn't load

### Bug Report Code (required, generate from Widget Tree)

ITESz/Hqx89gobUD0LXhKPlQhQkhNjN/bZIRjt5+FAgbGJyuP4l/evWlXBFoQvXjdGNMfUSmml8B7vzSueHfCscqITOeQJhRzKgJEALhTkC7U8HfU/HUACkbeacOQSj6

## Context (required)

I want load the Lottie Animaton. If use a Supabase Storage link it is works but doesn't work with Firebase Storage

## Screenshots / recordings

![image](https://user-images.githubusercontent.com/36147203/209863317-572485df-348b-439b-bd9f-1e8eff371d9f.png)

## Your environment

* Version of FlutterFlow used: 26 December
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by agreaves** [comment]
Hi @Franco98404, thanks for the bug report! The issue comes down to a CORS issue, some files types such as Lotties, PDFs, and a few others require configuration on Firebase Storage in order to be used in the Web. See our [FlutterFlow Docs](https://docs.flutterflow.io/actions/actions/ui-interactions/upload-media#web-access-for-pdfs-and-other-files) article on this for steps on how to fix this in your Firebase project.

Unfortunately there's not another workaround for this aside from following these steps or using a proxy. Hope this helps!
