### ISSUE TITLE
Listview with Firebase Query & Infinite Scroll enabled is causing slow performance

### ISSUE THREAD

**Issue by morad** [FlutterFlow/flutterflow-issues#301]
## Expected behavior (required)
Content Pagination from Firestore with infinite scroll enabled to provide a good scrolling performance, and fetch additional data as it scrolls.

## Current behavior (required)
The ListView feed is fetching from Firestore (infinite scroll and list for changes enabled) with pagesize 10. But it seems the pagesize is being ignored, and it's fetching and loading the entire 500+ posts with media metadata at once.

When I add .limit to the query directly on Android Studio, the performance is better.

## To Reproduce (required)
1. Create new page
2. Add ListView widget with Firebase backend Query to large set of data, and enable Infinite scroll
3. Set pagesize to 10
4. Click Run
5. Observe that project doesn’t perform well at first. Till it loads all data from Firebase, rather than loading only 10.

## Context (required)
The scrolling should be smooth as it fetches more data (by 10), and show loading indicator when its loading more.

## Your environment
iOS & Android

**Comment by aemelyanovff** [comment]
It behaves this way because there's no limit on the height of the list view, so it tries to expand indefinitely.

Try this:

- Wrap the ListView in a Container widget. Set some height, e.g. 300px.
- Wrap the Container in a Column, enable scrolling.

Then it'll load only one or two pages at first, and then load additional pages as you scroll.
