### ISSUE TITLE
Error when downloading APK

### ISSUE THREAD

**Issue by GMGSPT** [FlutterFlow/flutterflow-issues#3128]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Just got the premium upgrade to be able to download the APK but I am facing an error regarding the Manifest merger.
The following information is reported:

Error: Command failed: flutter build apk --no-pub --no-version-check
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /opt/.pub-cache/hosted/pub.dev/firebase_messaging-14.7.18/android/src/main/java/io/flutter/plugins/firebase/messaging/FlutterFirebaseMessagingPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /opt/.pub-cache/hosted/pub.dev/cloud_firestore-4.15.7/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/tmp/ff_service_scratch/HDRnQzMAI7RduVqantHy/suitapp/android/app/src/main/AndroidManifest.xml Error:
	uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [:flutter_ffmpeg] /tmp/ff_service_scratch/HDRnQzMAI7RduVqantHy/suitapp/build/flutter_ffmpeg/intermediates/merged_manifest/release/AndroidManifest.xml as the library might be using APIs not available in 21
	Suggestion: use a compatible library with a minSdk of at most 21,
		or increase this project's minSdk version to at least 24,
		or use tools:overrideLibrary="com.arthenica.flutter.ffmpeg" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 24 declared in library [:flutter_ffmpeg] /tmp/ff_service_scratch/HDRnQzMAI7RduVqantHy/suitapp/build/flutter_ffmpeg/intermediates/merged_manifest/release/AndroidManifest.xml as the library might be using APIs not available in 21
  	Suggestion: use a compatible library with a minSdk of at most 21,
  		or increase this project's minSdk version to at least 24,
  		or use tools:overrideLibrary="com.arthenica.flutter.ffmpeg" to force usage (may lead to runtime failures)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 53s
Gradle task assembleRelease failed with exit code 1

### Expected Behavior

Since the test run was working fine, I was expecting the APK to successfully download.

### Steps to Reproduce

Simply download the APK, since there are no bugs reported.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThc/l5c91rs9H+KXqcMdF/Sc4M0MBX5Ir1utvGQAdIqKvE5YHePfUaXdYOs+aTHNqJmKLsFEJpsrwuOL1Cu1dCzisG59607VqEwyWTnGjaa6vEYeCXWpBEZhgJ26l0JiJux4nFO92dCViwF+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

-

### Environment

```markdown
- FlutterFlow version:v4.1.59+ released June 12, 2024
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hey @GMGSPT, So sorry you are having this problem. The issue you are encountering is because of the minSDK requirement of a package your are using in your project (flutter_ffmpeg). Unfortunately, this has been reported in the past since it is not currently possible to edit the minSDK setting from flutterflow. 

There is currently a feature request added to the team's backlog. We hope they can get to it soon. 

As a workaround you could try to export the code and change this setting manually on a code editor (as suggested [here](https://community.flutterflow.io/discussions/post/how-to-change-the-minsdkversion-of-my-project-in-flutterflow-IOqsd7GdBZKyCTm)). If you need help with this i suggest reaching out to our support team, you can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow.

I'll close this issue as duplicated of the [previous report.](https://github.com/FlutterFlow/flutterflow-issues/issues/1809)

Thanks
