### ISSUE TITLE
Can't update the arguments in Custom Widget.

### ISSUE THREAD

**Issue by thruthesky** [FlutterFlow/flutterflow-issues#314]
## Expected behavior (required)

- Arguments on Custom Widget would be updated.

## Current behavior (required)

- The Argument disappears on Custom Widget save.

## To Reproduce (required)

1. Create a custom widget.
2. Complile.
3. Add arguments.
4. Click save.

### Bug Report Code (required, generate from Widget Tree)

N/A

## Context (required)

- When a developer updates(adds) an Argument on Custom widget, it should be added. But when the `Save` button was pressed, the argument to be updated disappears.

## Screenshots / recordings

https://user-images.githubusercontent.com/5080329/210355077-4700f4cb-28e8-4772-8f71-c84bd52b3a45.mp4

## Your environment

* Version of FlutterFlow used: v3.0 December 30, 2022 - Flutter 3.3.4
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Google Chrome, Version 108.0.5359.124
* Operating system and version (desktop or mobile): iMac 2020, macOS Ventura 13.1

**Comment by kjoyceee** [comment]
I experienced this today as well, but when working with Custom Actions.

My workaround:

1. Copy the existing code you have inputted (as it will override the code using my workaround)
2. Create any new Parameters
3. Near the top right next to "Widget Settings" click the green icon that looks like </>
4. Hit ok
5. Save
6. Replace your code

**Comment by agreaves** [comment]
Hi @thruthesky, thanks for the report! This is actually Working As Intended, although perhaps we should better communicate what's happening as it may be unintuitive.

We automatically infer parameters now from the code in the Custom Widget/Action, so when you save it overwrites the existing arguments you set manually. Otherwise, it would have caused an error when you try compile, so doing this prevents an error. Hope this makes sense!

**Comment by thruthesky** [comment]
> We automatically infer parameters now from the code in the Custom Widget/Action

Wow :)
