### ISSUE TITLE
Missing chat page on Pro plan

### ISSUE THREAD

**Issue by taggxyz** [FlutterFlow/flutterflow-issues#3168]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When creating a new page on a pro plan, there is no option to create a chat page.

### Expected Behavior

When creating a new page on a pro plan, there should be the option to create a chat page.

### Steps to Reproduce

Create a project on a pro plan
Create a new page
No chat page is available

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OzMmBw41PsctK14SJc8dagmAXQzsjarxMkcF+e0obIq3NGu4Iec/eUFZuZry7TQlUOWCWiTkxxvfqkob+VvEVAymaQa44+rVuFzvzUXOQWqaRCYezfW1fL8JhIB2P08GRhBB4KsxpSiUO1GWyfd+WbCjDHpDaOWwdMMmbJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="1012" alt="Screenshot 2024-06-18 at 15 10 51" src="https://github.com/FlutterFlow/flutterflow-issues/assets/53789605/f8e963a4-81fc-4949-a3d9-0b5b2ba024ad">

### Environment

```markdown
- FlutterFlow version: 4.1.60
- Platform: MaxOS Desktop, Web
- Browser name and version: N/A
- Operating system and version affected: N/A
```

### Additional Information

I want to add chat to my project and it's slowing down my build.

**Comment by rzambroni** [comment]
Hey @taggxyz, I do apologize, but the chat template was deprecated a while ago because it was old and buggy, what it was included, however, are the new chat flows: 

![image.png](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dba2a29f-5008-43a3-b664-8ac9ea7070eb/c46c22ee-3b5c-4764-8eb2-f81298fbb041?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYmEyYTI5Zi01MDA4LTQzYTMtYjY2NC04YWM5ZWE3MDcwZWIvYzQ2YzIyZWUtM2I1Yy00NzY0LThlYjItZjgxMjk4ZmJiMDQxIiwiaWF0IjoxNzE4ODEzMDIyLCJleHAiOjMzMjg5MzczMDIyfQ.nOsaByxreWsI8582-iTECgsHcUK_tqFYHZzjAhUNtjo "=501x")

Please make sure to take a look at the [documentation page ](https://docs.flutterflow.io/widgets-and-components/flows)of the flows feature if you have never used it. Some of these flows might require to have authentication configured as a pre-requisite.

Thanks.
