### ISSUE TITLE
Long loading latency like 5-15sec when reopening remaining tab after inactive(=around 5-10min)

### ISSUE THREAD

**Issue by MaoCTajiry** [FlutterFlow/flutterflow-issues#3172]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Very long loading time when reopening the existing tab in browsers (reproduced both in Chrome & safari in iOS)

### Expected Behavior

Within 5 seconds, page should show. (Or most of visitor will leave that link as they think it's not correctly working...)

### Steps to Reproduce

1. Create new page and publish in the web
2. Open that page (e.g., https://m-v-p-v1-dzaq53.flutterflow.app/)
3. Move to other app and stay in 2-3 minutes
4. Go back to the browser and choose existing open page (same with step.2 above)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfi+fq0ItPtbwC+a6JcsZviig7JUccTIMziNZ+exUbfaL1BuwcPvf8U1tCTbylaVNcJ1WkmkQEzOjOiITXLe0DByecGoRZ+JZUeg7ee2ilV83UPoeKS3FSAtFhCB260aa7qxRvKtRpLkYFw2a6H+q8bD7DFOu/Zwh9f6PHaOI=

### Visual documentation

[On Safari](https://drive.google.com/file/d/161nuNa5P3W7XxDl1OtS1vX8wqAhz-nb-/view?usp=sharing
)
As most of users would do, I can't wait for white screen after 5 seconds, so reloaded at 0:15~ but still took time to load...

[On Chrome](https://drive.google.com/file/d/1nPDnOu-deXqb2wvb5w3n9h98cNhlPAsZ/view?usp=sharing)
Tried to wait to be loaded, then it took 24 seconds... too long!

### Environment

```markdown
- FlutterFlow version: v4.1.60+ released June 15, 2024(Flutter version is 3.19.1)
- Platform: Web (iOS)
- Browser name and version: Chrome v126.0.6478.54 & Safari version 16.5 (18615.2.9)
- Operating system and version affected: iOS 16.5.1(c) iPhone 12 mini
```

### Additional Information

Note: I got the signin page(=https://m-v-p-v1-dzaq53.flutterflow.app/)'s Bug Report Code, but this issue can be reproduced in any pages. You can simply use my trial website for testing above. But I didn't try in Android as I don't have...

**Comment by rzambroni** [comment]
Hey @MaoCTajiry, thanks for the report. Unfortunately there are quite a few issues regarding loading time performance in flutter, it is not quite optimized yet and there is not much FF can do yet since it is a problem with Flutter for the web in general. Even with blank and very basic apps, sometimes the initial loading time is quite awful.

Here are some previous reports were people posted some workarounds that might be helpful:<br><br>[https://github.com/FlutterFlow/flutterflow-issues/issues/1463](https://github.com/FlutterFlow/flutterflow-issues/issues/1463)

[https://community.flutterflow.io/discussions/post/faster-web-load-time-KBGrT2tImbX764Q](https://community.flutterflow.io/discussions/post/faster-web-load-time-KBGrT2tImbX764Q)

Hope it helps, marking this issue as duplicated in favor of [#1463](https://github.com/FlutterFlow/flutterflow-issues/issues/1463)

**Comment by livingmydesign** [comment]
@rzambroni it certainly used to load much faster a year ago and I wonder why you don't try to integrate walkarounds like the one mentioned into your product? obviously everyone would greatly benefit from the user experience improvement. 

just very hard to understand why such an issue gets not being worked on for so long when it has such an impact
