### ISSUE TITLE
BuildError 'getInitialAppLink' isn't defined for the class 'AppLinksPlatform"

### ISSUE THREAD

**Issue by arniigreat1** [FlutterFlow/flutterflow-issues#3217]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Test mode on (2) separate projects no longerwork

### Expected Behavior

Test mode should run the app

### Steps to Reproduce

1. Run test mode.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40i87huIhNocNC1rrucPpVtCM5KWJ5bJIr0exraCosfZT2BLMcec/RVERCXuGnS39APFmWnWoW06HUjtmTG8ADCxeZRZxxys0BFDvwYGWjVrKhFJWgOGt7EcpYFWa738OFuBJ4PftqLFkt31yUIu6XEwjqJpzGC1csDq/LZO4=

### Visual documentation

**Below is exact error:**

109 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:11:38: Error: The method 'getInitialAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getInitialAppLink'.
    return AppLinksPlatform.instance.getInitialAppLink();
                                     ^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:16:38: Error: The method 'getInitialAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getInitialAppLinkString'.
    return AppLinksPlatform.instance.getInitialAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:21:38: Error: The method 'getLatestAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLatestAppLink'.
    return AppLinksPlatform.instance.getLatestAppLink();
                                     ^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:26:38: Error: The method 'getLatestAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLatestAppLinkString'.
    return AppLinksPlatform.instance.getLatestAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:41:38: Error: The getter 'allStringLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'allStringLinkStream'.
    return AppLinksPlatform.instance.allStringLinkStream;
                                     ^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:46:38: Error: The getter 'allUriLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'allUriLinkStream'.
    return AppLinksPlatform.instance.allUriLinkStream;
                                     ^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         71.6s
Failed to compile application.
![Screenshot 2024-06-25 at 8 47 18 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/168148353/d1e45ee5-3f21-497a-b2dd-0a00b1d5f3a9)

### Environment

```markdown
- FlutterFlow version: v4.1.61+
- Platform: MacOS Desktop
- Browser name and version: Chrome 126.0.6478.115 
- Operating system and version affected: macOS  Sonoma 14.3
```

**Comment by wwchiang** [comment]
Yep, same issue here! It's out of our hands for now, which is frustrating.

**Comment by msusviela** [comment]
Hi all. It seems to be related to a package upgrade on [pub.dev](http://pub.dev/). Our engineering team is already aware and working on a fix.<br><br>Thanks for your reports!

**Comment by stayelles** [comment]
same issue

**Comment by raycelgraterol** [comment]
**I have this error, It is very worrying because last night my project (in PROD) was working without problems and today I have not been able to start in any way. :**

97 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.
Launching lib/main.dart on Web Server in debug mode...
Waiting for connection from debug service on Web Server...      
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:11:38: Error: The method 'getInitialAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getInitialAppLink'.
    return AppLinksPlatform.instance.getInitialAppLink();
                                     ^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:16:38: Error: The method 'getInitialAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getInitialAppLinkString'.
    return AppLinksPlatform.instance.getInitialAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:21:38: Error: The method 'getLatestAppLink' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLatestAppLink'.
    return AppLinksPlatform.instance.getLatestAppLink();
                                     ^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:26:38: Error: The method 'getLatestAppLinkString' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getLatestAppLinkString'.
    return AppLinksPlatform.instance.getLatestAppLinkString();
                                     ^^^^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:41:38: Error: The getter 'allStringLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'allStringLinkStream'.
    return AppLinksPlatform.instance.allStringLinkStream;
                                     ^^^^^^^^^^^^^^^^^^^
/root/.pub-cache/hosted/pub.dev/app_links-3.4.1/lib/app_links.dart:46:38: Error: The getter 'allUriLinkStream' isn't defined for the class 'AppLinksPlatform'.
 - 'AppLinksPlatform' is from 'package:app_links_platform_interface/app_links_platform_interface.dart' ('/root/.pub-cache/hosted/pub.dev/app_links_platform_interface-1.2.0/lib/app_links_platform_interface.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'allUriLinkStream'.
    return AppLinksPlatform.instance.allUriLinkStream;
                                     ^^^^^^^^^^^^^^^^
Waiting for connection from debug service on Web Server...         66.9s
Failed to compile application.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/46403855/af298d81-41bc-47a9-a7db-15990c4de884)

**Comment by luca-heitmann** [comment]
seems like the "app_link" package causes the problem after the version 1.2.0 of app_links_platform_interface was released: https://pub.dev/packages/app_links_platform_interface/versions

app_link version 3.4.1 (which flutterflow uses) seems to use the latest version of app_links_platform_interface automatically: https://github.com/llfbandit/app_links/blob/3.4.1/app_links/pubspec.yaml#L13

there is a workaround: adding "app_links_platform_interface: 1.1.0" to the pubspec solves the problem. I added this to "Pubspec Dependencies" on a random custom widget. Idk if there is another way to change the pubspec in flutterflow.

**Comment by stayelles** [comment]
> seems like the "app_link" package causes the problem after the version 1.2.0 of app_links_platform_interface was released: https://pub.dev/packages/app_links_platform_interface/versions
> 
> app_link version 3.4.1 (which flutterflow uses) seems to use the latest version of app_links_platform_interface automatically: https://github.com/llfbandit/app_links/blob/3.4.1/app_links/pubspec.yaml#L13
> 
> there is a workaround: adding "app_links_platform_interface: 1.1.0" to the pubspec solves the problem. I added this to "Pubspec Dependencies" on a random custom widget. Idk if there is another way to change the pubspec in flutterflow.

how you dit it? you just take a custom widget from pub.dev and add "app_links_platform_interface: 1.1.0" for dependencies?

**Comment by stayelles** [comment]
> seems like the "app_link" package causes the problem after the version 1.2.0 of app_links_platform_interface was released: https://pub.dev/packages/app_links_platform_interface/versions
> 
> app_link version 3.4.1 (which flutterflow uses) seems to use the latest version of app_links_platform_interface automatically: https://github.com/llfbandit/app_links/blob/3.4.1/app_links/pubspec.yaml#L13
> 
> there is a workaround: adding "app_links_platform_interface: 1.1.0" to the pubspec solves the problem. I added this to "Pubspec Dependencies" on a random custom widget. Idk if there is another way to change the pubspec in flutterflow.

Maybe you have a screenshot please ??????

**Comment by luca-heitmann** [comment]
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/23654118/ce7d133f-51db-41b1-8a9b-a39169fb1307)

Hope it helps

**Comment by stayelles** [comment]
i think that now bugs is fixed by FF team, just test it now and it work

**Comment by AlexWrench** [comment]
I was experiencing the same issue with app_links which has seemingly been resolved for me, and I have been able to push a web update live... however... I a new error when compiling custom code has popped up. 

Error: Failed running flutter pub get...
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.

**Comment by raycelgraterol** [comment]
Now work for me without changing nothing FF seem find the solution. 
Thanks you so much.

**Comment by leighajarett** [comment]
This issue has been resolved, so sorry!
