### ISSUE TITLE
Supabase row now allowed as parameter in custom function

### ISSUE THREAD

**Issue by vagnerac** [FlutterFlow/flutterflow-issues#3249]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When added argument type Supabase Row, custom function get in error and does not work in the tests.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/97072906/fcc5c6d3-c475-4fa1-a00a-a3e022c24d56)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/97072906/9b0c07ed-1df1-466a-b109-494c305c0525)

### Expected Behavior

Custom function to work properly when Supabase Row type is set as argument or return of the function.

### Steps to Reproduce

1. Set up Supabase connection
2. Create a custom function
3. Set a Supabase Row type in arguments
4. Test the function

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTiPHq2ItPxeFK+KrqL8cxjSgXI0McWOdEl+tuZwgbIoznBuwqP/fSVFhpQsehaVNcelqajkEz08L3iuLDMcEBPRSCQaY6yKt6TDrke2ilV5PWDqigenB8GeFUGB2PyrbQuxR4Vc9tLyEWw2GMNe+vbHfDIuu/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/97072906/fcc5c6d3-c475-4fa1-a00a-a3e022c24d56)

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/97072906/9b0c07ed-1df1-466a-b109-494c305c0525)

### Environment

```markdown
- FlutterFlow version: v4.1.63
- Platform: Web
- Browser name and version: Chrome 125.0.6422.142
- Operating system and version affected: N/A
```

### Additional Information

There is a bug previously reported and closed with fix, but bug is not fixed actually: https://github.com/FlutterFlow/flutterflow-issues/issues/1509

**Comment by ignalauret** [comment]
Hey @vagnerac thanks for your report. I can confirm that I'm getting the same error trying to test with the Supabase row as argument. I will send this to our technical team so they can figure out what's going on and let you know. Have a great day!

**Comment by spiro4** [comment]
hey @ignalauret i am also facing this issue, doesnt seems to be resolved yet even for the return type the issue is there, please find the attached screenshot of the same 
<img width="1404" alt="image" src="https://github.com/user-attachments/assets/e549cb20-f97e-4310-99ba-b9afa3cf25de">


please help me with the same

**Comment by sheprograms** [comment]
Adding my +1 to this still being an issue. Super frustrating since I'm migrating from Firebase to Supabase and this caused me some major headaches. My workaround is to pass all the fields from the row that I need in as params, but it's tedious. 
<img width="1381" alt="image" src="https://github.com/user-attachments/assets/915ca052-bc87-4287-bd57-a62d9b0fa7c8">

**Comment by celervpn** [comment]
+ Some Problem
<img width="1363" alt="Image" src="https://github.com/user-attachments/assets/a2534305-58bf-4f5d-abf9-0d1edadb214c" />
