### ISSUE TITLE
Unable to validate firebase schema due to insufficient privileges.  Worked before.

### ISSUE THREAD

**Issue by KirilOkun** [FlutterFlow/flutterflow-issues#328]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Firebase schema should be valudated

## Current behavior (required)

Get attached error.  Unable to validate due to insufficient privileges.
![Screenshot_20230109_095052](https://user-images.githubusercontent.com/1024870/211233939-9c8a522a-88ed-4a3e-acb5-a63749817d6f.png)
.  

This used to work until recently.  There are several threads about this issue on the community site.

Firebase is setup properly.  firebase@flutterflow.io has Editor, Cloud Functions Admin, and Service Account User roles.
 
Replacing the first firestore rule below with the second allows validation to run successfully  but leaves the databse wide open.

>    match /{document=**} {
>      allow read, write: if request.auth.token.email.matches("firebase@flutterflow.io");
>    }
**Doesn't work**

>     match /{document=**} {
>      allow read, write: if true;
>    }
**Works**

## To Reproduce (required)

1.  Open a firebase project
2.  Open data page
3.  Open firebase settings
4.  Click Validate button in the schema validation section
5. 

## Your environment

* Version of FlutterFlow used: 3.0
* Platform (e.g. Web, MacOS Desktop):  Web
* Browser name and version:  Chrome Version 108.0.5359.124 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Kubuntu 22.04, Kernel 5.15.0-57-generic (64-bit)

**Comment by aemelyanovff** [comment]
I'm unable to reproduce the issue.

This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support@flutterflow.io for further assistance.

If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.

A couple of tips for troubleshooting this issue:
* Make sure "Email/Password" signin provider is enabled in your Firebase project.
* Try regenerating Firebase config files in FlutterFlow: go to Settings/Firebase, press "Regenerate Config Files".

Thank you for your contribution!

**Comment by KirilOkun** [comment]
@aemelyanovff    There's definitely a problem outside of just my project.  Below are several FF community threads discussing this very issue.  It might be worth a second look.

https://community.flutterflow.io/c/discuss-and-get-help/firebase-permission-error-when-trying-to-validate-flutter-app

https://community.flutterflow.io/c/discuss-and-get-help/unable-to-validate-firestore-schema

https://community.flutterflow.io/c/discuss-and-get-help/i-have-issues-with-validating-firebase-schema

https://community.flutterflow.io/c/discuss-and-get-help/missing-or-insufficient-permissions

https://community.flutterflow.io/c/discuss-and-get-help/firebase-permission-bug

https://community.flutterflow.io/c/discuss-and-get-help/firebase-schema-validation-error

**Comment by KirilOkun** [comment]
It was working fine until recently.   So perhaps a breaking change or problem with the configuration.   I'm still in dev so am keeping the db wide open.  But it won't be an option once we go live.

**Comment by KirilOkun** [comment]
Email sign-in is enabled.
Regenerated Firebase config files.
The problem persists.

**Comment by KirilOkun** [comment]
@aemelyanovff   Please reopen this issue as it's still happening to multiple users.

**Comment by aemelyanovff** [comment]
@KirilOkun I believe this is an issue, I just don't think this issue tracker is the right place for it because there are no reproducible steps. I suggest reaching out to support. Also, if you do find a solution, please let us know.

A couple more tips:
* Try disabling other Firestore security rules.
* If this issue prevents you from using Run Mode, you can disable this feature altogether in Firestore/Settings

![Screen Shot 2023-01-13 at 1 56 46 PM](https://user-images.githubusercontent.com/92294640/212397648-bfcdabb9-2d0c-4919-853b-bfa087b8224c.png)

**Comment by KirilOkun** [comment]
@aemelyanovff   I truly disagree with your assessment.  I, and other users from those threads, have followed FF instructions on how to setup Firebase.  The application worked for months without any issues with that very configuration, which did not change.  All of a sudden FF started complaining about it and throwing errors.  I might be wrong but i don't think the problem is with the Firebase or with the rules.  Something changed in FF.
