### ISSUE TITLE
Data Table removed all data when more than 10 columns added

### ISSUE THREAD

**Issue by Adatik** [FlutterFlow/flutterflow-issues#3294]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

in the Data Table, when I add more than 10 columns, it deletes all values and resets them to be like Edit Header 3, Edit Column 3, and so on and I need to retype my headers and column value again, which takes time to do that.

### Expected Behavior

I can add multiple columns without deleting any data. For example, if the first header is the first name it should be a first name not Edit Header 1. Notice this issue happens when it adds more than 10 columns.

For example, if my columns now are 7 and added all my header's names as well as the value, then later I decided to add more than 10 columns. it should save my header names as well as the value.

This is not a project issue this is a FlutterFlow bugs issue.

### Steps to Reproduce

1- Create a new page
2- Add a Data table on that page.
3- Add 7 columns and rename headers as well as add value in columns.
4- Add more than 10 columns and you will see the problem all headers and values will be reset to a default value

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXl/H1z89Nof5E+6n5Y/pavCIwGX4eUIIZku1EZ0gjGIjbB4YUZ/vRQEtuTdO0Y1VLPkyWgToK0NXemvL9A+47F06bbLpn1c0JdAHJeHu6acSbDcy8dm5/Dd5XIGKf4Z6vsBJ+CO9sW3wX3U6mJumiZHbfJpDAImojFv2XLZKK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/131679014/c3dd6174-9f77-425d-8f6b-63d87a1f6511

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.65+ released June 29, 2024
Flutter version is 3.22.2
- Platform: All
- Browser name and version: All
- Operating system and version affected: All
```

**Comment by vieiraes** [comment]
interesting... following

**Comment by Alezanello** [comment]
Hello!

First, thank you for reaching out to us with this issue.

I was able to replicate the behavior you described. However, it's not a bug but rather the way the data table handles column changes. When you increase the number of columns from, say, 7 to 10, the process involves changing the column count from 7 to 1 first, and then to 10.

This sequence means that the data table initially interprets the input as a request for 1 column, removing the others, and then it adds columns to reach the total of 10. This behavior occurs with any change where the new number of columns is lower than the current number.

For example, if you have 6 columns and change it to 17 by first entering 1, then 7, the table will temporarily drop to 1 column before adding the additional 16, effectively removing the previous columns.

This is more about the inherent behavior of the data table rather than a hard reset.

I'm going to send this for a double check to engineering to see if it is an expected behavior or something that could be improved. Thank you very much for your time.

Best regards,<br>Azanello
