### ISSUE TITLE
API Group Variables forced to send

### ISSUE THREAD

**Issue by ryutosh** [FlutterFlow/flutterflow-issues#3295]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In API Editor, Variables declared in Group are included in the request even if they are not used in Json.

### There are 5 group variables
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/da943c8f-3306-4cec-bbc2-b669ef870479)

### Use only 3 of them
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/2c93b915-5a20-46d1-a4d4-e5f591a71cf8)

### All group variables send
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/35ce3aa8-6673-4d93-88fb-e98590aa20c3)

This behavior is strange from the following two perspectives
1. The description of Group Variables states that these are options that can be set in the UI builder. They are options, not forces.
![image](https://github.com/FlutterFlow/flutterflow-issues/assets/71914270/56a8b469-d70b-4cf6-b731-dbe0da9d8ab2)

2. Two global variables that were not declared in the JSON format included themselves in the root even though they were not included in the format. Structure is determined by the format, and placement in the root is not always correct.

### Expected Behavior

As in description of Group Variables tooltip, Group Variables just shows on Builder UI, but not forced to appear unless they are explicitly written in format.

### Steps to Reproduce

1. Create API Group
2. Create API inside 1
3. Make ListView widget using 2
4. Test

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEehfKB35ZJpbwG1c7qcsJWiQMwJHI/auYvte5+d0shfJSrOu0HOuPeaktLYte9SmNcIWeajnEDwtWLud7pIMIoAzGCfoRxzr5XQQrjWkm6WoyxPZagX3NQL/FYBWHE1sOnhSJDKsVsci0Z3zqACPCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

as in "Current Behavior" section.

### Environment

```markdown
- FlutterFlow version: 4.1.65+
- Platform: web
- Browser name and version: Chrome Version 126.0.6478.127 (Official Build) (arm64)
- Operating system and version affected: MacOS sonoma
```

**Comment by Alezanello** [comment]
Hello!

Thank you for reaching out with your issues. I was unable to reproduce the problem in a blank project. In my test, the variables I set from the group did not include two of them in my format, and they were not sent to the API call.

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/174125846/aaadab2c-f42c-4ea1-baed-c37b4066b21d)

Could you please try to reproduce this issue in a blank project and share the Bug Report Code with us? This will help us determine if the issue is specific to your project.

Best regards,
Azanello

**Comment by ryutosh** [comment]
Hi @Alezanello 
I tried some case to reproduce.
Please try in "Make Private" toggle ON.

**Comment by Alezanello** [comment]
@ryutosh  Excellent! Let me try that and I'll get back to you shortly.

**Comment by Alezanello** [comment]
Hey! @ryutosh 

I've got some news! I was able to replicate the issue when the API call is made as a private call. I will forward this to our engineering team so they can take a deeper look and find a way to prevent this from happening.

Thank you very much for bringing this issue to our attention, and I apologize for any inconvenience this may have caused in your current project. We appreciate your patience as the team works on fixing and updating this issue.

Best regards,
Azanello

**Comment by MartinLockheart** [comment]
All of my API calls are private. Has this been fixed, or is this still an issue? I expect this will cause problems in some of my apps as well.

**Comment by aemelyanovff** [comment]
Sorry for the late response.

This is actually intentional — I think it's better for compatibility. Private APIs can be redeployed to use previously unused group variables. If FlutterFlow didn't include all the available variables in private API calls, it might break your app if it's already live.

Is this causing any problems? I couldn't quite figure out which use cases are being affected based on the issue description.
