### ISSUE TITLE
Run mode not working the same as test mode

### ISSUE THREAD

**Issue by Holdthat** [FlutterFlow/flutterflow-issues#3311]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In run mode the homeagent page does not show or scroll as expected, neither does the archive tab display archived data.

### Expected Behavior

Test mode works as expected, the homeagent page scrolls and the archive tab shows archived data.

### Steps to Reproduce

start test mode.
Click on list and scroll, or click on the archive tab.
then do same in run mode.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/q5ZNPmMBE7c+BbcBB/WUQOXojaLhNsctvaw4dfuLnBLQqfvSkN01oSOqHdwt2eVeGjk41w/z2vYaeFcEBBEiVbYNz1rhtUxDiRj+7WrKlBc60W0RPGf1hN0i10KWJmRBdKbdtLXBl6meMIPOAb3qCf9qOYwx5e6fDbOY=

### Visual documentation

none

### Environment

```markdown
- FlutterFlow version: V4.1.65+
- Platform: Web
- Browser name and version: Edge for test mode, chrome for run mode. Latest versions
- Operating system and version affected: Windows 11
```

### Additional Information

None

**Comment by Alezanello** [comment]
Hello!

First of all, thank you for reaching out with your issue. I was unable to replicate your issue in a blank project, which suggests that this might be a project-specific issue rather than a FlutterFlow bug. This issue tracker is intended for bugs that can be replicated from a blank project.

I strongly recommend contacting support via the in-app chat or at support@flutterflow.io for assistance with your specific case.

Best regards,<br>Azanello

**Comment by charliefabley** [comment]
I would agree with this, I have noticed that in test mode my application can literally ignore fairly simple actions in an action chain. It will simply stop without providing any error whatsoever and no explanation. However when I run it in run mode, those issues do not exist. This is particularly problematic as when I am using the test mode it's impossible to know if the application fails because of my errors, or because the application is not running because of FF errors.

**Comment by Holdthat** [comment]
I fixed the scroll issue by expanding the container/column.

My last issue is the archive (filter) tab not showing results. I have been able to investigate more. I have narrowed it down to a browser issue. Works as expected in Edge, does not work in Chrome.

**Comment by charliefabley** [comment]
Also many of the material icons do not appear in run mode.

Debug mode

[image: image.png]


And on run mode

[image: image.png]

**Comment by Alezanello** [comment]
Hello!<br><br>Just checking if this issue was fixed with the last FlutterFlow Update?

**Comment by charliefabley** [comment]
I would have thought this issue should only get closed if ff had fixed it!
There may be no new information to add to it simply because we've reported
everything, but it doesn't mean it should be closed because we've got
nothing else to report.

**Comment by Holdthat** [comment]
Last test I did, a few days ago, Chrome was still not working as expected.

**Comment by Alezanello** [comment]
Hey, I haven't closed this yet!

Actually, 22 hours ago I asked how everything was going after the latest update release from FlutterFlow.

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
