### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'nativeCommunication') while running as Web App

### ISSUE THREAD

**Issue by akashkoyani1** [FlutterFlow/flutterflow-issues#3317]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'nativeCommunication')
    at InAppWebViewFlutterPlugin.registerWith (web_platform.dart.js:56:60)
![Screenshot 2024-07-05 at 10 47 22 AM](https://github.com/FlutterFlow/flutterflow-issues/assets/169893039/4ff1425a-a692-4dc5-a1e5-3515dc66fe5c)

Showing error in Web Test session and in publishing to Web.

Error is caused because my project has used html_editor_enhanced: 2.6.0 and this dependency relies on  flutter_inappwebview.

As per the flutter_inappwebview document I need to add the below script to web/index.html (Reference Link :- https://pub.dev/packages/flutter_inappwebview)

<head>
    
    <script type="application/javascript" src="/assets/packages/flutter_inappwebview_web/assets/web/web_support.js" defer></script>
    
</head>

So, I added it by downloading the FlutterFlow code. And it works.

But, How can I add the same script to the FlutterFlow web/index.html file? So, I can run/use the FultterFlow's Test session.

### Expected Behavior

For the Web platform, FlutterFlow should add the script for inappwebview.

### Steps to Reproduce

1. Create a FlutterFLow web app-supported project.
2. Add html_editor_enhanced: ^2.6.0
3. Try to run in a Test Session on the FlutterFlow.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhcjfuYthnMxJ+ZSIY8JKqDksJnkcTIMziNZ+exUbfaL1BuwAZOPBSxFuZ73jaVNcPlKZgTgK0vyJi+D9JfYqPS2aRqo6wahIdwHee2iXb7nTBqizOWhSQOZUfFSF5sKjoCV7AOxidUVm11yUfu+XEzDDFOu/Zwh9f6PHaOI=

### Visual documentation

https://pub.dev/packages/flutter_inappwebview

### Environment

```markdown
- FlutterFlow version: v4.1.65+ released June 29, 2024
- Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Google Chrome
- Operating system and version affected: Mac OS
```

**Comment by Alezanello** [comment]
Hello!

The `html_editor_enhanced` package was affected after upgrading Flutter to version 3.22.2.

This is a project-specific situation and not related to a FlutterFlow error. Currently, there is no method to add this in test run because it is more app-focused than web-focused.

I found a temporary workaround within the community that might help you continue using the package. Please check the first comment on this post: [Rich Text Editor Custom Widget](https://community.flutterflow.io/app-showcase/post/rich-text-editor-custom-widget-FwwEg9LJxy3i1EJ).

I hope this solution works for you!

Best regards,<br>Azanello

**Comment by MauruschatM** [comment]
this kind of stuff really sucks about flutterflow
