### ISSUE TITLE
Unable to submit to App Store: The getter 'bodyText2' isn't defined for the class 'TextTheme'.

### ISSUE THREAD

**Issue by jcorn925** [FlutterFlow/flutterflow-issues#3326]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Xcode archive done.                                         76.6s
Failed to build iOS app
Error (Xcode): ../.pub-cache/hosted/pub.dev/flutter_linkify-5.0.2/lib/flutter_linkify.dart:109:44: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.

### Expected Behavior

Xcode archive done.                                         76.6s
Failed to build iOS app
Error (Xcode): ../.pub-cache/hosted/pub.dev/flutter_linkify-5.0.2/lib/flutter_linkify.dart:109:44: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.

### Steps to Reproduce

Xcode archive done.                                         76.6s
Failed to build iOS app
Error (Xcode): ../.pub-cache/hosted/pub.dev/flutter_linkify-5.0.2/lib/flutter_linkify.dart:109:44: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ehvHlvM91ofpE7c/Ab8FvmSQRIjs/RYInm9V+dAw0NZjtB+wLO+j+QHZVOMO/dFY3OlmI8TozzN7OkdmeVMEHPiiaf4By/8x2VA3wZHyjVc2UPKmKRHJ5LNxhCH2HzbWrgRBDCPdaLSUf1DqULuqUYC7YQbr4PFYRB/+LOovMnkqqLBzOXn0Jg1ZSfCvr

### Visual documentation

<img width="464" alt="image" src="https://github.com/FlutterFlow/flutterflow-issues/assets/67557245/377f56be-aac6-4f6c-874f-5474ac00a26d">

### Environment

```markdown
- FlutterFlow version: 4.1.65
- Platform: Web
- Browser name and version: Edge
- Operating system and version affected: Windows 11 Enterprise 22H2
```

### Additional Information

Blocked

**Comment by Alezanello** [comment]
Hello!

I was reviewing your code, and it seems the issue is specific to the 'flutter_linkify' package, which might not be compiling correctly with the newer version of Flutter. I highly recommend upgrading to the latest version to see if that resolves the issue, or switching to another package compatible with Flutter 3.22.2.

Currently, your project uses the package version `flutter_linkify: ^5.0.2`, but the latest version available on [pub.dev](https://pub.dev/packages/flutter_linkify) is 6.0.0. Please try updating to the latest version in your custom widget.

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
