### ISSUE TITLE
Test mode, run mode and web publish will not work.

### ISSUE THREAD

**Issue by leoleo-s** [FlutterFlow/flutterflow-issues#3378]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello team! I can't test my app anymore since the test mode, run mode and web publishing isn't working anymore. It was working perfectly just yesterday. If you try the test mode it will be loading forever and never opens the app, same on run mode. If you publish to the web, the app will just show a blank screen. I didn't tested the native version yet. There's no issues nor bugs on the app. It has some custom code, but all the code is tested on a dummy project before it goes to the main project. Tested on Chrome and Safari with the same result. Also, it seems to occur only on this specific project. I'm pretty scared since this is a big project that I'm working for 6 months now.

### Expected Behavior

Test mode, run mode and web should work as intended, showing the app ui and let the user test it.

### Steps to Reproduce

1. open the project on flutterflow
2. click on test mode
3. the app ui will never show up and will be loading forever.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lPHqx5d2m+FG+KryafpvtCAsQzI7a7s8mMFtbA88J5DaPOxzP/TBaldWUs+0Snx9M2KZvHsy7tnemvztNe0rMk+aUaJays9AYTuWZHmnWq6KCbiCRW5/De1RC22Oy7TZ2SYlXeNscVY+2mWMFt/KFzLfK7G2NTERDv/9F5OK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/8fd93cc5-9139-47bd-a5ed-bcf7a69399d5

### Environment

```markdown
- FlutterFlow version: 4.1.71+ Synced
- Platform: web
- Browser name and version: 126.0.6478.127 (Versão oficial) (arm64)
- Operating system and version affected: MacOS Sonoma 14.4.1
```

### Additional Information

This issue is preventing me from continue developing the app since I can't test anymore.

**Comment by Alezanello** [comment]
Hello!

I was checking your project, and indeed there is a problem running it from anywhere. However, I can't see anything that helps determine the cause of the issue. As you mentioned, this is a big project, and the error can't be replicated in a new blank project. Since this issue tracker is meant for issues that can be replicated in a new blank project, I need you to contact support via in-app chat or email at [support@flutterflow.io](mailto:support@flutterflow.io). They can dive deeper into your project's specific situation, identify the cause, and help you fix it so you can continue developing with ease.

Thank you for your understanding!

Best regards,<br>Azanello

**Comment by andreasvonfeld** [comment]
I have the same problem !

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
