### ISSUE TITLE
Expandable widget: toggle not working when adding an action to the header area of the widget

### ISSUE THREAD

**Issue by Alexandre-Lemyre** [FlutterFlow/flutterflow-issues#339]
## Expected behavior (required)

The Expandable widget has an option called "Tap Header to Toggle". This option does not work when an action is added to the header.

## Current behavior (required)
There is no toggle after adding an action to the header. 

## To Reproduce (required)
1- Add a column
2- Add an expandable widget in the column
3- Add content in the "Header", "Collapsed View", and "Expanded view" areas of the Expandable widget
4- Activate the "Tap header to toggle" option in the Expandable widget.
5- Then, test the widget to make sure the toggle works when clicking/taping on the header (the toggle should work at this point)
6- Add an action to the Header (I added an action to update a local state). 
7- At this point, the toggle should stop working (the action that was added in step 6 is performed, but there is no more toggle).

Code can be included in this section if it is relevant to reproducing the bug. 
N/A

See above

### Bug Report Code (required, generate from Widget Tree)
N/A

## Context (required)
I can't have the toggle and an action at the same time when tapping on the "Header" section of the expandable widget. 

## Screenshots / recordings
N/A

## Your environment
Desktop, Windows 11, Chrome, FF 3.3.4

**Comment by victoriahuang1** [comment]
Hi @Alexandre-Lemyre , thanks for the report. In this case, the behavior is as expected. Essentially what is happening is there are 2 conflicting "on tap" actions. The action you added to the header prevents tapping the header to expand the widget, due to both of these actions being defined over the same area.
You can check out https://github.com/FlutterFlow/flutterflow-issues/issues/343 for a more detailed explanation. Hope this helps!
