### ISSUE TITLE
Error: Email rate limit exceeded

### ISSUE THREAD

**Issue by CirQulor** [FlutterFlow/flutterflow-issues#3406]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In test mode : Error: Email rate limit exceeded whenever testing 

### Expected Behavior

Expect to be able to add more than one user via 'Signup'

### Steps to Reproduce

1. Create 'Signup' page from template
2. Link to Supabase
3. Test

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4khc/qy5d1m8tK7qnxbfkwnjoWG1g5TL07ttYbZxUjIuPtBJh/fcjeYhFWcN+4TWlhHFr9nkkGpt2Lj+zhUPY6YQWtQap7zc0BVQLvQXq8RbKPC7jhZUdCDcpQI2qd0JiNrRBTIu11c39g2GaQPtiQQnbfJ5+/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/4041f0a3-d5b3-4e89-9409-0adcc5e4b90c)

### Environment

```markdown
- FlutterFlow version: 4.1.72
- Platform: Win
- Browser name and version: Chrome 126.0.6478.127 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro 19045.4651
```

### Additional Information

Can't continue to build with confidence

**Comment by Alezanello** [comment]
Hello!

This issue seems to be more specific to Supabase than FlutterFlow. It is likely linked to the email rate limit configured in your Supabase project. You can adjust the rate limit settings by visiting this link: [Supabase Rate Limit Configuration](https://supabase.com/dashboard/project/\_/auth/rate-limits).

Alternatively, you can navigate to your Supabase project, go to **Authentication**, and then select **Rate Limits** to make the necessary adjustments.

Best regards,<br>Azanello

**Comment by CirQulor** [comment]
Thanks Alezanello. Will do.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
