### ISSUE TITLE
Build failed with no error message and cannot download code to inspect

### ISSUE THREAD

**Issue by marcelo-azevedo-br** [FlutterFlow/flutterflow-issues#3424]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After solving all errors, my app is not running in test mode. Build fails with no message error and also no error shown in Flutterflow builder:

![image](https://github.com/user-attachments/assets/e486dd19-a16e-4a84-a8f7-dc5acca212c4)

![image](https://github.com/user-attachments/assets/60c8b9e2-5dab-43e2-bf0b-d99a804bc9bc)

Also try to download via flutterflow cli to inspect the code:

![image](https://github.com/user-attachments/assets/982e824c-1324-4d26-825f-38fadd04a106)

### Expected Behavior

I expect to run in debug mode via flutterflow or ate least download my code to see what is going on... I REALLY need this to launch in production to a client...

### Steps to Reproduce

1. check that there are no errors
2. click Test button
3. get the Build error with no reason or error message about what is wrong.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sl8j6yIt2xdtA1pD2dsF7/GA6NmYkR688scp/bxIgGIDzPOw+ZPWkNhNuUtTmYwlUO0SmmlwzzPTIjdj9D8A4KQmbRapfzLt6SQKUZGOgQZOBErq/dEYnAZtgGECe55jYkRBSD7Z1W0YA2jile97KSg3AJO6xIndISq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/e486dd19-a16e-4a84-a8f7-dc5acca212c4)

![image](https://github.com/user-attachments/assets/60c8b9e2-5dab-43e2-bf0b-d99a804bc9bc)

![image](https://github.com/user-attachments/assets/982e824c-1324-4d26-825f-38fadd04a106)

### Environment

```markdown
- FlutterFlow version: 4.1.73+
- Platform: Flutterflow Web and Desktop App
- Browser name and version: Versão 126.0.6478.127 (Versão oficial) 64 bits
- Operating system and version affected: Windows 11 Home version 23H2
```

**Comment by Alezanello** [comment]
Hello!

I just checked your project and it seems the issue is with one of your widgets. I can't edit or move anything to try to fix it. Could you please check the widget and see if that resolves your problem?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e2323278-f0c7-4655-b9f4-3adc940445cc/9c5ef069-15cc-4985-9550-9b3074a14aac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMjMyMzI3OC1mMGM3LTQ2NTUtYjlmNC0zYWRjOTQwNDQ1Y2MvOWM1ZWYwNjktMTVjYy00OTg1LTk1NTAtOWIzMDc0YTE0YWFjIiwiaWF0IjoxNzIxMzA2NTM0LCJleHAiOjMzMjkxODY2NTM0fQ.JWFgy8ec7GKnt8hiQV8UucCjKaR_AGNaVZmpfdaM9wg " alt="image.png" width="269" height="115" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
