### ISSUE TITLE
Action is not working from a component that have an action as parameter

### ISSUE THREAD

**Issue by Franco98404** [FlutterFlow/flutterflow-issues#343]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

Execute the action from a component (not send action as parameter)

## Current behavior (required)

Nothing happens

## To Reproduce (required)

1. Create a component
2. Set an action as parameter
3. Create a page and add the componente created previously
4. Add an action as parameter and add an action to the component
5. You can observe that is executed the action sent as parameter and the action from the component is never executed

Happens something similar if to the component is not sent an action as parameter but is set an action (not sent as parameter) so the action is never executed

### Bug Report Code (required, generate from Widget Tree)

IT4ClcmAuIhOxLhc1pPpbfpVgmAUJjM6RYI30+5DZEgjN5PND+x/esnRQFJuZ9OrdgllfUyZpHk10NGKm9z1CcICKTaaRrpl+cx+chaXXkmlVL63O7qKekZgSJYGSSDy

## Context (required)

We were very confused about this feature because we don't understand the utility to send an action as parameter when is possible set action to the component. In our case we are doing some generic button to use along the app, the only idea that occurs me if the component is very complex so we can send an action as parameter to specific widget from that component.

Link to the project:
https://component-action-buj14g.flutterflow.app/

## Screenshots / recordings

N/A

## Your environment

* Version of FlutterFlow used: 10 January
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version: Version 1.46.144 Chromium: 108.0.5359.128 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Windows 11 - 22H2 - Os build: 22621.963

**Comment by agreaves** [comment]
Hi @Franco98404, thanks for the report. In this case, this is simply how Flutter works and is Working As Intended. I can explain this.

Imagine you have Widget A, and inside of it you have Widget B (like below). And then you add an Action to A, and also an action to B.

<img width="314" alt="image" src="https://user-images.githubusercontent.com/7757399/211718960-ec5c36c4-0ecb-45c0-b4f8-c2b435c0a788.png">

The question is, what happens when you tap on the Blue region (B) vs the Red region (A)? In Flutter, it will always choose the innermost widget, so if you tap anywhere in blue it will trigger the action for Widget B. And if you tap anywhere in red it will trigger the action for Widget A (essentially, anywhere in A that is not also in B).

In your case, in the project you linked, you added an action to the component on the page, and also an action inside the component. Since the component consists of just a Button, the entire area of the button is clickable. Using the example above, this means Widget A and Widget B are the same size, and therefore there is no "Red" area so Action A is never triggered (which is what you observed).

Hope this makes sense!

**Comment by Franco98404** [comment]
Thanks for you great explanation!
