### ISSUE TITLE
pauseOnNavigate not set in code for video player

### ISSUE THREAD

**Issue by Aging-Developer** [FlutterFlow/flutterflow-issues#3443]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

if you set a video to pause on navigation, as per screen shot:
![image](https://github.com/user-attachments/assets/119245af-f85b-4e6a-86a6-9ff7273ba4cd)

It is not being set in the code:
![image](https://github.com/user-attachments/assets/7c91ce7b-f432-4106-a4b8-ca32811d1d28)

### Expected Behavior

for the settings to be present in the code.

### Steps to Reproduce

1. create a page
2. add video control with forward navigate
3. look at code, the pauseOnNavigate parameter is missing

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocBH7pDMbMFAhQUjHGYkU4JEs+1uZ00jF5D4P4YHPMj8VFhpUtyzaH1qOFGlp3Ef0a3LjYbtVvABGwecfIQ5/7tyVRPPbGamWoyIC4eeRHZ8TNFbIG6D36a3vxQkIfpqdVo56kOLe9/LRT6Cf9qOYwx5e6fDbOY=

### Environment

```markdown
- FlutterFlow version: 4.1.74+
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

The Video Controller is throwing platform errors.

**Comment by laughingbuddha24** [comment]
@Aging-Developer Did you find a solution to this? I have the same issue.

**Comment by Aging-Developer** [comment]
I ended up writing my own video player as it was clear that FF have no interest in fixing the issue.

**Comment by laughingbuddha24** [comment]
Thanks for the update. Is that something you can share? I'm now testing Karol's custom video player at https://community.flutterflow.io/c/community-custom-widgets/post/custom-video-player-with-play-pause-on-tap-yionqnb1CNDQxuG which resolves the issue of Pause on Forward Navigation, but it has some height and width issues.
I would really like FF to have less features that were fully built out rather than lots of half completed features.
