### ISSUE TITLE
API not working in Android Deployment

### ISSUE THREAD

**Issue by williamgomez71** [FlutterFlow/flutterflow-issues#3456]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

 I have been reviewing the server logs and the request never arrived to the server, that is like an issue on the api call in Android because if I try in web or IOS the request is sent to the server but in Android, this never happens, please help with this issue. this happen when I deployed the app in the app store or when I download the apk and then install this in Android  device, other way to test is download the github code and test with flutter run

### Expected Behavior

send the request to the server.

### Steps to Reproduce

only create an API request and try to send this in production environment,  this happen when I deployed the app in the app store or when I download the apk and then install this in Android  device, other way to test is download the github code and test with flutter run

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

n/a

### Visual documentation

n/a 

### Environment

```markdown
- FlutterFlow version: lasted version
- Platform: Android
- Browser name and version:n/a
- Operating system and version affected:  Android
```

### Additional Information

asdf

**Comment by Alezanello** [comment]
In order to see the issue more closely could you please generate a Bug Report Code from your widget tree?

Just go to any Page, Right click on any widgets from the Widget Tree and select the option "Get Bug Report Code" and share it with us

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e565bb7c-4b6d-4760-8d9a-114325be3e9c/2fef73de-5b9a-4270-b74d-d271a146afba?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNTY1YmI3Yy00YjZkLTQ3NjAtOGQ5YS0xMTQzMjViZTNlOWMvMmZlZjczZGUtNWI5YS00MjcwLWI3NGQtZDI3MWExNDZhZmJhIiwiaWF0IjoxNzIxNzM3MDc2LCJleHAiOjMzMjkyMjk3MDc2fQ.pqd0B5mnIwBP3fk7KOwHblB7aRrdAY9Xyh78d5KyfPI " alt="image.png" width="459" height="522" />

**Comment by williamgomez71** [comment]
@Alezanello done and thanks for your help,  this issue is happeing with any API call, I created a lot of API and none is working in android, none are sent to the backend server, I don't know what is happening

ITFfhsmAw49On7xY1a6JY8cwlmMWG1scTIMziNZ+exUbfaL1Buwcd8+kaRNVYNenaVNcMU79uFwFweDpjtmWG/dcB0mCGYhazatuVQ3ke2iuM76pPM6wdnFSJ+dNCmqx3J2n2hFQNuhfV0YO1zm2e+SQaDTDIuu/Zwh9f6PHaOI=

**Comment by Alezanello** [comment]
Hello again!<br><br>I created an account (worked) <br>I verified the account (worked)<br>Tried to login (not worked)<br><br>Verifying the API Call directly when i use the account it says "invalid service account"<br><br>Tried all this on a Android 11 Pixel 4a<br><br>So creating account API worked correctly on Android (the account was created correctly)

**Comment by williamgomez71** [comment]
@Alezanello please verify the issue with login api (not log in with google), log in with any user and any password ... this request never will send to the server.

**Comment by Alezanello** [comment]
I created the user with email and password. not used the google log in<br><br>try in your Login API Call an email and password and is going to give you an error saying there is an invalid service account.
