### ISSUE TITLE
Local Test failing when selecting any page that is off of the main navigation

### ISSUE THREAD

**Issue by QuinnGunter** [FlutterFlow/flutterflow-issues#3463]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Running my app in local test and selecting account settings, detail view of an item or any other item that is off of the main toolbar navigation causes an error
![IMG_2CF03FD28ED7-1](https://github.com/user-attachments/assets/8a6934f0-43a1-43e0-adb4-7f66f2008a33)

### Expected Behavior

Navigation off of main nar items properly load

### Steps to Reproduce

1. Create a list view
2. Add some items
3. Create a new detail view of the item 
4. Allow navigation from the list view to a new page for the detail view

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48lfLqw4VgoctF7r6Jc8Ewlj0vJl87U4E7jdYaZxU8KOvUB+x/evXsUEtuTsurdH9MJUSmml8F/vyPvuLlIPA5NSyafKZmzbpudxXNfFuna5OBCKmKdXZ8He1hClOP0cPYqglSPtFpWEIjwE2EGN+UYz3DNYTFImdISq/LZO4=

### Visual documentation

![IMG_2CF03FD28ED7-1](https://github.com/user-attachments/assets/934b3f96-2831-448b-8018-2d55a9061491)

### Environment

```markdown
- FlutterFlow version: Version 4.1.75 (4.1.75)
- Platform: desktop app MacOS
- Browser name and version:
- Operating system and version affected: MacOS 14.5 (23F79), iphone 15 pro max for local test
```

**Comment by vereggen** [comment]
Experiencing the same issue. Here's the full error message from Local Run log ...

flutter: Error debug serializing parameter: NoSuchMethodError: Class 'List<UserProfileRecord>' has no instance method 'toDebugSerializableMap'.
Receiver: Instance(length:1) of '_GrowableList'
Tried calling: toDebugSerializableMap()

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building InheritedGoRouter(goRouter: Instance of 'GoRouter'):
setState() called after dispose(): _TodayWidgetState#8217d(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in
the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error
can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose()
callback. Another solution is to check the "mounted" property of this object before calling
setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is
retaining a reference to this State object after it has been removed from the tree. To avoid memory
leaks, consider breaking the reference to this object during dispose().

The relevant error-causing widget was:
  InheritedGoRouter
  InheritedGoRouter:file:///Users/vereggen/.pub-cache/hosted/pub.dev/go_router-12.1.3/lib/src/router.dart:248:11

When the exception was thrown, this was the stack:
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1167:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1202:6)
#2      _TodayWidgetState.didPushNext (package:habits_coach/pages/home/today/today_widget.dart:122:25)
#3      RouteObserver.didPush (package:flutter/src/widgets/routes.dart:2157:22)
#4      _NavigatorPushObservation.notify (package:flutter/src/widgets/navigator.dart:3372:14)
#5      List.forEach (dart:core-patch/growable_array.dart:416:8)
#6      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:4368:27)
#7      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:4330:5)
#8      NavigatorState._updatePages (package:flutter/src/widgets/navigator.dart:4196:5)
#9      NavigatorState.didUpdateWidget (package:flutter/src/widgets/navigator.dart:3837:7)
#10     StatefulElement.update (package:flutter/src/widgets/framework.dart:5659:55)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#14     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#18     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#19     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#23     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#27     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#31     StatelessElement.update (package:flutter/src/widgets/framework.dart:5563:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#35     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#39     ProxyElement.update (package:flutter/src/widgets/framework.dart:5816:5)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:3827:15)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5512:16)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5650:11)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:5203:7)
#44     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2905:19)
#45     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1136:21)
#46     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:443:5)
#47     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1392:15)
#48     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1313:9)
#49     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1171:5)
#50     _invoke (dart:ui/hooks.dart:312:13)
#51     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#52     _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════════════════════════

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3004 pos 18: '!navigator._debugLocked': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      _RouteEntry.handlePush.<anonymous closure> (package:flutter/src/widgets/navigator.dart:3004:18)
#3      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:435:15)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:847:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:876:13)
#6      Future._completeWithValue (dart:async/future_impl.dart:652:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:722:7)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49<…>

**Comment by akblackman** [comment]
Same issue here .... any word from FF on this?

**Comment by ryutosh** [comment]
Same issue after updates.

**Comment by guibertjulien** [comment]
Same same

**Comment by peteplatohc** [comment]
I am also having the same issue.

If it helps,  I personally can select and navigate to pages from the Home Page so long as I don't navigate to any other page via the Nav Bar.  If I navigate to another page off of the nav bar, then go back to the home page, and then try to acccess a link, I get the error.

PS -- I also deleted all my animations and still didn't work.

Pasting my error in case it helps:

![image](https://github.com/user-attachments/assets/dd1b8c0a-8b4d-4129-b907-0e5af7947903)

**Comment by leighajarett** [comment]
Thanks for flagging, we're looking into this - will report back ASAP!

**Comment by leighajarett** [comment]
We've just deployed a fix for this and it should be live in 20 minutes or so - so sorry about this!

**Comment by QuinnGunter** [comment]
Thank you for the fast turn around 🙏🏼

**Comment by akblackman** [comment]
Thank you, team FF!

**Comment by reachgvm** [comment]
The issue is happening still. @leighajarett can you tell about what fix was made?

**Comment by leighajarett** [comment]
The fix was to check that its mounted before calling setState in route aware callbacks. If you are experiencing the issue can you open up a new bug with your project information so that we can make sure its the same root cause?
