### ISSUE TITLE
FlutterFlow builder issue

### ISSUE THREAD

**Issue by DevLHS** [FlutterFlow/flutterflow-issues#3465]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After deployment to the App Store and Google Play flutterf flow builder started to act up, closing different widgets and won't let edit on-screen elements. In my case when you go to the Global_Search screen, the clients section it won't show up any search results, won't let you edit elements and they show up as blank. But you can still see on the left panel that elements still exist
After some testing, now this bag is also shown on a few other screens inside a builder - WorkOrderDetailsV2

### Expected Behavior

Soused to be a regular builder allows you to edit components, fields, and elements inside a builder 

### Steps to Reproduce

1. Go to project
2. go to WorkOrderDetailV2 or Global_Search 
3. in WorkOrderDetailV2 go to Finances and list of items will become blank and then the whole builder crashes // same goes if you navigate to Global_Search then Clients it wont show any part of the screen build and then will freeze the whole builder 
4. 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8ojMmAx5dOtbxf1s+Jde9agjwWH1A/UOcrmMNxcxQgfb3qB4YEeOHCakhBTu7hSnlHG1eJpHE00sLPhuzDBPoFHAStfLo41s9XQx7gWnymRrKsDaigS3ZTO9NbGh3E0bav2SNAVbJwd2wkwE6yFe+XcCbqNpjINW0NR/qYUbL4jHSJHA3/OSBt4w4UPHKbTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

Attached in support request via Intercome

### Environment

```markdown
- FlutterFlow version: v4.1.75
- Platform:FlutterFlow builder
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I'm sorry you're experiencing this issue. I've confirmed that it is happening, but this GitHub Issue Tracker is intended for issues that can be replicated from a new blank project. This seems to be a very project-specific issue due to the size and complexity of your page and the number of widgets it contains.

I strongly recommend contacting support via the in-app chat or at support@flutterflow.io for this specific case. They have the right tools to see what's happening with your project and help you fix it.

Best regards,<br>Azanello
