### ISSUE TITLE
Test, run mode not working

### ISSUE THREAD

**Issue by ahnsunnyyoung** [FlutterFlow/flutterflow-issues#3470]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Everything seems loaded fine, but UI is not coming up. Tried several times of refresh and re-build.

Tried emulator and local run for edge and chrome, and it works. Also did released new version of the app with current code. But Test, run is just not working.

### Expected Behavior

UI should be shown after getting all loaded

### Steps to Reproduce

1. Click test
2. Wait test mode is loaded

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sj+fqw5d1rtdc+KqJK8BB/GAQJjt9bLsascp/bxIgGIDzPOw+ZPWkSFdCOMugd2xmJESmmmEF+tbsk/PQUfAqIQiCG9VMwodqUzmUZHGue5OBPLmzP3xtEcBhCh244KbYsRBCKth1SFoS2zu6HNiXXjfdNpzxImdISq/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/88d59947-0d08-4b2d-8080-ea102d021359)
![image](https://github.com/user-attachments/assets/9419e40d-112f-438c-a630-92a1b34365d7)

### Environment

```markdown
- FlutterFlow version: v4.1.75+
- Platform: Web
- Browser name and version: Chrome 126.0.6478.127
- Operating system and version affected: Window 11
```

**Comment by msusviela** [comment]
Hi @ahnsunnyyoung. Thank you for filling in. So sorry you're experiencing this issue. Our team is already working on a fix for this. I'm closing this issue because it's a duplicate of this: [https://github.com/FlutterFlow/flutterflow-issues/issues/3270](https://github.com/FlutterFlow/flutterflow-issues/issues/3270)

You can follow the original issue there.

**Comment by msusviela** [comment]
Hi! A fix for this has been deployed to production

**Comment by ahnsunnyyoung** [comment]
It's still same for our project...

**Comment by msusviela** [comment]
@ahnsunnyyoung, I'm sorry to hear that. Currently, this is a duplicate and the original issue is going through revision with the ENG team, would you mind commenting on it so they can check your particular case? Thanks!<br>[https://github.com/FlutterFlow/flutterflow-issues/issues/3270](https://github.com/FlutterFlow/flutterflow-issues/issues/3270)

**Comment by wenkaifan0720** [comment]
@ahnsunnyyoung. I can see some errors coming out of the `flutter_uxcam` package when testing locally with Flutter web. This package doesn't seem to support web. The UI does show up locally so I am not 100% certain it is the root cause. Could you try removing this package and see it the UI shows up? Or do you have another project which depends on this package and does work in test mode?

Alternatively, you can use local run to test your app, which also supports debug panel and should have better third party dependency compatibility.

**Comment by ahnsunnyyoung** [comment]
@wenkaifan0720  I did remove uxcam part, but it looks still same. I think it might also because package dependencies are not fully removed. I'll also check that if other project is running with uxcam or not. Thank you for fast response.

**Comment by ahnsunnyyoung** [comment]
@wenkaifan0720 
![image](https://github.com/user-attachments/assets/0b0aa84c-55f5-4ed3-b84b-06f20c8dedba)
Here's one example that using uxcam and web is working. In this case, I guess uxcam is not an issue... Can you check is there any other possibilities?

IT40j+fqw5d1rtdc+KX2dvpahjw5KWI/UII7lcFraCosfZT2BLMcec/RVERWTbDhTWw+emCkjWoW0M2Oi/PhA/VeEE6Ab6Z7/rp+aj3hQXGQRrXTFJWge2pDEcFMf3aB58PQ3BMkCNhiSX9l1zuUG+m8bHHsNLrLPm0CDq/LZO4=
This is bug report code for the other project (whichi is working fine).

**Comment by wenkaifan0720** [comment]
I removed the `initializeAppState` at the beginning of the main.dart file and can load the app in test mode. Could you try that and see if it works? And to actually use this function in main, I think you can try add it to the end of `main.dart`, after the AppState class has been instantiated.

**Comment by ahnsunnyyoung** [comment]
@wenkaifan0720 Amazing. I also checked that it is working after romoving `initializeAppState`. Will try to find where was exact issue. Thank you so much!

**Comment by ahnsunnyyoung** [comment]
@wenkaifan0720 Amazing. I also checked that it is working after romoving `initializeAppState`. Will try to find where was exact issue. Thank you so much!
