### ISSUE TITLE
"Failed to compute merge conflicts" 

### ISSUE THREAD

**Issue by mubarismubi** [FlutterFlow/flutterflow-issues#3477]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am unable to merge any of my branches into Main . When I try to merge or rebase , it says setting up merge and  followed by a red error message saying, "Cannot compute merge conflicts."

### Expected Behavior

expected to view merge window , that shows conflicts or merge/ abort .

### Steps to Reproduce

1. go to mubaris_visibilitySetting branch 
2. try to merge/ rebase. 
3. after the setting up merge , it shows "Cannot compute merge conflicts." on red 
![Screenshot (169)](https://github.com/user-attachments/assets/9cebe1dd-9329-4420-bf7d-b94f4375764f)
 alert below

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iPGCx7thoctI4rrMdu1umhY4NWl+XeVMptVBaCgofePtOol3evWkS1hWZNCoSlZ5MESmmnEz+NqKjoTTLvkoIQ+dbLY9yc9qQwvwWl+WQZOBBbi0S2pAO+dYCkyf5KbZ2RElWLJfR0Y5606UNeeXSnLvJLrWImdISq/LZO4=

### Visual documentation

![Screenshot (169)](https://github.com/user-attachments/assets/e404740a-84ae-43d6-a555-f35a75d69675)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

I have been facing this issue for a while.

**Comment by msusviela** [comment]
Hey @mubarismubi, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: [support@flutterflow.io](mailto:support@flutterflow.io) or using the in-app chat inside of FlutterFlow. I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. Thanks so much!

**Comment by leighajarett** [comment]
Oh no! So sorry you are experiencing this - we are taking a look

**Comment by mubarismubi** [comment]
Resolved @leighajarett
