### ISSUE TITLE
Cursor TextField going below typing line in web

### ISSUE THREAD

**Issue by AlessioGarofalo** [FlutterFlow/flutterflow-issues#3524]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When in an TextField you configure Max Lines parameter to be >1 or leave it empty. Once you deploy on Web this textfield provide an incorrect behavior with the cursor dropping to the beginning of the second line and the text on top of it in the first line. This behavior happens only if you are writing character and not with numbers. The same is also happening for search box inside a dropdown. 

### Expected Behavior

The cursor should remain at the end of the sentence all the time without jumping up and down. Please note the no OnChange actions are configured. 

### Steps to Reproduce

1) create a new page
2) add a text field 
3) configure autofocus and Max Lines 3 
4) deploy on web
5) try to write in the text box, the cursor should drop below 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESyfHq25dgot8B1pDQbsBqhQMjNlx7bZAnktV+WRMhfJ+vOuwuOcz7SElLYtendAtmfVWjnXEywejrjvOeEMEoJTWsG5RPyK5XQQriRnGtVbKRPKjpPUBBL/9XIUzC4KSrryRCOtpvcXwN3zuyIvCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![Screenshot_20240731_153751_Samsung Internet](https://github.com/user-attachments/assets/1d975e08-3ce2-4471-b979-9dd242277192)

### Environment

```markdown
- FlutterFlow version: v4.1.79+ released July 30, 2024 Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Samsung Internet 26.0.1.3
- Operating system and version affected: Android 14 UI 6.1
```

**Comment by rzambroni** [comment]
Hey @AlessioGarofalo, i was not able to replicate the issue you are describing on a blank project with the provided steps. I was also checking yours to see if there were any differences on the config of the textfields (like the onChange action) but i don't see the action or the max lines configured. 

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/98c2ff1a-3b2e-4fa1-9f77-a7a9b4eb74ff/5bc63008-c901-4b70-8e8e-e1f11cfcc15a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85OGMyZmYxYS0zYjJlLTRmYTEtOWY3Ny1hN2E5YjRlYjc0ZmYvNWJjNjMwMDgtYzkwMS00YjcwLThlOGUtZTFmMTFjZmNjMTVhIiwiaWF0IjoxNzIyNDU2MjgzLCJleHAiOjMzMjkzMDE2MjgzfQ.vCZ7rNgGmvwhUXpPDsgprj7WIKe-oQYv9tWUPB5ZQtU " alt="image.png" width="1092" height="957" />

[screen-20240731-165906.mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7a994deb-10e9-4c9e-807b-cd9f1079fe3a/9e4dc5f1-a610-462f-845a-1a84a05f023d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83YTk5NGRlYi0xMGU5LTRjOWUtODA3Yi1jZDlmMTA3OWZlM2EvOWU0ZGM1ZjEtYTYxMC00NjJmLTg0NWEtMWE4NGEwNWYwMjNkIiwiaWF0IjoxNzIyNDU2MjgzLCJleHAiOjMzMjkzMDE2MjgzfQ.jRFqEsSoymNPOuq_3f4hSt2kVRUSnnE81Zl4AdaQMTk)

Would you mind creating a quick blank project where this bug is replicable? I'm suspecting this might be OS/Device related. 

Thanks!

**Comment by AlessioGarofalo** [comment]
@rzambroni Can you please show me the textfield configuration tab you have? Do you have a max line configured? Try to put max lines 3.

Alessio
________________________________

**Comment by AlessioGarofalo** [comment]
![image](https://github.com/user-attachments/assets/bf16df2a-68b4-4df3-877f-7b2ef05184cc)

**Comment by AlessioGarofalo** [comment]
The same behavior I get it also from search on dropdown but there I don't have any setting I can modify. See this video.
https://github.com/user-attachments/assets/55948fde-a983-445b-a956-738c5964f679

**Comment by rzambroni** [comment]
@AlessioGarofalo, i have the same settings on the textfield.

There might be something else in your project that could be affecting the widget, we need to find out what it is, is this issue replicable in a blank project for you?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c2fc91e3-10cc-4e87-85bf-26d5efc50d6a/df281bcc-0efe-45d8-ab68-b503929fb3f1?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMmZjOTFlMy0xMGNjLTRlODctODViZi0yNmQ1ZWZjNTBkNmEvZGYyODFiY2MtMGVmZS00NWQ4LWFiNjgtYjUwMzkyOWZiM2YxIiwiaWF0IjoxNzIyNTI3MjE1LCJleHAiOjMzMjkzMDg3MjE1fQ.qUIpyuzDTscmbtlF3TJsGuckFE4oTamo9aQVeDfKYTU " alt="image.png" width="308" height="205" />

**Comment by AlessioGarofalo** [comment]
@rzambroni yes same behavior both for the TextField and the search in Dropdown is replicable in a empty project where we have only the text field and the drop down. See the video here. 

https://github.com/user-attachments/assets/63c01fc1-82e7-473f-983b-004220cb9fea

**Comment by rzambroni** [comment]
Could you please share the bug report of that empty project?  thanks in advance!

**Comment by AlessioGarofalo** [comment]
@rzambroni here you are the bug report on the empty project: IT4oz/Hqx89grs9J1s/IdfoxnSQQNmE1ROcJlspBZywgfZzzBLN/fPfQPxFBTsjhYWx+JE2mp14Kp9bUjeHfJsBeCy2dGal8+pByUgzJeH+nM5OTF7iKSUYlM8FgBWK44auNvhIkJtteV3g93FOEI+vKE3PZNpjJNWo8Sq/LZO4=

**Comment by rzambroni** [comment]
I just gave it a try on my own device, and the exact same project works as expected (see video). That's why I suspect it might be specific to some devices or configurations.

I'm using Android 14 on a Google Pixel 8 Pro. I will ask other team members to test it on their devices to see if we can identify a pattern or the specific cause of the issue. I'll keep you updated with our findings.

If you happen to find out more info pleas let us know!

[screen-20240801-144931.mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f3f2bcb3-8b17-436a-9332-05e2deeb7f37/774cef1e-b53f-4c53-b734-0efa6796e510?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mM2YyYmNiMy04YjE3LTQzNmEtOTMzMi0wNWUyZGVlYjdmMzcvNzc0Y2VmMWUtYjUzZi00YzUzLWI3MzQtMGVmYTY3OTZlNTEwIiwiaWF0IjoxNzIyNTM1ODIxLCJleHAiOjMzMjkzMDk1ODIxfQ.t1khYJKXjF09W_w_V868tIKL7TQQOPb4C5uqVRTqhP0)

**Comment by AlessioGarofalo** [comment]
@rzambroni I have also android 14 but on Samsung flip 5. Please note that I have also tried the same on a Samsung S23 and same issue persit also there. You have tried web app deployment right? Just to check I have pwa active.

**Comment by rzambroni** [comment]
Yes, I'm testing on the same web app that you are. It might be a Samsung-specific issue. I'll try to find a similar device to the ones you mentioned.

What browser are you using?

**Comment by AlessioGarofalo** [comment]
@rzambroni I have tried both on Samsung Internet and Google Chrome. Same error for both widgets

**Comment by rzambroni** [comment]
Hi @AlessioGarofalo, we tested on several Android devices, including Samsung, Motorola and Pixel devices. We were, unfortunately, unable to replicate the issue.

Can you confirm if you see the issue while browsing:[ https://testproject1234.flutterflow.app](https://testproject1234.flutterflow.app) 

That's the URL generated by the web deployment on the blank app you shared but wanted to be sure we are browsing the exact same url.

**Comment by AlessioGarofalo** [comment]
@rzambroni yes I confirm that I have the same issue from the link you sent. Here a video.

https://github.com/user-attachments/assets/29c580b9-0a5f-46ec-b76a-c5f4cb62c714

**Comment by rzambroni** [comment]
Thank you for your patience, and I apologize for the delay in getting back to you. We tried to replicate the issue across different devices and operating systems but, unfortunately, we weren't able to reproduce it. It seems this might be specific to your device, browser version, or some other unique factor.

Given that we couldn't replicate the problem and it doesn't seem to be affecting a wider audience, we'll go ahead and close the issue for now. However, if you come across any additional details that could help us troubleshoot further, please don’t hesitate to reach out. We're here to help.

Thanks again for your understanding.
