### ISSUE TITLE
Appstate change Issue

### ISSUE THREAD

**Issue by KavyaDevv** [FlutterFlow/flutterflow-issues#3527]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The problem is that whenever status of a appstate is modified, it automatically causes all the items in list status of the other app state to change as well. It appears that each item in MissionStatusList is linked to currentMissionStatus instead of containing its own value.

### Expected Behavior

The update of the item should not change the other app state

### Steps to Reproduce

1. There is an app state called currentMissionStatus which is initially assigned the value of another app state known as initialMissionStatus.
2. Whenever the interface is modified, it also updates the current mission status. Each time this happens, I include the current mission status in the Mission Status List.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ez/Hqx89Nobhe+KryacFvniAXHGk7aI0zmOt+dAw3fIutPZkhO+j+QHZVOMO/dFY3OlmI8Xkz0NbJvYfPCMY9PiirQbpFyKlyQwnwWl6QMqqvDqiKQERtGfFjfUuHzbbYrBV/ANBZc0Us2F73Gd6sTgHBNJjxPG0vJsqLMZDIng7mASLKXn0Jg1ZSfCvr

### Visual documentation

https://github.com/user-attachments/assets/8bcc58ae-5b9f-4a22-aaba-ac85cbc3080b

### Environment

```markdown
- FlutterFlow version:v4.1.79+ released July 30, 2024 
- Platform:
- Browser name and version: Version 127.0.6533.73 (Official Build) (64-bit)
- Operating system and version affected:
```

**Comment by msusviela** [comment]
Hi @KavyaDevv, thanks for submitting the issue! I'll send it to ENG so they can work on this.

**Comment by AnushaFF** [comment]
Hi,
I apologize for the inconvenience you're facing with this issue. Unfortunately, at this time, we only support assigning app state variables with custom data types through reference. This means that the variables will stay in sync. As a temporary workaround, you might consider one of the following options:

- Use "To Json" in the available options after updating the app states and then convert it back to the required datatype
<img width="640" alt="Screenshot 2024-08-08 at 1 02 51 PM" src="https://github.com/user-attachments/assets/88491a72-580e-4665-84d6-859e997892fc">

- Alternatively, you can create an appState variable as a List<Coloring> directly, instead of using a custom datatype Drawing to define a List<Coloring>.

We understand this isn't ideal, and we have a feature request in our pipeline to allow easier copying of data types. Until that feature is available, we hope these workarounds help in the meantime.

**Comment by kaymasse** [comment]
Hi @AnushaFF, thank you for your answer 🙏 The first workaround you propose (converting to JSON and back to original datatype) works well for me 💛

I would like to mention that I find the behaviour confusing but also very difficult to debug/pinpoint, which may cause others to struggle with it too. It may be worth documenting the fact that FlutterFlow only support assigning app state variables with custom data types through reference, and propose the workaround you suggested to me.

**Comment by MattWillen** [comment]
I almost went crazy trying to figure out the issue. Luckily I found this workaround (I didn't test it yet, might come back for help).
Happy to see the devs noticed it, a little less happy noticing 6 months went by and we still have the same issue :/
