### ISSUE TITLE
Web app doesnt work

### ISSUE THREAD

**Issue by bmw559** [FlutterFlow/flutterflow-issues#3528]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Since the last update on June 26, 2024, my web application has stopped working. The web app published through FlutterFlow no longer functions, and even when I download the code and try to deploy it on my custom domain, it still doesn't work. The application doesn't load and only displays a white screen. In the console log, I see this error. I'm attaching a screenshot for reference.

Feel free to attach the screenshot and let me know if you need any further assistance!

### Expected Behavior

App should be initialized and loaded properly

### Steps to Reproduce

1. Publish web app
2. Try to access it 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4oi+fl/otItbxc0KXyb8BFmSQvJnp+RLhMkcpBZywgfZzzBLN/fPfQP1BvTcOlT0FIOGacp14GwsGPjoThGMICaBeafap5yLlTWBXLfHu6VbGTF7rpS3FBI+1WJ2qd1reJhBIkIul1cXwW112IfvPLSj7YNYzPDGowSq/LZO4=

### Visual documentation

![WebAppDoesntWork](https://github.com/user-attachments/assets/dccfbb50-3891-4056-b0bf-c7b4afeb0052)

### Environment

```markdown
- FlutterFlow version: Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Chrome,Safari,Edge
- Operating system and version affected: Windows
```

**Comment by Alezanello** [comment]
Hello!

This issue seems to be very specific to your actions and packages within your project. I tried to run it locally, and the permission handler was causing problems. I commented it out to run without the `requestPermission` from the `main.dart`, and then it threw an error about the rendering box of the login.

You will need to download the code to VS Code and debug it to identify which of your custom actions/widgets is causing this issue.

Remember that FlutterFlow updated to Flutter version 3.22.2 on June 25th (see [FlutterFlow Update - June 25, 2024](https://community.flutterflow.io/c/whats-new-in-flutterflow/post/what-s-new-in-flutterflow-june-25-2024-MNd3u70ipLLlMKa)), so it seems that some packages in your project might be outdated for the latest Flutter version.

Best regards,<br>Azanello

**Comment by bmw559** [comment]
> Hello!
> 
> This issue seems to be very specific to your actions and packages within your project. I tried to run it locally, and the permission handler was causing problems. I commented it out to run without the `requestPermission` from the `main.dart`, and then it threw an error about the rendering box of the login.
> 
> You will need to download the code to VS Code and debug it to identify which of your custom actions/widgets is causing this issue.
> 
> Remember that FlutterFlow updated to Flutter version 3.22.2 on June 25th (see [FlutterFlow Update - June 25, 2024](https://community.flutterflow.io/c/whats-new-in-flutterflow/post/what-s-new-in-flutterflow-june-25-2024-MNd3u70ipLLlMKa)), so it seems that some packages in your project might be outdated for the latest Flutter version.
> 
> Best regards,Azanello

Hey thanks for feedback will try to start with the custom actions then.

**Comment by bmw559** [comment]
Solved thanks guys

**Comment by Alezanello** [comment]
I'm glad this worked for you! If you encounter any other issues or bugs, please feel free to create a new issue.

Best regards,<br>Azanello
