### ISSUE TITLE
DataTables max items -> stops loading in after around 11250 objects

### ISSUE THREAD

**Issue by Alpay8** [FlutterFlow/flutterflow-issues#3536]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If my JSON - API response ( which will be data for a paginated DataTable ) has more than 11150 objects, the DataTable does not show anything, although the data is loaded through to the page ( Network tab loads )

### Expected Behavior

All Data to load in correctly

### Steps to Reproduce

1. Create support for bigger payloads for DataTables

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4KlfLcxIt1xdtK0LqBbe9V/TgWMjt+RYIWlu5tbwwaJYutG7YyXvTBYlJuZ8PidGxcDFqWmmMG097WvvPxBMI7C0ytbNw6/pN5Qx7gez+iVYybPbqCQn8kO59gC2bG36uFnSZdLfVwd2wM3U2MHdytcz3tGOPFNlckR/iaLrrO+0qbHQ3zFhFtzRQ+IWaZTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

Empty DataTable

### Environment

```markdown
- FlutterFlow version: 4.1.79
- Platform: Web
- Browser name and version: edge
- Operating system and version affected: all our OS, mac and windows
```

**Comment by Alezanello** [comment]
Hello!

Due to the heavy load, I don't have any API to test this assumption about the number of items causing the issue. However, I noticed that you are saving the item returned from the API to a PageState and generating the DataTable from that PageState.

Have you tried generating the children of the DataTable directly from your API response?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c52d11d2-3d57-4c58-b7c0-b1c60edd4f64/9498aaac-bd3f-439a-940b-f9e6a47484f5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jNTJkMTFkMi0zZDU3LTRjNTgtYjdjMC1iMWM2MGVkZDRmNjQvOTQ5OGFhYWMtYmQzZi00MzlhLTk0MGItZjllNmE0NzQ4NGY1IiwiaWF0IjoxNzIyNjA4NzI4LCJleHAiOjMzMjkzMTY4NzI4fQ.0sjANjjPiKXOXfJe7zpESuImKNrXh17E3dQLyLK5pgE " alt="image.png" width="580" height="657" />

<br>Let me know if this works correctly for you<br>Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
