### ISSUE TITLE
Data Table: crash in FlutterFlow internal code

### ISSUE THREAD

**Issue by bloemy7** [FlutterFlow/flutterflow-issues#3537]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using a data table, we are seeing a lot of remote reports of crashes coming in.
Attaching the crash log here.
The main crash is here:
```flutter_flow_data_table.dart - Line 217
_FlutterFlowDataTableState.initState.<fn> + 217
```

which triggers a crash in:
```
framework.dart - Line 1223
State.setState + 1223
```

All of this code is completely out of our control. Can the FF team investigate this please?
[crash_session_463c71a90c72485bacd983322cbfe4b5_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16472352/crash_session_463c71a90c72485bacd983322cbfe4b5_DNE_0_v2_stacktrace.txt)

### Expected Behavior

No crashes when using the Data Table.

### Steps to Reproduce

1. Add a Data Table
2. Observe remote crashes

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelcmB05NItb0E+YfyL8dvqwMyQEgnU+cRl9ZxcxQjCoj2OpkAWvTBTFFWXLy9THx9eWCaiTgJ7Pfqudj1EsY7BAWbbqJjz7pybgv/Wn+neJirDbq7fW1RL+FVChCB3KSCkR55LttqdUVhwV77JPDKc3PaNo/7IFYzJf61KdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="1212" alt="Screenshot 2024-08-02 at 8 28 00 AM" src="https://github.com/user-attachments/assets/34ac3e70-eb22-46a3-97f6-47770e858ea1">

### Environment

```markdown
- FlutterFlow version: v.4.1.79+
- Platform: iOS & Android
```

**Comment by bloemy7** [comment]
```
controller.addListener(() => setState(() {}));
```

this line in `flutter_flow_data_table` line 217 is the issue.
This needs to check if the component is still mounted.
It never removes the listener when we unmount/dispose, so that should be the main fix.
But another fix is:

```
controller.addListener(() {
  if (mounted) {
    setState(() {});
  }
});
```

Please fix this.

**Comment by JulianMarc1** [comment]
This issue extends beyond just tables; it involves numerous errors triggered by attempting to set the state when the widget is no longer mounted.
You might say that it is our responsibility to avoid changing the component state after it has been unmounted. However, in a lot of cases we cant do that because many of these set states are initiated by Flutterflow code.
Flutterflow utilizes a flag called \_shouldSetState, which can sometimes be triggered via the UI by selecting the "updatePage"/"updateComponent" or other similar options. However, there are instances where this flag is automatically set to true.
Example:
When creating a document in Firestore, there is no need to update the page since the document creation does not result in any visual changes for the user. In this example, the action is triggered when a user clicks "yes" on a modal.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/338f63c2-4315-440a-87bc-4e9de2a6d1b3/865f9c61-ed99-4118-b0e7-ed5f1815fd26?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8zMzhmNjNjMi00MzE1LTQ0MGEtODdiYy00ZTlkZTJhNmQxYjMvODY1ZjljNjEtZWQ5OS00MTE4LWIwZTctZWQ1ZjE4MTVmZDI2IiwiaWF0IjoxNzIyODcwMTY4LCJleHAiOjMzMjkzNDMwMTY4fQ.m4GbvH9McPEcl2U9k_E54PLz4bs8kkl0RXNS1qB-wjc)

After the document is created, the modal closes. Despite not needing to change the component state, Flutterflow sets _shouldSetState to true:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c0065a99-c5b7-4560-8519-26c594627806/9f69b005-d3fa-4ef9-85be-ccef7859b3e0?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMDA2NWE5OS1jNWI3LTQ1NjAtODUxOS0yNmM1OTQ2Mjc4MDYvOWY2OWIwMDUtZDNmYS00ZWY5LTg1YmUtY2NlZjc4NTliM2UwIiwiaWF0IjoxNzIyODcwMTY4LCJleHAiOjMzMjkzNDMwMTY4fQ.WRi61NFuBAhQC1jYvJo1SL8Y12vyVh_jhD-zrB4KBRA)

This leads to a setState call that serves no purpose, especially since the modal has already been closed.

In many cases, a chain action might end with navigation to another page. Even if there are no app or component state changes within that chain action and the updatePage option is not enabled, Flutterflow sets \_shouldSetState to true. This results in a setState call (usually after the navigate action has concluded, meaning the widget is no longer mounted), generating an error.

These errors, while not always visible to the user, clutter our error reports (we use Sentry) and make debugging more difficult. Additionally, this impacts performance.

Making sure that no action calls the set state unnecessarily is the best option, but, as we do not have full control over the code generated by flutterflow, maybe encapsulating the setState with a check to see if the widget is mounted would be a good alternative:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/aca26660-d09c-4d63-8e18-1bdc84fd8dd1/c0b361ef-61a7-4245-abd5-4be5e9febce9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hY2EyNjY2MC1kMDljLTRkNjMtOGUxOC0xYmRjODRmZDhkZDEvYzBiMzYxZWYtNjFhNy00MjQ1LWFiZDUtNGJlNWU5ZmViY2U5IiwiaWF0IjoxNzIyODcwMTY4LCJleHAiOjMzMjkzNDMwMTY4fQ.WPMa8yP6o9e_-gaKWE1f0dhAV_mHE90NzsVE36a1nHw)

I've seem you already use a similar approach in other parts of the code:

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/c37e99b5-7976-4d71-8523-cf9d9206334b/2abbe491-2760-4d4d-aef2-4b1d1f3835ca?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jMzdlOTliNS03OTc2LTRkNzEtODUyMy1jZjlkOTIwNjMzNGIvMmFiYmU0OTEtMjc2MC00ZDRkLWFlZjItNGIxZDFmMzgzNWNhIiwiaWF0IjoxNzIyODcwMTY4LCJleHAiOjMzMjkzNDMwMTY4fQ.cWdH_FkOXRQTnkEwVIaBt0_v96RI-1y0Pmo_fbjh-1E)

**Comment by Alezanello** [comment]
Hello @bloemy7 & @JulianMarc1 !

Thank you so much for bringing this to our attention and providing a well-documented explanation of why this is happening and a possible way to fix it. I will ask the engineering team to take a deeper look into this case so they can double-check it and find a proper solution.

Best regards,
Azanello
