### ISSUE TITLE
Several copies of SQLlite in folders not all get updated

### ISSUE THREAD

**Issue by adominicci** [FlutterFlow/flutterflow-issues#3538]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Each time I do a change to my SQLlite db structure it doesn't "carry over" the simulators or when deploying the app.  I have to look for the database in the folders and there are dozens. I have to open one by one to find the current one or add a bogus command in the first SQL statement so it throws an error and I can get to the actual path.  

Sometimes removing the db asset and uploading the right one works or sometimes you have to overwrite all the different db's so they all worked in all the possible scenarios.

### Expected Behavior

If there's a change in the current SQLlite database it should be carried over to any other folders in the projects.

### Steps to Reproduce

1.  Create SQLlite db, upload it.
2. Run in simulator and on the phone simulation.
3. Change any table, view or field. 
4. Run again all the different simulators
5. Debugger will crash because it can find the object added

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4OlMjf5c12rsRE1qqBcsdVtDw5Jj8jbaxMiO19e0k0F7XNG7UIec/4VEptXbC+TVc3MGCZmTsfzNaPkszIN/JcC06Zc6JBzrpuSgLMIT+WaLK0BYeSQUQnTdpKC0DF5KSNrCR7AO1pSCEO6l+qINyRFy3cJ5ewPWw4Rc+HNpn5s3PuQ0SLb3kNh1JWeC/v

### Visual documentation

Don't have one available now. 

### Environment

```markdown
- FlutterFlow version: 4.1.79
- Platform:Mac
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

I just checked your project and there is only one SQLite database. If the database name is different from the previous one you had, it might download the new one locally but doesn't delete the older ones created before. However, this only happens locally.

What I recommend is to remove the old database from the `assets/sqlite` folder because the app will only use the latest one.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/a174e62a-8405-4af6-8007-cefffb886edd/fd7b7513-380f-4e5e-a36d-2e25936a8c42?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hMTc0ZTYyYS04NDA1LTRhZjYtODAwNy1jZWZmZmI4ODZlZGQvZmQ3Yjc1MTMtMzgwZi00ZTVlLWEzNmQtMmUyNTkzNmE4YzQyIiwiaWF0IjoxNzIyNjE1OTM4LCJleHAiOjMzMjkzMTc1OTM4fQ.dZyuDxh7D-RuFgjhUfw5g8RNXyxE1Ebo9jVIgj2eJU4 " alt="image.png" width="193" height="58" />

Best regards,<br>Azanello

**Comment by adominicci** [comment]
So I proceeded to do that and indeed it loaded again when I ran the iPad simulator. I see all my data. For testing purposes opened the db from `assets/sqlite` as instructed and deleted all the data. 

I can still see the data in the simulator although I have no data in the db located in assets.  Why does it keep different dbs locally and does that affect when deploying?

**Comment by adominicci** [comment]
Update*** proceeded to create a new build and I still see the old data in the app with TestFlight. So there's something going on there. I deleted all the records from the 'assets/sqlite' it should had sent the updated sqlite db to App Store Connect.

**Comment by Alezanello** [comment]
The `assets/sqlite` folder is just for testing locally. To ensure new apps find the latest SQLite database, I recommend changing the name of the database and uploading it. This way, the next time the app compiles, it will trigger the latest named database instead of always using the same one.

**Comment by adominicci** [comment]
Do you mean the actual name of the sqlite database or the database file name and upload it again or the database name to the left of the file in FF?

![image](https://github.com/user-attachments/assets/c162123a-e5dc-4537-a5bf-7dcc05e728e7)

Which one?

**Comment by Alezanello** [comment]
Try changing both names, so the new compiled app will override the old db that was downloaded in the app assets

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
