### ISSUE TITLE
Translation are dissappearing

### ISSUE THREAD

**Issue by celiostat** [FlutterFlow/flutterflow-issues#3549]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

It happens a lot recently  : when using the translation built-in capability, they will not autosave. I have to reiterate several time to input again the translations before it is actually picked up. This morning, some of the translation of the app that I haven't been changing for months have dissappeared in secondary language.

### Expected Behavior

Translation disappear without reason

### Steps to Reproduce

1. Open app 
2. Translation disappeared

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXi/Lqw5VIrsBE7arhKe1anj8wFjsaU40V0tcbbAEjIuP1BLQuPer+V1tYYbXjYFBmBE6YrDgBpq31kvGeLfEBEE+uQoNozrhITgzybEmXMbqOPcyCQHZRL/xRJmqb06WzriVBAPFYLnw7w1r/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/user-attachments/assets/f43d24c3-3479-4a14-94c6-8525057fa050)

### Environment

```markdown
- FlutterFlow version: V4.1.80
- Platform: Windows FF app
- Browser name and version: Version 127.0.6533.89 (Official Build) (64 bits)
- Operating system and version affected: Windows 11
```

**Comment by shodan78** [comment]
It happened to me with the Text widget. The problem seems to occur mostly when copying the text with copy and paste from other sources (in my case Google Translate) while the text is correctly inserted or modified most of the time when writing directly.
No problem if the change is made from Settings --> Languages
Browser used Chrome Version 127.0.6533.89 (64 bit)

**Comment by msusviela** [comment]
Hi @cellostat. So sorry you're experiencing this issue. I'm closing this issue since it's a duplicate of [https://github.com/FlutterFlow/flutterflow-issues/issues/2346](https://github.com/FlutterFlow/flutterflow-issues/issues/2346)<br><br>You can follow up the issue in the related GitHub issue.<br><br>Thanks!

**Comment by msusviela** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by celiostat** [comment]
Hi team, still facing the issue, but you did mention there was another issue opened : [https://github.com/FlutterFlow/flutterflow-issues/issues/2346](https://github.com/FlutterFlow/flutterflow-issues/issues/2346)
