### ISSUE TITLE
Multiple broken "Docs" links

### ISSUE THREAD

**Issue by BottaBazaar** [FlutterFlow/flutterflow-issues#3552]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Under subsections of settings (such as "Mobile Deployment"), there are buttons for "Tutorial" and "Docs". The buttons for "Docs" is a broken/dead link so I can't review the documentation for each section. This is true for the "Firebase" subsection as well. 
Here is an example of a link that is dead: https://docs.flutterflow.io/data-and-backend/firebase/firestore-database/storage-rules

### Expected Behavior

The relevant document should open. 

### Steps to Reproduce

click: settings
click: mobile deployment
under "google play store" click "Docs"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40hcr15YpJpbwA15D+c8Iwmik5JmY9aJInlMBraCosfZT2BLMcec/RVERCUt+lTFY/Pk6jgWoW0vvFiePTU/A5GAeeGK5/zqVxWA/MQlm5MrHSFJWvdHd8GphQG0iY16Wjsx4mJfhuWFI/2mb7JuiAdB7XHYzwIW4SD6/LZO4=

### Visual documentation

![Screenshot 2024-08-04 170214](https://github.com/user-attachments/assets/1ab108a1-1989-4744-ac2e-cf729d4e801d)

### Environment

```markdown
- FlutterFlow version: 4.1.8
- Platform:windows desktop
- Browser name and version:
- Operating system and version affected:
```

**Comment by Luigibro26** [comment]
Yeah, I've noticed this quite a bit while looking through the flutterflow docs.

Like the entire CheckboxListTile widget or any of its subpages don't link to any page at all and just auto link to the home page.

Examples:
[https://docs.flutterflow.io/widgets-and-components/widgets/base-elements/checkboxlisttile](https://docs.flutterflow.io/widgets-and-components/widgets/base-elements/checkboxlisttile)
[https://docs.flutterflow.io/#add-a-checkboxlisttile-to-your-project](https://docs.flutterflow.io/#add-a-checkboxlisttile-to-your-project)

Despite once being an active page
![image](https://github.com/user-attachments/assets/78a11361-9db5-4c32-9386-7c06724ed1b8)

**Comment by msusviela** [comment]
Thanks for the report! I'll send it to FlutterFlow's team so they can work on this.

**Comment by ryutosh** [comment]
@msusviela
I mention it here because it is relevant to this issue.

After the renewal of doc site, all descriptions regarding FlutterFlow actions seem to have disappeared.

![image](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/80d38e18-ddfc-48cc-b70a-ec7f5d4777dd/d4b25484-e51d-4794-ad36-31ec0cab6ef7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MGQzOGUxOC1kZGZjLTQ4Y2MtYjcwYS1lYzdmNWQ0Nzc3ZGQvZDRiMjU0ODQtZTUxZC00Nzk0LWFkMzYtMzFlYzBjYWI2ZWY3IiwiaWF0IjoxNzIyODYxMjg4LCJleHAiOjMzMjkzNDIxMjg4fQ.fZZapahPNcsW_qVLX6iOeeAuT0L7bS0vWNJCbe_c0W4)

I noticed it was missing because I was referring to "Upload Media" but there may be others missing.
It would be very helpful if you could also publish the old version of the documentation site in the interim while you review it.

**Comment by PoojaB26** [comment]
We are looking at the broken links issue but @msusviela, Actions are available under "Control Flow > Functions" or a quick search (from the top right) should take you there. And can you check for upload data now? You should see Upload media or Upload File content too. Again, you can either search for this keyword or look for it under Building Concepts > File Handling.

**Comment by PoojaB26** [comment]
Regarding broken links, some of the old docs to new doc redirections are now fixed. Additionally it also needs some changes to be deployed from the product side, so docs links from the product redirect to correct page. That may be deployed in the next release! Any other missing widgets, we are looking into that. But other fundamental topics like Actions, File Handling mentioned in this thread, are already available in the new docs.
