### ISSUE TITLE
Missing Ability to compile code with custom packages on the desktop application.

### ISSUE THREAD

**Issue by jdspeyer** [FlutterFlow/flutterflow-issues#3587]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The desktop application does not allow you to compile custom code/ widgets that utilize pub.dev packages (or anything imported from your pubspec.yaml file from what I have seen). I have had to resort to a really odd workflow of writing my code in the desktop application, compiling it in the web application, and then going back to the desktop application to deploy to my local device.

Maybe I am missing something, but I feel like the desktop application should be able to compile custom pub.dev packages.

### Expected Behavior

Both the desktop application and web application should be able to compile custom code which imports external packages. Not just the web application. 

### Steps to Reproduce

1. Open custom code tab in new or existing project within the desktop application.
2. Click "+ Add Dependency" 
3. Observe the text that states "Custom code with pubspec dependencies will not compile on desktop. Open in web app to compile."

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5fksn6389IsdtJ+KriasExryQvKWI4U403ku1+dw0dB5fqEYYuOs/8UFdJYsOGdwlIJFmj8XgK0qDFvoaTFe44OQuAaYNewpFIczrKQnmgbpTSCqW7PWh9O+hMfWKCy6SsmA9TPbNhLFYs3EOUPPOATh/DQr7BNm4zB8+kKpz/jEK7HQ/NMxR7wmNecCfn

### Visual documentation

![Screenshot 2024-08-08 at 8 14 47 AM](https://github.com/user-attachments/assets/3ef42ff8-8f18-4067-8497-df7c11fb94dd)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.78 released August 8, 2024
- Platform: MacOS Desktop
- Operating system and version affected: MacOS Sonoma 14.5
```

**Comment by Alezanello** [comment]
Hello!

I understand that it can be frustrating to add dependencies via the web while working on the desktop application. Our desktop apps are currently in a preview phase, with significant improvements planned. As indicated by the label, this feature isn't yet available on the desktop app, and it’s a known limitation rather than a bug. I'll go ahead and mark this as a feature/enhancement request for the engineering team.

We appreciate your patience as we continue to enhance the platform and make it the best it can be!

Best regards,<br>Azanello
