### ISSUE TITLE
Error debug serializing parameter: Stack Overflow

### ISSUE THREAD

**Issue by bitgandtter** [FlutterFlow/flutterflow-issues#3589]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm trying to run the app on the browser. on the console, we got

Error debug serializing parameter: Stack Overflow. Dauthands of errors, even crashing the browser

### Expected Behavior

been able to run the app

### Steps to Reproduce

run my project

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ghcnfsM5ItbwG1s+Nde9VuykQKUw5bYc0sNobbxAjIoDoPJkUacnRUFBtTebmd1FbKEWKnXwe0fCMvfH1L/Q7AxWVb7pEzKpMUxXiYEK/aoSuBqmSRER5BcFmfm6A08CnpBZ+XPVfR3hl612qftmWTh/AQJv7Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/85c471d9-8ec4-40f9-8c9f-d3cf99aab8e7

### Environment

```markdown
- FlutterFlow version: v4.1.81+
- Platform:
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

**Comment by Alezanello** [comment]
Hello!!

Could you provide a test email and password so I can log in and observe the behavior on that page?

Best regards,<br>Azanello

**Comment by bitgandtter** [comment]
Not sure of got your ask @Alezanello credentials for which page?

**Comment by Alezanello** [comment]
As you demonstrated in the video, the issue is on the Introduction Page. I planned to run the project to observe the behavior directly, but I need to authenticate to access the Introduction Page. Do you have any test credentials available, or should I create one myself?

**Comment by bitgandtter** [comment]
its not actual on the introduction page. it basically the startup page, loading the app. there is no need for credentials. the app does not even load

**Comment by Alezanello** [comment]
Sorry, I initially thought the issue was on the next page based on your video. After running it locally, it seems the problem lies within your `FbAppCheck` Custom Action. I commented it out locally in the `main.dart`, and everything runs smoothly.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/4a5e957a-59cd-4cb5-b536-a1f4a14eaa64/89c925a8-8626-4ea5-b36f-8c402a015d24?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80YTVlOTU3YS01OWNkLTRjYjUtYjUzNi1hMWY0YTE0ZWFhNjQvODljOTI1YTgtODYyNi00ZWE1LWIzNmYtOGM0MDJhMDE1ZDI0IiwiaWF0IjoxNzIzMjM3MzI3LCJleHAiOjMzMjkzNzk3MzI3fQ.xWJm_3yuKiX-9LDAKHy21SaN6-6j_DPwFcXM5H1e4Xk " alt="image.png" width="1420" height="995" />

Best regards,<br>Azanello

**Comment by bitgandtter** [comment]
i will try. but that said that function have been working before. the only requirement is to set the FF debug token on firebase app check

**Comment by bitgandtter** [comment]
just to be on the same page, I'm trying to run the app on FF web and it still fails even after I have removed the code for that function. Locally the app works as expected

**Comment by Alezanello** [comment]
Did you remove the function from the main.dart and when deployed via Web Publishing it fails to publish or did it publish correctly but when you open the URL it doesn't load anything?

**Comment by bitgandtter** [comment]
No im not publishing to web. Im running it on test mode, with the blue lightning

**Comment by Alezanello** [comment]
Has the error changed after removing the `FbAppCheck` from the `main.dart`, or are you still encountering the same issue with serializing the parameter? <br><br>Unfortunately, I don't have the necessary permissions to run the test mode on your project, so I can't double-check it from my end.<br><br> If the issue persists, I recommend reaching out to support via the in-app chat or at support@flutterflow.io so they can take a closer look at this specific project issue.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by bitgandtter** [comment]
This is the worst support system ever. The issue persists. its on your system, don care to debug and clod see bug just because there is no interaction. And we pay for the platform. At least keep the decency of helping your users.

**Comment by Alezanello** [comment]
Hello bitgandtter,

As I mentioned five days ago, I don’t have the necessary permissions to test your specific project. This GitHub Issue Tracker is intended for issues that can be replicated from a new blank project. Since this issue is specific to your project, I recommend reaching out to support via the in-app chat or at [support@flutterflow.io](mailto:support@flutterflow.io), as I previously suggested.

Thank you for your understanding.

**Comment by bitgandtter** [comment]
You all work for the same company. Either this via or any other users who pay for the software should be taken care of. We have written to the support email you shared. We have written through the live chat. Nobody cares, but at the end of the month, the bill comes. How is this possible? Now, to the permission issue, on FF, when a bug is reported, we give permissions to test the app, so again, same company, same people. All I can see above are complaints, not resolutions.
