### ISSUE TITLE
Issue submission: An option is mandatory!

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3590]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

While submitting a bug, there is an Checkbox at top, "Can we access your project?", although its an Option ('?'), unless its checked, we can't submit the Bug report. Which kind of becomes a mandatory option for us. 

### Expected Behavior

if its an option for a user, the form should allow us to Submit without checking it.

### Steps to Reproduce

Open a new issue on: https://github.com/FlutterFlow/flutterflow-issues/issues
fill all the details on the form, without checking 'Can we access your project?' checkbox.
Click, Submit new issue button

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sls/l6otPvsdG1ZDuc8dB/TkQJUw8U508scp/bxIgGIDzPOw+ZPWkXFBpYNe/Smw7OESmmmAJ+d7KhtrDF/kCHzecfapR+rl5FgLgcECiUZOBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/7e41010d-1f34-4c6e-8dc2-996b761602d9

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.82+ released August 7, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2
```

**Comment by rzambroni** [comment]
Hey, thanks for bringing this concern to our attention. Unfortunately, our ability to efficiently replicate and troubleshoot reported bugs is often dependent on our ability to access the user’s project. This is why it’s mandatory for us to have your acknowledgment in order to investigate further.

If you’re uncomfortable with giving our team access to your project, you can create a blank example where the bug is also replicable. We can then use that example to look into the issue.

Thanks!
