### ISSUE TITLE
No way to check for updates on Flutterflow Mac OS app

### ISSUE THREAD

**Issue by EjazullahSupport** [FlutterFlow/flutterflow-issues#3614]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

hey. so once you disable the dialogue for update in flutterflow mac os app, then there is no way to check for updates or enable that dialogue again. the only way to do it is to go to the website and download the app again.

### Expected Behavior

there has to be a button in the menu to check for updates.

### Steps to Reproduce

open up the mac os app and disable the update dialogue

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

no report code just functionality issue

### Visual documentation

none

### Environment

```markdown
- FlutterFlow version: App
- Platform: Mac os
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello,

You’re absolutely right—there isn’t a button to check for updates. I’ll be forwarding this as a feature/enhancement request to the engineering team. After that, I’ll close this issue since this GitHub Issue Tracker is primarily for bugs that can be replicated from a new blank project. If you encounter any bugs in the future, please don’t hesitate to open a new ticket!
