### ISSUE TITLE
regular expression filter on textfield blocks when using ampersand

### ISSUE THREAD

**Issue by SamVdvd** [FlutterFlow/flutterflow-issues#362]
## Expected behavior (required)
I tried to configure a regular expression on a textfield to check an emailaddress.
I used the regexp which I found on the official documentation (https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/form-elements-1/textfield): ^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+.[a-zA-Z0-9-.]+$
With this regexp, one should be able to enter a valid emailaddress

## Current behavior (required)
I cannot enter any text into the field as long as I use the ampersand in the regular expression.

## Your environment

* Version of FlutterFlow used: v3.0
* Platform (e.g. Web, MacOS Desktop): web
* Browser name and version: Chrome 108.0.5359.126
* Operating system and version (desktop or mobile): windows 11

**Comment by agreaves** [comment]
Hi @SamVdvd, thanks for the bug report! This is actually an issue with our documentation. In reality, the Filter on a TextField should only be used to specify valid characters (e.g. "^[a-zA-Z0-9]*\$" to only accept alphanumeric characters). The email Regex will never accept input because when you start to type it will immediately be invalid since a single character will not match the email regex.

What you want to do is use the Form widget, and add validation to the TextField to use Custom Regex to only allow emails. We'll fix the documentation accordingly. Thanks!
