### ISSUE TITLE
Data "Reshuffle" Bug (Reproducible with example app)

### ISSUE THREAD

**Issue by jryankennedy** [FlutterFlow/flutterflow-issues#3649]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am making a trivia app and I noticed that when I tap anywhere outside of the card area, or when a dialog box or sheet component is dismissed, the trivia data changes out of nowhere.

### Expected Behavior

The data shouldn't randomly change for no reason.

### Steps to Reproduce

I went ahead and created a separate app just for this bug: https://app.flutterflow.io/project/dialog-reshuffle-bug-auggfn 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SlMrlz4xOxO5E15DuY8JKmj0vHHIjRYI309VQEBAdGL7wBLNyXOj9SFRuZNe6T2w7JWCi8WUxp9KKhobhUMYtPiiCGYh6+LlqWgnJTka7WrauO6qOZURQJ8JgIFOHzbSnpR5+HNRedEJn3zv7IO/KHx/cNabMOmwFPvmbItrI+WvgLDLCXn0Jg1ZSfCvr

### Visual documentation

https://github.com/user-attachments/assets/f267215d-f147-4d8e-bd75-87299cd00d2b

### Environment

```markdown
- FlutterFlow version: 4.1.81
- Platform: Web
- Browser name and version: Safari or Chrome on a Mac
- Operating system and version affected: Web
```

**Comment by Alezanello** [comment]
Hello!

I understand what you're referring to. The issue seems to stem from the fact that every move triggers a query, which retrieves new information. To improve performance, I suggest changing the query in the column to trigger on page load rather than streaming.

This way, the data will be retrieved once when the page loads and stored in a page state, rather than continuously querying as you interact with the page.

After making this change, try setting the children elements from the page state values to see if this resolves the issue.

**Comment by jryankennedy** [comment]
Thanks, I did what you requested, but now I have a new problem. I have to click anywhere on the page before the card will show now. Please see the attached video recording. 

https://github.com/user-attachments/assets/5eac0dd6-e69f-4762-a716-191be79d40be

**Comment by jryankennedy** [comment]
I was able to resolve. This ticket can be closed.

**Comment by astadevelopers** [comment]
> Pude resolverlo. Este ticket se puede cerrar. 
How did you solve it?
