### ISSUE TITLE
Conditional Builder Limit of "ELSE IF" statement (25)

### ISSUE THREAD

**Issue by matlin76** [FlutterFlow/flutterflow-issues#3653]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When using Conditional Builder on a page or in a component, after adding "ELSE IF" 24 times the "Plus sign" button starts to disappear. When adding "ELSE IF" two more times it is gone (Hidden behind a bottom container, I guess)

### Expected Behavior

I don't expect any limits on the number of "ELSE IF" statements because of the UI.

### Steps to Reproduce

1. Create a new page 2. Add a "Conditional Builder" 3. Add more than 25 "ELSE IF" statements

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kj8nqy4x2rulA18/tbcdajSo7C1M3TL0Jpu0bFBMYF4juPOxzZ8/TTBNtXf25dGNEL06Wmj8K+d7Wvd7AA+UqNUiVR7U+zZdQZxWVJVytVJ/XCauOT2tTEptJJVzC4Z2oniUnKtFiLFYc11+XOOiQTgLtQoezOGtMLvqYVJ3XjlmrQ0SLb3kNh1JWeC/v

### Visual documentation

![Screenshot 2024-08-20 at 16 21 36](https://github.com/user-attachments/assets/77eff347-46f5-4add-b0f4-bb75f58792b4)

### Environment

```markdown
- FlutterFlow version: 4.1.81+
- Platform: Both Web and MAC
- Browser name and version: Chrome Version 127.0.6533.120 (Official Build) (x86_64)
- Operating system and version affected: Ventura 13.6.7 (22G720)
```

**Comment by Alezanello** [comment]
Hi there,

Thank you for bringing this to our attention! <br><br>We appreciate your input. This issue is already on our radar and is being tracked for resolution. You can follow any updates on the main issue here: [Issue #3617](https://github.com/FlutterFlow/flutterflow-issues/issues/3617).

I'll be closing this issue as a duplicate to keep things organized.

If you have any other questions or concerns, feel free to reach out. Have a great day!
