### ISSUE TITLE
Adding item to user record array not working

### ISSUE THREAD

**Issue by SoLexGrowth** [FlutterFlow/flutterflow-issues#3655]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have a list of integer item which I have to tap on a button then the one item will be added to the list item in user collections but if will only add once and it won't add again. 

### Expected Behavior

When I tap on the button the item should be added to the list item in the user collection

### Steps to Reproduce

1 create a new page 
2 add a field called ratings as integer and is a list of integer
3 add action to add any integer maybe 1 or 5 to the list and then check if it's adding

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEekM/l25J2n7wC0bX2YccxqwMwJ0QlUIInj+0bWRMhNbLwO4kAes+lRxFLYteXf1ZbeGGWkmcC+aHWjc71FPI5B0mbGKZ9/r5XQTmXZD+7Vaa1DaqsVXFBGehVGkCx4auNpAlNJbZpdFpiwGGUGvCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

![IMG-20240821-WA0000](https://github.com/user-attachments/assets/61ab041e-6d83-4b5f-b51b-ea8cce22e1f5)
![IMG-20240821-WA0001](https://github.com/user-attachments/assets/034bb62d-f972-40c6-a54c-f0d275da0b82)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

Please this is my last part on this project please help me

**Comment by Alezanello** [comment]
Hi there,

Just a quick note about using a list of integers in Firebase for storing ratings.

When you add a specific value to the list, if that value already exists, it will overwrite the existing entry. For example, if you have a list of ratings from 1 to 5:

Ratings = \[1, 2, 3, 4, 5\]

And a new rating with a value of 3 is added, the existing 3 in the list will be replaced, meaning you won't have duplicate entries for the same rating.

Because of this behavior, I strongly recommend against using a list of integers for storing ratings.

**Comment by SoLexGrowth** [comment]
@Alezanello  Thank you for your response

How do I achieve this because I need to store the list of ratings for each users in their document let me know if there's another way to achieve this

**Comment by Alezanello** [comment]
Hi again!

There are several posts in the community and YouTube videos that could help you achieve this. Since I haven’t done it myself, I’d rather not guide you incorrectly. For example, you might find this post helpful: [Average Rating](https://community.flutterflow.io/custom-code/post/average-rating-9kAWZTGloGcb3kl).
