### ISSUE TITLE
Dynamically created drop downs don't send to api calls

### ISSUE THREAD

**Issue by sgardoll** [FlutterFlow/flutterflow-issues#3664]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

1. A dropdown that contains dynamically generated items is selected
2. onSelected the dropdown item is recorded to a pageState variable correctly
3. An API call made then using this page state variable comes through to the endpoint as "null"

### Expected Behavior

The page state variable should come through with the value selected on the dropdown

### Steps to Reproduce

1. A dropdown that contains dynamically generated items is selected
2. onSelected the dropdown item is recorded to a pageState variable correctly
3. An API call made then using this page state variable comes through to the endpoint as "null"

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozMmAvJR2rsRE17r+bPlVuyQRQlwmaudJ18pOGDsdF4iuPOxzacjBblttcM+8T3NhKEWLoH40+vztkobfD8YnIRWaGIhO+M9UZgvzVnG/aouVELjpZEQlHedPCkyu3MGNrRRCWfhvSmQa1ziHfujKVgDbO5/7Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-08-22 at 5 29 45 AM](https://github.com/user-attachments/assets/4e555633-f7d4-499d-98c7-f0e085524b9b)
![Screenshot 2024-08-22 at 5 29 23 AM](https://github.com/user-attachments/assets/aeb6b31a-59de-4a67-b2d9-3d7ff0cece16)
![Screenshot 2024-08-22 at 5 29 08 AM](https://github.com/user-attachments/assets/1bd5b4af-a5e7-4f32-a8fa-e4dc5e98bac6)

### Environment

```markdown
- FlutterFlow version: v4.1.90 released August 21, 2024 Flutter version is 3.22.2
- Platform: Mac 14.6.1 (23G93)
- Browser name and version: Chrome Version 127.0.6533.120 (
- Operating system and version affected: As above
```

**Comment by Alezanello** [comment]
<br>Hi there!

I noticed that in your project, the country value you're sending to the API call is coming directly from the Widget State, rather than from the Page State where the "countrySelected" variable is stored.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/60917ffd-8d2a-4025-92b4-f9825af3ce64/9553a26d-a225-4f7b-82d9-85b1f1532897?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82MDkxN2ZmZC04ZDJhLTQwMjUtOTJiNC1mOTgyNWFmM2NlNjQvOTU1M2EyNmQtYTIyNS00ZjdiLTgyZDktODViMWYxNTMyODk3IiwiaWF0IjoxNzI0MzM2NDk5LCJleHAiOjMzMjk0ODk2NDk5fQ.VAegRFCymerAwbLMSnnB7IB_OrGJK5zjSa9kVq06aPE " alt="image.png" width="606" height="516" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
