### ISSUE TITLE
bug with Tabbar

### ISSUE THREAD

**Issue by mrkooder** [FlutterFlow/flutterflow-issues#3674]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I can't add or edit Tabbars, whenever I try to add a new one or edit the current one I get this error!!! yesterday it was working fine

### Expected Behavior

to add and edit the tabbars

### Steps to Reproduce

1. create new page and add new tabbar but still can't add/edit

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTzPHl34x2rsdK+KXia8FF/SMvI0MCX5I7i9caZ003GOuuE+0cY+r+VBRtYcuCfW1mJVr+glEd0f/FjeHDFPQ6G06qeINowqpXFzqXIUSVMISqDJG3e0FTO/hRIUyO4JmnvyJ/BNJqZXdkw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![Screenshot 2024-08-23 092414](https://github.com/user-attachments/assets/c310893c-ff04-428e-9ccd-44a6fac1decc)

### Environment

```markdown
- FlutterFlow version: v4.1.83+
- Platform: 
- Browser name and version: Chrome Version 127.0.6533.122 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Pro Version: 23H2
```

**Comment by rzambroni** [comment]
Hello @mrkooder, 

I attempted to replicate the issue you described, but I was unable to do so using the steps you provided. The TabBar widget appears to be functioning as expected on my end.

Additionally, I checked the project you shared, but it seems the widget and page are no longer present, so I couldn't investigate further.

Are you still experiencing this issue? It seems like it should be quick to replicate, so if possible, could you share a blank project where the bug is reproducible or provide a video of the steps you're taking? This would help us identify the problem more efficiently.

Thanks for your cooperation!
