### ISSUE TITLE
Apps wont run after building

### ISSUE THREAD

**Issue by infinixbolt** [FlutterFlow/flutterflow-issues#37]
I can't run my apps. It brings up an empty screen after building for 2-4 minutes. I have taken the following steps but it still wont work.
1. Reload Frame.
2. changing the device (left side of your screen).
3. Refreshing the page.
4. Upgrading to the latest version of FlutterFlow Ctrl + R on Windows or Cmd + R on Mac. After you have done this, clear your browser cache and log in/out of FlutterFlow.
![run mode](https://user-images.githubusercontent.com/55094860/195212988-775d046b-d54d-44aa-a772-4654102efa80.jpg)

**Comment by bulgariamitko** [comment]
Did that happen to all your projects? Is Test Mode loading for you?

**Comment by infinixbolt** [comment]
It happens on all my projects (2). After multiple taps and drags on the screen it eventually comes up. In some cases it doesn't

**Comment by infinixbolt** [comment]
I started experiencing this 3 days ago. I have been using FF for more than a month now and never experienced that. I'm using the same internet connection and computer so nothing has changed from my end.

**Comment by infinixbolt** [comment]
Can you provide an email so I can add you to the project to try running it from your end?

**Comment by infinixbolt** [comment]
Done!

**Comment by infinixbolt** [comment]
"dimitar@flexmoney.uk is not on Flutterflow. Send an invite?"
OR do I send a public link to access the project?

**Comment by bulgariamitko** [comment]
Try again, please

**Comment by bulgariamitko** [comment]
![Test-Mode-testrun](https://user-images.githubusercontent.com/7221384/195597282-3fa6232b-5fb8-4688-b1c6-cd123da1c7dc.png)

everything is running like it suppose to. 

@agreaves , do you have some advice?

**Comment by infinixbolt** [comment]
I don't think it's running like it's supposed to. There are drop-down and button widgets on that page. Why is it not displayed?

**Comment by infinixbolt** [comment]
I'm still waiting for a response please. @agreaves and @asmengistu , Can you please advice?

**Comment by bulgariamitko** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
Thank you!

This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/) for further assistance.
If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
Thank you for your contribution!

**Comment by infinixbolt** [comment]
Thank you.
