### ISSUE TITLE
Am unable to execute a callback action on a component

### ISSUE THREAD

**Issue by SpencerHaven** [FlutterFlow/flutterflow-issues#3734]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I followed this flutterflow tutorial on components to the T and cannot get the action to work on a component: https://www.youtube.com/watch?v=EiHY5WP_pDk

On the component, I add an action parameter. Then, on the component itself I set the action to on tap -> execute callback and bind the "action" parameter to it. Lastly, on the page I have the component added to, I set the component properties to navigate to another page. When I go to test this out nothing happens. I've looked over it several times and am at a loss.

### Expected Behavior

I would expect that, once I have the action on the component set up, when I pass the action to it, it should perform that action. In this case, navigating to another page. 

### Steps to Reproduce

1. Create a component
2. Add component Parameter
3. Set type to action
4. Select component and define action to `on tap execute callback` and set callback to the parameter previously added
5. Add component to page
6. Pass data to component and set action to navigate to a page
7. Select Preview
8. Select component
9. Nothing happens

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESz/Hqx89gocdc+s72cMJqhQMkQzM6bZI7ku1EdwEhNYD3PYkiZOP8QFVLYteDY35iJVaYgXMJpcGPi+GTUfcnHxyVQLlyyoRXQQz/QlqhVrKJCs67e398TMVRGmKn08O3hRVQPvZfSGQ460yEIvCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1268" alt="Screenshot 2024-09-01 at 8 55 28 PM" src="https://github.com/user-attachments/assets/bca426ba-48aa-41b0-896d-fd2230d21fc1">
<img width="1064" alt="Screenshot 2024-09-01 at 8 55 09 PM" src="https://github.com/user-attachments/assets/ed22429e-5ad6-495d-a1ae-8096911fb082">
<img width="1073" alt="Screenshot 2024-09-01 at 8 54 42 PM" src="https://github.com/user-attachments/assets/483c8be1-f1a9-4abe-b3b2-902f9030699d">
<img width="1072" alt="Screenshot 2024-09-01 at 8 53 51 PM" src="https://github.com/user-attachments/assets/4d492e11-7238-4d8b-b8c9-760163a4d23b">

### Environment

```markdown
- FlutterFlow version: 4.1.85
- Platform: MacOS Web
- Browser name and version: Chrome, 128
- Operating system and version affected: macOS Sonoma 14.6.1
```

### Additional Information

I'm trying to create a reusable component. Since I cannot use the component to navigate, it is essentially useless to me. If I want to make changes to this widget, I can't do it in one spot, which will just take more time.

**Comment by Alezanello** [comment]
Hello!

Thank you for reaching out! <br>It looks like you were testing the app in **Preview Mode** to check the actions, but I'd like to clarify that Preview Mode is primarily designed to display the UI and data without building the full app. <br><br>Some action callbacks or features may not function as expected because the app hasn't been fully compiled—it's more of a UI view.

To properly test the actions and behaviors you're working on, I recommend using **Test Mode** or **Run Mode**, which offer a more accurate reflection of the app's functionality. Alternatively, you can use our **Desktop Apps** for a local run or download the code to run it locally.

For more details, you can refer to the [Preview Mode documentation](https://docs.flutterflow.io/testing/run-your-app#preview-mode). Right below that section, you'll find helpful documentation on Test/Run Mode and Local Run for deeper testing.

If you need further assistance, feel free to ask!

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
On another note, I just tested your project and confirmed that you’ve successfully implemented the Action Callback in the component. Great job, congratulations!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e63ab042-38ac-48ec-a221-ef65ac660514/1d9bb7d3-cf4c-463f-b6c2-5e443bcaa632?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lNjNhYjA0Mi0zOGFjLTQ4ZWMtYTIyMS1lZjY1YWM2NjA1MTQvMWQ5YmI3ZDMtY2Y0Yy00NjNmLWI2YzItNWU0NDNiY2FhNjMyIiwiaWF0IjoxNzI1NDQ5MTU1LCJleHAiOjMzMjk2MDA5MTU1fQ.PCg2urzT379838cVu7212dWENzM5cmxJUsznABpMzVE " alt="component button.gif" width="1607" height="739" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
