### ISSUE TITLE
cant start walkthrough on button Click

### ISSUE THREAD

**Issue by coach1990** [FlutterFlow/flutterflow-issues#3736]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have created a walkthrough in the project, its all working, but when i try to start this on the button click, it shows disabled.

### Expected Behavior

should be able to start Walkthrough on the button click

### Steps to Reproduce

please refer the video for the detailed explanation

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjPHq2ItOodhE7rXyccd7/WYXC217beYescp/bxIgGIDzPOw+ZPXsbRBtXsviTWNMMUSmmkcF/9bTi9+eVMBfNk+cY4R7yLhqVAndeHyVe5OBDqiOdEdBM9tUC2GM5pjZkxZ5HLFucl4s7U6yG+/KUXTrHu/AIndISq/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/7aaf09a3-25ca-4ffe-9327-8f7c11a01091

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.85+ released August 27, 2024 Flutter version is 3.22.2
- Platform: Desktop App Windows
- Browser name and version: Microsoft Edge Version 127.0.2651.74 (Official build) (64-bit)
- Operating system and version affected: Windows 11 Home Single Language , 23H2

Project: letMeDraw
Project ID: let-me-draw-zo88ww
```

**Comment by Alezanello** [comment]
Hello! <br><br>It looks like the Walkthrough is being triggered in the SplashScreen instead of the MainPage, where it’s actually supposed to be initiated. <br><br>Have you tried using the "Get Started" button to navigate to the MainPage and then trigger the Walkthrough from there? <br><br>You can follow the documentation for guidance: [FlutterFlow Walkthrough Documentation](https://docs.flutterflow.io/resources/projects/settings/project-setup/#2-start-walkthrough-action).

**Comment by coach1990** [comment]
Hello Alzanello,
Yes please, i tried it and also checked the doc. however i am not sure what's not working.

**Comment by coach1990** [comment]
its resolved
