### ISSUE TITLE
Issue with the trailing icon for listTitle

### ISSUE THREAD

**Issue by arbindbhagat** [FlutterFlow/flutterflow-issues#3738]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When we apply line height to the subTitle of the ListTitle widget, the trailing arrow/icon is no longer in the middle.

### Expected Behavior

When we apply line height to the subTitle of the ListTitle widget, the trailing arrow/icon should still be in the middle.

### Steps to Reproduce

(1) Create a new page. (2) Add a List and LIst Title Widget. (3) Apply some line height to the sub-title.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sicrxuItJpbxK7arAb8Fr/WEXOUggbJEascp8WQgafIjJP4kQPPWkVFdBXse4TAhMOESmmmEKw8rQit7DJ8EoPTGBc4Nx1s1fEwzMcDm5e5OBCJOWeXdRFplVIHKEyqbR2yRdPsB2Ll4f2Uy2DO6vcDfsNbrNImdISq/LZO4=

### Visual documentation

simple enough to reproduce

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by paulperez-dev** [comment]
Hi @arbindbhagat!

This is the expected behavior according to the Material 3 Design System. I'll be submitting a Feature Request to support the `titleAlignment` property, which will allow you to easily align the trailing icon without needing a custom widget.

In the meantime, you can achieve the same effect by creating a custom widget. 

Thank you for your understanding!
