### ISSUE TITLE
FlutterFlow windows desktop app doesnt work

### ISSUE THREAD

**Issue by nev-21** [FlutterFlow/flutterflow-issues#3757]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The app doesnt start after login (neither google nor password sign-in). 

### Expected Behavior

That desktop app works.

### Steps to Reproduce

1. Download and Install Flutterflow windows app
2. Open it, sign in (google or password)
3. Infinite spinner shown.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXzMrlvJdPvsxE0KrXY8JWij4wFjsaU40V0tdTbEgYG7LvO7M2O+r+VHZvcMekY1Y/JlmKkk8E0/Tsv/GeIPQCIkiZUoNo1rhyFA7ycHqtMM2UPs3hOmpfEdxbN0y81rSo2xFNCPtaR3Mtw3z/cq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

![image](https://github.com/user-attachments/assets/6a2784b5-59a9-4aae-b4a2-3c14cc3af331)

### Environment

```markdown
- FlutterFlow version: 4.1.86
- Platform: Web, mobile
- Browser name and version: FF Desktop App
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hello!,

We've just released a new hotfix, and the current version is 4.1.87. Could you please update to this latest version and let us know if everything is working as expected?

Thank you!

**Comment by nev-21** [comment]
I updated to 4.1.87 
It doenst work yet

![image](https://github.com/user-attachments/assets/4e729d28-c920-4cad-b446-3766654babb0)

**Comment by nev-21** [comment]
Hi, @Alezanello I just installed the version 4.1.88
It is with the same error. Thank you for trying.

**Comment by nev-21** [comment]
I have not received an answer yet, please help

**Comment by rhasan104** [comment]
I'm having the same issue. I have attached a screenshot of the version I have installed. I also included the event viewer log.

![FailureLog](https://github.com/user-attachments/assets/7f64775d-216e-4637-83c9-367e1662d07d)

`Windows cannot access the file  for one of the following reasons: there is a problem with the network connection, the disk that the file is stored on, or the storage drivers installed on this computer; or the disk is missing. Windows closed the program flutterflow because of this error.

Program: flutterflow
File: 

The error value is listed in the Additional Data section.
User Action
1. Open the file again. This situation might be a temporary problem that corrects itself when the program runs again.
2. If the file still cannot be accessed and
	- It is on the network, your network administrator should verify that there is not a problem with the network and that the server can be contacted.
	- It is on a removable disk, for example, a floppy disk or CD-ROM, verify that the disk is fully inserted into the computer.
3. Check and repair the file system by running CHKDSK. To run CHKDSK, click Start, click Run, type CMD, and then click OK. At the command prompt, type CHKDSK /F, and then press ENTER.
4. If the problem persists, restore the file from a backup copy.
5. Determine whether other files on the same disk can be opened. If not, the disk might be damaged. If it is a hard disk, contact your administrator or computer hardware vendor for further assistance.

Additional Data
Error value: 00000000
Disk type: 0`

![FFVersion](https://github.com/user-attachments/assets/129c3c97-f556-4d9e-a8d3-9c505633b939)

Additionally, I deleted the firestore and firestore-heartbeat folders in C:\Users\\{User}\AppData\Local  dir. Once I relaunched the app, it lasted a little bit longer but within 30 seconds, it crashes again.

**Comment by nev-21** [comment]
Hi, just want to notify that it is broken in version 5 too. 

![image](https://github.com/user-attachments/assets/8ab4ce6e-e8c2-4702-aef1-d2a7f59b9bed)

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by nev-21** [comment]
Hi, 
It is still hapening, version 5.0.9, windows 11:

![image](https://github.com/user-attachments/assets/82388cc8-ae55-4a27-87eb-6a4d47bb95b6)

![image](https://github.com/user-attachments/assets/867280fd-276d-465b-ba0c-da7ea4b56180)

**Comment by nev-21** [comment]
Just want to mention that in version 5.0.11 the issue persist

![image](https://github.com/user-attachments/assets/ea6905a6-3e20-42e5-a044-798fa76fc40f)

**Comment by Alezanello** [comment]
Hello!!<br><br>Lets try another approach and delete all cache:<br><br>Close the FF app

* Delete the `FlutterFlow` folder present in `C:\Users<user_name>\AppData\Roaming`
* Uninstall the FF app
* Re-install and try running again

**Comment by nev-21** [comment]
Hi, I did the process and it is still happening. I have another laptop where I installed FF-windows for the first time and the spinner never ends too.

**Comment by Alezanello** [comment]
I’ll escalate this issue to the engineering team fore a deeper look on what's possible going on

**Comment by nev-21** [comment]
I found the problem, It seems it was blocked by the antivirus self signed cert.
