### ISSUE TITLE
Changing Primary Language issue

### ISSUE THREAD

**Issue by chrislcs98** [FlutterFlow/flutterflow-issues#3772]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After changing the primary language from English to Greek, we observed that the Greek translated text content was replaced (and deleted) by the original English text. The English text is now displayed in place of what should be the Greek translations.

### Expected Behavior

The text content should display in Greek, utilizing the correct translations without being swapped.

### Steps to Reproduce

1. Add 2 languages to the project.
2. Add a couple of text fields with English text.
3. Add translations to texts for both languages.
4. Change the primary language setting from English to Greek.
5. Observe the text content across the platform.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sleflzItIxNtb7rrUbPl7/SU4KUA4R5IKsct/cxQcB4j4EIkQPfSlQFdBQuqzaH1+GVr+/XIFpPDwieD9U/I3ORyafN14wqh2aRPPbDinMaaoDaqoSHBSI8BXfXbF0aur3QhSXbBYLV5h70+IH+ytEj6Cf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/20c4e551-39a5-44c2-8c32-b58e119f7e0f)
![image](https://github.com/user-attachments/assets/fc9fc64b-b572-4ed0-85ff-2041b41a32a5)
![image](https://github.com/user-attachments/assets/b72064e6-fed6-41b2-8400-604a1cc39da8)
![image](https://github.com/user-attachments/assets/41f0c68f-55be-4b66-b825-ed692586eb0c)

### Environment

```markdown
- FlutterFlow version: 3.22.2
- Platform: Web
- Browser name and version: Opera GX 112.0.5197.115
- Operating system and version affected: Windows 11 Pro 23H2
```

**Comment by Alezanello** [comment]
Hello,

I’ve tested this behavior multiple times and can confirm it is expected. When the Primary Language is set to English and you translate everything to Greek, a message pops up when you try to change the primary language again, warning that everything will be deleted. This means all settings will reset to their default values.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b3f76d5c-0b4e-4568-9650-5588ea24e447/8f2fec96-6028-4fbe-89de-7f116e23b59d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iM2Y3NmQ1Yy0wYjRlLTQ1NjgtOTY1MC01NTg4ZWEyNGU0NDcvOGYyZmVjOTYtNjAyOC00ZmJlLTg5ZGUtN2YxMTZlMjNiNTlkIiwiaWF0IjoxNzI1OTI4Mjg4LCJleHAiOjMzMjk2NDg4Mjg4fQ.NPpiSDq6jKmBmWO9jX_uo5DQgBegSqVzyJWq21Y2ACY " alt="image.png" width="481" height="253" />

Since the default values in the app are in English, the app won’t automatically translate to the new language. You’ll need to manually update the app with the Greek default values.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
