### ISSUE TITLE
Custom code packages inserted not change between codes !

### ISSUE THREAD

**Issue by ImadBouirmane** [FlutterFlow/flutterflow-issues#3773]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created new custom action and inserted his packages but after I checked that the whole custom codes use the same new packages recently inserted !

### Expected Behavior

Its should every custom code save his sepecified packages integrated as before.

### Steps to Reproduce

- Create new custom code 
- Add new packages 
- Check if the whole rest use same new packages added !

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jMrluJdgocNJ7qr+KcJV9SU5Jn49R5E/l+17aCosfZT2BLMcec/RVERoONe+T1FEJUyJv2oW0MLOhobLU8I3HwurbN1OyagJVjrMYHiuMrnSFJWgY3B9P+lmCFClyqW7rx1vCLR1LyEu1GD3GdiQRT3BNu/xOkQWDa/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/a5e79058-cc3f-46d9-bae2-cc972fe62286

### Environment

```markdown
- FlutterFlow version: v4.1.86
- Platform: Web & Windows
- Browser name and version: Chrome 128
- Operating system and version affected: Win 11
```

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention, and we're sorry for the inconvenience you're experiencing. We want to reassure you that this is a known issue, but it's only a visual bug. It does not affect any of your existing custom actions or code.

Our team is actively working on a fix, which will be included in the next deployment. In the meantime, you can follow the progress of this issue here: [GitHub Issue #3747](https://github.com/FlutterFlow/flutterflow-issues/issues/3747).<br><br>Given this context, I'll close this issue as duplicated you can follow any updates in the Issue referenced!

Thank you for your patience!

Best regards,<br>Azanello
