### ISSUE TITLE
ToggleIcon and Checkbox are useless when using Supabase

### ISSUE THREAD

**Issue by csfalcao** [FlutterFlow/flutterflow-issues#3776]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Both ToggleIcon and Checkbox can't write to Supabase. All other elements of CRUD actions are ok. I tried in and out of components, toggle on and off actions, conditional actions, widget, and local state and it won't work. It's so disappointing, It's so a basic thing to set. The forum is full of people with this same problem.

### Expected Behavior

Click ToggleIcon and Checkbox and DB is updated accordingly

### Steps to Reproduce

1-Add listview
2- set Supabase query
3- add toggleIcon or checkbox element
4 try to link that to the DB boolean row field
5- it will either be blank or will not update the DB
6- alternatively, create actions on click to update Supabase, set field>tru to false and vice versa
7-alternatively, create a component, set boolean parameter, get the listview attached to the row query

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Top Cat is reading a book @ recording studio

### Visual documentation

![image](https://github.com/user-attachments/assets/34942cd2-227d-4fa3-b245-14449757c984)
![image](https://github.com/user-attachments/assets/b242e52d-d9ff-43b0-a8b2-27944e3b45ef)

### Environment

```markdown
- FlutterFlow version: 4.1.88+
- Platform: Windows
- Browser name and version: Chrome 128.0.6613.120 (Versão oficial) 64 bits
- Operating system and version affected: Win 11 23H2 22631.4112
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate the issue you’re experiencing. I successfully triggered the update of the boolean field using both a ToggleIcon and a Checkbox. To help you further, I’ve shared a public project that includes all the actions needed to achieve this functionality.

Since you didn’t provide a Bug Report Code, I can’t directly identify what might be causing the issue in your project. Please review the public project, and feel free to reach out if you have any questions. I’m here to help!<br><br>Public Project: [https://app.flutterflow.io/project/qa-1937-dackqs](https://app.flutterflow.io/project/qa-1937-dackqs)<br>Loom showing the Updated Field in Supabase:<br>[https://www.loom.com/share/52205781deb14e98b9e88c88be415c51](https://www.loom.com/share/52205781deb14e98b9e88c88be415c51)

**Comment by csfalcao** [comment]
Thanks for the help! The sample project and the video are a great effort from you @Alezanello, and you're right FF works with SB. I came from Bubble, and there it's a simple 2-way workflow to set a toggle or check action. I'll try to examine your example better, as I see you had to create 3 parameters and 3 actions (or 6 for the checkbox), I'll get a hand on it soon.

**Comment by csfalcao** [comment]
I could easily use the Toggle Icon with Firebase the first time, I just set the widget to a boolean field in my DB and it worked fine. Doing the same with Supabase didn't work, it need additional steps. I'll wait for the FF Supabase integration to leave the beta status, as announced in FF 5.0 to try again.
