### ISSUE TITLE
The addition of dependencies in Custom Code will apply to all Custom Code.

### ISSUE THREAD

**Issue by Lee-Jinzen** [FlutterFlow/flutterflow-issues#3778]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Currently, when you try to add a dependency to a single Custom Code, the dependency is added to all Custom Code in this FF project.

### Expected Behavior

I'm not sure if this behavior is the expected specification at the moment.

### Steps to Reproduce

This issue always occurs when editing a Custom Code.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48ismBw5R2rsRE0M/UKcJB/Tg5JmE7R4E40OthexI8J5zKB+wAYvf7P1FWTLy5Y3w/M1mJjjg11vfquNjDJ/oDByWcGLpJzahUbTuXQkOuMoiYCrmZfW1TN8pWFVSO06WNgB57AOtic1pi21z3Cu6WZCraH4zqPW4ZAs+lJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://firebasestorage.googleapis.com/v0/b/mshopping-2e739.appspot.com/o/developer%2F%E7%94%BB%E9%9D%A2%E5%8F%8E%E9%8C%B2%202024-09-08%2017.01.55.mov?alt=media&token=589a27e5-af6d-47d8-9a81-b26c8ab4012c

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.86+ released September 7, 2024
Flutter version is 3.22.2
- Platform:Web
- Browser name and version:Chrome 128.0.6613.113（Official Build） （arm64）
- Operating system and version affected: macOS Sonoma 14.6.1
```

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention, and we're sorry for the inconvenience you're experiencing. We want to reassure you that this is a known issue, but it's only a visual bug. It does not affect any of your existing custom actions or code.

Our team is actively working on a fix, which will be included in the next deployment. In the meantime, you can follow the progress of this issue here: [https://github.com/FlutterFlow/flutterflow-issues/issues/3747](https://github.com/FlutterFlow/flutterflow-issues/issues/3747)

Given this context, I'll close this issue as duplicated you can follow any updates in the Issue referenced!

Thank you for your patience!

Best regards,

Azanello
