### ISSUE TITLE
Custom code dependencies is now shared across all widgets and actions

### ISSUE THREAD

**Issue by zein1016** [FlutterFlow/flutterflow-issues#3782]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

All custom actions and widgets now display all dependencies. It might be better that way since i want to add the same dependency every time but  I'm not sure if new codes are actually using these dependencies or not?

### Expected Behavior

Before this, Flutterflow shows all custom actions and widgets with their unique dependencies. 

### Steps to Reproduce

Create a widget or action.
Add a dependency 
create another widget you will see the dependency there.. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4si8rq24p2rsNK+Kr+bsBB/WUsKWIlaLgssct/cxQcB4j4PIkAPOLRTxNvQtSzaH1YGlKkkkME0s7Sk/PqG/YoIUmtG5Rj/852ERPPYzuuV4uVBZeaXUcnGfxUGB2A0cKN2hB4PsBtWUYY7FyMBOyAaz2Cf9qOYwx5e6fDbOY=

### Visual documentation

Any widget 

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by khomya** [comment]
I have the same problem.

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention, and we're sorry for the inconvenience you're experiencing. We want to reassure you that this is a known issue, but it's only a visual bug. It does not affect any of your existing custom actions or code.

Our team is actively working on a fix, which will be included in the next deployment. In the meantime, you can follow the progress of this issue here: [GitHub Issue #3747](https://github.com/FlutterFlow/flutterflow-issues/issues/3747).<br><br>Given this context, I'll close this issue as duplicated you can follow any updates in the Issue referenced!

Thank you for your patience!

Best regards,<br>Azanello
