### ISSUE TITLE
Showing null value screen for 1 sec and then loading the page completely

### ISSUE THREAD

**Issue by principiumOne** [FlutterFlow/flutterflow-issues#3787]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If I click on the chat with a user, I get the null value screen for a short time. Around 1 secon. After this the page is loading successfully. I am not sure on how to fix this. Maybe you have an idea on this.

### Expected Behavior

Chat page is loading smoothly without interruption and null value error screen.

### Steps to Reproduce

https://www.loom.com/share/62dc6f6a39364c9b8bcee3497d12a70f

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4giMjf5Yp1xOFH1aXube9WjigsJjs1bL00r9pEGEshNb7yEZk+deP8VxNLYtenfGw+eEyYiTgF7tr7vvL9Cfo7PSSVRtlN1ZRXQQyVTliiV8XSPKWOOkdQO9pgGB3A1MGVsR1SNbJhW1IR1DumIPCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://www.loom.com/share/62dc6f6a39364c9b8bcee3497d12a70f

### Environment

```markdown
- FlutterFlow version: v4.1.86+ released September 7, 2024
- Platform: Debug mode, android, ios
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
The issue might be due to the complexity of the inner components and how references are passed between them, which could result in seeing the red error screen. However, this behavior typically occurs only in test/debug mode.

One thing you can try is to start by checking the deepest component, in this case, **"chat_message"**, and ensure it has proper null-checks in place, such as displaying a loading widget or placeholder while the data is being loaded.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/dbab15dc-0bbd-4896-b80e-30466b5d47ae/4fbd88c6-194f-48e9-8142-b242b9efe205?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kYmFiMTVkYy0wYmJkLTQ4OTYtYjgwZS0zMDQ2NmI1ZDQ3YWUvNGZiZDg4YzYtMTk0Zi00OGU5LTgxNDItYjI0MmI5ZWZlMjA1IiwiaWF0IjoxNzI1OTcyNjM3LCJleHAiOjMzMjk2NTMyNjM3fQ.WUgPtALw8mxuVBMF3DGWc1gSDFqP0z1-KBIq2zBVvOg " alt="image.png" width="1867" height="880" />

**Comment by principiumOne** [comment]
Alright. I will check this out.

Do you think the bad loading time is also caused from the parameter? I use
a document instead of a document reference.

Does this need longer for loading? What do you recommend for better
performance? Document or document reference with a query on the page?

Am Di., 10. Sept. 2024 um 14:50 Uhr schrieb Alezanello <
***@***.***>:

**Comment by principiumOne** [comment]
The ticket has to be answered from team.

github-actions[bot] ***@***.***> schrieb am Mi., 18. Sept.
2024, 03:57:

**Comment by rzambroni** [comment]
Hey @principiumOne, apologies for the delay as we're working to catch up on open tickets.

As @azanello suggested, it's best to start by implementing null-checks to prevent the errors, and then observe if that improves the loading times.

While I’m not an expert, using a document instead of a document reference could potentially impact loading times, particularly when dealing with large datasets or complex, deeply nested documents—though it seems like you're already doing that.

It might also be beneficial to reach out to the [FlutterFlow community](https://community.flutterflow.io/) for additional insights or recommendations.

I'll be closing this ticket since this list is intended for FlutterFlow-specific bugs. Thanks!
