### ISSUE TITLE
Wait time Integer not selectable from any variable (Must be hardcoded)

### ISSUE THREAD

**Issue by Kato-Official** [FlutterFlow/flutterflow-issues#3789]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Time integer in action: "Wait(Delay)" not selectable from any variable and must be hardcoded in milliseconds.

![Group 2](https://github.com/user-attachments/assets/0813da77-b2f9-4e66-ae33-b044c715da6a)

### Expected Behavior

To have a selectable variable just like this: 
![Like this](https://github.com/user-attachments/assets/c403e9d8-30e6-4bd0-b31e-d72288d9364d)

### Steps to Reproduce

1. Create new project and page
2. Go to any action and select Wait(Delay) and try to set the integer from any variable.
3. Not possible as the icon to select that variable is not there.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Oksn6389IsdtJ+KriasExryQsH1whaqxM0MIbEQIaIpPNG4gIZfTBXE9uOP25dkFXMVqanXIe+t7Vm9z1U/ArOT6efbp5z4dtEQrJcFqXMaaNPbu8SnxEGshRCUyF5omvpSRDAOhhLUYT2k2YFfC+cBbXGIToIXozMv/8JrvXrgfuQ0SLb3kNh1JWeC/v

### Visual documentation

![Group 2](https://github.com/user-attachments/assets/063cfd57-d56c-4c90-a8e2-f2caa1335137)
![Like this](https://github.com/user-attachments/assets/48a02c44-5d44-49f7-aefa-4761826a5e6f)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v4.1.86+ released September 7, 2024 Flutter version is 3.22.2
- Platform: Web and native
- Browser name and version: Chrome
- Operating system and version affected: All
```

**Comment by Alezanello** [comment]
Hello!

You're correct—the only way to set the time currently is manually, as there is no option to do it dynamically using variables. Since this is a feature/enhancement request rather than a bug, and this GitHub Issue Tracker is specifically for bugs that can be replicated from a new blank project, I’ll go ahead and create a request ticket directly with the Engineering Team.

I’ll be closing this issue to keep the tracker focused on bugs. Thank you so much, and if you encounter any other bugs, please don’t hesitate to open a new issue!
