### ISSUE TITLE
Unable to click on Compile Code

### ISSUE THREAD

**Issue by hprager07** [FlutterFlow/flutterflow-issues#382]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## Expected behavior (required)

After making changes to a custom action, clicking on compile code will compile the code. 

## Current behavior (required)

I made changes to a custom action, I was able to hit save but clicking on compile code does absolutely nothing

## To Reproduce (required)

1. Log in to account
2. Navigate to page where you can edit/add custom function
3. Edit an existing custom action or create a new one
4. click save. 
5. attempt to compile code. 

## Context (required)

I literally cant do anything because of this issue

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by victoriahuang1** [comment]
Hi @hprager07 , thanks for the report. I was not able to reproduce the issue. Could you provide more information? Screen recordings + information on your environment would be great.

**Comment by victoriahuang1** [comment]
Hi @hprager07 , there have been a couple of updates to the compile code button recently. Hopefully those have solved your issue, but feel free to update with your bug report code if that is not the case.

**Comment by andrhubb** [comment]
https://drive.google.com/file/d/17U1M9DIbmwQ-D21mEV3NRtSF4AF1sKFp/view?usp=sharing

**Comment by victoriahuang1** [comment]
Hi @andrhubb , thanks for the report. Compile code issues tend to be project specific, so it would be great if you could open up a new issue with the necessary info on your project -- so that there is no confusion between the issue affecting the original user and your own project.

In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided. Thank you for your contribution!
