### ISSUE TITLE
Reopen Issue #3693, Can not delete branch that I created

### ISSUE THREAD

**Issue by alyssa51402** [FlutterFlow/flutterflow-issues#3824]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created my own branch within a project. When I went to delete the branch I created I could not find an option to delete it. 

### Expected Behavior

Since I created the branch myself within the project, I assumed that I would be able to delete a branch I created. I am not the owner of the project but I should be able to delete something I created. 

### Steps to Reproduce

1. create a new branch 
2. go to delete it
3. you will find there is not delete button 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkMrlw5NPm7hA7aqMbcd4iiYUG0t+TL07ttYbZxUjIuPtBJh/PePeUBJuXu3md2lhHE6IpF0K+fzujoTpLsddFzubGYg/ybhuYQvKd3q8RrqvPrqeZEdQP51jIG6XyKaRoh5+WctsW0Yg2E+YFem+Ti3fCZ+/Zwh9f6PHaOI=

### Visual documentation

<img width="1438" alt="Screenshot 2024-09-13 at 5 52 38 PM" src="https://github.com/user-attachments/assets/7f5dd695-c85b-4390-903f-bad7f039951e">

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hello @alyssa51402,

Thank you so much for your follow-up, and I apologize for the delay in getting back to you. I just wanted to confirm that the [original ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/3693) is still open, though it was tagged as stale due to inactivity. I’ll be following up on it promptly to make sure everything is on track.

Thanks again for your patience and understanding!
