### ISSUE TITLE
Custom Functions needs to be checked

### ISSUE THREAD

**Issue by calumboomerang** [FlutterFlow/flutterflow-issues#3832]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Every few minutes I get the "Custom Functions needs to be checked" error
<img width="359" alt="Screenshot 2024-09-15 at 19 46 03" src="https://github.com/user-attachments/assets/0a54a6a1-0496-4bb5-9aa7-d37983514d16">

### Expected Behavior

I run the check, everything is checked fine but it comes back after a few minutes

### Steps to Reproduce

Use Flutter Flow
Randomly, even if no changes have been made to any custom functions, the error will appear

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klsmAsIt2rsdY1pDbbe0w9GQRJVAgTL03pu0bFEggGLbrBIYMaczeTFhuQsOiTQhPKEWGrzgz/tWLkvL1EsAEHzWsf7ZP1rlpEA7yXn6/aoS3DLWVP3BSRPJMG0y13J6vhhZ+WcR2WiUN1E2HfeiufDHrO5P7Zwh9f6PHaOI=

### Visual documentation

<img width="359" alt="Screenshot 2024-09-15 at 19 46 03" src="https://github.com/user-attachments/assets/38dabc8a-9dc1-46d6-919d-7e60fbfc0339">

### Environment

```markdown
- FlutterFlow version: 
- Platform: mac os
- Browser name and version:
- Operating system and version affected:
```

### Additional Information

In addition, it is clearly an issue with others too

https://community.flutterflow.io/database-and-apis/post/persistent-custom-functions-needs-to-be-checked-error-tet9jdHb754HUNB

**Comment by Alezanello** [comment]
Hello!

I understand how frustrating it can be to deal with this issue repeatedly, and I’m sorry for the inconvenience. We’re actively working on improving the frequency and process to make things smoother. We know this is a common concern within the community.

For now, this is expected behavior to ensure everything is in order for deployment and compilation. While I can provide more details if needed, please rest assured that we’re focused on making improvements in this area. 😊

Thank you for your patience!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by EJ-hue** [comment]
![Image](https://github.com/user-attachments/assets/51ffce3c-669d-4a9e-ad2c-d36fe2d33eb3)
I have checked my custom functions but no error. Why is this happened again?
