### ISSUE TITLE
Page Parameters not working 

### ISSUE THREAD

**Issue by apatilis23** [FlutterFlow/flutterflow-issues#3837]

**Comment by paulperez-dev** [comment]
Hi @apatilis23,

I’m sorry to hear you’re facing this issue. I noticed that the first part of the combined text isn’t visible in the screenshot you shared, so the issue might be with that widget rather than the parameter. Could you please try using a Text widget with fixed text and let me know if the value displays correctly?

Thank you for your help!

**Comment by apatilis23** [comment]
@paulperez-dev it doesn't show within the container. 
<img width="400" alt="Screenshot 2024-09-16 at 9 49 50 PM" src="https://github.com/user-attachments/assets/5d9c53f5-8b96-4fda-be77-69004d4e55b3"> Its showing outside of it though if you can see at the bottom I put a text. I literally did the exact same thing just outside the container. No conditional visibility as well on the container. Any reason why this may be? I think it has to be a bug.

**Comment by paulperez-dev** [comment]
Hi @apatilis23,

The issue may be related to the combination of the container and text widgets. Could you please share a new bug report code with this configuration so we can investigate further?

Thank you for your cooperation!

**Comment by paulperez-dev** [comment]
Hi @apatilis23,

I’m glad to see that the issue seems to be resolved! If you need any further assistance or have any additional questions, feel free to reach out.
