### ISSUE TITLE
Mux Broadcast not loading on physical Android Device

### ISSUE THREAD

**Issue by ozan-celebi** [FlutterFlow/flutterflow-issues#3842]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The mux broadcast widget will not load on a real Android device

### Expected Behavior

The expected behaviour is for the broadcast widget to load on the Android Device

The device is a Samsung SM-A115F and it is running Android 12.0 (31)

### Steps to Reproduce

1- Create a page
2- Only put the Mux Broadcast Element
3- Open on a real android device preferably with the system descriptions described above
4- Observe functionality

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEeysmBz4dNpbxI17XxbvlGrwMzJDt+bJA3m+0bZxMgfZzkOph/es7eR1pvTcjhT3lhHFSarHox0Nbpit7DG/Q5OUicQYhTzatIWxXMRXq8SqawEcyaQ3QkJ8BWGGqc1Kar2hNTLvRpLWBlw0+HeueQZBPaN5+/Zwh9f6PHaOI=

### Visual documentation

Here is what the page looks like during local run:

![327830406-3a7551d3-6e9b-4bff-92cf-48dd0f8486db](https://github.com/user-attachments/assets/5d0f26f1-b3e4-45d9-85d9-1fc7f5c9d044)

Here is the entire debug panel screenshots when a button is pressed to navigate to a page that only has Mux Broadcast Widget.

<img width="790" alt="367624167-d1e8f220-71ee-4e3d-9446-52f366ca3d1d" src="https://github.com/user-attachments/assets/e5060ab6-3856-43b4-b629-9112aa061787">

<img width="788" alt="367624185-a469801f-2334-4577-a84a-4e539022f439" src="https://github.com/user-attachments/assets/60c0be42-c23b-410d-b11c-555d59daa48c">

### Environment

```markdown
- FlutterFlow version: v4.1.91
- Platform: Android
- Browser name and version: Android Physical Device Android 12 API Level 31
- Operating system and version affected: Android
```

### Additional Information

Same issue as:

https://github.com/FlutterFlow/flutterflow-issues/issues/2853

**Comment by Alezanello** [comment]
Hello!

Thank you for reaching out. I attempted to replicate the issue by creating a new blank project with a Mux LiveStream and compiling it to a physical Android device (Samsung A52, Android 14). However, I wasn't able to reproduce the problem on my end.

Have you tried compiling the project on a different phone to see if the issue is specific to your device? This might help us rule out whether it's a device-specific issue.

Additionally, I tried to access the page in your project, but it appears the page no longer exists. Could you confirm if it’s still available or if any changes have been made?

Looking forward to your response!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/65a5ca99-3a94-444d-b035-d0b0c8631c38/05cf8067-0051-41b9-bfbb-33f3be2ff64f?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS82NWE1Y2E5OS0zYTk0LTQ0NGQtYjAzNS1kMGIwYzg2MzFjMzgvMDVjZjgwNjctMDA1MS00MWI5LWJmYmItMzNmM2JlMmZmNjRmIiwiaWF0IjoxNzI2NjA2NTk1LCJleHAiOjMzMjk3MTY2NTk1fQ.ZS4kdD5Uraq3ozDTKNDu7TkD0udrEya-6FtSfN0Vei0 " alt="image.png" width="1553" height="825" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/58cd60da-7237-4adf-8e3d-f4ab3d16a578/c5b08c77-7d40-4971-ad76-fe2870bfe15d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81OGNkNjBkYS03MjM3LTRhZGYtOGUzZC1mNGFiM2QxNmE1NzgvYzViMDhjNzctN2Q0MC00OTcxLWFkNzYtZmUyODcwYmZlMTVkIiwiaWF0IjoxNzI2NjA2NTk1LCJleHAiOjMzMjk3MTY2NTk1fQ.paOMbkyaCkF8U3XNieLdwnhHCQEw2UVld_mAKuMVoyU " alt="Imagen de WhatsApp 2024-09-17 a las 17.56.22_81dbe1d2.jpg" width="760" height="1600" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
