### ISSUE TITLE
Blank display in test mode in one of my projects

### ISSUE THREAD

**Issue by mor4b** [FlutterFlow/flutterflow-issues#3865]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I back again to an app that I worked on few months ago to add fix some issues. When I tried view it on test mode (after the fixes), The test mode is blank.

### Expected Behavior

I need to test my app in test mode

### Steps to Reproduce

1. check all the queries on the page
2. check all default values to see if set
3. check the console but I doesn't understand the error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkcjfsMxgrt9A1qrtbflFniE4OUh8TL07r+5xb0gvIrbyOu9+eOCkTFJDXcziY0NhHFa0kmo0wa3tjt/hE/Y7EzOYfIhE/7l2SxfyLHq8R7WYBpCddHJQBZtWBXKl4Ji7oRFSFOx2W1Vl60+Aed6Rdz/sCZ+/Zwh9f6PHaOI=

### Visual documentation

<img width="1499" alt="Screenshot 2024-09-21 at 10 12 20" src="https://github.com/user-attachments/assets/3eaf5ca4-0607-48d2-833c-db564e87a611">

<img width="1497" alt="Screenshot 2024-09-21 at 10 06 51" src="https://github.com/user-attachments/assets/58a04de4-0b74-4320-b2e3-f823d77dc906">

### Environment

```markdown
- FlutterFlow version: v4.1.89 (released September 12, 2024)
- Platform: mac web
- Browser name and version:Chrome 128.0.6613.138
- Operating system and version affected: MacOS Sonoma 14.5
```

**Comment by Alezanello** [comment]
Hi there!

I'm sorry to hear you're experiencing this issue. The GitHub Issue Tracker is intended for bugs that can be replicated in a new, blank project. In this case, it seems the issue is specific to your project, and we don’t have access to run Test Mode on your project to investigate further. I recommend reaching out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io) for assistance.

Thank you for your understanding!
