### ISSUE TITLE
New Index not consistent for on reorder action

### ISSUE THREAD

**Issue by max-h-silverman** [FlutterFlow/flutterflow-issues#3869]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When an item is dragged up the list, New Index is the actual index of the new position. When it's dragged down in the list, it's the position (i.e. one more than the index).

### Expected Behavior

New Index should be calculated consistently regardless of which direction reorder is done.

### Steps to Reproduce

1. create reorderable listview
2. add an 'or reorder' action
3. Set an alert to show the value of New Index
4. Drag up and down in the list

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ki87lx4lgoddA1rrtbcExvCo4H245TL07r+5xb0gvIrbyOu9/e87eXElDQtDgT1NhHFf+knE0pfDwjd+fFfYEYDqrf4h6watyaAHzd3q8R8SYPKWeQUF5IJ5mJnK536awkxVRAPBYWkIR6ma2H+6UVhbsGZO/Zwh9f6PHaOI=

### Visual documentation

[screen-capture (8).webm](https://github.com/user-attachments/assets/94a307d8-05b4-48d8-9ac3-fda637ba601f)

### Environment

```markdown
- FlutterFlow version: 4.1.91
- Platform: macos/android
- Browser name and version: chrome latest
- Operating system and version affected: multiple
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you're experiencing this issue. The good news is that the team is already aware of it, and it’s on the backlog for a fix. You can track progress here: [https://github.com/FlutterFlow/flutterflow-issues/issues/3444](https://github.com/FlutterFlow/flutterflow-issues/issues/3444).

Since this is a duplicate, I’ll mark it as such to consolidate efforts and keep everything organized. I’ll also internally link your report to ensure the team has access to your evidence. Thank you for bringing this to our attention, and we appreciate your patience!
