### ISSUE TITLE
Cannot create/remove/connect Firebase project in new created branch

### ISSUE THREAD

**Issue by KittipochSae** [FlutterFlow/flutterflow-issues#3877]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have just created a new branch from the main branch that works properly and provides production service. Then, I cannot manage the Firebase setting of a new branch. I cannot manage the Firestore setup or deploy private API Config because it says `No Firebase project present in Firestore project.` I try disconnecting the Firebase project. It raised `FlutterFlow project not associated with this Firebase project.` So, there's no workaround to solve this problem anymore.

### Expected Behavior

Cannot remove the Firebase project after creating a new branch.

### Steps to Reproduce

1. Create a Firebase project with the main branch
2. Create a new branch.
3. Disconnect the Firebase project

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40if2D3M54mMhJ+avQb/lKijg6NH4/XZIJ0upBaCsofePrOpkAf8/7UFtUOeG7T39YOWCkinkX/MrHkfztO/EDNkyZG4RZyc1McjnzfEiuMoSIPq63b0YnQZtTfXLH1KSK2B5AXc9vdVFk6k+MDOvKQhLqHbLjNXowR+aoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/30dab193-5462-46b4-a3f7-a88b47f81ffe)
The main branch works just fine.

![image](https://github.com/user-attachments/assets/df8c7b72-1055-473f-bffa-4b00b61fe1a2)
![image](https://github.com/user-attachments/assets/d5da2f67-81d4-46d8-9685-a5fbb3365d21)
After creating a new branch, Flutterflow raised warnings about services related to the Firebase project.

![image](https://github.com/user-attachments/assets/f9ef084b-0f65-400b-801a-87139fce9237)
After trying to solve the warning, the error was raised `Error: No Firebase project present in FlutterFlow project. Please set your Firebase project ID in Firebase settings.`

![image](https://github.com/user-attachments/assets/2cd5229a-3acc-4b45-be71-df1f958e56fa)
So I tried to remove the connected Firestore project that was originally connected with the main branch. It raised `FlutterFlow project not associated with this Firebase project.`

### Environment

```markdown
- FlutterFlow version: v4.1.91 released September 12, 2024
- Platform: MacOS App, Web
- Browser name and version: Chrome Version 128.0.6613.138 (Official Build) (arm64)
- Operating system and version affected: MacOS
```

**Comment by Alezanello** [comment]
Hey @KittipochSea, Thanks for your report, So sorry you are experiencing this issue. I was not able to reproduce this on a blank project, but it is replicable on yours. That's why I'm suspecting this is a project-specific issue and our support team is our best chance to get it solved. Do you mind following up with them? You can do that either by email: support@flutterflow.io or using the in-app chat inside of FlutterFlow. <br><br>I'm going to close this issue since this tracker is specifically for bugs reproducible from blank projects. <br><br>If you were able to reproduce this on a blank project as well, please let us know and provide the bug code of that project. <br><br>Thanks so much!

**Comment by instantsoftgithub** [comment]
I encountered the same issue. To reproduce it, starting from a functional project already configured with Firebase, create a new branch. In this new branch, it will not be possible to start test mode because it will show index update errors. You won't be able to create a new project either, as it will indicate that a project already exists, even though you won't be able to connect to it or identify the connected project. It will also not be possible to remove the connected project. In other words, it's not possible to proceed with development.

**Comment by KittipochSae** [comment]
Hey @Alezanello, a person facing the same issue as @instantsoftgithub faces the same issue. Could you reopen the issue?

**Comment by dariepl** [comment]
Had a similar issue. You could try this:
Check  “Custom code”, at Custom files at “main.dart” so that at “final action” there is no function that refferes to Firebase. 
After that you can merge/ rebranch/ reconnect firebase.

![final actions initialize ](https://github.com/user-attachments/assets/1d16ce5f-c5dd-4461-afaf-483892bd1ed6)

**Comment by instantsoftgithub** [comment]
> Tive um problema semelhante. Você pode tentar o seguinte: Marque "Código personalizado", em Arquivos personalizados em "main.dart" para que em "ação final" não haja nenhuma função que se refira ao Firebase. Depois disso, você pode mesclar / reramificar / reconectar o firebase.
> 
> ![final actions initialize ](https://private-user-images.githubusercontent.com/175425394/370484857-1d16ce5f-c5dd-4461-afaf-483892bd1ed6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTk4NjUsIm5iZiI6MTcyNzI5OTU2NSwicGF0aCI6Ii8xNzU0MjUzOTQvMzcwNDg0ODU3LTFkMTZjZTVmLWM1ZGQtNDQ2MS1hZmFmLTQ4Mzg5MmJkMWVkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQyMTI2MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmI2YjE2ZTVkNjdjNjJhOGY1ZjQ4NjE1YWQ3ODkwYTMxZDg2NThjNDQ1MTI3MTdiNDE1ZDc4M2FiMzQ3ZjY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ej9QU2oksRquSxbjWpzZXcJBXGBIhUPKxL_peoUemuM)




but I don't have any custom code in my project

**Comment by AndreSchm** [comment]
I have the same issue after creating a new (first) branch today:
![1](https://github.com/user-attachments/assets/55826fb5-700f-453b-a65e-0c13b6377742)
![2](https://github.com/user-attachments/assets/b83e2376-1a24-4f38-b19d-6e56ed477c31)
![3](https://github.com/user-attachments/assets/cb9160ae-df36-44f2-a391-41e20da92cc2)

**Comment by instantsoftgithub** [comment]
After a huge exchange of emails with support, all they said was to create a new project in Firebase from Flutterflow, I've done it more than 7 times with the same results observed by my colleagues.

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by AdrKacz** [comment]
The issue still persist, I can confirm that creating a new branch from main:
1. Prevent any update to the Firebase configuration (*I understand this can be by design)*
2. Prevent to click on "Regenerate Config Files" (which is useful when you `main` in on Production environment but your feature branches need to be on Development environment, both environment being linked to a different Firebase project)
3. All option when it's needed to deploy to Firebase are marked in red with "Not deployed", switching back to `main` branch without touching any "Deploy" button fix the issues which shows that everything was already deployed.

Can we have update on how to mitigate this issue (either with actions to perform or upcoming release with fix)? This issue prevent teams to use FlutterFlow, indeed the only branch where you can work is `main` as it is the only one reading Firebase deployment status correctly. However you really can't have engineers all working on the same branch at scale.

Thank you for your help and your great work to make development faster and easier.

@Alezanello

**Comment by AdrKacz** [comment]
I opened a new PR to keep track of this issue: https://github.com/FlutterFlow/flutterflow-issues/issues/4943
Please continue the discussion there if any.
