### ISSUE TITLE
Can't run by FF Desktop Windows

### ISSUE THREAD

**Issue by ImadBouirmane** [FlutterFlow/flutterflow-issues#3887]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

A conflict in dependecies for url_launcher with flutterflow_debug_panel

### Expected Behavior

It was working properly last hour and I re-install th app even that and still

### Steps to Reproduce

- Not related to this !

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WlcmA8Y91mMdA+Kr2YPlVimAXQkM7UI0/lcN+FAkaC7bvOowPQvj7PxFUOPGid2NAe079pGMX/MrXidriGPFfaDqCUaZS1c56egmVbH2lMq6QEb63b0RRPNJTFXa60JmNvhVCD7FedXAb7TmYAOuiSXTDCb7SDUY0ROa4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image](https://github.com/user-attachments/assets/71dba294-e56b-4918-b95e-511ee9beefdb)
![image](https://github.com/user-attachments/assets/24e0b472-351c-4660-93b5-121af7004acf)

### Environment

```markdown
- FlutterFlow version: v4.1.91
- Platform: Windows
- Browser name and version: chrome 125
- Operating system and version affected: Win 11
```

**Comment by Alezanello** [comment]
Hi there!

I'm sorry you're experiencing this issue. The good news is that we’re already aware of it, and a fix will be deployed soon! Since we already have a ticket open regarding this dependency conflict, I’ll close this issue as a duplicate. Please follow any updates on the original ticket here: [https://github.com/FlutterFlow/flutterflow-issues/issues/3873](https://github.com/FlutterFlow/flutterflow-issues/issues/3873).

Thank you for your patience!
