### ISSUE TITLE
Firestore Query Collection throws error if OR filter condition value on "array contains any" is empty list

### ISSUE THREAD

**Issue by leonardstiller** [FlutterFlow/flutterflow-issues#3894]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to query a list of documents (called "activities") from Firestore. I have two conditions I filter this list with:

- "createdBy" field (type user reference) equals authenticated user reference

- "sharedGroups" field (list of "groups" document references) contains at least one groups document where the authenticated user reference is a group member (members field is a list of user references of the groups document)

So the relevant document structure is:

users:

    reference

activities:

    sharedGroups (List<DocRef(groups)>)

    createdBy (DocRef(users))

groups:

    members (List<DocRef(users)>)

I was able to filter for the 1. condition. I was also able to filter for the second condition by creating a separate query in a container above where I query all groups documents where the members field contains the authenticated user reference and then using the result of that query to filter the sharedGroups field for that list with "groups Documents -> Reference mapping. I was also able to combine both filters with an OR statement which should produce the result of what I am trying to achieve. But if there are NO groups documents as a result of the seperated above query, I get an error (see screenshot). If there is a groups document returned everything works as intended..

### Expected Behavior

I would expect the query working even if an empty list is used. Also using the "filter on null values" should have an effect here imo which it doesn't as far as I can tell.
So I am missing the option to catch an "empty list returned" case here since Firestore seems to be unable to handle that on Firebase side.

### Steps to Reproduce

1. Create "Query Collection" to Firestore with two filters connected via OR
2. Make one of the filter conditions check for "array contains any" on an empty list

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfz8r13ItOseFK0L6IYcBWoGEsC1scTeUzlO1hdwwbI+P1PIYuOfSkYldVcuqHdAhifVqjnnIHwNbXhs7tN+0EPU+CQYhqz6ttUxDgfGq7V6qIEru8R3FPO/JMG37A4LaJrhF+ANNpV0Y1w2Chf+uub3qCf9qOYwx5e6fDbOY=

### Visual documentation

![sldLRnyJvc4PoLyjJVHqa](https://github.com/user-attachments/assets/4154b77d-c855-40d6-9c2b-a5b49e492bab)

### Environment

```markdown
- FlutterFlow version: Web
- Platform: iOS, Android, Online Emulator
- Browser name and version: -
- Operating system and version affected: -
```

**Comment by Alezanello** [comment]
It seems you're encountering a limitation with Firestore's querying capabilities. Specifically, Firestore does not support combining filters like `isEqualTo` and `arrayContainsAny` in a single query, especially when the second filter (in your case, `sharedGroups`) is an empty list. Firestore can't process queries where `arrayContainsAny` is used with an empty list, as there's no valid result for such a condition.

### Why This Query Isn't Supported:

* **Combining** `isEqualTo` and `arrayContainsAny`: Firestore allows certain filter combinations, but using `isEqualTo` alongside `arrayContainsAny` in this context isn't one of them.
* **Empty List in** `arrayContainsAny`: Firestore can't process queries where the list provided to `arrayContainsAny` is empty. If attempted, it results in an error because there’s no way to match an array with "any" of zero elements.

Let me know if you need further clarification or assistance!

**Comment by leonardstiller** [comment]
Thanks for your summary. 

Wouldn't it be possible to catch the case of an empty list in the Flutter flow logic? Since it works if the list is not empty, one could check for this case and disregard the filter condition in this case. Similar to "filter on null values" but something like "filter on empty list values". 
Otherwise I don't see a good solution to my use case without braking the realtime change listening functionality. And Flutterflow could enable a use case here that Firestore natively doesn't support.
