### ISSUE TITLE
"UI Rendering Issue" or "UI Layout Issue" in test mode

### ISSUE THREAD

**Issue by cesarcostar** [FlutterFlow/flutterflow-issues#3909]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm working with FlutterFlow models, and the UI elements are not displaying correctly during test mode. Some widgets and text appear to be missing or are not rendered as designed.

### Expected Behavior

All UI elements from the FlutterFlow models should display as designed in the editor, with all text, buttons, and icons appearing in their correct positions and layout.
![Captura de tela 2024-09-26 102946](https://github.com/user-attachments/assets/28a90c90-adff-4444-bca5-30fe0ae8f996)
![Captura de tela 2024-09-26 103130](https://github.com/user-attachments/assets/4a347dbb-c3bd-4b50-916f-2a7d27b7dfce)

### Steps to Reproduce

test mode

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFflcn15ZVgoctH176IKcBWpCIWQmUcTLkvjuphcz8YGIztBJh/PMjOQFJpXczgY1NhHFmb/WAC0PTLiM7pF/U7AymZY75xzLhcSjuWRXq8RpDQPpOSY2pAFplnIWK4y8GFvBZCFNRvLF4O2F+PfOmvXgjsN5O/Zwh9f6PHaOI=

### Visual documentation

![Captura de tela 2024-09-26 103130](https://github.com/user-attachments/assets/4379b159-c999-45d8-a2fb-7d3f97cba026)
![Captura de tela 2024-09-26 102946](https://github.com/user-attachments/assets/b84febb9-9c07-46f0-a3e9-312a0a3c8111)

### Environment

```markdown
FlutterFlow version: v5.0.0+ (released September 24, 2024)
Platform: Production
Browser name and version: Chrome 129.0.6668.71 (64-bit)
Operating system and version affected: Windows 10 Home Single Language, Version 22H2, Build 19045.4894
```

**Comment by Alezanello** [comment]
Hello!

This issue typically occurs when your app has multiple languages, but not all content has been translated yet. You might also notice this behavior inside the project if your computer's language settings differ from the default language of your app.

For example, in your project where both English and Portuguese are available: if you've built everything in English but your computer is set to Portuguese, when you open Test Mode, it will default to Portuguese. Since the content hasn't been translated, it may appear blank until you add the translations in **Settings** -> **Languages**.<br><br><br>How to check it in your project without going to test:

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/cd541fc5-794b-425c-968d-2bb8cf329f6e/43aa8aec-6df2-4b4b-a4c9-2ef6676edb5e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9jZDU0MWZjNS03OTRiLTQyNWMtOTY4ZC0yYmI4Y2YzMjlmNmUvNDNhYThhZWMtNmRmMi00YjRiLWE0YzktMmVmNjY3NmVkYjVlIiwiaWF0IjoxNzI3MzU4ODcwLCJleHAiOjMzMjk3OTE4ODcwfQ.IgmVmImAiW8Rd6v8ZOZeOWOFrQqsBdGNGFUCRZJwzb8 " alt="languages.gif" width="888" height="822" />

**Comment by cesarcostar** [comment]
10x mate :)

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
