### ISSUE TITLE
Can't add custom widget to widget builder (the first time)

### ISSUE THREAD

**Issue by kium-one** [FlutterFlow/flutterflow-issues#3918]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When adding a component that uses a widget builder, I'm opening the variables to select a custom widget but once I press Confirm, the widget selection stays "unknown".
In order for this to work, I need to select a normal component first, and then change to a variable -> custom widget.
It's a small bug but I thought it wasn't possible to select custom widgets at all because of that.

### Expected Behavior

Selecting a custom widget and saving should work right away.

### Steps to Reproduce

1. Create a boilerplate custom widget
2. Create a component
3. Add a parameter "Widget builder" to the component
4. Add a widget builder to the component's widget tree
5. Add the component to a page
6. Go to the component's "widget builder" property and open the variables right away (without selecting a standard component) and try to select the boilerplate custom widget.
7. Press Confirm. The property remains "Unknown".

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITESivHqx89gofVa15D2avlqhQIgQ0QnU7gnlO1ucx43JZPmEOwMePfsS0NKTN+bSn1EAVGj8UMG097Jjd7PEsYFEzecGpxN0JVPWz3NWj2uMrnQEs+wWHJSI99PfWHD5KbQ2yRvBNpZW3dl1DnyNq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

<img width="540" alt="image" src="https://github.com/user-attachments/assets/5144fc73-a0d0-4af1-87c3-39a7ba46d66c">

### Environment

```markdown
- FlutterFlow version:  v5.0.1 released September 26, 2024
- Platform: MacOS
- Browser name and version:
- Operating system and version affected: MacOS 14.6.1
```

**Comment by Alezanello** [comment]
Hello!

Apologies for the delayed response. I’ve been working to replicate the issue you reported. It appears that the engineering team has applied a patch that prevents adding Custom Widgets to the Widget Builder. From what I can see, this is now the expected behavior.

Could you please try to replicate the issue on your end? For me, the Custom Widget option appears in red when I attempt to select it.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f0be6233-2b6e-4178-b35f-104c5d08f665/e4ea8208-c691-4c36-9770-2e75cb01081b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMGJlNjIzMy0yYjZlLTQxNzgtYjM1Zi0xMDRjNWQwOGY2NjUvZTRlYTgyMDgtYzY5MS00YzM2LTk3NzAtMmU3NWNiMDEwODFiIiwiaWF0IjoxNzI3ODEzMDU2LCJleHAiOjMzMjk4MzczMDU2fQ.znCBvrHwNWwA-yljCL_Hs0cu74evlLzG0nr940bCmdU " alt="image.png" width="322" height="300" />

Let me know if you're seeing the same behavior, or if there's anything else I can assist you with.

Best regards,<br>Azanello

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by kium-one** [comment]
@Alezanello sorry I answered by email and it didn’t go through.
I meant the widget selection itself, not the preview component like in your screenshot (which doesn’t work for custom widgets). Does it work for you?
