### ISSUE TITLE
 Flutterflow web test mode having cache issue

### ISSUE THREAD

**Issue by dbfcode** [FlutterFlow/flutterflow-issues#3919]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Changes are not being updated in the web test unless I clear the cache on **each** run.

### Expected Behavior

With each test/instant reload, correctly update the changes

### Steps to Reproduce

Run the web test

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

  there's no report code.

### Visual documentation

  lllll

### Environment

```markdown
- FlutterFlow version: desktop
- Platform: web test
- Browser name and version: chrome - Versão 129.0.6668.70 (Versão oficial) 64 bits
- Operating system and version affected: windows 11 - Flutter version is 3.22.2
```

### Additional Information

that's all

**Comment by dbfcode** [comment]
FlutterFlow v5.0.1+ released September 26, 2024
Flutter version is 3.22.2

**Comment by rzambroni** [comment]
Hi there,

Thank you for your report! I tried replicating the issue in my own projects, but everything seems to be working as expected on my end.

Could you let me know if the issue occurs with all changes, or is it just certain changes that aren’t reflected? Also, just to confirm, when reloading the testing session, are you using the instant reload button rather than refreshing the page (F5)?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/823d39a4-c63d-409a-8647-c37423b4d5f0/62a33c75-faa7-4c1f-b72b-8f70f76ad639?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84MjNkMzlhNC1jNjNkLTQwOWEtODY0Ny1jMzc0MjNiNGQ1ZjAvNjJhMzNjNzUtZmFhNy00YzFmLWI3MmItOGY3MGY3NmFkNjM5IiwiaWF0IjoxNzI3NDcwNTk4LCJleHAiOjMzMjk4MDMwNTk4fQ.hdRENn_2EhHfOrRaIcdqSyf7Yq26Dc6cRzeLT1z3hIs " alt="image.png" width="484" height="237" />

Since appears that you are using the Windows desktop app, i would recommend checking if the problem doesn't occur on the [web app](https://app.flutterflow.io), just to discard if this is a windows specific issue and a valid workaround.

Your feedback will help us investigate this further!

**Comment by dbfcode** [comment]
Yes, i'm using the Instant Reload always and i have tryed using the browser refresh too. Acctually, it only works if i clean the cache, even in another browser, like Edge. This problem occurs in the desktop version, i haven't tested in the web version.

**Comment by rzambroni** [comment]
I wasn’t able to replicate the issue on my Windows desktop either. As a next step, you might want to try clearing the contents of the following fo

`C:\Users<user_name>\AppData\Roaming\FlutterFlow\flutterflow`

Please let me know if this resolves the issue. If not, it may be related to your specific configuration. In that case, reaching out to our support team would be the best option to get this resolved. You can contact them via email at **support@flutterflow.io** or through the in-app chat in FlutterFlow.

I appreciate your patience, and I hope this helps!

**Comment by dbfcode** [comment]
thanks
