### ISSUE TITLE
Condition to check the Number of Items in a list is broken

### ISSUE THREAD

**Issue by henrroga** [FlutterFlow/flutterflow-issues#3925]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Trying to select the Number of Items option when doing a conditional visibility check doesn't work, it automatically deselects it.

### Expected Behavior

The Number of Items option should be selected and we can compare it with any number.

### Steps to Reproduce

1. Query an API call parsed as a list data type or Supabase table rows
2. Try to check if the number of items is greater than 0 in a conditional visibility option
3. The option Number of Items will not be selected

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFThcj6389Om+FC+KriL8BKqDssGUMcWOdEl+tuZwgbIoznBuwXPczCUFNoUsOqaVNcOVGlkmYCw8rti9mSDfkrFAeqRbU/z85yWD3ke2inRrawPJeCSmpTGeVNCBWZ58OzmBNSGNBtL2wh22GqJd+sZDPDFOu/Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/abe76d92-7f4e-4e1d-aed1-ef26d4490a75

### Environment

```markdown
- FlutterFlow version: v5.0.0+ (released Sep 27, 2024)
- Platform: Web
- Browser name and version: Brave Version 1.69.168 Chromium: 128.0.6613.138 (Official Build) (arm64)
- Operating system and version affected: macOS Sonoma 14.1.1
```

**Comment by Alezanello** [comment]
Hello!

To check a condition (such as "greater than 0" or any other condition related to the number of items), you need to select the "Single Condition" option first. We are aware that, prior to the recent UI update, unassignable variables were highlighted in red. We're currently working on an update in version 5.0 that will make everything dynamic (as mentioned in the FFDC), which is why you no longer see the red indicators.

I apologize for any inconvenience this may cause during development, and we appreciate your understanding as we work on improving FlutterFlow!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
