### ISSUE TITLE
FlutterFlow deploying Incorrect Firestore Rules

### ISSUE THREAD

**Issue by Kato-Official** [FlutterFlow/flutterflow-issues#3927]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When deploying new rules upon deletion or creation of new collection the rules are deployed incorrectly and are not recognized even when deployed. [(https://dummy-1d799.kxcdn.com/videos/Flutterflow.mp4)](url)

### Expected Behavior

To deploy the correct rules and recognize the rules.

### Steps to Reproduce

Please see video attached. [(https://dummy-1d799.kxcdn.com/videos/Flutterflow.mp4)](url)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTjsmAsItNm7RG+KnTKPpvoCEUGUMdXOczitVEew4bCIj4ELMQfczCUFVoTcyzaHNIHlGLvD0e06nSj4bLOvk6H06bRbpiyZN+TRPPbEK7RYSYEs2sdHJAO8VYCH6705+KnglDLutpWFlnw16QH96sZz6Cf9qOYwx5e6fDbOY=

### Visual documentation

[(https://dummy-1d799.kxcdn.com/videos/Flutterflow.mp4)](url)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released September 27, 2024
Flutter version is 3.22.2
- Platform: Web & Mac Desktop
- Browser name and version: Chrome
- Operating system and version affected: Mac
```

### Additional Information

Hi, hope you are well. This bug is really critical (for my case at least). Thanks for looking

**Comment by SagarChandra07** [comment]
try this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme

you may need to install the c compiler

**Comment by Kato-Official** [comment]
Update: [https://dummy-1d799.kxcdn.com/videos/Update.mov](url)
FYI: I made a screen-recording and is mov extension so it will download when open link. Cheers

**Comment by Kato-Official** [comment]
Temporary Solution: [https://dummy-1d799.kxcdn.com/videos/temporary_solution.mov](url)

**Comment by Alezanello** [comment]
Hello,

I'm having trouble downloading the video, as the link directs me to this GitHub page: [https://github.com/FlutterFlow/flutterflow-issues/issues/url](https://github.com/FlutterFlow/flutterflow-issues/issues/url). Could you please upload the video to another platform or use a tool like Loom that allows for easy sharing once the recording is complete?

I appreciate your help and look forward to receiving the video.

Best regards,<br>Azanello

**Comment by Kato-Official** [comment]
Hi @Alezanello thanks for your message. To open the first mp4 you can simply copy and paste the link in any browser (please see here). 

https://github.com/user-attachments/assets/f0f4b921-53ec-4b10-a3b3-827140880fa7

To open the other 2 .mov same (However being extension .mov it will download them). (Please see here). 

https://github.com/user-attachments/assets/ef211c74-170c-424a-bc2c-5833be2845f0

Cheers mate

**Comment by Kato-Official** [comment]
Hi @Alezanello, any update?

**Comment by Kato-Official** [comment]
Hi @Alezanello , hope you are well. Are there any updates?

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?<br>We sent a lot of fixes yesterday!

**Comment by Kato-Official** [comment]
Hi, thanks for the reply. Yes, the bug is still there. [https://dummy-1d799.kxcdn.com/videos/bug.mp4](url) Please copy and paste this link on any of your browser. If you click it directly from github won't work. Please send me a message when this bug is fixed. To Recap: the bug displays wrong firestore rules on what to be changed "Diff", "After", it also deployes the wrong rules, in particluar the "Delete" previous rules does not work. Cheers mate

**Comment by Kato-Official** [comment]
FYI the video send is from a fresh project. Cheers

**Comment by Alezanello** [comment]
Hello,

I sincerely apologize for the delayed response. This behavior is intentional—FlutterFlow will only modify the Firestore rules of the collections present in your project. This approach ensures that, if you have multiple FlutterFlow projects using the same Firestore database, one project’s deployment won't inadvertently override rules for other collections.

If you wish to delete rules for old collections, you will need to manually remove them directly from the Firestore rules.

Thank you for your understanding! Let me know if you have any other questions.

**Comment by Kato-Official** [comment]
Hi @Alezanello,

I noticed that you closed this bug, but I believe there are still some unresolved points that need clarification.

You explained:

"FlutterFlow will only modify the Firestore rules of the collections present in your project."

However, as clearly demonstrated in the video, that is not what's happening. Additionally, you mentioned:

"If you wish to delete rules for old collections..."

The issue isn't with old rules, it's with current rules NOT being deleted when done from the FlutterFlow project itself. To replicate the issue, simply create any collection using the FlutterFlow interface and then delete it. You'll notice that the Firestore rules for that collection will not be removed, which contradicts your explanation.

Also, based on your explanation, should we entirely disregard the "Delete Collection" button? Because it seems to neither delete the collection nor handle its associated rules correctly “when done from your FlutterFlow project" as expected. 

![Group 1](https://github.com/user-attachments/assets/f91a6766-a795-44f8-ad84-eef0f93b3185)


Moreover, regarding the checkbox option:

"If collection excluded from rule generation" 

![Frame 2](https://github.com/user-attachments/assets/929a008c-9796-41ee-8d2e-48ba10b0a7d1)


It would then mean that this checkbox only controls rule generation for the "create, read, and update" sections of CRUD operations according to your explanation. This behavior is misleading because one would assume that if a collection is excluded from rule generation, it would apply to all CRUD.


Could you please confirm whether this behavior is intended and not a bug? 

Thanks for your attention to this!

**Comment by Alezanello** [comment]
Hello Kato,

Just to clarify, this issue is still open and has not been closed yet.

Let me try to explain the situation in more detail:

For example, imagine you have **Project A** with the following collections:

1. Collection A
2. Collection B
3. Collection C

When you deploy these collections, both the Firebase Console and FlutterFlow will display rules for all three collections as being deployed.

Now, let's say you delete **Collection B** from your FlutterFlow project. When you go to deploy the rules again, FlutterFlow will only update the rules for **Collection A** and **Collection C** because **Collection B** was deleted from the project. As a result, the rules for **Collection B** will remain in place until you manually remove them from the Firestore Rules in the Firebase Console.

Why is this the case?<br>Once **Collection B** is deleted in FlutterFlow, the platform no longer tracks it, but it doesn’t automatically remove its associated rules. This is because you may still be using that collection in production or in another project, and FlutterFlow avoids deleting or overriding rules that it no longer recognizes.

For instance, consider an example like an Uber-like application with two separate apps—one for Drivers and one for Riders.

**Project A** (Driver App) has collections:

1. Users
2. Services
3. Bill History

**Project B** (Rider App) has collections:

1. Users
2. Services

The only difference between the two projects is the **"Bill History"** collection. If both projects use the same Firebase project, it would be problematic if deploying Firestore rules from **Project B** deleted the rules for **"Bill History"** in **Project A**. Since FlutterFlow doesn’t track the **"Bill History"** collection for **Project B**, it won't modify or delete rules for collections it no longer sees.

This behavior ensures that FlutterFlow never deletes or overrides Firestore rules for collections that are not found in the current project to prevent unintended data access issues.

**Comment by Kato-Official** [comment]
Hi @Alezanello and thanks for the reply, yes that makes perfect sense, as it's definitely safer, so just to reconfirm when I delete a collection pushing the button in reality we are just kind of "removing" from FlutterFlow interaction with Firebase Backend, but in reality we are not "really" deleting it, right? It's more of a UI thing to keep it neat and clear, right? I mean that's why when we delete for example the collection we get the warning that the rules are not up to date. Correct?

**Comment by Alezanello** [comment]
That's Correct!!<br>All schema on Collections is just FF Side, the only thing that gets to Firebase are the rules and indexes when they are deployed!
