### ISSUE TITLE
Unable to Deploy Indexes and Firebase Push Notification. Says Failed to create server directory

### ISSUE THREAD

**Issue by Mdmuzammil16** [FlutterFlow/flutterflow-issues#3936]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Not able to upload firebase indexes and push notifications. Says Failed to create server directory

### Expected Behavior

The indexes and notification should be deploy

### Steps to Reproduce

Create a project
Add Firebase
Make some collections & queries
Upload indexes

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4SiMjfsIh2rscA0arcccdFmmMsKWE7ap03lNVqEU0aIoD1OpkPXOmmSFRuQtOmTFc2eWCKozke/vOLhubIN/U3AwWVb4h8/rl2ZA3ifFyubrqNOqjhWmtfHtpKCFSB1J6JgRYlPbB0SHwMwV+EHuuiTXbfJbm3NUYjAsqXJqjUo3PuQ0SLb3kNh1JWeC/v

### Visual documentation

<img width="1030" alt="Screenshot 2024-09-29 at 13 55 19" src="https://github.com/user-attachments/assets/cc89fc05-ed40-4ab1-ae5a-8109936be986">

### Environment

```markdown
- FlutterFlow version: 5.0.1
- Platform: MAC
- Browser name and version: CHROME
- Operating system and version affected:  ANDROID/IOS/WEB
```

**Comment by rzambroni** [comment]
Hi @Mdmuzammil16,

Thanks for your report!

I wasn't able to replicate the issue on my own projects, as everything seems to be working as expected. While checking yours, it appears that your indexes were deployed correctly.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/44014862-5f82-418f-ad0e-66e7adf0dba9/0b820270-873a-47ee-b107-cf3c65b3a175?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80NDAxNDg2Mi01ZjgyLTQxOGYtYWQwZS02NmU3YWRmMGRiYTkvMGI4MjAyNzAtODczYS00N2VlLWIxMDctY2YzYzY1YjNhMTc1IiwiaWF0IjoxNzI3NzEzMjYwLCJleHAiOjMzMjk4MjczMjYwfQ.byj-UMo-0XwmLkLR32JxRCLeMpMjiEbV8N4UN0jExU8 " alt="image.png" width="884" height="185" />

It’s possible this was due to a temporary outage. Could you please confirm if everything is working fine on your end now?

Looking forward to your response.
