### ISSUE TITLE
Firebase Remote Config and the Firebase Installations service triggering rate limiting on iOS 18

### ISSUE THREAD

**Issue by sanjayelate** [FlutterFlow/flutterflow-issues#3945]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When trying to test a build on a simulator with iOS 18, the app just shows a white screen and doesn't load. However, the app works fine with iOS 17. This has resulted in my update being rejected by Apple

iOS 18 Simulator Key Error from device logs:

[firebase_remote_config/internal] Failed to get installations token. Error : Error Domain=com.firebase.installations Code=2 "Too many server requests."

The difference in the device logs between the working iOS 17 simulator and the iOS 18 indicates that the app is making too many requests to the Firebase Installations service, resulting in rate limiting. 

### Expected Behavior

App should load but instead the app shows a white screen and doesn't proceed further. 

### Steps to Reproduce

Try iOS 18 simulator with build using Firebase and remote config

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfk8n1z892pbwC+a6JLMJKiSkXNW0cTIMziNZ+exUbfaL1Bux3ZM6kVxJoTeqraVNcAGaKjjgdpPzxufOSU8A5BxGtRYB6ypNpFjree2imVL6kBqW7dXJCBeZTGB2m5Kek2R5COsZpSGMuw1OyN+mRVjLDFOu/Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-09-30 at 22 23 54](https://github.com/user-attachments/assets/0811d9bf-1db8-4f0b-8efe-f4141cef9083)

### Environment

```markdown
- FlutterFlow version: 5
- Platform: iOS 18
```

**Comment by Alezanello** [comment]
Hello!

It looks like this issue might be related to the API Token rather than FlutterFlow itself. I recommend regenerating the config files from Firebase Settings to ensure everything is set up correctly. Additionally, please check if the iOS key (created by Firebase) is properly configured in the GCP console.

When troubleshooting, it’s important to focus on the error message "Failed to get installations token" rather than "Too many server requests," as that will help you debug more effectively. For more details, you can refer to this helpful StackOverflow post:<br>[StackOverflow Post](https://stackoverflow.com/questions/71949005/unable-to-get-firebase-messaging-token-error-messaging-unknown-too-many-se)

Let me know if you need any further assistance!

**Comment by sanjayelate** [comment]
Thanks @Alezanello, the api key was the issue and this is now resolved.

**Comment by sanjayelate** [comment]
Hi @Alezanello, thanks! I was able to resolve the issue with those suggestions
