### ISSUE TITLE
iOS app crash

### ISSUE THREAD

**Issue by Emvipy** [FlutterFlow/flutterflow-issues#3996]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

In this app we have a section called Community, it is a facebook wall and then we have the comments of each post (both are ListView).
In iOS devices (because in Android and iOS simulator I have not been able to reproduce it) when you alternate sometimes between these 2 screens, the app closes completely. Attached video.

### Expected Behavior

not to be closed.

### Steps to Reproduce

1-Click on the comments of a post
2-back
3-click on comments of the same or another post
4-repeat

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klPHl05NOm9tJ7s7TbflvgScQH0c3TL07r+5xb0gvIrbyOu9/Ovf8VE9WTd+mS2lhHFGb8T0GwN6JiPHtF/leOU6bfZx4+odqcguUe3q8RpCUEKiCXEdtEZpbGWqn4Zi3gSRQVdtaSVIj3EOABuu8Qi7sJ5O/Zwh9f6PHaOI=

### Visual documentation

https://github.com/user-attachments/assets/a51aadd3-3e73-4fd6-8538-6638634d4699

https://github.com/user-attachments/assets/b416ce36-20d9-4acc-964c-59d6a1c1ba67

https://github.com/user-attachments/assets/d69af172-3fa9-41c6-af3f-3f6840dda42b

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.3 released October 4, 2024
Flutter version is 3.22.2
- Platform:
- Browser name and version:
- Operating system and version affected: iOS1 18
```

**Comment by rzambroni** [comment]
Hi there,

After reviewing the video, it looks like the app might be experiencing a memory-related issue. When the app surpasses a certain memory threshold, iOS may close it automatically to maintain the device's performance. This often happens if there are many images being loaded or if they are not optimized.

I recommend reviewing the image handling in your app to ensure they are optimized for performance. Additionally, integrating a tool like Crashlytics could provide more insights into the root cause of the crashes, helping you address them effectively.

Since this issue seems specific to the app/project and not directly related to FlutterFlow, I'll go ahead and close this ticket for now. 

Thanks.
