### ISSUE TITLE
Placepicker label reset despite selection still active

### ISSUE THREAD

**Issue by max-h-silverman** [FlutterFlow/flutterflow-issues#4007]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When a placepicker is hidden and the unhidden, the label resets to whatever the initial state is, but the place picker itself retains the selection, which is confusing to the user.

### Expected Behavior

Either the label should retain the selection name or it should reset the selection and show the initial state.

### Steps to Reproduce

1. create a page
2. put a place picker in it
3. add a toggle to show and hide the place picker
4. select a location
5. hide and un-hide placepicker

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT48kvHqw4ZJpbxe1s/qbcExnj8vKUM7UOdJldZ9ewI8J4jPPJkAZffARFJVOPG+TVc2PmCKmToyp+iLhebIN/cEaBWCGZs4wbp+Zg6XZz+mWpvWDcy8PHJBFtpKCByM5qunpCN7ObdfdEIb1F6TNe++SjXtNoDHC20BJ/ihELv4o3/uQ0SLb3kNh1JWeC/v

### Visual documentation

https://github.com/user-attachments/assets/9441db84-544f-48e3-b278-b3360b77e6c9

### Environment

```markdown
- FlutterFlow version: 5.0.3
- Platform: osx
- Browser name and version: chrome latest
- Operating system and version affected: Android
```

**Comment by paulperez-dev** [comment]
Hi @max-h-silverman,

It seems the steps in the video don't match the ones described here. Could you please verify the steps or check the video for consistency?

Thank you for your help!

**Comment by max-h-silverman** [comment]
@paulperez-dev  it's the same whether the place picked is hidden by a page state or by navigating back or forward from a pageview page. If you need the video to match exactly then you can use the pageview case as the steps to reproduce.

**Comment by rzambroni** [comment]
Hi @max-h-silverman,

Unfortunately, this is the expected behavior of the PlacePicker widget, as it loses its state when it becomes not visible.

We’re aware of the limitations of this widget, and we understand that it’s not ideal. Many users opt for custom implementations to work around these issues, but we recognize that this isn't the most convenient solution. Rest assured, there’s already a feature request in place to improve this experience by moving to a better default implementation in the future.

We sincerely apologize for the inconvenience caused and appreciate your understanding as we work toward enhancing the platform.
