### ISSUE TITLE
Visibility condition not working

### ISSUE THREAD

**Issue by lahlis** [FlutterFlow/flutterflow-issues#4008]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Visibility conditions are not working for two Rows that contain Buttons. Neither Button is obeying the conditions.

### Expected Behavior

O botão "Continuar" deveria aparecer na última página do PageView (PageView Current Index == 2) e o botão ">" deveria aparecer apenas nas duas primeiras páginas (PageView Current Index < 2)
![Captura de tela 2024-10-08 152333](https://github.com/user-attachments/assets/4a691cec-722b-442b-9a97-f2d86933531a)
![Captura de tela 2024-10-08 152319](https://github.com/user-attachments/assets/714e2777-746f-494f-b3dd-42218c2a9740)

### Steps to Reproduce

1. Create a Container
2. Add a Column widget
3. In Column, add a PageView widget and two Rows
4. In one Row, add an Icon Button ("<"). In the second Row, add a Button ("Continuar").
5. Set conditional visibility in each Row
6. In first row: PageView Current Index < 2
7. In second row: PageView Current Index == 2
8. Click Run
9. Observe that button of second row ("Continuar") doens't appear when PageView Index == 2

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8gl8j6yItPxdtH7qXxbfpajikXQlAnRYIriet+VRAdCLasB413e8/7cRZtZMiBan1EP2f/8XgypvDTvePLFfo9PiieGdg7ybtiTArgYH+6M6qJELqdPGhABdxhfXWHzbWC2RJ+ItZuc1Jk6mb7Je+yQjLfQJzSOjJMJeSbJrvA+krgKxzCXn0Jg1ZSfCvr

### Visual documentation

https://github.com/user-attachments/assets/dcc75940-095c-43e8-8bf0-bf1fe0ca0804

### Environment

```markdown
- FlutterFlow version: v5.0.2
- Platform: Web and Windows Desktop
- Browser name and version: Chrome 129.0.6668.90
- Operating system and version affected: Windows 11
```

**Comment by Alezanello** [comment]
Hi there!

The issue you're experiencing might be due to the current page not being rebuilt when the index is updated, which affects the conditional visibility trigger. Here's a possible solution:

In your **PageViewMobile** widget, go to **Actions**, and under **"On Page Swipe"**, set the action to **"Update App State"** without selecting any variable. Then, make sure to check the option to **Rebuild Current Page**.

If that doesn't resolve the issue, try selecting **"Rebuild All Pages"** instead.

Let me know if this works or if you need further assistance!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/223ed0ed-6cc1-471f-b1ad-b01e25631d5f/3c3a52cb-f051-455d-ba02-9cfcc2a3dc8e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8yMjNlZDBlZC02Y2MxLTQ3MWYtYjFhZC1iMDFlMjU2MzFkNWYvM2MzYTUyY2ItZjA1MS00NTVkLWJhMDItOWNmY2MyYTNkYzhlIiwiaWF0IjoxNzI4NDc4MDUzLCJleHAiOjMzMjk5MDM4MDUzfQ.LlvN8JWEBJLdfGzy6vSoiSQw547cjcCxrvXb_C2BE_E " alt="image.png" width="1917" height="908" />

**Comment by lahlis** [comment]
It worked! Thanks!

**Comment by Alezanello** [comment]
I’m glad everything is working as expected now! I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
