### ISSUE TITLE
Using Canvas Kit option make localisation flag not appearing 

### ISSUE THREAD

**Issue by sergedahdouh** [FlutterFlow/flutterflow-issues#4017]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When i select the canvas kit option and publish my web, the localization flag is not showing.

### Expected Behavior

When i select the canvas kit option and publish my web, the localization flag should appear.

### Steps to Reproduce

1. create project
2. add localization  widget 
3. select canvas kit 
4. publish the app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ol/Lcw491xLRG1r6JKvlVhSQRJm17R4IZiMpOEC0jF7KuBqQMPOPsVFdvXse4aVNcPE6koE0G3NbrkfPDO/A5OQWrfpRhyc5QVjr0e2iWR5iQPJCdOXJCJ8VbfG7A1rbQrSVCWel2V1ph3F6MGe6idHLDFOu/Zwh9f6PHaOI=

### Visual documentation

<img width="1624" alt="ada" src="https://github.com/user-attachments/assets/3861a1d6-97e0-4d93-ae4b-44c881216458">

### Environment

```markdown
- FlutterFlow version: 5.0.2+ 
- Platform: mac 
- Browser name and version: chrome 
- Operating system and version affected: os
```

**Comment by rzambroni** [comment]
Hi @sergedahdouh,

Thank you for your report. Please keep in mind that enabling CanvasKit can introduce some incompatibilities that may require adjustments, and since it is still in beta, there could be some bugs that make it less suitable for production apps.

Regarding the issue you're experiencing, it appears that images might be getting blocked. There could be several possible causes based on your specific implementation. I recommend reviewing the [documentation](https://docs.flutterflow.io/deployment/web-publishing/#advanced-web-settings), as it may provide insights that could help resolve the problem.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/e3805032-d870-4f24-9788-eab033f7da34/69102940-4d2f-41ae-9b9a-2d75db971198?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9lMzgwNTAzMi1kODcwLTRmMjQtOTc4OC1lYWIwMzNmN2RhMzQvNjkxMDI5NDAtNGQyZi00MWFlLTliOWEtMmQ3NWRiOTcxMTk4IiwiaWF0IjoxNzI4NTgzMjE3LCJleHAiOjMzMjk5MTQzMjE3fQ.7Cpa_3nlnd1DqFlDvqTtwp49SsXIjkFb_fNsMAXGuhk " alt="image.png" width="733" height="363" />

Hope that helps,

Thanks.

**Comment by rzambroni** [comment]
I'm sorry, i just noticed you are using the FF Default Localization Widget, i thought it was a custom implementation.

However, i could't replicate the issue by just enabling canvas kit, it might be it's usage in combination with other options, will take another look.

**Comment by sergedahdouh** [comment]
Actually, when you test it on test mode, the flag is appearing; however, when you publish, the flag is not appearing you can test it in my project

**Comment by rzambroni** [comment]
Yes, I see the issue. It doesn’t seem to be solely related to CanvasKit. I believe it’s the combination of CanvasKit with another option, possibly the "Use Original Engine Initialization." You could try disabling that setting while keeping CanvasKit enabled; this resolved the issue for me.

**Comment by sergedahdouh** [comment]
yes it works for me as well. i do not know what the issue is
