### ISSUE TITLE
 FormatException: SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2) 

### ISSUE THREAD

**Issue by metysj** [FlutterFlow/flutterflow-issues#4046]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I see the error mentioned in the title poping on the console when I test my app: "FormatException: SyntaxError: Expected property name or '}' in JSON at position 1 (line 1 column 2)" The source is obfuscated in main.dart.js:3978. It's easily reproducible as one just need to launch a debug session of my project, and open the debug console. The error repeats in a loop and appears on every page, so it doesn't seem to be a page related error.
![JSON parse errors - Screenshot 2024-10-12 022819](https://github.com/user-attachments/assets/68123ae3-f61b-4786-9450-3c965a95f934)

### Expected Behavior

No error messages.

### Steps to Reproduce

1. Open the Project
2. Run the project in test mode
3. Open the Developer Console in the browser 4
4. See the error messages that keeps popping up

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4sjM/lx41JpbxH1ar2a8B7/WYvNUc2a788scp/bxIgGIDzPOw+ZPWkS1VoZ7zgTFVmI0SmmnsdpvSPkfPTLvVfNU6tb758/89+agLyezina5OBCbrpOXElEtxjGhWc37S3gCZCBMxpc0Yu3VymCd6ucCzAHufHIndISq/LZO4=

### Visual documentation

![JSON parse errors - Screenshot 2024-10-12 022819](https://github.com/user-attachments/assets/04b6e35d-f8b2-4db2-a999-a64078ca20c7)

### Environment

```markdown
- FlutterFlow version: v5.0.0+ (released October 9, 2024)
- Platform: Web
- Browser name and version: MS Edge Version 129.0.2792.79
- Operating system and version affected: Windows 11 Pro 23H2 (Build 22631.4317)
```

**Comment by Alezanello** [comment]
Hi there!

I ran your project locally, and it seems the issue is related to AdMob trying to run in web (Test Mode). Could you please try running it locally to see if this is the issue you're referring to? Aside from that, I didn’t notice any other errors.

Let me know if that helps!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d6b177e2-89ef-4cc5-aae4-9b2f77f1dded/9017624f-73dd-41af-96cc-a698db5ebb96?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kNmIxNzdlMi04OWVmLTRjYzUtYWFlNC05YjJmNzdmMWRkZWQvOTAxNzYyNGYtNzNkZC00MWFmLTk2Y2MtYTY5OGRiNWViYjk2IiwiaWF0IjoxNzI4OTA2Njk2LCJleHAiOjMzMjk5NDY2Njk2fQ.mvIHfICp20epNOHVC3eL54XMwT32Ok7t-pOozGdCpqw " alt="image.png" width="949" height="980" />

**Comment by metysj** [comment]
Hello,
Thanks for your response, and sorry for the delayed reply. I'm curious to understand a bit more why AdMob would try to render on the web since I have the visibility of the control conditional to the platform not being web?
Also when you say running locally, are you suggesting I download the code and run it on a local server?

**Comment by Alezanello** [comment]
Hello!<br><br>When I say Locally is downloading the code in ZIP or via CLI and run it on your computer to see the error logs detailed correctly!

**Comment by metysj** [comment]
Oh I see. I could do that - it might take me a while however as I don't have a proper environment setup for this. One of the main benefits of using FF was "no-code" but I guess this is one of the gottchas.
If you are certain that this is something benign and caused by AdMod, I'm happy to just resolve/close this ticket.

**Comment by metysj** [comment]
Hello again,
I'm reviving this thread as I reproduced this error with another project I started, and that new project doesn't use AdMob at all, so I'm pretty sure the problem is not with AdMob.
