### ISSUE TITLE
Remove/add from List at Index not working.

### ISSUE THREAD

**Issue by buildthick** [FlutterFlow/flutterflow-issues#4052]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I'm using ListView's "generate children from variable" functionality so users can add/delete specific items from an unbound list. The number of items is based on appstate variable list of integers. However, the "remove from list at index" and "insert at index" functions simply add/delete from the _end_ of the list and _not at the index_.

This problem was also reported here and never resolved: https://github.com/FlutterFlow/flutterflow-issues/issues/3067

### Expected Behavior

"Remove from list at index" should delete specific list item, not only delete the last item in the list.
"Insert at index" should add list item wherever desired, not only add an item to the end of the list.

### Steps to Reproduce

1. Set appstate variable integer list, e.g "numberOfItems"
2. Create a listview in builder
3. Add container under listview, insert text widget for visibility, insert button icon with X, insert button icon with +
4. Navigate to listview's Generating Children from Variable
5. Name the variable "ItemNumber"
6. Set value to Appstate -> Map List Items -> Item in List
7. Find X button icon, define action -> update appstate -> Set field as "numberOfItems" appstate variable -> "Remove from List at Index"
8. Find + button icon, define action -> update appstate -> Set field as "numberOfItems" appstate variable -> "Insert at index"
9. Run Test Mode
10. Observe that X and + button only delete and add items to end of list, respectively 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wz8r15ZVNj7xa15DucsJanSQRNlw1bZZNmsNxTQE3F4urOowPXfnRalhoTN+idGNqL2H8kmYew9KNuNn2A+UnEzGBbL5a1LlcWj3jUnOiMrKOPLmRdHEmLNxJJVyg5JmC2yVCOtZiL1IM2U6qBuzISXfXHu/LPVUSDciJEK/Ao12pQ0SLb3kNh1JWeC/v

### Visual documentation

https://jmp.sh/hDgKz4c1

Jumpshare link of videoˆ

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.6+ released October 12, 2024 Flutter version is 3.22.2
- Platform: Web
- Browser name and version: Firefox 131.0.2
- Operating system and version affected: MacOS Sequoia 15
```

### Additional Information

Without this functionality I cannot develop the app. Dynamic user input is required to fulfill promised results, and I cannot preset a number of items because it varies greatly by user.

**Comment by buildthick** [comment]
Hey Paul, happy to exchange with you and to jump on a call if needed. Feel free to contact me via email. I suspect this is impacting anyone using shopping carts based on listview, and users effectively cannot manage their cart.

**Comment by buildthick** [comment]
Hello, any updates?

**Comment by buildthick** [comment]
Hello, any updates from FlutterFlow team?

**Comment by Alezanello** [comment]
Hello,<br><br>I apologize for the late response. Does this issue still persist, or was it fixed in the latest FlutterFlow updates?

**Comment by noahgomz** [comment]
Yes, the problem persists.

**Comment by noahgomz** [comment]
Hello, the problem persists. Could you please address it?

**Comment by TimothyWCTI** [comment]
Chiming in to mention I'm also encountering this. I have abandoned features due to this issue.

**Comment by Alezanello** [comment]
Hello everyone,

I wasn’t able to replicate this issue. I created a small example where a random index is inserted into the list with a specific number. When I choose to remove an item by index, it correctly removes the item at the specified index rather than the last one.

Let me know if there’s any additional context or details I might be missing!<br><br>Public project so you can clone, test it and modify it:<br>[https://app.flutterflow.io/project/qa-2284-xuebk6](https://app.flutterflow.io/project/qa-2284-xuebk6)

[Screen-Recording (56).mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/09fdad3b-da94-4044-a26e-75fbbd7151f5/09ea27a3-1d86-4b25-8121-cc65e651979b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8wOWZkYWQzYi1kYTk0LTQwNDQtYTI2ZS03NWZiYmQ3MTUxZjUvMDllYTI3YTMtMWQ4Ni00YjI1LTgxMjEtY2M2NWU2NTE5NzliIiwiaWF0IjoxNzMyMjEwMDY1LCJleHAiOjMzMzAyNzcwMDY1fQ.gGz4xB2xJhv3Ry7PrtYurYd5qSkH-2pjvAQrXDrCmcg)

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!

**Comment by vinojko** [comment]
The issue still persists. The remove from list at index, removes the last item and not the item at the correct index.

**Comment by Alezanello** [comment]
Vinojko, in that case, please clone the public project I shared, replicate the issue, and share it with us. In the video I provided, I demonstrated that it’s working as expected. If you’re experiencing something different, kindly provide evidence to help us understand and address the issue.

**Comment by vinojko** [comment]
@Alezanello 
I discovered a different problem with the component, and I managed to recreate it. While the list correctly deletes an item, there's an issue when a component within the list maintains its own state, such as a text input or a date selected from a calendar picker. For example, if a user sets a date or enters text in a specific item, and then an item from the list is deleted, the state of the component in the last item is unexpectedly cleared. This behavior suggests that the deletion is causing the components' states to shift or reset improperly.

Here is also an example (sorry for the overflows i quickly wanted to recreate it). You can click on the green container to set a date, then try to delete an item from a list.

It's probably fault on my side. Maybe its a problem with uniqe keys, will try to fix it.

https://app.flutterflow.io/project/qa-2284-sdmnxd

**Comment by vinojko** [comment]
Okay i figured out it's a problem with unique keys, it's not a FlutterFlow issue (at least in my case).  Flutter might incorrectly match widgets to list items because it assumes the key represents the same widget. We need to set Unique Key not to index in a list but truly unique. I created a costum function which generated a uuid:
```dart
String? generateUUID() {
  /// MODIFY CODE ONLY BELOW THIS LINE

  const int length = 8;
  const String chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  final math.Random random = math.Random();

  final String uuid =
      List.generate(length, (index) => chars[random.nextInt(chars.length)])
          .join();

  return uuid;

  /// MODIFY CODE ONLY ABOVE THIS LINE
}
```

and then used that as a unique key - keep in mind the component also needs to be assigned the same id.
![image](https://github.com/user-attachments/assets/4ed4b108-ece8-4515-bcc6-edd952a52e36)

if someone knows of a better solution, welcome!
