### ISSUE TITLE
Cannot access mobile deployment after update. Only in Main branch. Before it was possible also with feature branch

### ISSUE THREAD

**Issue by JeffersonFarFan** [FlutterFlow/flutterflow-issues#4057]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

After update I cannot do anything in mobile deployment. it's disabled. for main branch its working. but when I did a merge. the themes are not set from feature branch. colors are different. I did not change anything. cannot work anymore. 
my main branch is obsolete I worked too long on feature branch. Also I cannot change theme settings anymore in feature branch 

### Expected Behavior

Mobile deployment and other stuff is working also on feature branch 

### Steps to Reproduce

1. Go to feature branch 
2. Go to mobile deployment in settings 
3. try s.th. not working

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

eg

### Visual documentation

as described. 

### Environment

```markdown
- FlutterFlow version: Latest Version
```

**Comment by Alezanello** [comment]
Hello!

It is expected behavior for this to work only in the main branch. You can go ahead and merge everything from your feature branch into the main branch, overwriting the main branch.

If you encounter any issues or need assistance with the merge, feel free to reach out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io).
