### ISSUE TITLE
Branch cannot publish to FlutterFlow domain

### ISSUE THREAD

**Issue by itsstevenliu** [FlutterFlow/flutterflow-issues#4067]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We are using branching to organise our project. However, from a branch, we cannot publish to the FF domain. 
The reason why we need to publish to the public domain is because majority of the app is locked out to Authenticated User however there are certain pages available to public. We want to specifically test these pages prior to publishing to our production domain.
![image](https://github.com/user-attachments/assets/706518ec-d65e-43f3-887e-e0d85cebd743)

### Expected Behavior

You should be able to publish to the FF public domain from a branch as it is an option shown. 
![image](https://github.com/user-attachments/assets/d09e9bcb-8aa5-440d-af3a-c1818ce7830f)

### Steps to Reproduce

1. Create App
2. Set Web app deployment as available 
3. Create branch
4. Try publish to FF domain from branch

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40jMnf/ZVjrttg47XuasZvmgAQJ1g5UOQ7it57aCosfZT2BLMcec/RVERvZ+KrTWNUP06ggWoW3M7yi9nIGvpfKU6rbYc4/89iFgrKTkGnRr63FJWvOHF5J/NNCUCPyLSR2RNNIvV0R3wQ3Wb7I/OsY3TUQ4ztDVQeDa/LZO4=

### Visual documentation

![image](https://github.com/user-attachments/assets/d09e9bcb-8aa5-440d-af3a-c1818ce7830f)

### Environment

```markdown
- FlutterFlow version: 5.0.06
- Platform:Mac
- Browser name and version:Chrome Version 129.0.6668.91
- Operating system and version affected: Every website
```

**Comment by Alezanello** [comment]
Hello!

Thank you for reaching out. Unfortunately, this is the expected behavior: only the Main branch can be published directly. However, if you'd like to test a different branch, you can download it to your local environment and run tests there.

To do this, while you're in your desired branch, navigate to the Developer Menu and copy the command to download it using the FlutterFlow CLI. You can then compile and test the branch locally.

If you don't already have the FlutterFlow CLI installed, you can follow this guide to get set up: [https://docs.flutterflow.io/exporting/ff-cli/](https://docs.flutterflow.io/exporting/ff-cli/)

Let me know if you need any further assistance!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/90ca9f2d-b682-462c-a709-1741839b143a/cbe6e29e-9835-4708-9e49-2d102bcebc0a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85MGNhOWYyZC1iNjgyLTQ2MmMtYTcwOS0xNzQxODM5YjE0M2EvY2JlNmUyOWUtOTgzNS00NzA4LTllNDktMmQxMDJiY2ViYzBhIiwiaWF0IjoxNzI5MDgzNzQ2LCJleHAiOjMzMjk5NjQzNzQ2fQ._VY-6PKQeM_auAiLY7JTGHHd8KhcOl0C_53UyLawvf4 " alt="image.png" width="430" height="376" />

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
