### ISSUE TITLE
Usability: Drawer left open when changing pages

### ISSUE THREAD

**Issue by DanielEdrisian** [FlutterFlow/flutterflow-issues#407]
## Expected behavior (required)

When you open a page in Page A, then go to Page B, then go to Page A, the drawer should be closed and you should be able to interact with the widgets of the scaffold.

## Current behavior (required)

When you open a page in Page A, then go to Page B, then go to Page A, the drawer appears to be closed, but is actually marked as open, which means you need to go to the properties bar of the scaffold and hit "Hide Drawer" before you can do anything with the page.

## To Reproduce (required)

N/A

## Context (required)

N/A

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by yoheisoito** [comment]
Hi @DanielEdrisian ,

Thank you for your post.
I've created a mock up to demonstrate this.

https://mbox-fc5rnc.flutterflow.app/

When you do a navigate to page from an open drawer then navigate.pop, then your page 1 would still have the drawer open. When you do Navigate.push, you would see the drawer closed given the way stacking works among push and pop. This is an expected behavior. 

https://mbox-fc5rnc.flutterflow.app/

If you want to have the drawer closed, then you can consider calling drawer close before you navigate to your other page.
I am closing this for now, but you can reopen it anytime if you continue to see issues.

Thanks!

**Comment by DanielEdrisian** [comment]
This is about the FlutterFlow UI builder, not the generated project.

**Comment by DanielEdrisian** [comment]
Sorry I should have clarified

**Comment by yoheisoito** [comment]
Oh apologies for my mistake.
And I can confirm that your point is indeed reproducible, as shown in the movie attached.

Thank you for acknowledging this, @DanielEdrisian.
We will include this to our list of fixes in our next update.

https://user-images.githubusercontent.com/115172813/214714188-f70a0512-7a4a-466a-8e27-73bcfcce88c2.mov

**Comment by agreaves** [comment]
Hey Daniel! Nice catch! This will be fixed next deploy.
