### ISSUE TITLE
Set from variable changes automatically removed

### ISSUE THREAD

**Issue by VenzpireZero** [FlutterFlow/flutterflow-issues#4106]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

If we set the variable values means, it's suddenly removing (Not saving)

### Expected Behavior

If we set the variable values means, it should not change. Last updated value should be saved.

### Steps to Reproduce

1. Just update the any set from variable feature in anywhere
2. Frequently you may face the issue. Applied value will be automatically removed

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glfLlvIp1occB7rrqLO9WoGQvKWk3Rpc0rdoacxAgfa74E7M2Z8/7T1VCTsSzaHNfeFCgkT4x/9bTjvDDEsE3FweCQIQ4zZFUExPPbEiVac2NBpOKXUZ9EplWFW7C1rerpQp+Wc11SF1h6l+mFtmvQT2Cf9qOYwx5e6fDbOY=

### Visual documentation

![image](https://github.com/user-attachments/assets/5be94e1d-d0ea-4036-91ce-25d06d4b7e28)

### Environment

```markdown
- FlutterFlow version:  v5.0.6+ released October 9, 2024
- Platform: windows
- Browser name and version: Chrome Version 129.0.6668.100 (Official Build) (64-bit)
- Operating system and version affected: windows 10
```

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. The good news is that our team is already aware of it and is actively working on a fix, which will be deployed soon. You can track the progress of this issue here: [GitHub Issue #3934](https://github.com/FlutterFlow/flutterflow-issues/issues/3934).

I’ll close this issue as a duplicate to ensure we focus all efforts on the main ticket.

Thank you for your understanding!
