### ISSUE TITLE
PDFViewer widget not appear when run in Test Mode

### ISSUE THREAD

**Issue by williamgh2019** [FlutterFlow/flutterflow-issues#419]
## Screenshots / recordings

In development mode is working.
![image](https://user-images.githubusercontent.com/17005582/215388258-acb1da2e-ada6-4c7c-b7bc-81d2e284d6e7.png)

In Test Mode does not appear anyway.
![image](https://user-images.githubusercontent.com/17005582/215388354-50df0c03-a40d-4792-91e9-e9e1e2e0a8ad.png)

Debug code from Widget Tree:
ITEehc/635RJpbxF187yd+1F/AMwHUgkU7knktVxRRQaI+PtBLQQd8nBVBdvcuqHTX5IeFX+rF8K//TtkoTxDfdfGxabGKpY+LppH1yjEA8=
## Your environment

* Version of FlutterFlow used: 3.0
* Platform (e.g. Web, MacOS Desktop):  Mobile
* Browser name and version: Chrome Version 109.0.5414.120 (Official Build) (64-bit)
* Operating system and version (desktop or mobile): Desktop

**Comment by hariprasadms** [comment]
Hi @williamgh2019 - Thanks for the issues details. I have tested this issue and working fine in my projects.

Looks like this issue is because of CORS policy is blocking the PDF loading from the website where pdf file is delivered. 
Navigate to chrome browser developer console and see if there are any error. You may see below error.

![image](https://user-images.githubusercontent.com/17435678/215526733-49cfa3cb-1853-4042-9a33-be89378f3aef.png)
 
If you can see the same error, Install this plugin [https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en) and reload the run mode and see if PDF can load with no errors. Please confirm this details.

**Comment by hariprasadms** [comment]
Hi, I presume the my earlier comment details help to resolve the issue. This is mostly related to configurations at deployment settings, Hence I am closing the issue.

**Comment by williamgh2019** [comment]
> If you can see the same error, Install this plugin https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en and reload the run mode and see if PDF can load with no errors. Please confirm this details.

After install this plugin it is worked.

Thank @hariprasadms
