### ISSUE TITLE
Using vscode extension results in all the default project dependencies to appear in custom action dependancies

### ISSUE THREAD

**Issue by sanjayelate** [FlutterFlow/flutterflow-issues#4300]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Not sure if this is a bug or would cause any problems but when using the new vscode extension in Cursor AI, when you go back into flutterflow 

### Expected Behavior

Before I connect with the extension, there's only two dependancies in my custom actions. Now there's a huge list.

### Steps to Reproduce

Use the new extension in Cursor AI (assume the same happens in VS code)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

The named parameter 'queryFn' is required, but there's no corresponding argument. Try adding the required argument.

### Visual documentation

![Screenshot 2024-10-20 at 19 10 26](https://github.com/user-attachments/assets/20036253-ced5-4671-82e0-b2b35c04330c)

### Environment

```markdown
- FlutterFlow version: 5.0.7
- Platform: Cursor AI
```

**Comment by Alezanello** [comment]
Hello!

This issue is not related to the VS Code extension. In the Custom Code section, every custom action or widget now displays all the packages that have been included in the project. This change allows you to easily view all dependencies without needing to remember which action uses a specific package. You can simply click on any custom action and modify the dependencies for the entire project in one place.

**Comment by sanjayelate** [comment]
Cool, thought that might have been a change but it didn't display if I rolled back to a previous save so wasn't sure
