### ISSUE TITLE
Canceling media upload results in unexpected write to firebase

### ISSUE THREAD

**Issue by kjoyceee** [FlutterFlow/flutterflow-issues#455]
## Expected behavior (required)
If a user taps to upload media but changes mind, there should be no firebase actions triggered

## Current behavior (required)
When I go to upload media by either gallery/camera and I press cancel, the action still continues, resulting in unwanted writes to firebase document.

## To Reproduce (required)
1. create a firebase collection to accept a imageURL
2. create a page with an action to upload media to firebase
3. on the same action, have the uploaded url write to the collection previously created in step 1
4. run project
5. go to upload media but when prompted to select a photo or take picture hit cancel
6. a document is written, even though the user cancelled resulting in a write to the collection with a blank imageURL

### Bug Report Code (required, generate from Widget Tree)
IT4glcmAuIhOseFY1pD2de9WmjoWNkA/apc0ttx+bw4bJJCvOpYUec/6P0lWcOaqS29mOFq2p14y//DKht+SK/VdISeqbIhFwaV9EA7xVkWmSqnfU/HUACkbeacOQSj6

**Comment by kjoyceee** [comment]
I have tried using the Widget state 'Uploaded File URL' as a conditional action to see if the URL is empty/set before doing actions. This works. However, when you go to upload a second file after the first and cancel, it will write to the firebase collection using the first file url.

**Comment by kjoyceee** [comment]
We need a way to clear Uploaded File URL once all our actions are complete. as well, would be nice if we had a bool similar to Widget state 'Is Media Uploading' but to call once media is done uploading such as 'Is Upload Complete'

**Comment by victoriahuang1** [comment]
Hi @kjoyceee , thanks for the report.

It is actually the expected behavior for downstream actions to get triggered even if you choose to cancel the upload.

> I have tried using the Widget state 'Uploaded File URL' as a conditional action to see if the URL is empty/set before doing actions.

This is exactly the recommended approach for handling this situation.

As for your suggestions:
- How would 'Is Upload Complete' be different from _"NOT 'Is Upload Complete'"_?
- I agree that a "Clear Uploaded Media" action would help in cases like this a lot! It is a feature request though, so I will not be implementing it for this ticket, but I can bring it up to the team and see if we can get deliver this feature. For now, can you add a local state variable to keep track of the last uploaded file URL and only write to firebase if it gets updated?
