### ISSUE TITLE
End of data error in Swipeable stack

### ISSUE THREAD

**Issue by OldFred2023** [FlutterFlow/flutterflow-issues#460]
If the swipeable stack widget is bound to a map/json, the user can navigate past the end of the stack(data), causing a blank widget with no way to navigate back other than refreshing the page.

This should not be the case as it makes the user experience (and therefore the widget) unusable in a commercial app with this functionality, it should do one or all of the following:

- block going past the end of the data
- loop back to the 1st record
- allow to swipe backwards through the stack.

**Comment by Pepino-GR** [comment]
Hi OldFred2023, 

the widget works as intend. It is using the package 'swipeable_card_stack'. As you can use the swipeable actions, you can build your logic yourself. I can set this issue to generate a feature request.

**Comment by OldFred2023** [comment]
I cant see how that is possible in FF, although you can get the current element:
![image](https://user-images.githubusercontent.com/122821259/218278061-d991c0f6-9daa-4df5-9646-81e34bf28c5a.png)

It is not possible to get the number of elements in a list<Datatype>:
![image](https://user-images.githubusercontent.com/122821259/218278113-12074ef1-4a6f-4342-ac40-fed778664da0.png)

So unable to check if swiping passed the last record.  

So I would still say this is a bug !

**Comment by katherineqian** [comment]
Hi @OldFred2023, 

Thanks for your report! In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. You will see this template when you click "New Issue", or in README.md. The template also asks for a bug report code, which you can generate by right clicking on a widget and selecting "Get Bug Report Code". 

As for this issue, you could not select "Number of Items" since your condition would be comparing it to the Swipable Stack Current Element (not an int). For now, you can achieve each of the desired behaviors that you described by creating your own page state index which you can change (increment/decrement) on swipe actions and which you can compare to the length of your list. 

As @Pepino-GR said, we will of course be happy to consider this as a feature request to make it easier to achieve the behaviors you described, but the widget is working as intended. 

Thank you for your contribution!

**Comment by katherineqian** [comment]
Hi @OldFred2023, 

Thanks for your report! First, in order to keep our issue tracker useful and maintainable for all users, please follow the bug report template in the future while reporting bugs. You will see this template when you click "New Issue", or in README.md. The template also asks for a bug report code, which you can generate by right clicking on a widget and selecting "Get Bug Report Code".

As for this issue, you could not select "Number of Items" since your condition would be comparing it to the Swipeable Stack Current Element (not an int). 

Normally, you should be able to achieve all of the desired behaviors (and more) that you described by creating your own page state variable which you can change (increment/decrement) on swipe actions and which you can compare to the length of your list.

However, you can't do this with the current implementation. The feature request to allow this workaround would be to expose the index of the list item. However, there appears to be a problem with the [swipeable_card_stack](https://pub.dev/packages/swipeable_card_stack) package used by FlutterFlow that prevents this from functioning properly. @aemelyanovff has created an issue there: https://github.com/codetoart/cta-flutter-tinder-card-animation/issues/11. 

I would agree with @Pepino-GR that the widget is working as intended, because it's not an unexpected behavior -- our Swipeable Stack just runs out of cards when there is no more data. However, there are significant limitations to it which need to be addressed (there are a couple of other issues raised on Swipeable Stack that could benefit from an exposed list item index). Usability-wise, we could also consider providing built-in options for looping items, etc. as you described.  Since it's not a bug, I'm going to keep this ticket as a feature request as part of an overall upgrade to Swipeable Stack, but please be assured your concerns are heard.

Thank you for your contribution!
