### ISSUE TITLE
AppBar can not control its responsive visibility in editor and preview mode. 

### ISSUE THREAD

**Issue by Rrrrnnyg** [FlutterFlow/flutterflow-issues#4634]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

<img width="659" alt="image" src="https://github.com/user-attachments/assets/2dfed857-7a44-44b4-98be-52c619c89ec2">

### Expected Behavior

appbar will not display in the laptop/desktop width in editor/preview/run mode. 

### Steps to Reproduce

1. go to settings and unselect laptop/desktop in the responsive visibility section. 
2. go to build editor, switch to laptop/desktop mode. Not work.
3. go to preview mode and do the same. Not work. 
4. go to run mode and do the same, Work.

Navbar's responsive visibility control is fine in every mode.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz8+A5c9IsdtJ+KXfbe54ijsvNjs8TLJEoetxc0gbfe/4EIocZc74Yk5tOPazaH1qKFCajnIy0eDTkuzXGO4BAxKtbpR/z88JehPPYzqmMISOCc+0X0R7BZ9bG0iC4J7UhBNAKsVhWVYe2DqMHOnKbz6Cf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1114" alt="image" src="https://github.com/user-attachments/assets/4504ecbd-19d2-497a-8377-ad7e0246c020">

### Environment

```markdown
- FlutterFlow version: 5.0.8
- Platform:web
- Browser name and version:chrome lastest
- Operating system and version affected:  mac os
```

**Comment by Alezanello** [comment]
Hello!

In Preview Mode, conditional logic won’t function as expected because this mode only simulates the UI; it doesn’t compile any code, so it won’t evaluate height, width, or other visibility conditions.

When you mention "Builder," are you referring to the app-building stage? If so, the issue may relate to the breakpoints set in the Design System. You can adjust these as needed. Personally, I don’t see any default AppBar in desktop mode—just the custom one you’ve created.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/aac89db1-a64a-42dc-8545-940a7b7f5d3d/908bf52f-162e-484c-bd8f-08412e4bad45?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9hYWM4OWRiMS1hNjRhLTQyZGMtODU0NS05NDBhN2I3ZjVkM2QvOTA4YmY1MmYtMTYyZS00ODRjLWJkOGYtMDg0MTJlNGJhZDQ1IiwiaWF0IjoxNzI5ODU5NTk5LCJleHAiOjMzMzAwNDE5NTk5fQ.8z7H8JhKm1taseDtutxQ8ClfAdH72OMxzryzLuzXHqU " alt="image.png" width="1659" height="367" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/96fd704d-7492-4e17-9ebc-298f2bb9a79c/4503ff1e-5ca7-42b8-9688-d409762088a7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NmZkNzA0ZC03NDkyLTRlMTctOWViYy0yOThmMmJiOWE3OWMvNDUwM2ZmMWUtNWNhNy00MmI4LTk2ODgtZDQwOTc2MjA4OGE3IiwiaWF0IjoxNzI5ODU5NTk5LCJleHAiOjMzMzAwNDE5NTk5fQ.1hzWHKQ7xL7dhC8QCJ4kemGeBpzDO2mwtGvyh8iQaFo " alt="image.png" width="484" height="198" />
