### ISSUE TITLE
Progressbar not respecting width of parent Container

### ISSUE THREAD

**Issue by livingmydesign** [FlutterFlow/flutterflow-issues#465]
## Expected behavior (required)
a 100% - Progressbar within a 60% Container fills to 100% within the Container

## Current behavior (required)
a 100% - Progressbar within a 60% Container shoots out of the Container

## To Reproduce (required)
1. Create a Container with 60% width
2. Create a horizontal Progressbar within that Container
3. Set the width of the Progressbar to 100%

### Bug Report Code (required, generate from Widget Tree)
ITEezc/134VItb0F1brccvlKjQMzN0g2a+cZm9VxbwIoIpznBqQQO+PeQ1ttXe7gaVNfMVSYp3EH+dbliob9JO0pEwqBGZRZzLhAehbQKTbkEuzyT+3IHDUHZbsSXTTm

## Context (required)
Can't use the horizontal progressbar widget within nested components.

## Screenshots / recordings
![progressbar](https://user-images.githubusercontent.com/93006467/218027316-520823c5-506a-416a-975e-46de1a3d1cd9.png)

https://community.flutterflow.io/c/discuss-and-get-help/flutterflow-not-respecting-width-on-progress-bar

## Your environment
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop): MacOS Desktop
* Browser name and version: Chrome Version 109.0.5414.119 
* Operating system and version (desktop or mobile): MacOS Ventura 13.0.1

**Comment by victoriahuang1** [comment]
Hi @livingmydesign , thanks for the report. This is actually the expected behavior -- the `%` refers to the screen and not container size, as you can see [here](https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements/base-elements/progressbar#changing-size-1).

To make the progress bar fit inside of the container, you can either:
1. change the width % of the progress bar, or
2. clip the progress bar by selecting the clip option from the container's properties
3. use a custom widget.

If you choose to make a custom widget, you can do something like the following:
<img width="1356" alt="Screenshot 2023-02-13 at 4 08 18 PM" src="https://user-images.githubusercontent.com/16326980/218604690-6cb3617f-f458-474c-a2ec-5c4f9fb1009a.png">

This custom widget will make it so that the width % will be relative to the container you choose to place this custom widget in, instead of the entire screen width.

Hope this helps!
