### ISSUE TITLE
When I hit test mode on the mac desktop app, even though its the production app, the web testing url is beta.flutterflow.io instead of app.flutterflow.io

### ISSUE THREAD

**Issue by piershare** [FlutterFlow/flutterflow-issues#4658]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I hit test mode on the mac desktop app, even though its the production app, the web testing url is beta.flutterflow.io instead of app.flutterflow.io

### Expected Behavior

should simply be app.flutterflow.io. On web this is what happens.

### Steps to Reproduce

1. Open app
2. Press test mode at top right
3. See beta.flutterflow.io in the URL

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kiMrl34ZPxOVY15Dtbe5sjjg4G1B7TLJEoetxc0gbfe/4Pe0IfvfBfk9DQtCzaH1felmjrFgx3MrMhvPpO8Y6ZBCVRYg9yqgJERPPYz+5eJSDPKqVPEFTM8ZbGky50LunqwpTOtt0SFI63Tn3BuitVT6Cf9qOYwx5e6fDbOY=

### Visual documentation

Press test button, see beta.flutterflow.io in web url

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.13 
- Platform: Mac desktop
- Browser name and version: mac desktop
- Operating system and version affected:
```

### Additional Information

Nnot applicable

**Comment by rzambroni** [comment]
Hello @piershare, thank you for reporting this issue. One of our team members was able to replicate what you're experiencing—it appears that when you open the production app, MacOS is instead launching the beta app, which takes you into the beta environment.

Could you check if the beta app is installed on your system? If it is, I recommend uninstalling it and then trying to access the production app again. Reinstalling the production version may also help ensure it launches correctly. You should see version *5.0.9*, which was released today, when opening the production app.

I hope this helps resolve the issue for now. I’ll also pass this along to our engineering team to investigate the root cause further.

**Comment by piershare** [comment]
Thanks! I did uninstall flutterflow beta and emptied the trash and it does
still happen unfortunately. Please feel free to keep me posted.

Best,
Jonathan

**Comment by rzambroni** [comment]
Have you tried reinstalling the FlutterFlow production app after deleting the beta? When you open a project now, do you see the correct version, *5.0.9*, which was released today?

**Comment by piershare** [comment]
I have not uninstalled production yet, but I am on version 5.0.13 now...

**Comment by rzambroni** [comment]
Please follow the steps i mentioned. 

1. Uninstall Beta.
2. Uninstall Prod.
3. Install Prod from the [official link](https://www.flutterflow.io/desktop)
4. Try opening a prod project. You should see 5.0.9

**Comment by piershare** [comment]
Understood, will do, thanks!

**Comment by piershare** [comment]
It worked! Thanks! For the future, how do I know if there is a roll back in
the code if I'm already on a later version going forward?
