### ISSUE TITLE
App State list clear value not showing default items

### ISSUE THREAD

**Issue by jeffcyw95** [FlutterFlow/flutterflow-issues#4715]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Upon clearing value of an app state with default values, the app state becomes empty instead of having the default value

### Expected Behavior

app state to have default value after clearing value in an actions

### Steps to Reproduce

As above

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4WhsmA8YxJpbxE1s+NdcZR/WAWHEwlaOcrm8N9cw0aF5fpPaYPX/z4UBJoTbyndkFqemaWhT4Jp9rKm9z1J/UBEyuZfIQ6+qhASQv/QmK6RbqaCLmCSEF+GshgI0Ck0p6RsxImKvh1SEY+2VOLfO6/EwXDJufXIkQeRPGICKjXvgfuQ0SLb3kNh1JWeC/v

### Visual documentation

![image](https://github.com/user-attachments/assets/96ce106c-9a24-4727-9673-48d5531e075d)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

You're absolutely correct; this is the expected behavior when clearing values. When you set a default value, you are assigning an initial value to the variable. Clearing the values removes all assignments, allowing you to add new ones.

As a workaround, you could create a second variable called `"DefaultXXXXValue"`. This variable can store the default value. When you want to reset to the default, you simply clear the original variable and set its value from the `"DefaultXXXXValue"` as a backup. This way, you can easily restore the default value when needed.
