### ISSUE TITLE
The supabase destop client for the mac does not have the signin with apple option

### ISSUE THREAD

**Issue by bskyper** [FlutterFlow/flutterflow-issues#4716]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I was planning on testing my app on my mac via setup local run.  In order to do that I need to download the desktop version.  What I noticed when I downloaded the app is that it does not provide a login with apple option where the web instance does.  
<img width="866" alt="image" src="https://github.com/user-attachments/assets/356578d2-1ab8-418d-9720-8a4c3da0c65c">

### Expected Behavior

I would expect the app to provide a singin with apple option, but it does not exist.

### Steps to Reproduce

1. Download the desktop app on the mac
2. Run the desktop app

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfl8rqwIt1m7RK14SJKMZWijw7NW0cTeUzlO1hdwwbI+OoEKQDPfTsVBRtcuqHeWxIM1elkmEy/s3HveHhFPYDOSqufYBx/pBxUxDveGGiV4ipBbqodmpTO+RWIWLF0LaC2hMkBNJqLHgO2lOtetyQY3qCf9qOYwx5e6fDbOY=

### Visual documentation

![flutterflow-desktop](https://github.com/user-attachments/assets/771babc2-39d5-4a8d-b49a-d86e6e440eaa)

### Environment

```markdown
- FlutterFlow version: Desktop version 
- Platform: Mac
- Browser name and version: Desktop Version
- Operating system and version affected: Mac Desktop Version
```

**Comment by Alezanello** [comment]
Hello!

This is the current expected behavior, and the team is already tracking it for future implementation. However, I can't provide a specific timeline for when it will be available. In the meantime, one workaround is to reset your password even if you initially signed in using Apple Sign In on the web. Once you've reset your password, you can log in directly with your email and password in the macOS app.
