### ISSUE TITLE
Apps changed in the last 2 weeks will not render in FF TEST mode

### ISSUE THREAD

**Issue by xenomorph78** [FlutterFlow/flutterflow-issues#4758]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When running the app in TEST, it builds and then goes to a blank run screen. 
No errors
Tried on Chrome and Safari
Previously working tests load fine if you click on the test URL.
<img width="1612" alt="Screenshot 2024-10-29 at 10 35 37 AM" src="https://github.com/user-attachments/assets/5fc47260-8976-47f5-9d1a-ca21030c38c4">

### Expected Behavior

Expect it to render the app as usual.

### Steps to Reproduce

1. Click the TEST to run ane let it render for a few minutes. 
2. When it's done, it just loads a blank page inside the Run box
<img width="1619" alt="Screenshot 2024-10-29 at 10 39 20 AM" src="https://github.com/user-attachments/assets/cc9b381d-50ec-46d4-b8e7-6f9226545faf">

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfhfHlzItOodtc0L6IKvp4imQ7KUMcTeUzlO1hdwwbI+PoP7Mhdcz8ZVtpYuqHfVd+C1eJ+WMJzM6KjtrtL/kEGzmsGaZfyZNTUxDhRT+5branCs+CZHdDEfNMf3K51ImjpxJ/IfVtdVln7F2mCN+uY3qCf9qOYwx5e6fDbOY=

### Visual documentation

<img width="1619" alt="Screenshot 2024-10-29 at 10 39 20 AM" src="https://github.com/user-attachments/assets/cc9b381d-50ec-46d4-b8e7-6f9226545faf">

### Environment

```markdown
- FlutterFlow version: 5.0.9
- Platform:Mac OS Sonoma 14.4 - 2.6 GHz 6-Core Intel Core i7 - 
- Browser name and version: Chrome and SAfari
- Operating system and version affected: Mac OS Sonoma 14.4
```

### Additional Information

This happens on the last 2 projects I've been working on.

**Comment by rzambroni** [comment]
Hello @xenomorph78,

I'm sorry to hear you're facing this issue. Since it seems specific to certain projects and, unfortunately, we don’t have access to initiate test or run sessions on your projects, reaching out to the FlutterFlow support team directly might be the best next step. They’ll have the tools and permissions needed to troubleshoot effectively. You can contact them via email at [support@flutterflow.io](mailto:support@flutterflow.io) or through the in-app chat in FlutterFlow.

Thank you for your understanding, and I hope it gets resolved smoothly!
