### ISSUE TITLE
Update Local State code has recently changed

### ISSUE THREAD

**Issue by tofwono** [FlutterFlow/flutterflow-issues#476]
hello, after the update on 9th feb, this error appeared with no pop up to dismiss it after the changing the local state code.

Update Local State code has recently changed. Visit the custom code page to review the changes and dismiss this error.

All my local state codes were updated to :

FFAppState().update(() {
  FFAppState().ttTelephoneNumber = '';
});

I cant dismiss the error because there is no popup and at the same time i cant compile with this error showing up.
am i missing something?

**Comment by agreaves** [comment]
Hi @tofwono! Happy to look into this, however please follow the template and include the required Bug Report Code to assist in debugging the issue. Thanks!

**Comment by bulgariamitko** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
 
 Thank you!

Can you please provide a Bug Report Code as well. This is how you can create it

![whats-new-FlutterFlow](https://user-images.githubusercontent.com/7221384/215421133-34dab909-6647-4b03-8d40-2539ca0b0b3a.png)

**Comment by hariprasadms** [comment]
Hi, There are few fixes made round local/app states in latest FF updates. As there are no follow up on this issue, we assume this issue has been fixed and works fine now. Hence closing the issue. We can re-open the issue if the issue persisting again. Thanks
