### ISSUE TITLE
Navigate Action on button is opening the same page again and again

### ISSUE THREAD

**Issue by duuetdev** [FlutterFlow/flutterflow-issues#4762]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I duplicated a page to follow the same design and there's a button on the page. Page 1 contains a button that navigates to page 2. But when I click on the button in page 1 it is opening page 1 again and again and it is not going to page 2.

### Expected Behavior

When I press on the button on page 1 it should navigate to page 2.

### Steps to Reproduce

1. Create a page with a button on it
2. Duplicate the page
3. Add navigation action on page 1 to navigate to page 2
4. Notice that clicking on the button on page 1 is navigating back to page 1

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEelM/q35NItbxb+bnQKMFGiQMxQUB+bZ0vlO1FGBYbfIOuEYkfeM7EaXdpXearT0FMAGCIpEIJ/t6OiuPDNPQoORCZR4t607VQaTvwJXKuRrqPCc60XmtCGehhBWq5yKSs2h4kLrdsc14d20+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

https://github.com/user-attachments/assets/4a8493c1-41e0-4752-b3e9-44aeaf6def17

### Environment

```markdown
- FlutterFlow version: v5.0.8+
- Platform: Web + Desktop
- Browser name and version: Arc
- Operating system and version affected: MacOS 15.0.1
```

**Comment by Alezanello** [comment]
Hello!

The issue occurs because the "onboarding2" page requires authentication, and the user is not authenticated at this point. I recommend disabling authentication on this page to allow users to proceed to the next screen.

Additionally, I noticed the "Next" button on the "Onboarding1" page was difficult to access on my device because it’s positioned at the bottom, and the column isn’t scrollable. To improve accessibility across different devices, I suggest enabling scroll functionality on this column so users can easily reach the "Next" button.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9fcff5e5-8f99-48df-be0b-bc6d2a457dc4/5efe824b-4928-4560-85a2-4e3139e2e41b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85ZmNmZjVlNS04Zjk5LTQ4ZGYtYmUwYi1iYzZkMmE0NTdkYzQvNWVmZTgyNGItNDkyOC00NTYwLTg1YTItNGUzMTM5ZTJlNDFiIiwiaWF0IjoxNzMwMjI5MzYxLCJleHAiOjMzMzAwNzg5MzYxfQ.ZlJc6OMnlIHkveGRLLIAcGO1MKQvNfOnN42ifMFdD_0 " alt="image.png" width="785" height="173" />

**Comment by duuetdev** [comment]
Thank you for the help! This has solved the issue. 

Thanks for the tip as well, I'll make the according changes.
