### ISSUE TITLE
Action editor area greyed out

### ISSUE THREAD

**Issue by HotshotJacko1** [FlutterFlow/flutterflow-issues#4783]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The action editor on the right is greyed out. Also when selecting a text widget value from variable, the whole screen greys out. Images attached.

It also stops the app from being run in test mode.

### Expected Behavior

It shouldn't be greying out.

### Steps to Reproduce

Either:
A) Open the action tree, click some actions, and you'll see the right-hand area to edit the action being greyed out.
B) Click a text widget with a variable value, and some of them grey the whole screen out.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Kk8nc05NOsbRH7q6JcMdVnj4vKVg/a7geltVuewIYfYyqG7l3WvfObhJUcMejdAk2ME6kjmAX/MrRi/HTLcFfJgedfIQ6zrhAbTvJVXyVb827CpS3b396EcBbGnalyImjvhZAWdZuSWQgwDiYCe+uShXBNr76PW4nAOaeXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

![image_2024-10-30_151815014](https://github.com/user-attachments/assets/8866ea79-7a6d-4aec-8aae-4cedc795b193)
![image_2024-10-30_151855918](https://github.com/user-attachments/assets/3f851db7-e1c8-4f73-9751-ae6f5c037bfb)

### Environment

```markdown
- FlutterFlow version: 
- Platform: 
- Browser name and version: Tried on Flutterflow desktop programme, and on Opera and Chrome
- Operating system and version affected: Windows 11
```

### Additional Information

Can't edit my app.

**Comment by Alezanello** [comment]
Hello!

I’m sorry to hear you’re experiencing this issue. I’ve looked into your project but couldn’t locate or reproduce the problem. If the issue is still occurring on your end, could you please share a screen recording showing how it’s triggered? This would be a huge help for us in diagnosing the problem.

Thank you!

**Comment by HotshotJacko1** [comment]
[https://photos.app.goo.gl/XjdeuZMs8duYsBj29](url)

Thanks for looking into this. Above is a screen recording showing how to replicate the issue in both ways.

Below is a similar issue someone experienced last year:

[https://github.com/FlutterFlow/flutterflow-issues/issues/1322](url)

**Comment by wenkaifan0720** [comment]
Hi @HotshotJacko1. Sorry for the late response. We found out that this is because in this action chain, you are trying to access an action's output from a later action in a previous action, and this caused a stack overflow. We will fix the gray screen issue so you can remove the problematic variables. And in the near future we will do a refactor on our action system so that such an issue can't happen in the first place.
