### ISSUE TITLE
DataTypes not working on Cloud Functions

### ISSUE THREAD

**Issue by geret1** [FlutterFlow/flutterflow-issues#4784]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I've tried to use a DataType as a parameter into a cloud function with a validation error on runtime.

### Expected Behavior

Accept DataTypes (proper mapping validation) or remove it from accepted parameters.

### Steps to Reproduce

1. Create a DataType.
2. Create a CloudFunction.
3. Pasa the DataType as CloudFunction.
4. Run

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kz/Ll8ZNIvulA187pbfowtDg7Q1g/TL03pu0bFEggGLbrBIYMaePedk1CTbSgTVFbKEWLsGMd08Lsjvz1EfFdBxGbGqZR+LVcVTyXJVO/aoTSCKmwXURCTJtMGBWD5LaNoCJ5JbdhSloB2DmICty8aDLvJo/7Zwh9f6PHaOI=

### Visual documentation

![Screenshot 2024-10-30 at 17 09 44](https://github.com/user-attachments/assets/b5c75dfb-087a-4522-8c54-ea205a97c2e0)

### Environment

```markdown
- FlutterFlow version: FF latest
- Platform:Web, MacOs Desktop
- Browser name and version: Chrome (latest)
- Operating system and version affected: OS X Sonoma 14.5 (23F79)
```

**Comment by geret1** [comment]
Switching from DataTypes to JSON solve the issue because at cloud function level FF is considering DataTypes as dynamic and that's the main error. That's the main purpose of DataTypes avoid dynamic.

**Comment by Alezanello** [comment]
Hello!

You’re absolutely correct; this is the expected behavior when using Cloud Functions with the DataType setting. To send a JSON, please refer to our documentation for more examples and guidance: [Cloud Functions Documentation](https://docs.flutterflow.io/concepts/custom-code/cloud-functions/).

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7bbd2e95-552f-4ce1-8049-0adf1a2c4189/c045a6f1-e290-4542-b326-61d943e067cd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83YmJkMmU5NS01NTJmLTRjZTEtODA0OS0wYWRmMWEyYzQxODkvYzA0NWE2ZjEtZTI5MC00NTQyLWIzMjYtNjFkOTQzZTA2N2NkIiwiaWF0IjoxNzMwNDY4NTQzLCJleHAiOjMzMzAxMDI4NTQzfQ.1fks1ud6nD_QLDYUpBZVsumqhO9vbubN6NXHT-zFfhI " alt="image.png" width="1134" height="380" />

Thank you!

**Comment by geret1** [comment]
Maybe this is the most stupid question ever but how is DataType reachable and selectable while defining arguments in cloud functions?

Please review it because this is the bug. Users can expect that FF map datatypes as serializable map.

**Comment by geret1** [comment]
Close ticket due to lack of support.
