### ISSUE TITLE
POST request with JSON body don't encode multiline text

### ISSUE THREAD

**Issue by sarim** [FlutterFlow/flutterflow-issues#482]
## Expected behavior (required)

JSON is properly encoded.

## Current behavior (required)

Passed string variable is passed as is to the body, making the request body invalid json.

## To Reproduce (required)

Public Project: https://app.flutterflow.io/project/apipostlinebreak-82fbip

## Context (required)

Please check the recording where I explain it in details.

## Screenshots / recordings

Screen recording showcasing the bug, cause and potential solution of the bug: 
https://youtu.be/6356RGbruuw

## Your environment

* Version of FlutterFlow used: v3.0
* Platform (e.g. Web, MacOS Desktop): Web
* Browser name and version:  Microsoft 110.0.1587.41
* Operating system and version (desktop or mobile): Windows 11

**Comment by victoriahuang1** [comment]
Hi @sarim , the issue you are encountering is due to line breaks (`\n`) not being supported in JSON.

You should make sure the strings you pass into your JSON body have all their line breaks escaped. For example, `\n` should be encoded as `\\n` in JSON.

We will not be updating our code to automatically escape strings, as this may break some existing usages. But you should be able to escape your own strings with custom functions.
