### ISSUE TITLE
Slowness when typing text in Block Action properties

### ISSUE THREAD

**Issue by richenri** [FlutterFlow/flutterflow-issues#4829]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When typing text into a Block's properties or block title, the IDE becomes extremely slow and may even freeze for a moment. This significantly impacts work performance. In the video, I typed the text normally and you can see the delay until all the text appears.

https://github.com/user-attachments/assets/e2284002-ff23-419d-90ef-99e57ebda117

### Expected Behavior

Display typed text instantly

### Steps to Reproduce

1. open a Action Block
2. Include a Show Snack Bar block
3.  Put some text in message property  

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40lsmBw5dgrs9J1oSJbsFFimU5Jm16R+cVjup7aCosfZT2BLMcec/RVERBOc+mS2NEMGeJgWoW08r7juHtE/I6OTuWR6ZTwqVIEA3iUTutVrXQFJWgOnR8BZ9jJ2q+35+33RBANfhtdGQC3DmMHNiydDLvQee2OjA8Da/LZO4=

### Visual documentation

https://github.com/user-attachments/assets/d5ce2af0-b951-4476-98d3-7aa0aed640f3

### Environment

```markdown
- FlutterFlow version: 5.0.9
- Platform: Windows
- Browser name and version: N/A
- Operating system and version affected: Windows 11
```

**Comment by rzambroni** [comment]
Hi @richenri,

Thank you for your detailed report. I wasn’t able to replicate the issue in my own projects, but I did observe significant lag in your project, not just within the action block, but across various actions. I'll reach out internally to see if someone can take a closer look at this. In the meantime, I recommend contacting the FlutterFlow support team directly, as this issue seems specific to your project and they may have the tools to help troubleshoot it effectively. You can do that either by email (support@flutterflow.io) or using the chat inside the app.

Thanks!

**Comment by rzambroni** [comment]
Hey @richenri, thank you so much for your patience on this! I’ve checked in with the engineering team, and they’re actively working on optimizing overall UI performance. In the meantime, they suggested a potential workaround: try closing the widget tree temporarily when making edits that trigger frequent, high-volume changes. This should help ease performance until the improvements are implemented.

I'll go ahead and close this issue to avoid duplication since it's already on the team’s radar. Please feel free to reach out if anything else comes up!

**Comment by richenri** [comment]
Thanks
