### ISSUE TITLE
Text Widget with Conditional Visibility Based on Firebase Document Count Always Showing

### ISSUE THREAD

**Issue by NessyCat** [FlutterFlow/flutterflow-issues#4832]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to set a text widget's visibility conditional based on whether or not a User has any tasks currently assigned to them.

However the text is always showing no matter what I try.

This is my current solution design (if you would please critique it):

Set a QueryCollection on the Text widget to the usersTasks collection, filtered uid == [User ID]

Set Visibility - Conditional TRUE

Set the Condition variable to:

Single Condition

First value "usersTasksCount"

Equal to

Value = 0

When I test it, this query is returning "6" so the text should not be showing, however it is still showing.

### Expected Behavior

When the Document Count returns any other value than 0, then the text widget "You have no tasks to do today. 
 Time for a cup of tea!" does not display.

### Steps to Reproduce

1. Create a new page
2. Add a text widget.
3. Create a Firebase Document Collection
4. Create a query against the text widget that does a document count of documents in the collection that have the same UID as the authenticated user's UID.
5. Set the text widget to have conditional visibility.
6. Set the conditional visibility to be a single condition, IF documentCount EQUALS 0 then show the text widget.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wkfLqw5R2obhA1pDbbfpajicWCDp7RIIZj9VHeCs9GYjyO5YUacz7chFpXsPiY2w2KEWImlIH0ejvuODpM/U7BzaVRpRb1at+YA3iZGe/aoSUPoeSRGtfFp5mGFSk34mNmxFdBLF2dGAX1FOEJOjKY3TaN7X4Zwh9f6PHaOI=

### Visual documentation

[Screen Recording 2024-11-05 at 3.29.17 PM.zip](https://github.com/user-attachments/files/17628653/Screen.Recording.2024-11-05.at.3.29.17.PM.zip)
As you can see here, in the test I have created a count of the documents returned below.  You can see it's returning 6, yet the text is still showing.  When I test it in a User with 0 document count, it still shows also.  

### Environment

```markdown
- FlutterFlow version: 5.0.8+
- Platform: Apple Mac
- Browser name and version: Chrome Version 130.0.6723.92
- Operating system and version affected: Apple Mac
```

### Additional Information

I am unable to create widgets with conditional visibility based on whether a document exists in the Firestore database or not.  A lot of my User Stories rely on this and I'm not sure how I will be able to use this platform if I can't do this.

**Comment by szymdzie** [comment]
I have similar issue with widgets based on conditionals

**Comment by Alezanello** [comment]
Hello!

I understand what you're trying to achieve. Here’s a suggestion:

Consider turning the "No tasks today" message into a reusable component. Then, in your ListView, remove the Conditional Visibility. Instead, within the ListView settings, use the "Empty List Widget" option and set it to display the component you created for "No tasks today."

This way, you don’t need an additional query to check the number of tasks. If the list is empty, FlutterFlow will automatically show your component instead of hiding the ListView. It’s a more efficient approach using just one query.

Hope this helps! Let me know if you have any questions.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f8dfc74b-165c-4a8c-aa74-1332916adaed/ce77cd71-9c3c-428e-851e-a0203c908c61?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mOGRmYzc0Yi0xNjVjLTRhOGMtYWE3NC0xMzMyOTE2YWRhZWQvY2U3N2NkNzEtOWMzYy00MjhlLTg1MWUtYTAyMDNjOTA4YzYxIiwiaWF0IjoxNzMwODMyNzQyLCJleHAiOjMzMzAxMzkyNzQyfQ.2kgNPT5I8hBqnF-dSO_fe-iIuj2I__LynkNNYo7MmfU " alt="image.png" width="526" height="340" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/46879c73-50e1-4000-97e6-2d9c7d34f06a/e715c01a-4816-40cc-8427-340e4c3c7090?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80Njg3OWM3My01MGUxLTQwMDAtOTdlNi0yZDljN2QzNGYwNmEvZTcxNWMwMWEtNDgxNi00MGNjLTg0MjctMzQwZTRjM2M3MDkwIiwiaWF0IjoxNzMwODMyNzQyLCJleHAiOjMzMzAxMzkyNzQyfQ.7ijiB3PCKtKkyBRbpo4A40yEp62boRn6oAo0Gz74zl4 " alt="image.png" width="1100" height="301" />

**Comment by NessyCat** [comment]
Hi Alezanello, thanks for that elegant solution. I'm all about speeding up the app.
I've implemented it in this instance and it works well.
I do have other instances where if an element returned from a Document, or a list of Documents is empty then behave differently than if they are populated.  For example, the [taskTimePerPlant] and [taskTimePerPlant] text fields that should show if there is a value and not if there isn't.  These don't work either.  Is FlutterFlow's conditional visibility just not able to handle these Use Cases?  If not I'll have to try and find other way to solve the problems like above.
Thanks in advance.

**Comment by Alezanello** [comment]
Using the Count query can sometimes be challenging, as it operates as a "single query" rather than continuously streaming the count of documents in a collection with applied filters. As a result, you may need to perform a database refresh request to ensure the count reflects the most current data. However, please be aware that this approach can lead to performance issues, especially when used for conditional visibility.

**Comment by NessyCat** [comment]
Thanks Alezanello
