### ISSUE TITLE
Infinite scroll does not work on StaggeredView 

### ISSUE THREAD

**Issue by alih552** [FlutterFlow/flutterflow-issues#4846]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When setting Infinite scroll to True it shows a blank & empty space.

### Expected Behavior

It should show the dynamic components normally inside the straggeredView comp.

### Steps to Reproduce

- create a firestore collection something like "products" and populate it with some data more than 30
- create a straggeredView comp. & query from the products collection
- in query settings set the infinite scroll to true & page size of 6 (less than 30)

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITEShfLl05dgotdc7ofQLflAhQcgQlgnU+cZjuxEdxMvIrbyOu9/O/elQFtuXtCod0NhHFeJkkcywdbev4T1U/VeGASufrZj+M5yED3JWXq8R7LREruWPHx5P9pUGG6i5Lujmh0lBNt1dUEj3F+XN+yAQgLqN5+/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/81536c9d-330c-4dff-8fa0-f979959ef1f9)

### Environment

```markdown
FlutterFlow v5.0.9+ released October 25, 2024
Flutter version is 3.24.2
Windows desktop app
```

**Comment by Alezanello** [comment]
Hello!!

I hope you're doing well!

I wanted to let you know that I wasn't able to replicate the issue. When I tested it with a page size of 6, I was able to scroll down, and it retrieved everything as expected while scrolling. It’s possible I might be missing a step or detail you took during your testing.

To help clarify, I’ve included a public project that you can clone and modify as needed: [Project Link](https://app.flutterflow.io/project/qa-2989-7sl1x5).

Additionally, here is a video demonstrating the behavior I observed for your reference.

[Screen-Recording (38).mp4](https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/444bef00-ba44-49a6-94db-7fb2e462e774/d4a77839-a675-43b9-830a-74c20d884308?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS80NDRiZWYwMC1iYTQ0LTQ5YTYtOTRkYi03ZmIyZTQ2MmU3NzQvZDRhNzc4MzktYTY3NS00M2I5LTgzMGEtNzRjMjBkODg0MzA4IiwiaWF0IjoxNzMxMDc0MjQzLCJleHAiOjMzMzAxNjM0MjQzfQ.0SPw8mr21wT5jVBEePkIQLj3_p5t7yG9JMcfpE9pBM0)

**Comment by Nanyorng** [comment]
Hi

**Comment by alih552** [comment]
Hi @Alezanello 
Ok so if we put a straggeredView comp. inside a scrollable column it won't work.

**Comment by alih552** [comment]
![image](https://github.com/user-attachments/assets/3cbf9e6a-b103-46f8-b640-373e680ad857)
![image](https://github.com/user-attachments/assets/909b9641-4f4e-484f-8904-4a46b03b1308)
![image](https://github.com/user-attachments/assets/97d82c8f-8a0c-42cb-85de-c6b95443a4d9)

**Comment by Alezanello** [comment]
Unfortunately, having both the `Column` and the `StaggeredView` scrollable at the same time creates a conflict in how Flutter handles scrolling. This happens because the `StaggeredView` is already a scrollable widget, and when you make the parent `Column` scrollable (for example, by wrapping it in a `SingleChildScrollView`), Flutter gets confused about which widget should handle the scrolling behavior.

To avoid this issue, it's best not to make the entire `Column` scrollable. Instead, let the `StaggeredView` manage its own scrolling. Here's the idea:

* Keep the `Column` as it is, without wrapping it in a `SingleChildScrollView`.
* Allow the `StaggeredView` to handle all the scrolling independently.

This ensures smooth scrolling and avoids any conflicts. Let me know if you need further clarification or help implementing this!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
