### ISSUE TITLE
GoogleMap zoom-in/zoom-out behind BottomSheet

### ISSUE THREAD

**Issue by krystian-dev548** [FlutterFlow/flutterflow-issues#4847]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I used the GoogleMap widget, but if you display over it a BottomSheen with a scroll, the GoogleMap behind it zoom-in/out when the cursor scrolls.

### Expected Behavior

The GoogleMap should zoom-in/out only if the uses scrolls directly on it, but only if it's visible.

### Steps to Reproduce

1. Create a blank page with GoogleMap widget inside it
2. Create a new bottom sheet with some content inside a column scrollable
3. Create a button to show the bottom sheet

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40iMn1z4pItbxK1aXqKcJV+T45Jj98a+dI1u1raCsrfePoBOw+Y/nBQFVUOP24YXNEMWH8/D4X/Mr7idmSEuw6KSWsfbo9zKVUcDqWVlmgM73XPpS3b3R5N5lhfWKs5quziBVDHMx0SXBmw1+mCfPISgXZNIDRDno0AOaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

Note the:

1. Starting and final position of the map
2. Mouse pointer changing

https://github.com/user-attachments/assets/b6d0d63a-5bad-498f-8396-7a81364f7ad8

### Environment

```markdown
- FlutterFlow version: v5.0.9 released October 25, 2024
- Platform: macOS
- Browser name and version: Safari v. 18.1 (18619.2.8.111.5, 18619)
- Operating system and version affected: MacBook Pro 13.7.1 (22H221)
```

**Comment by Alezanello** [comment]
Hello!

Thank you for bringing this to our attention. We’re aware of this issue, and our team has already added it to our backlog of improvements. You can view the original issue and track updates here:<br>[GitHub Issue #1759](https://github.com/FlutterFlow/flutterflow-issues/issues/1759).

I'll make sure to add your feedback internally as well. Since this is a duplicate, I'll close this thread for now.

Thank you for your understanding!
