### ISSUE TITLE
Unwanted character at text end in appbar.

### ISSUE THREAD

**Issue by Shubham-VE** [FlutterFlow/flutterflow-issues#486]
## Expected behavior (required)

Long text should be truncated in appbar.

## Current behavior (required)

Long text is truncated with some unwanted character/icon at end.
## To Reproduce (required)

1. Add very long text in the title.
2. run and observe that the text has an unwanted character at the end when truncated.

## Screenshots / recordings

<img width="752" alt="Screenshot 2023-02-14 at 2 10 18 PM" src="https://user-images.githubusercontent.com/102008213/218684949-46da1435-3236-41b7-98f3-adce362094b2.png">
Notice the character at the text end(just before the settings icon) even though the text is made expandable.

## Your environment

* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by bulgariamitko** [comment]
Which character do you mean? I only see the 3 dots. 

Can you please provide a Bug Report Code as well. This is how you can create it

![whats-new-FlutterFlow](https://user-images.githubusercontent.com/7221384/215421133-34dab909-6647-4b03-8d40-2539ca0b0b3a.png)

**Comment by Shubham-VE** [comment]
Bug Report:
IT40z/Hqx89gocNf7aXpbfpajic5KVgjbY0nlutRaCgoF5jpD7MAdvXsS1VvcMPgdwhLfUSmmTgKpuDGhdmSV+woJS+tfJhTycxiSw7zQl27Q8HfU/HUACkbeacOQSj6
<img width="752" alt="Screenshot 2023-02-14 at 2 10 18 PM" src="https://user-images.githubusercontent.com/102008213/218932291-c13281da-f232-4b6d-8824-ae8221ff90ee.png">
The encircled character/icon appears whenever the text is truncated. This issue is not there only in app bar, on the page the text is truncated normally with 3 dots.

**Comment by agreaves** [comment]
Hi @Shubham-VE, thanks for the bug report. Unfortunately this appears to be an underlying Flutter issue so there's not much we can do on our end to fix this. I can suggest a few options though:
1. Make the Text auto-sized or give your Text a defined width to restrict it's maximum size.
2. Add padding between the Text and the icon so that it does not interfere with the rendering of the icon.
3. Consider shortening the AppBar title, as AppBar titles are generally not meant to span the entire length of the screen.

Apologies that there is nothing else we can do, but I hope one of these suggestions is helpful! Closing this issue for now.
