### ISSUE TITLE
Place API google key reveal in chrome 

### ISSUE THREAD

**Issue by sergedahdouh** [FlutterFlow/flutterflow-issues#4871]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Hello, 
When I add the place api widget and add the api for Google Maps in the setting, then the api will be revealed in the Chrome browser. I tried to restrict it to the website only but it is not working, giving me an error that occurred when getting the place response:
API keys with referer restrictions cannot be used with this API.

### Expected Behavior

hello,
the api key should be shown in chrome 

### Steps to Reproduce

1) create a page
2) add place picker widget
3) add the api key 
4) publish
5) Inspect the console 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ol/Lcw491xLRG1r6JKvlVhSQRJm17R4IZiMpBcykbCJz0BIgEf/Skck5vZrykdAhfPk60oD0x7Pfqv4TDCu0CYEidR6Vx/7gNTj3hTmWWMM2OC5GRfW1QDeNjfm6eyqWNrB0nItFedHwa3znzOue+ZD3rJoDGOVUZR86bKdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

<img width="734" alt="Screenshot 2024-11-10 at 21 33 52" src="https://github.com/user-attachments/assets/43715976-aa1c-43b8-976d-8f3254109d75">

### Environment

```markdown
- FlutterFlow version: v5.0.8+
- Platform: mac
- Browser name and version: chrome
- Operating system and version affected: os
```

### Additional Information

this issue is very critical as we cant deploy the web with google map

**Comment by Alezanello** [comment]
Hello!

The Google Maps API Key generated by a Firebase Project is linked exclusively to that specific project. This means that even if someone else gains access to that key, the API would only function within the context of that particular Firebase project. This setup prioritizes security by limiting its usage to the project level, rather than solely restricting access to specific URLs. You can find more details here: [Firebase API Keys Documentation](https://firebase.google.com/docs/projects/api-keys#:\~:text=Open%20the%20Credentials%20page%20of,API%20key%20to%20have%20access).

**Comment by sergedahdouh** [comment]
Thank you for replying. So you mean I use the API key generated from Firebase? and is enough 
<img width="1282" alt="Screenshot 2024-11-12 at 20 06 35" src="https://github.com/user-attachments/assets/3db38752-58a2-4c06-b50b-e91b4401ddd8">

**Comment by sergedahdouh** [comment]
actually, is not correct, as i have tested the same api with another project, not same firebase and is work

**Comment by Alezanello** [comment]
If the key isn’t working as expected and cannot be restricted, you may need to reach out to Google Cloud Support for assistance. They can help address issues related to the API key not being restricted to a specific project.
