### ISSUE TITLE
Algolia Search Results are not showing in Mobile App ListView

### ISSUE THREAD

**Issue by asifmasroor** [FlutterFlow/flutterflow-issues#4876]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have copied the Algolia Search Page from template in a new project with new Firebase connection. I enabled Algolia Search in the project settings and linked the required API search ID'/config as per the tutorial. I have enabled action os searching in the textfield onChange Event and linked the listview to the Algolia Search results from index (same name as firestore document). I am able to see the integration and search results on the web version. However, I am unable to see the results on Android or iOS app.
<img width="1053" alt="Screenshot 2024-11-13 at 1 26 05 PM" src="https://github.com/user-attachments/assets/81d30fce-d474-4528-83ef-f4ba3f54a5e8">

### Expected Behavior

Search results should appear on the mobile App (Android & iOS) as they are appearing on the web version.

### Steps to Reproduce

1 - I have copied the Algolia Search Page from template in a new project with new Firebase connection. 
2 -I enabled Algolia Search in the project settings and linked the required API search ID'/config as per the tutorial. 
3 -I have enabled action os searching in the textfield onChange Event and linked the listview to the Algolia Search results from index (same name as firestore document). 

I am able to see the integration and search results on the web version. 

However, I am unable to see the results on Android or iOS app.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kPLl8ZdOtbxa1s+NbPlVgmA5JkQlRpJElOtraCotCLbkOpgcf/fOYkRuZ9yrYEFtfU2kkWoW0fDWvoaeA8BdA0ucY5xYyKV1EA/LXmOgWqaKFJWgP3QmHf9MFX3D5LTQmRJTCMd0WUEj21yEftiUcD/rNYzFNVU8Da/LZO4=

### Visual documentation

![Uploading Screenshot 2024-11-13 at 1.26.05 PM.png…]()

### Environment

```markdown
- FlutterFlow version: 5.0.9 (5.0.9)
- Platform: MacOS 15.1 (24B83)
- Browser name and version: Chrome 130.0.6723.117 (Official Build) (arm64)
- Operating system and version affected: MacOS
```

**Comment by Alezanello** [comment]
Hello!

I was unable to replicate the issue, but it may be due to a different approach I used:

1. Place the Algolia query within the ListView widget.
2. Use the TextField with an `OnChange` action to refresh the database connected to the ListView.

Here is the public project for your reference so you can see how it’s set up.<br><br>Project: [https://app.flutterflow.io/project/q-a-algolia2-kn3jd2](https://app.flutterflow.io/project/q-a-algolia2-kn3jd2)

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/9f85acf5-3840-4314-81e4-c5d1376a4ff7/e64d7e7a-8f02-41a8-b8c8-39770d995495?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85Zjg1YWNmNS0zODQwLTQzMTQtODFlNC1jNWQxMzc2YTRmZjcvZTY0ZDdlN2EtOGYwMi00MWE4LWI4YzgtMzk3NzBkOTk1NDk1IiwiaWF0IjoxNzMxNjAyMjg5LCJleHAiOjMzMzAyMTYyMjg5fQ.YPMawbTyEB33fZRufcbsaul0KaLHbrOYGlFpguYFkEQ " alt="image.png" width="1691" height="1028" />

**Comment by asifmasroor** [comment]
@Alezanello Thanks for your reply. I am unable to see the project https://app.flutterflow.io/project/q-a-algolia2-kn3jd2 and getting this
error message: Uncaught Error: [cloud_firestore/permission-denied] Missing
or insufficient permissions. Can you please assist me how to access this public project.

**Comment by Alezanello** [comment]
Hello!!<br><br>There was an error with the public projects, it should be resolved at this moment, could you try to access it gain please?

**Comment by asifmasroor** [comment]
Good Morning,

Yes, I can see it now. Thank you.

However, the issue I’m encountering seems to be related to enums in the
Algolia Search results within my project, which is already being discussed
in another thread. Could you kindly expedite this issue? Here’s the link
for reference: https://github.com/FlutterFlow/flutterflow-issues/issues/3464
.

Thank you so much! I honestly didn’t expect a response, but you’re amazing
for addressing this!

Cheers!

**Comment by Alezanello** [comment]
It’s great news that we’ve identified the root cause of the issue as enums with Algolia. Even better, the team is already aware and actively working on a fix. I’ll go ahead and mark this issue as a duplicate and link it to the one you referenced in your comment above.<br><br>Thanks for the patience!
