### ISSUE TITLE
After the update on November 13, 2024, when the Cursor Position is set to "end", the "highlight flashes"(bug) and then moves to "end".

### ISSUE THREAD

**Issue by AlligatorCode** [FlutterFlow/flutterflow-issues#4918]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When I set the "Cursor position" property in Set Form Field Action to End ,  the "highlight" flashes and then moves to "end".

![_____111Captura de tela 2024-11-16 210048](https://github.com/user-attachments/assets/62194a66-2dee-4c8e-8ec4-59769f8c8f20)

### Expected Behavior

The "highlight" must not occur; the cursor should only move to "end".

### Steps to Reproduce

1- Create new Page
2- Add a Text field
3- Add a button
4- Set on Tap action of button to "Set Text Field", enter a "23" as value and choose End as Cursor Position.
5 - Test the button.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40zPHlwIt1rs9H+Kr1bcBr/SQ5Jnk2U4IO19ZRaCgoIYyuOpl/evXsXFFWQuarTUFcOUSmmlwz0NLXjvH1GO0rH02rGKk5+KVcWwuWXl2WUZOBEaqgVnFCIJ9Pf2LC0cG0niYnIrN1dCFg72GAHvDIbHfDQZDrImdISq/LZO4=

### Visual documentation

![chrome_6is4hTqcVk](https://github.com/user-attachments/assets/7168fea8-1b74-447b-a113-a807cd3e1660)

### Environment

```markdown
- FlutterFlow v5.0.11+ released November 13, 2024
- Flutter version is 3.24.2
- Platform: Web
- Browser name and version: Chrome
Versão 130.0.6723.117 (Versão oficial) 64 bits
- Operating system and version affected: Windows 11 Home
```

**Comment by paulperez-dev** [comment]
Hi @AlligatorCode! I’ll go ahead and forward this to the Engineering team so they can work on this. Thanks!

**Comment by paulperez-dev** [comment]
Hi @AlligatorCode!

The 11/13 update included a necessary change to ensure the cursor appears in the text field (focus call), which wasn’t working properly on some platforms. However, this change might occasionally cause the text to highlight.

At the moment, we can’t modify this behavior because the focus call is essential for the text field to function correctly. We’ll continue to monitor this and revisit it in the future to better understand why the delay happens.

I hope this explanation clarifies the current behavior. Since we’ll be keeping an eye on this for future improvements, I’ll go ahead and close the issue for now. If you have any further questions or concerns, feel free to reach out anytime.
