### ISSUE TITLE
Start Record and Stop Recording no longer working

### ISSUE THREAD

**Issue by mal2087** [FlutterFlow/flutterflow-issues#4946]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I previously implemented start record and stop record to generate a FFUploadedFile type in bytes. This was previously successfully working, confirmed with being able to send audio tiles to OpenAI's text to speech. In the last few days however, the file is no longer being generated. I tried testing it as well by trying to upload the FFUploadedFile to firebase and then trying to play the audio but there is no file that is produced. In addition, prior when it was working, it was only working on the chrome browser and never on the safari browser. On the safari browser, start record would initialize for 2 seconds, and then automatically stop by itself. So it went from only partially working to not working at all now, rendering voice interactions using FF inbuilt features not functional.

### Expected Behavior

Start record and stop record resulting in a audio file as a FFUploadedFile type

### Steps to Reproduce

1. Create a page
2. Add the start record and stop record in-built actions
3. Try to use the resulting audiofile in some way, whether its trying to uploade it to firebase storage to test it out or sending to a service like OpenAI speech to text to transcribe

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4glsjfz49On7xZ15DuKu9ahjwRQmI8U5c0st5Hd0gdCOPrBqQIec77VFtoXsPgaVNcelekkXwHw9L4ivLhC/YnHymuUa5f1ZZQSDnke2igRLqqCc+WXX97EfhQfGKD1MCwnhBTOsl2SmQ73E+hfvK8aAHDBOu/Zwh9f6PHaOI=

### Visual documentation

[screen-capture (4).webm](https://github.com/user-attachments/assets/bd135af1-b1fe-4687-af11-693fa30b6d69)

### Environment

```markdown
- FlutterFlow version: V5.0.0+
- Platform: chrome
- Browser name and version: Chrome
- Operating system and version affected: Windows, Chrome
```

**Comment by Alezanello** [comment]
Hello!!

I wasn’t able to replicate the issue on my end. I was able to record audio, pause the recording, and then play back the recorded audio without any problems. Here’s a public project based on your test for reference: [https://app.flutterflow.io/project/qa-3093-7rdryp](https://app.flutterflow.io/project/qa-3093-7rdryp).

**Comment by mal2087** [comment]
Nice thanks! That does work on web browser on desktop. Do you have any insights on why this doesnt work on any web browser on apple devices?

**Comment by mal2087** [comment]
Actually, more importantly. Would appreciate your help trouble shooting: It was previously working to send to OpenAI's whisper via API call, but in the last few days it suddenly stopped working. Was there a change in the way that the recorded file is stored?

**Comment by SitnAlex** [comment]
Hello, don't know if I have the same exact issue but something is definitely wrong with files. I have two versions of my web app. And in newer one I'm now unable to load the file to api because it has strange file format so api rejects it.

Here's a file from old version: 
- recordedFileBytes.mp3
- content-type: audio/mpeg

Here's a file from new version:
- recordedFileBytes.app/142a106d-5cb5-47c5-b700-d9cf1aaad214
- application/octet-stream

Bug report code (from a component with api call): IT4Klcr135VNxLxc+Kr+avlVuCosJj8kar80lutuUQIYF7aqG7YMS8+kMxJVXemndGNEL02Zqzo1+cqKkfPqA+UpGwSaGd1Tyc8JSQnKXk+5V7qNEpC8R3FCI9tJJVy84baFuiR4GPZsV0Ie2lOmfuyvHx/fJZDTClgZPuX/Ld/Ms3uqQ0SLb3kNh1JWeC/v

**Comment by SitnAlex** [comment]
@Alezanello can you provide any info on that? I need this to work asap. Tell me how to fix this

**Comment by drdevinhopkins** [comment]
Same here, the changes in the stopAudioRecording() util function also broke my app. No longer able to send the recording to an external API. Possibly due to the following change, where the file no longer as a file extension?

audioName: '[recordedFileBytes.mp](http://recordedfilebytes.mp/)3' became audioName: 'recordedFileBytes',

**Comment by IanCarrasco** [comment]
Hi, we are aware of the issue and fix will be rolling out

**Comment by drdevinhopkins** [comment]
> @Alezanello can you provide any info on that? I need this to work asap. Tell me how to fix this

not sure why, but the new changes work fine when I'm running my project locally on Chrome, but bug out when deployed remotely to web (on flutterflow, codemagic, firebase hosting)

my temporary fix:

open lib/flutter_flow/flutter_flow_util.dart
find the stopAudioRecording() function
go to the line containing 
`String extension = getFileExtension(recordedPath) ?? 'mp3';`
and replace it with
`String extension = 'mp3';`

this will essentially set all your audio recordings to the mp3 extension
my external apis are now accepting the files

hope that helps for now until Flutterflow rolls out their fix

**Comment by SitnAlex** [comment]
> Hi, we are aware of the issue and fix will be rolling out

Hello, so you didn't include the fix in this Thursday's update, will it be included in the next one?

**Comment by IanCarrasco** [comment]
The fix has already been submitted and should be rolling out in the coming days. Effectively the cause of the issue is due to platform specific support for certain audio encoders. We're going to be using the m4a container format to reduce encoder compatibility issues. Existing OpenAI whisper flows will be compatible with m4a. Thank you all for your patience on this issue.

**Comment by SitnAlex** [comment]
@IanCarrasco  Will there be an option to have audio files in any of these formats?
.aac,.aiFF,.alac,.flac,.mp3,.mp4,.ogg,.pcm,.wav,.wma

**Comment by drdevinhopkins** [comment]
@IanCarrasco Do you know if m4a works for recording with flutter web on mobile (safari, chrome)? that's another bug I keep running into, have to manually change the encoding from opus to wav for it to work, but the wav files tend to become huge

**Comment by IanCarrasco** [comment]
The main limitation is widespread support of certain audio encoders across platforms. m4a is a container format so it can store audio that was encoded using both aac lc (mobile) as well as opus (web) vs. mp3. If we wanted to support the other formats we would need to bake in ffmpeg conversion from m4a to .mp3/.wav/..., which is a possibility. 

The .wav encoder has widespread support across platforms but being an uncompressed format is problematic due to large file sizes as @drdevinhopkins also pointed out.
