### ISSUE TITLE
Possible critical library bug (...but may be a feature request...or maybe im an idiot...but pretty sure a bug)

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#4953]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/d01159c4a24b4ffa998bb0dc008e9090

This is a big of a complicated one...

It seems like with how imports are automatically generated and handled with libraries and then definitions called that you can't extend database functionality with libraries. 

So not sure whether to call this a "bug" or a "feature request" but it seems like the spirit of the library feature which is otherwise amazing I believe this to be critical enough to library functionality to call this a bug.

Basically, if you set up Supabase in a ilbrary project and a main project you get definitions conflicts.

I THINK it is because the automatic imports dont allow you to alias them properly but I could be wrong.

### Expected Behavior

I think the solution would be to simply allow aliasing in the automatic imports in custom code but I could be wrong? Check that the path is defined but then allow aliases? Not sure... but that's my best guess

### Steps to Reproduce

create main app
create library
activate supabase in both
create a custom action that actively calls the database
watch everything break

### Reproducible from Blank

- [x] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT5TiOfqxItOseFZ15D+YMZR/SAXKUg5arsslutudwIdDOvzP7AQd8mlS3FJXMu4d2xUJGH8sGAI7vDGuOzDEu47E0iIQ75e1s0IEw2WWmOuRLXTDM+CX0QkEp9TGBG64LCOiglRKu1qcUIB22GqH9+/EwXBNpD6O0QjJf+LOp/LpEqBK3vKFDh2tmNecCfn

### Visual documentation

https://www.loom.com/share/d01159c4a24b4ffa998bb0dc008e9090

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected: 


Main project bug report code
IT5TiOfqxItOseFZ15D+YMZR/SAXKUg5arsslutudwIdDOvzP7AQd8mlS3FJXMu4d2xUJGH8sGAI7vDGuOzDEu47E0iIQ75e1s0IEw2WWmOuRLXTDM+CX0QkEp9TGBG64LCOiglRKu1qcUIB22GqH9+/EwXBNpD6O0QjJf+LOp/LpEqBK3vKFDh2tmNecCfn

Library bug repost code
IT4wi87huIhgrsBE1rrUcMBviikQIjs6bZIw0u0bUis8GZT0B4kcYs+kfklUOe2+S2xie2CagnsX/Mrrjd7PNPErHyuuc75ZyM56dg2Vez6WaL60Bb63b2tTM8RTI3Kj0JmJuSVQWcB0WlIs2k+UHem+fDLfHqbQCzM4AOa4XdeK2SrDX1iXc2URm05KZDPz
```

### Additional Information

I think this breaks libraries for extending or abstracting out database functionality so a pretty big deal

**Comment by Alezanello** [comment]
**Hello,**

Thank you for your patience while I took some extra time to review this issue. I consulted with the engineering team regarding the possibility of using a Supabase database in a library to be consumed by a project. It turns out that this functionality is not currently intended to be supported (yet).

The team clarified that the real issue here is that the Supabase feature isn’t properly disabled for library projects, as it should be (similar to Firebase). Therefore, the current behavior—where Supabase doesn’t work in this context—is actually expected.

I apologize for any confusion or inconvenience caused and appreciate your understanding. Please let me know if there’s anything else I can assist with!

**Comment by chuggmuffinReturns** [comment]
Thanks @Alezanello for the clarification and taking the time to look it up!

This may not be the right forum for this question but while the issue is fresh on your mind...

...once this is properly disabled are you aware of any techniques to be able to do imports from a project into a library?

It seems like the other way to do this would be to be able to access '/backend/supabase/supabase.dart'...

**Comment by chuggmuffinReturns** [comment]
The goal is not to "use a Supabase database" per se but to extend the functionality while being able to access the FF logic.

Precise use case is to turn PowerSync into a library

**Comment by jonl-percsolutions-com** [comment]
> The goal is not to "use a Supabase database" per se but to extend the functionality while being able to access the FF logic.
> 
> Precise use case is to turn PowerSync into a library

You might consider reorganizing your library and using the library properties that can be passed down.

I do something similar with Firebase.

I add firebase dependencies in my library.

Then pass down my properties to the library for accessing the right firebase app instance and other things required through the library parameters.

Also, one work around I have found is you can do almost anything in a custom action or widget.

So you can expose functions that do specific tasks and have complex code shared between custom code and widgets.

If you exclude from compilation, since everything is in the same project ultimately, you can use relative paths to access almost anything so long as you know where it is.

**Comment by chuggmuffinReturns** [comment]
@jonl-percsolutions-com I DMed you! Thanks for the lengthy reply! Soooo curious about what you're talking about!
