### ISSUE TITLE
project-environment is CLI doesn't work

### ISSUE THREAD

**Issue by AdrKacz** [FlutterFlow/flutterflow-issues#4964]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

As of now, the CLI export the code always with the environment selected on the branch exported.

### Expected Behavior

According to the documentation, I expect the argument `--project-environment` to force a different environment that the one selected in the application.

### Steps to Reproduce

1. Create a new project
2. Set up Firebase in the Production environment
3. Create a new Development environment and setup a different Firebase project here (one project per environment as per Firebase best practices: https://firebase.google.com/docs/projects/dev-workflows/overview-environments)
4. Make sure you have Development environment selected in FlutterFlow
5. Open a terminal and run `export-code` with `--project-environment Production`
6. Read `google-services.json` and verify it uses the Firebase project from your Development environment and not your Production environment as expected.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not relevant

### Visual documentation

Not relevant

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform: Desktop
- Browser name and version: Not relevant
- Operating system and version affected: MacOS
- FlutterFlow CLI version: 0.0.25.
```

**Comment by AdrKacz** [comment]
Early october @leighajarett mentionned you are actively working on this feature here: https://github.com/FlutterFlow/flutterflow-issues/issues/3951#issuecomment-2388677812

Any chance you updated the documentation before completing the feature?

Documentation: https://docs.flutterflow.io/exporting/ff-cli/

**Comment by Alezanello** [comment]
Hello!!

It appears that the system downloads the environment currently selected in the project settings, rather than the intended one.

This is definitely a bug. As a temporary workaround, I recommend selecting the **Production Environment** in the project settings when you want to download that environment, and switching to **Development** when you need to download the development environment. During my testing, this method worked reliably.

I’ll escalate this issue to our engineering team for further investigation. Thank you for bringing this to our attention! Let me know if you need help with anything else in the meantime.

**Comment by AdrKacz** [comment]
Thank you for your investigation and your suggestion. I'll make sure to switch to Production manually waiting for the bug to be fix.

**Comment by AdrKacz** [comment]
@wenkaifan0720 @Alezanello @asmengistu @organicnz I see this item is completed, however I can confirm this bug still exist as of today.

Can you please explain why did you close it early? Or maybe you have a pre-release with the fix ready?

Thank you,
