### ISSUE TITLE
VS Code extensions can't import main branch

### ISSUE THREAD

**Issue by AdrKacz** [FlutterFlow/flutterflow-issues#4969]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The **Download code** options doesn't work with `main`. It does work with other branches. The current error is:

```
Error downloading project: status: 404 Message: Branch name "main" not found
```

### Expected Behavior

I expect to be able to download code from `main`.

### Steps to Reproduce

1. Create a project
2. Setup the VS Code extensions
3. Open the command palette and select "Download code"
4. Ack the error

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

Not applicable

### Visual documentation

Not applicable

### Environment

```markdown
- FlutterFlow version: 5.0.13 (FlutterFlow) + 1.0.14 (VSCode extension)
- Platform: Desktop + VSCode
- Browser name and version: Not applicable
- Operating system and version affected: MacOS
```

**Comment by AdrKacz** [comment]
The error **only occurs** if you manually set `main` either in the extension setting or in the dialog. If you keep the fields empty it can fetch the branch without issue.

Could it be that the `main` branch is not named `main` by FlutterFlow? I tried `Main`, `master`, and `Master` but none worked.

**Comment by Alezanello** [comment]
Hello!

This is the expected behavior at the moment. If you want to download the "main" branch, you don’t need to set anything—just leave it blank. Only specify a branch if it is different from "main."

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/514a6c65-1ac0-41d9-8c9d-6eced3e0653e/b0897acf-7626-4264-bbbe-b8bfa89aac94?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MTRhNmM2NS0xYWMwLTQxZDktOGM5ZC02ZWNlZDNlMDY1M2UvYjA4OTdhY2YtNzYyNi00MjY0LWJiYmUtYjhiZmE4OWFhYzk0IiwiaWF0IjoxNzMyNjQ2NjY1LCJleHAiOjMzMzAzMjA2NjY1fQ.uKt0d7R4649nbaLJhBKiwP62DS6VxSY7s4skSSFszc0 " alt="image.png" width="763" height="122" />

**Comment by AdrKacz** [comment]
Thank you for your response. If this behavior is intentional, I’d recommend rephrasing the message to say, "leave blank for main" instead of using "default". The term "default" implies a preset value, but since setting it to main doesn’t produce the same result as leaving it empty, this can cause confusion.

That said, this is still a bug, as the product doesn’t behave as described. While it might be a minor and easily fixable issue, it remains a discrepancy. Understanding how it’s supposed to work doesn’t make it any less of a bug.

**Comment by Alezanello** [comment]
You're absolutely right! I'll forward this to the engineering team so they can update the description to make it clearer on how to retrieve the main branch.
