### ISSUE TITLE
Web published app crashing safari.

### ISSUE THREAD

**Issue by starsplitterrecords** [FlutterFlow/flutterflow-issues#498]
I'm having trouble with a web published app crashing in safari. i'd love for web publishing to work, I've been exporting my code and compiling to publish on my the web with my main app for over a year. i'd like to help you work out the issues.
I think the problem has to do with scrolling a column with sub columns of with generated child rows. I got it to work with listview widgets rather than columns, but those don't scroll right when nested.

**Comment by hariprasadms** [comment]
@starsplitterrecords -  Could you please follow the issue template to share the issue details. Screenshots and recorded videos will help us to rectify the issues quickly. If you could provide these details in recommended standard issue template formate, that will be great. Thanks

**Comment by kovacskz** [comment]
The app also crashes for me in Safari, but not in Chrome.
I'm using Gridview, 2-30 doc/collection/query, and after 5-10 quick page changes, the app crashes and restarts itself. This phenomenon started this week and only appears in Safari.
There was an IOS update this week, where the webkit was also updated (due to 0day), since then I have had this problem. It is possible that another error occurred due to the quick error correction.

**Comment by katherineqian** [comment]
Hi @kovacskz and @starsplitterrecords, 

For reference, as @hariprasadms mentioned, we have an issue submission template that helps us get enough information to assess the issue. 

For now, can you please provide a bug report code (generated by right clicking inside widget tree and selecting Generate Bug Report Code) for your failing projects? Thanks.
