### ISSUE TITLE
Text, buttons, fields don't have value

### ISSUE THREAD

**Issue by king-anna** [FlutterFlow/flutterflow-issues#4981]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Login page, signup page and many others don't have text value, fields value are missing and buttons.

### Expected Behavior

Buttons, text, fields have assigned values

### Steps to Reproduce

Add buttons, fields and text, some of them (not all) will be missing when published. (Unfortunately I cannot see it in test because I'm experiencing another bug: the pages are blank in test mode)

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXi8mAvJNIschE1s7xLcBGqD8wFjMLa+cF0+1+FB4aF5CtBOw2P8/8S0NKTe7gTAtqME6IrFgJ+dLyiPP9EPE5CwqrUYs60JVASA7gLUK5Mb6mEpOSfHNQHcdbI3Kk0JiC3RNBKtJoR3hn21z6Nq3qNleeY8aSfxBlZ7vfcPo=

### Visual documentation

<img width="1224" alt="Screenshot 2024-11-27 at 9 50 55 AM" src="https://github.com/user-attachments/assets/f713037c-6638-430c-aad5-b26f19e3b599">
![Screenshot 2024-11-27 at 9 51 39 AM](https://github.com/user-attachments/assets/c3bf8626-5a49-4df8-9cf0-38c8dbfbe648)

### Environment

```markdown
- FlutterFlow version: 
- Platform: Web
- Browser name and version: 
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

The issue occurs because multiple languages are enabled in your app, but the text values for those languages haven't been filled in, or the translation tool in the language settings hasn’t been used. You can verify this in the UI Builder by checking the World icon in the settings.

For example, if you are building the app in English but the app detects that the OS is set to another language, it will attempt to display the content in that language. If no translations are provided for a widget in that language, it will appear blank.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/fa28a3b1-2b0c-48c5-ae33-c687b6b40c15/3476f357-7921-432d-8774-d61487380448?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mYTI4YTNiMS0yYjBjLTQ4YzUtYWUzMy1jNjg3YjZiNDBjMTUvMzQ3NmYzNTctNzkyMS00MzJkLTg3NzQtZDYxNDg3MzgwNDQ4IiwiaWF0IjoxNzMyNzI5NzM4LCJleHAiOjMzMzAzMjg5NzM4fQ.g4m1Tp0l1yhvqlV9Rojo0mTfUt_jiR41KbjwazXTGz8 " alt="language.gif" width="1215" height="892" />

**Comment by king-anna** [comment]
Hi, I have removed all languages but the values are still default. The problem is not in the test but in the build mode. They are not empty as in your example when you select a different language; they are set to default value like the button is "button" while it should be "signup", the fields "text field" instead of "email" etc
![Screenshot 2024-11-28 at 12 06 19 PM](https://github.com/user-attachments/assets/03503fa6-8fc8-4085-9c79-aa78f56eace3)

**Comment by king-anna** [comment]
I see you removed my other post about an empty screen in test mode. It is a separate issue from the one described above.nThe issue is in the test mode, the screens are completely empty. I can see only the background and no elements at all. The run mode works fine, as well as the preview and publishing. It's only the test that shows it blank. The screenshot attached. <img width="532" alt="Screenshot 2024-11-28 at 11 32 49 AM" src="https://github.com/user-attachments/assets/0ada4228-e685-4d06-8508-e9616fe90b7b">

**Comment by Alezanello** [comment]
Hello!

I just downloaded and compiled your project, and everything appears to be working as expected. I'll go ahead and close this issue for now.

If any new issues arise, please don't hesitate to create a new ticket!

Thank you!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/50e7c485-d753-49d8-b8fe-2d8faef6a47f/84774f8c-2f36-4c8c-a9c3-441d03d1dbc9?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81MGU3YzQ4NS1kNzUzLTQ5ZDgtYjhmZS0yZDhmYWVmNmE0N2YvODQ3NzRmOGMtMmYzNi00YzhjLWE5YzMtNDQxZDAzZDFkYmM5IiwiaWF0IjoxNzMzMzQwMzE1LCJleHAiOjMzMzAzOTAwMzE1fQ.CBllCSZQqP6X95l-wmJwLeJY5oj0Hi_KSI0s8fCmwvY " alt="image.png" width="1919" data-linear-height="1019" />
