### ISSUE TITLE
SMS Verification issue

### ISSUE THREAD

**Issue by oper2k** [FlutterFlow/flutterflow-issues#50]
Many dev on FF have this issue
PLs check
https://community.flutterflow.io/c/discuss-and-get-help/phone-sign-in-stuck-on-recaptcha#comment_wrapper_12267990

Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## To Reproduce (required)

1.
2.
3.
4.

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 
* Platform (e.g. Web, MacOS Desktop): 
* Browser name and version: 
* Operating system and version (desktop or mobile):

**Comment by bulgariamitko** [comment]
Please add the information requested or this issue will be closed.

**Comment by oper2k** [comment]
Expected behavior (required)
Users enter your phone number and go to the sms confirm screen

Current behavior (required)
Users enter your phone number and nothing happens

To Reproduce (required)
go to the site vsetut.shop and try to signup

Steps to reproduce the behavior:
1. open vsetut.shop
2. click to any button
3. enter your phone number and click button

Context (required)
link to app - https://app.flutterflow.io/project/vse-tut-xp4uk1

**Comment by bulgariamitko** [comment]
No those need to be generic Steps. Like
1. Create a new project....
2.

**Comment by masfour7** [comment]
Hi, just helping out here. This issue happens with my phone number while testing; I haven't tested with real users to confirm the issue persists. But maybe @oper2k  has.

------
Expected behavior:
When I press the sign-in button, I should be navigated to the verify SMS page and sent an SMS.

Current behavior:
- The sign-in button shows a loader indicator for 1-3 seconds.
- A reCAPTCHA logo shows on the bottom right
- I do not get navigated to the verify SMS page
- I do not receive an SMS message

Steps To Reproduce - example:
1. Create a sign-in screen (just like formal templates from FF)
2. follow the docs for the phone sign-in method on FlutterFlow
3. Start run mode or publish the app
4. use a phone number to sign in. then log out. Then after sometime login again (twice or three times not sure)

Context:
I understand this is done for security reasons, but locking the customer's phone number after the second trial only is too much. Usually, customers are given multiple trials until their phone becomes locked; and they would be notified about it as well for a better user experience.

Screenshots / recordings:
Attached is a photo of the logo that appears when I hit the sign-in button:
![image](https://user-images.githubusercontent.com/60685289/197914523-cee962ca-423f-4ae1-b86b-0f67912ddbb3.png)

Your environment
* Version of FlutterFlow used: latest
* Platform (e.g. Web, macOS Desktop): Web
* Browser name and version: Chrome latest and Microsoft Edge latest
* Operating system and version (desktop or mobile): Windows 11

**Comment by Pepino-GR** [comment]
For testing you can set a dummy phone number to avoid blocking the original phone number in Firebase. Because you have to pay for the Phone login and for security reason, Firebase blocked the used phone number after , I think,3 unsuccessfully tries. The normally behavior is, that after you login, you stay a while inside the application.  For testing purpose, use the dummy phone number, that you have set in the Phone Authentication on Firebase.

  
<img width="962" alt="Bildschirm­foto 2022-10-26 um 10 54 10" src="https://user-images.githubusercontent.com/35230751/197982624-104fa852-6cf1-4adc-b04d-054c9876e205.png">
