### ISSUE TITLE
list variable can't be accessed in conditional to see if list is empty in a component? maybe?

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5002]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/2becd3de0477449bae58b18047905b55

In a component and trying to conditionally show or hide the list based on the number of items in the list

But it seems like I don't have access to the list variable..........

### Expected Behavior

Have access to the list variable

### Steps to Reproduce

component
listview in component
set list and name variable
try to access variable to determine conditional visibility seem to fail?

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8ozMr15c92pbxD7arydcFB/WAvJjs4a5I70tV6EAsYGJDnB4YMOuHBUFpWTu7hY0NHGVL88Xg0w6nKhIbLDu5cA0ytc75+3JVqWw2VeGqXb5SpCKjtQ3ZAJ/lPGWa80JmviBVGA+F1W1I732WUGuiQThfsNuPAIEUzD/+LNrjOjWCmHiX3MREyxikXAx7eTI5ODEz25eKMrop5yfj/0w==

### Visual documentation

https://www.loom.com/share/2becd3de0477449bae58b18047905b55

### Environment

```markdown
FF Desktop

Side note...

...you have the FF version in the app when you press the "bug report" button...

...couldn't this get prepopulated?
```

**Comment by Alezanello** [comment]
Hello!

In this case, the **Dynamic Children** value generated from the variable is only accessible by its children. Since the Column you’re selecting is a parent (and not a child) of this Dynamic Children value, it cannot directly access it.

One solution is to copy the value from the variable set and use it in the Column as a filter. This way, you can get the number of items you need.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/f24c4af9-0859-4c75-acb6-b95df48f72d1/5683edf8-0388-4ad6-afd7-0946a918118e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9mMjRjNGFmOS0wODU5LTRjNzUtYWNiNi1iOTVkZjQ4ZjcyZDEvNTY4M2VkZjgtMDM4OC00YWQ2LWFmZDctMDk0NmE5MTgxMThlIiwiaWF0IjoxNzMyODQ2MjcyLCJleHAiOjMzMzAzNDA2MjcyfQ.MLW1DkIM7mjmjS0RMeoyXjTlXsTs4ZnR7ZMPjptlQKo " alt="example.gif" width="1867" height="818" />

**Comment by chuggmuffinReturns** [comment]
hmmmmmmm....... ok cool! I will work with that thanks!

**Comment by Alezanello** [comment]
I’ll go ahead and close this issue, but if you encounter anything else, please don’t hesitate to open a new one!
