### ISSUE TITLE
on page load first calc action output and then the page itself with the widget. conditions on these widgets are evaluated then when all actions are calcualted

### ISSUE THREAD

**Issue by markusbecher** [FlutterFlow/flutterflow-issues#5005]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/d870056266604143a49772b2718ac320

### Expected Behavior

first everything on pge load is calculated and the action output value is set... then building the page and evaluating the attributs of action output

### Steps to Reproduce

add page. load SingleDoc from FB with a ref of auth user.  action outname = groupno.     make a row visible when certain field of groupno has got certrain value

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFXlfLIwIhhnNxE+s/yY8dvliEwFnIca+YZhOtta0gYNbL1PKQPbuveT1VDXM+rSmNqHVCgmlwHw/CMhYXlJvUoHE6EQ5R8/rVQVAqXJHGmRKaSCZOWVWpQAe1gfxWe0aW7vwp7HNBpWHMtig/GSw==

### Visual documentation

https://www.loom.com/share/d870056266604143a49772b2718ac320
![image](https://github.com/user-attachments/assets/8f491d8c-7484-4ed4-b213-0643e404b580)

### Environment

```markdown
- FlutterFlow version: 5.0
- Platform: Windows
- Browser name and version: Chrome
- Operating system and version affected:
```

### Additional Information

https://www.loom.com/share/d870056266604143a49772b2718ac320
![image](https://github.com/user-attachments/assets/453ecdcb-3b5e-424e-86db-130b47f2a865)

**Comment by markusbecher** [comment]
it is not an issue of Simulation,  I created apk and run it... same issue.

**Comment by Alezanello** [comment]
The Read Document it queries but never tells the app to rebuild the UI with the new data, to achieve this you need to update the State of the App from AppState or PageState.

To address this, I recommend the following options:

1. **Use "Update AppState" to Rebuild the Page:**
   * After the "Read Document" action, add an "Update AppState" action.
   * Leave the variable selection empty and enable the option **"Rebuild Containing Page."**
   * This ensures the page refreshes after the document is read, reflecting the updated values.
2. **Use a Page State Variable to Store the Document:**
   * Create a **Page State variable** of type **Document**, and name it something like `"userDoc"`.
   * In the **Page Load** event, after reading the document, add an "Update PageState" action to save the fetched document into this variable.
   * Enable **"Rebuild Containing Page"** in this step.
   * Then, instead of accessing variables or conditionals directly from the "Read Document" action, retrieve them from the Page State variable.

Both approaches ensure the page updates correctly and uses the document data effectively

**Comment by markusbecher** [comment]
perfect, works. Thanks for your quick help!!! I really love your product !
