### ISSUE TITLE
Error after latest update: Multiple heroes share the tag within subtree

### ISSUE THREAD

**Issue by squirrel-o** [FlutterFlow/flutterflow-issues#5014]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Can't test the app locally using Chrome, code doesn't update and I get the error that the same tag  https://picsum.photos/200/300 is used multiple times. Wasn't a problem before the update and I haven't touched the images in several versions

### Expected Behavior

I should be able to run the latest code locally to test the app

### Steps to Reproduce

1. Start local run
2. Navigate to candMainProfile

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTjufq5ot1rs9H+KX6LcJao2QRI0McWOdEl+tuZwgbIoznBu0hP87CQFRoQuGjaVNcKGGZ+WQz09bpidrDC8IFGE2ZbYhz+ZN2EQH0e2igM6anDamaWkYmEZ9RC3ab0KaRvyZ/PtdhLy0b22D3CtmyTijDFOu/Zwh9f6PHaOI=

### Visual documentation

<img width="766" alt="Screenshot 2024-12-01 at 15 07 48" src="https://github.com/user-attachments/assets/5e881a70-211f-425a-9dcf-dbbb0cc8f314">

### Environment

```markdown
- FlutterFlow version: 5.0.14
- Platform: macOS
- Browser name and version: Chrome 131.0.6778.86
- Operating system and version affected: Sonoma 14.6.1
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate this issue on my end. Has it already been resolved for you?

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/962f12e3-b52f-4e62-9c6d-49024362fdb9/763681b8-25bc-48d2-8632-1017fa798700?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS85NjJmMTJlMy1iNTJmLTRlNjItOWM2ZC00OTAyNDM2MmZkYjkvNzYzNjgxYjgtMjViYy00OGQyLTg2MzItMTAxN2ZhNzk4NzAwIiwiaWF0IjoxNzMzMjM2NzYyLCJleHAiOjMzMzAzNzk2NzYyfQ.9C-1iqun3LRVD0LEYeMAW_BFmMX1gzoUdscIIGAwOt4 " alt="image.png" width="1911" data-linear-height="1000" />

**Comment by squirrel-o** [comment]
@Alezanello hi, nope still happening :/ 

I only get the error when I navigate to the candMainProfile page, not the login. Do you need a test user access?

**Comment by Alezanello** [comment]
If you can provide a test user would be awesome!

**Comment by squirrel-o** [comment]
Sure 

o@ribin.com
123456 

when you log in, navigate to the user profile and you’ll see 
1. It’s not the latest version of the code (I was testing something using a button which isn’t the latest version) 
2. You’ll get the errors on the log

**Comment by Alezanello** [comment]
Hi there!

I came back with some news.

The problem occurs because Flutter’s `Hero` widget requires each tag to be **unique** within the same navigation subtree. This is a key design rule to ensure the Hero animation framework works as expected.

When you trigger a Hero animation (like during a route transition), Flutter looks for matching `Hero` widgets in the source and destination routes based on their tags. If there are multiple Hero widgets with the same tag in the same subtree, Flutter can’t figure out which one to animate, which leads to this error.

The tag acts as a unique identifier that links the source and destination `Hero` widgets for the animation. If multiple widgets share the same tag, Flutter gets confused about which one to animate, breaking the animation process. This requirement helps keep animations consistent and ensures the right widgets are animated.

To resolve this, make sure all `Hero` tags are unique within the same subtree. If you’re generating `Hero` widgets dynamically (like in a list or grid), give each one a unique identifier for its tag. It’s also worth double-checking your widget tree to ensure duplicate tags aren’t accidentally created in overlapping subtrees.

**Comment by squirrel-o** [comment]
Thanks, I got that much from the error message. 

I figured it out, changing the images for the test account solved the issue. It turns out flutterflow uses the image path as tag, and since I had the same test image twice, it was causing the issue. This would be nice to see in your help centre, since there's no way to assign a tag to an image from the UI
