### ISSUE TITLE
Infinite scroll does not work

### ISSUE THREAD

**Issue by dr-shoe** [FlutterFlow/flutterflow-issues#5034]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Because infinite scroll does not work, though I want to set infinite scroll in all of listviews, I cannot set infinite scroll.
For checking I set infinite scroll in a few pages.

### Expected Behavior

It is expected to work as infinite scrolling.

### Steps to Reproduce

To set infinite scroll in FF UI.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4klMmAx89gofVA1pDLbcFvnikXJno1TL07r+5xb0gvIrbyOu9/efekMxFoTu24THlhHE3++T00wfSLieGeEccpIQ+VbaZf/89UUwzzVXq8R6bTPrmKWHJBBeFXCWai5MG3sCZ7LvtZSmAd7VyUNe+vYCnrN5+/Zwh9f6PHaOI=

### Visual documentation

![image](https://github.com/user-attachments/assets/0fcbb318-47eb-4cba-a543-287bbe4a5b17)

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by rzambroni** [comment]
Hi @dr-shoe, 

Thank you for taking the time to submit this report.

This issue is actually a known one, and our team has already added it to our backlog for resolution. You can keep an eye on the [original ticket](https://github.com/FlutterFlow/flutterflow-issues/issues/2843) for any updates as we work on it.

We appreciate your patience and understanding!
