### ISSUE TITLE
Build error when adding "Items Spacing" to ListView

### ISSUE THREAD

**Issue by matlin76** [FlutterFlow/flutterflow-issues#5045]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

My ListView is working as expected until I add any value in "Items Spacing"
First of all, the added spacing is not shown in the UI and when running Test Mode you get "Build Failed"

### Expected Behavior

The added spacing is shown in the UI and no build errors

### Steps to Reproduce

1. Add ListView with items
2. Run in Test Mode
3. Add "Items Spacing"
4. Reload

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kj8nqy4x2rulA18/tbcdajSo7C1M3TLJEpu0bWUkbGO/4E4k2eeD4YVptZOKzaHNMGE6IgjkBpqn2koXhA/lfJQqYRt1byM1qehPPbD+QbLWVPc+eX3wkN+NbGXGB0JmJrCQkPbNsdC0N31z2OPC9RT+Cf9qOYwx5e6fDbOY=

### Visual documentation

No Images

### Environment

```markdown
- FlutterFlow version: v5.0.13+
- Platform: Web
- Browser name and version: Chrome 131.0.6778.87
- Operating system and version affected: Mac 13.6.9 (22G830)
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate this issue on my end. I created a new project using a ListView populated with a list of random strings and set the **Item Spacing**. You can check out the public project here:<br>[https://app.flutterflow.io/project/qa-3206-e4hbx4](https://app.flutterflow.io/project/qa-3206-e4hbx4)

It seems the issue you’re encountering might be caused by something other than the **Item Spacing** setting.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/d8a531d4-ac92-4f2f-8645-6ec323c9ea98/12c2d940-8126-408d-9d89-acf8618c3fb7?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9kOGE1MzFkNC1hYzkyLTRmMmYtODY0NS02ZWMzMjNjOWVhOTgvMTJjMmQ5NDAtODEyNi00MDhkLTlkODktYWNmODYxOGMzZmI3IiwiaWF0IjoxNzMzNDAzNTM0LCJleHAiOjMzMzAzOTYzNTM0fQ.13IRaO8l9B63ezCb03Fzbb103MXfCsc77ak-zCvO7CY " alt="image.png" width="1913" data-linear-height="670" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/17b7ff43-a735-447b-869c-b721725157ba/9d2bcf1f-cffc-431d-8d88-587a425aa204?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xN2I3ZmY0My1hNzM1LTQ0N2ItODY5Yy1iNzIxNzI1MTU3YmEvOWQyYmNmMWYtY2ZmYy00MzFkLThkODgtNTg3YTQyNWFhMjA0IiwiaWF0IjoxNzMzNDAzNTM0LCJleHAiOjMzMzAzOTYzNTM0fQ.SwZfLgDdiUCuM9YLDf72Wuxo_a4dmkOGA1m6meUYxUU " alt="image.png" width="1279" data-linear-height="896" />

**Comment by matlin76** [comment]
Hi @Alezanello 
Sorry, I forgot to add that it is "Reorderable"

**Comment by Alezanello** [comment]
Thanks to clarify this!<br><br>With this indeed it breaks! I'll send it to the engineer team for a fix.<br>Thanks!

**Comment by Alezanello** [comment]
Hello!<br><br>Just a quick update, it will never let you have both enabled, Item Spacing and Reorderable, It seems the error is not staying after you enable it and showing no errors on project while it should not let you have Item Spacing + Reorderable

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/84fedaf4-fc0b-4b33-b5df-ae89315e9a85/a3a16f61-dabf-405e-87ff-4032c086d74e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS84NGZlZGFmNC1mYzBiLTRiMzMtYjVkZi1hZTg5MzE1ZTlhODUvYTNhMTZmNjEtZGFiZi00MDVlLTg3ZmYtNDAzMmMwODZkNzRlIiwiaWF0IjoxNzMzNDIzMTgxLCJleHAiOjMzMzAzOTgzMTgxfQ.1KhoawD6wE9U7IVL9WEyGwpukr81nrYBekUNUmtF6ds " alt="image.png" width="307" data-linear-height="216" />

**Comment by leighajarett** [comment]
We have a fix for this issue in beta and it will be fixed in production tomorrow!
