### ISSUE TITLE
Google login with firebase works on local Chrome only - not in web and not with apk

### ISSUE THREAD

**Issue by markusbecher** [FlutterFlow/flutterflow-issues#5052]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/9a2d2971d48946bab006bbaf9e975bd9

### Expected Behavior

https://www.loom.com/share/9a2d2971d48946bab006bbaf9e975bd9

### Steps to Reproduce

login with Google works

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFTlfLIwIhhnNwD+KXiLMFVpCo7I0MfWOdEket+EA0hNYOqELAqfODCT1hLYtThT1BhelmIpEQypKn6vfzpOPEnFzWbb7lxzb5XQTvvfD+WMpisEs2KW0RBL9FVCUyE16TYnR5AXdVtS15i216QIPCdG3qCf9qOYwx5e6fDbOY=

### Visual documentation

https://www.loom.com/share/9a2d2971d48946bab006bbaf9e975bd9

### Environment

```markdown
- FlutterFlow version: 5.0.12
- Platform: windows
- Browser name and version: Chrome
- Operating system and version affected: Chrome
```

**Comment by Alezanello** [comment]
**Hello!** 

To resolve the APK issue, you’ll need to add a **SHA1 key** to your Firebase project. You can find detailed instructions on how to do this in our documentation here: [Generate the SHA1 Key](https://docs.flutterflow.io/integrations/authentication/firebase/initial-setup/#generate-the-sha-1-key).

Regarding the domain you’ve added, we recommend including only the base domain rather than the subdomain. For example, instead of using `<subdomain>.flutterflow.app`, use either **flutterflow.app** or **flutterflow.io**.

Let us know if you have any further questions or need assistance!

**Comment by markusbecher** [comment]
there have been SHA1 and SHA256 keys already.... but I regenerate them.....

now see what happens..  !!!!


[cid:73d3c1dc-96e2-4626-b32d-92950cdc3497]

HELP !




Markus Becher

Limmatstrasse 7

81476 München

Tel: 0171 5679963

Email: ***@***.******@***.***>



________________________________
Von: Alezanello ***@***.***>
Gesendet: Freitag, 6. Dezember 2024 14:14
An: FlutterFlow/flutterflow-issues ***@***.***>
Cc: markusbecher ***@***.***>; Author ***@***.***>
Betreff: Re: [FlutterFlow/flutterflow-issues] Google login with firebase works on local Chrome only - not in web and not with apk (Issue #5052)


Hello!

To resolve the APK issue, you’ll need to add a SHA1 key to your Firebase project. You can find detailed instructions on how to do this in our documentation here: Generate the SHA1 Key<https://docs.flutterflow.io/integrations/authentication/firebase/initial-setup/#generate-the-sha-1-key>.

Regarding the domain you’ve added, we recommend including only the base domain rather than the subdomain. For example, instead of using <subdomain>.flutterflow.app, use either flutterflow.app or flutterflow.io.

Let us know if you have any further questions or need assistance!

**Comment by Alezanello** [comment]
Hi Marcus,

It seems the media you sent didn’t make it to GitHub, possibly because it was lost when replying via email.

Just a quick clarification: this GitHub Issue Tracker is primarily for reporting bugs that can be reproduced in a new blank project. For issues that are specific to your project, we recommend reaching out to our support team via the in-app chat or by emailing [support@flutterflow.io](mailto:support@flutterflow.io).

**Comment by markusbecher** [comment]
OK, the in app chat is this here ?

[cid:00d238f0-40c6-43d3-87cc-9a64fb694340]




Markus Becher

Limmatstrasse 7

81476 München

Tel: 0171 5679963

Email: ***@***.******@***.***>



________________________________
Von: Alezanello ***@***.***>
Gesendet: Freitag, 6. Dezember 2024 15:33
An: FlutterFlow/flutterflow-issues ***@***.***>
Cc: markusbecher ***@***.***>; Author ***@***.***>
Betreff: Re: [FlutterFlow/flutterflow-issues] Google login with firebase works on local Chrome only - not in web and not with apk (Issue #5052)


Hi Marcus,

It seems the media you sent didn’t make it to GitHub, possibly because it was lost when replying via email.

Just a quick clarification: this GitHub Issue Tracker is primarily for reporting bugs that can be reproduced in a new blank project. For issues that are specific to your project, we recommend reaching out to our support team via the in-app chat or by emailing ***@***.******@***.***>.

**Comment by Alezanello** [comment]
The app chat is the one at the bottom right corner!

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/b536ac56-8154-4af5-801c-42bb5c6b9078/b4631377-6352-4253-9255-6be7ed528b81?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS9iNTM2YWM1Ni04MTU0LTRhZjUtODAxYy00MmJiNWM2YjkwNzgvYjQ2MzEzNzctNjM1Mi00MjUzLTkyNTUtNmJlN2VkNTI4YjgxIiwiaWF0IjoxNzMzOTM5MTE4LCJleHAiOjMzMzA0NDk5MTE4fQ.3cOzZ4SXW0K1aV4bMO2t5Zop7YmB8WUe8T9cDNJ3b74 " alt="image.png" width="1652" data-linear-height="904" />
