### ISSUE TITLE
not responsive API autocomplete

### ISSUE THREAD

**Issue by caetanoInovadora** [FlutterFlow/flutterflow-issues#5064]
### Can we access your project?

- [ ] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I created a textfield on a flutter-flow project with an onChanged event/action triggering an API call resulting in autocomplete options.
The call is successfull, but results are only populated after the user click on the textfield (long after the search text is typed) or triggers an extra space and backspace (long after the search text is typed). The search doesnt seem responsive and looks like only the cached options are displayed and populated.

OBS: This issue is similar to this flutter community post: https://community.flutterflow.io/ask-the-community/post/dynamically-autocomplete-on-textfield-PdCiGoqMpyGP4Ib

### Expected Behavior

The results of an API call autocomplete are populated/displayed without necessity of any further event triggers and dont show only cached results. 

### Steps to Reproduce

1. Create a textField widget
2. Set a onChanged event/action backend API call.
3. On the same widget select autocomplete option getting the result from the api action.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4kkeflz4p1ofVA18/tbcIwvCkXQ257TL03t9VxSUgrIrbyPJkUaeD7cltBTbSkTGxpKEWIgnIC/8ryioXDVPcBOgeaQL5CyYduaDnvVj+/aoStC5aoZUZ8RNNmBXHG38PUsQhTNbBYSmAj2ky6N+iUbB/vJqH7Zwh9f6PHaOI=

### Visual documentation

![flutter_flow_autocomplete_issue](https://github.com/user-attachments/assets/ad805314-b9be-4234-939a-59c822f371cd)

### Environment

```markdown
- FlutterFlow version: 5.0.13
- Platform: Web
- Browser name and version: Google Chrome
- Operating system and version affected: Linux
```

**Comment by Alezanello** [comment]
Hello,

The issue arises due to how Flutter renders data. The UI doesn’t automatically recognize that new data is available until a refresh or rebuild occurs.

To resolve this, I highly recommend saving the query result to a `PageState` or `AppState`. Then, trigger a rebuild whenever the state is updated. Set the Autocomplete widget to fetch data from the `PageState` or `AppState` rather than directly from the query.

This approach ensures that when the `AppState` or `PageState` receives the latest data, the UI will automatically refresh and display it correctly.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
