### ISSUE TITLE
Cant download code to VS code when there are project errors...

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5067]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/cef250d93cde4f06b8ccb4578f91137f

I want to edit and fix errors

FF is preventing downloading the code to VS code

This seems like a similar issue to the previous one where restricting action is pointless and just slows things down because error handling is largely covered later at compilation. 

### Expected Behavior

Be able to download broken code to edit it

### Steps to Reproduce

some errors in code lead to not being able to download code and some do not. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT8ozMr15c92pbxD7arydcFB/WAvJjs4a5I70tV6EAsYGJDnB4YMOuHBUFpWTu7hY0NHGlL88X40097PvtnxG/tcCwiuRpw+wqpyUx/PRmeVVqabCJO8WnMlBtxPCW6e0ae73SJNAPt2dns3wE+EIOyUcBLbGb7SDUVANeSKJpLOjWyBGwzdFiRs+ww+R26UEeljIVDq+f6QspZl1eTjzw==

### Visual documentation

https://www.loom.com/share/cef250d93cde4f06b8ccb4578f91137f

### Environment

```markdown
mac desktop latest to vs code latest
```

**Comment by Alezanello** [comment]
Hello!

This is the current expected behavior. Certain validations are in place to prevent the code from leaving FlutterFlow, primarily due to how the code generation process works. Addressing this would require deep enhancements and improvements to the core functionality.

For this reason, I believe it’s more of a feature/enhancement request than a bug. I’ll go ahead and forward this directly to the engineering team and link it internally for tracking.

Thank you for your feedback!

**Comment by chuggmuffinReturns** [comment]
Ok fair enough @Alezanello 

Thanks for looking into it!
