### ISSUE TITLE
Textfield execute big amount of API Requests, and also renderize the window

### ISSUE THREAD

**Issue by saruskas** [FlutterFlow/flutterflow-issues#5074]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am developing a web chat application. I have a listview listing the messages and a textfield to input a new message. When I tap in the textfield, a lot of api calls are executed, even the textfield only have "OnSubmit" action, and disable all the updates (component on focus change & component on text change).
Also if I renderize the window a lot of requests are also executing.

### Expected Behavior

The textfield to execute an api call only OnSubmit.
Not execute api calls when renderize the window.

### Steps to Reproduce

Create a new page
Add a stack
Add column backend query with dynamic children
Inside the column add a row with another backend query
Add a text field (stack parent).
Configure the text with Clear Field Icon and Autofocus.
When you tap the textfield api calls are executed.
When you renderize the window a lot of api calls are executed.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4wz/Hqx89gocNf7aXpbcAwiiksIjp8RJJM1MJ+GSs8I4jyO5YUSMzBUFFWTLygYFZ+OVn8gXId1vfqv+DPJvYpPTmaGd1qyZZccjnMIUamabaoBZbgfW1TL+BMfR2j35mniApNCNhvcnwl32D3LuescDbYNJy3DEg7M8ibJdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://github.com/user-attachments/assets/f86334e0-73a4-4d8d-b7bd-703a7c0a8b5c

### Environment

```markdown
- FlutterFlow version: v.5.0.12+ (released nov. 20 2024)
- Platform: Web
- Browser name and version: Chrome Version 130.0.6723.117 (Official Build) (64-bit)
- Operating system and version affected: Windows 10 Pro
```

### Additional Information

My company can not afford with a huge amount of api calls that shouldnt been call.

**Comment by saruskas** [comment]
Credentials to access:
user: vasken@brand4impact.com
password: password

**Comment by Alezanello** [comment]
Hello!!<br><br>This is not caused because of the Textfield.<br>It feels that way because it Autofocus when the page loafs, but when I click outside of the Textfield it also generates the queries and is because on your "On initialization" of the component you added a periodic action that triggers every 5000 ms.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/1c730de4-df1a-48ac-9349-b6a67e8cecd7/b56b426f-33a8-4748-8a2f-5bd33ad791b4?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS8xYzczMGRlNC1kZjFhLTQ4YWMtOTM0OS1iNmE2N2U4Y2VjZDcvYjU2YjQyNmYtMzNhOC00NzQ4LThhMmYtNWJkMzNhZDc5MWI0IiwiaWF0IjoxNzMzODQzMTIyLCJleHAiOjMzMzA0NDAzMTIyfQ.i3sOz-zBcMzYaymucKg5_cOYIdwaVL5qUBiLoBa4b-c " alt="query.gif" width="1803" data-linear-height="900" />

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/7d812dbd-a96c-4ed4-b617-f9e1cf581bac/6ec92b5e-072d-4fa6-8138-aada52418cee?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS83ZDgxMmRiZC1hOTZjLTRlZDQtYjYxNy1mOWUxY2Y1ODFiYWMvNmVjOTJiNWUtMDcyZC00ZmE2LTgxMzgtYWFkYTUyNDE4Y2VlIiwiaWF0IjoxNzMzODQzMTIyLCJleHAiOjMzMzA0NDAzMTIyfQ.z6jAkUoQfgWVufZEF2Uc5tNNxr46JHpHrQkFcEkX810 " alt="image.png" width="1779" data-linear-height="805" />

**Comment by saruskas** [comment]
Hi, thanks for your feedback. Sorry, I gave wrong the Bug Report Code and you access the wrong project. Please, access correct one with this Bug Report Code: 

ITFTls/l6ot2n7xd+KrcKcdFlikUI0McX5Ir1utsewgjGKL1BuwUfs/ObRJuXu3jaVNcBVD/uEgGwMrOkeOeKPEqJk+dQIQ4yaVyVQ/Oe2i6aZPRC8yKYWhBGtNmfEi55LSRqhN5HO5tSGQB12WuON7KaD/DIuu/Zwh9f6PHaOI=

And this project url (its a simplified project to see the possible bug): 
https://app.flutterflow.io/project/bug-f-f-gttfri?tab=uiBuilder&page=signIn

**Comment by saruskas** [comment]
See that just tapying in textField or outside execute an amount of api rquest not indicated

**Comment by Alezanello** [comment]
Hello again!<br><br>This is caused because`FutureBuilder` Rebuilds on `setState`<br><br>The `FutureBuilder` in your widget relies on the `getChatsCall API Call` result. Every time the widget's `build` method is called (e.g., when the `TextField` gains or loses focus and causes a `safeSetState` call), the `FutureBuilder` re-runs its `future`, causing the API call to trigger again.<br><br>And because FF uses FutureBuilder to call the API Calls at least for now is the current expected behavior

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
