### ISSUE TITLE
light mode/dark mode in web run not synced to run mode toggle?

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5082]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.loom.com/share/be0ea05edaef420d8ee53f97bc700c66

runmode lm dm toggle doesnt change the app if it is set to system mode

### Expected Behavior

the runmode lm/dm toggler to be "system mode" and reflect in app

### Steps to Reproduce

page with lm / dm enabled
click run mode, defaults to system as expected
click the run mode toggler which switches the browser lm/dm no problem...

...but app doesnt change. 

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CisnLuJVOxN9c+KXcacZviikvOUB6RYEoldZEcwAgJ5PMC+wIZ/f7XFRuTde0SmN+IlmannIz/vPemvL9IcI4BEyab4tx1bhUbQ7iZ3ynV4yOBoeSSW5/AptPGky14aWzughQVfFvdFFg31OEAvOsYArAHuPBDmwzRMi1IZCK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://www.loom.com/share/be0ea05edaef420d8ee53f97bc700c66

### Environment

```markdown
FlutterFlow v5.0.15 released December 11, 2024
Flutter version is 3.24.2

mac desktop -> chrome
```

**Comment by Alezanello** [comment]
Hi there!

Thanks for reaching out.

It seems that the toggle you’re referring to is specific to the browser and not the app itself. This is designed to accommodate situations where someone might prefer having a light theme in their browser while keeping dark mode for the app. The toggle doesn’t control the app’s theme; instead, the app theme is determined by the system settings and not the browser.

If you want to toggle between themes for the app, it should be managed directly within the app by implementing a theme toggle feature. This would allow users to switch themes during run/test/release phases, just as you described.

This toggle is different from the one in the UI Builder, which is used solely for previewing themes during development.

So, this is the expected behavior: during run/test/release, the only way to change the app theme is through a toggle within the app itself, not the browser toggle.

**Comment by chuggmuffinReturns** [comment]
Oh ok so this was not there to mimic system settings... got it! Thanks for looking into it :)

**Comment by Alezanello** [comment]
My pleasure!!!
