### ISSUE TITLE
Missing language fil - Filipino (Pilipino)

### ISSUE THREAD

**Issue by x-oli** [FlutterFlow/flutterflow-issues#5101]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

No Philippine language available

### Expected Behavior

Add Philippines - fil language

### Steps to Reproduce

1.	Go to Settings
2.	Select Languages
3.	Search for Philippines language

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

0

### Visual documentation

;

### Environment

```markdown
- FlutterFlow version: 
- Platform:
- Browser name and version:
- Operating system and version affected:
```

**Comment by Alezanello** [comment]
Hello!

This appears to be more of a feature or enhancement request rather than a bug. I’ll make sure to add your request to the team’s backlog for consideration. However, I’ll go ahead and close this ticket here to keep the GitHub Issue Tracker focused on bug reports.

Thank you for your understanding, and feel free to reach out if you have any further questions or concerns!
