### ISSUE TITLE
scrolling interrupted by webview widget

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5103]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.tella.tv/video/scrolling-woes-htik

seems like the webview widget blocks scrolling

different behaviour on web vs macos

### Expected Behavior

normall scrolling behaviour

### Steps to Reproduce

scroll over a webview 

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CisnLuJVOxN9c+KXcacZviikvOUB6RYEoldZEcwAgJ5PMC+wIZ/f7XFRuTde0SmN+IlmannIz/vPemvzLO+44ISuCGK5+wc0BZAnJXkygbrquBqWSS25/AptPGky14aWzughQVfFvdFFg31OEAvOsYArAHuPBDmwzRMi1IZCK2SrDX1iXc2URm05KZDPz

### Visual documentation

https://www.tella.tv/video/scrolling-woes-htik

### Environment

```markdown
FlutterFlow v5.0.16 released December 12, 2024
Flutter version is 3.24.2
```

**Comment by Alezanello** [comment]
Hello!

The issue occurs because the WebView widget has both horizontal and vertical scrolling enabled. When you place your mouse over the WebView, it triggers its own scrolling, which is separate from the main scroll of your app. This behavior is intentional, as some users embed websites inside the WebView that require their own scroll functionality.

In your case, since you're displaying a YouTube video, the extra scroll might not be necessary. I could suggest creating a feature request to allow enabling or disabling scrolling within the WebView widget. However, I can't guarantee if it's feasible or if the team will prioritize it for development—it would depend on their evaluation.

Let me know if you'd like me to submit the request!

**Comment by chuggmuffinReturns** [comment]
ahh interesting... makes sense

Does make YouTube videos a problem since the native player doesnt allow that but maybe theres a custom player that could solve that problem

Yes could you put that in a feature request please?

Thanks!

**Comment by Alezanello** [comment]
Of course!

I’ll attach it internally right away—thank you!
