### ISSUE TITLE
Cannot login with Email after update

### ISSUE THREAD

**Issue by Prim0rdius** [FlutterFlow/flutterflow-issues#5106]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

App launched in run mode from Flutterflow Desktop is unresponsive after adding credentials and attempting to sign in via Chrome.

Chrome dev console shows error with main.dart.js

![image](https://github.com/user-attachments/assets/9aff6115-3502-409a-b4cb-87714caa1fb8)

### Expected Behavior

Expecting to be able to sign into the app to test components when logged in.

It should move to the home page once logged in to then test profile features.

### Steps to Reproduce

1. Load project in run mode
2. Go to profile from bottom nav bar
3. Notice no firebase data loads
4. Click edit profile
5. Click logout top right button
6. Click sign-in option
7. Enter username and password
8. Hit sign in

Result is unresponsive for 2 testing accounts

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4Wj8/c4ot2m9tJ0LrUasJanmU5Jm42a+YrlcNxdxY2B4D3P5wPXfikSEpWZ9+kTHxcL06KnjkxwN7UveOfA+UqIU6tGqU+wboBbg3yfHinRLKUBc6wSXwmGeRJJVyO35i3oSJSKu5sSkFl2F7zfuSsfHPUHqGyOlcaDeWbNpjDp1WrQ0SLb3kNh1JWeC/v

### Visual documentation

![image](https://github.com/user-attachments/assets/beb5d491-d713-4cc3-bbf9-6a48817ac254)

https://github.com/user-attachments/assets/4878862b-3e5d-4e3a-b06e-1bdad2a00818

### Environment

```markdown
- FlutterFlow Desktop version: 5.0.13
- Platform: Desktop
- Browser name and version: Chrome Version 131.0.6778.140 (Official Build) (64-bit)
- Operating system and version affected: Windows 11 Home Version 24H2
```

### Additional Information

This issue is preventing any iteration and testing on the app that involves a logged in user.

**Comment by Alezanello** [comment]
Hello!

I’ve reviewed the project and couldn’t identify any errors that might be causing this issue. Could you please provide us with a test or demo account so we can log in and investigate further?

Thank you!

**Comment by Prim0rdius** [comment]
Thanks for getting back to me.
It appears sign-up works but sign-in does not.

Try test@test.com
123456

Thank you

**Comment by Alezanello** [comment]
Hello!

I’m really sorry to hear you’re facing this issue. After reviewing your project, everything appears to be set up correctly. Unfortunately, I’m not entirely sure why you’re encountering this error when trying to log in.

While I was able to replicate the issue in your project, I couldn’t reproduce it in a new project where the login action works as expected.

For cases like this, I recommend reaching out to FlutterFlow Support directly via the in-app chat (blue icon at the bottom right) or by emailing **support@flutterflow.io**. They’ll be able to investigate further and help identify the root cause.

Thank you for your understanding, and I hope this gets resolved for you soon!

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Have a great day!
