### ISSUE TITLE
TextEditingController was used after being disposed : Pin auth login

### ISSUE THREAD

**Issue by waminos** [FlutterFlow/flutterflow-issues#512]
Hi! When i use phone authentification and then pin validation the keyboard does not autodispose which cause this error when running the code locally on android studio. I found a stack solution maybe here [stackoverflow](https://stackoverflow.com/questions/60555912/a-texteditingcontroller-was-used-after-being-disposed)

![image](https://user-images.githubusercontent.com/18538948/220380755-b15d4d82-da6a-456b-8961-c367b1dca2d4.png)

View after clicking login when receive the code:
![image](https://user-images.githubusercontent.com/18538948/220381536-373bffe6-0d8a-4208-b43b-58ec5dc65d39.png)

Thanks

**Comment by bulgariamitko** [comment]
In order to keep our issue tracker useful and maintainable for all users, please follow the bug report template while reporting bugs. We will be happy to re-assess when the necessary information is provided.
 
 Thank you!

Can you please provide a Bug Report Code as well. This is how you can create it

![whats-new-FlutterFlow](https://user-images.githubusercontent.com/7221384/215421133-34dab909-6647-4b03-8d40-2539ca0b0b3a.png)

**Comment by waminos** [comment]
IT4kkcjf5ZR1ofVc15PpbcBWliY4KUw/TL07ttYbZxUjIuPtBJh/Ps/8ahJtcMCodENhHFKYgjsG+e+NhvLIUe04PSmcfrlyzKgNZAHNTTbkEuzyT+3IHDUHZbsSXTTm

**Comment by wenkaifan0720** [comment]
Hi @waminos. This will be fixed in our next update. Thank you!
