### ISSUE TITLE
Reopening a crucial issue with dev environment and branches

### ISSUE THREAD

**Issue by humbitious** [FlutterFlow/flutterflow-issues#5139]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

See #4943

We are having the same issue, but 4943 appears to have been designated as stale. Unacceptable. This is a show stopper for anyone who is trying to adhere to proper development practice for an app that is already deployed to active/paying users.  If we can't trust branches/development environment ops in Flutterflow, we must stop using Flutterflow. 

### Expected Behavior

See #4943

### Steps to Reproduce

See #4943

You can reproduce this from blank, but as with us, the deployment failure doesn't happen right away. It took 12+ hours (overnight) for it to appear for us.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40qOTn8bx5vtd755byTvBWimAgGl97Wp00mNlRaCsofePrOpkAf8/7UFtUcM+iT3NhfVr8vGAX/MmOj4bhUvYBExSZQKI/+sxQZA3gIUGuVZ/WO663b3MmJNxWN3ax1rSVqhV4JsxoV14m70yIHOi9Y3LbQbLBPGsjOOaoXdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

We have a full video for private review upon request.

### Environment

```markdown
- FlutterFlow version: 5.0.18
- Platform: Mac and web
- Browser name and version: Chrome
- Operating system and version affected: Firebase, iOS (but not relevant here)
```

### Additional Information

See #4943

**Comment by humbitious** [comment]
If this a problem where we are going about this wrong, or if it is an issue that isn't likely to have a knowable near-term resolution, then ok -- we just need to know that so we can either change our mental model and practices to make it work reliably, or if the latter, so that we can stop using FlutterFlow and move on.

**Comment by Alezanello** [comment]
Hello!

Currently, interacting with Firebase is only possible on the main branch. If you need to deploy something to a development environment, you can use the **Environment Settings** to configure and deploy to a Firebase project set up for your development environment. This functionality is independent of whether you’re working on branches or not.

At the moment, branches in FlutterFlow are designed to support parallel development within the same project, such as working on features, resolving issues, or experimenting. For Firebase and Cloud Functions, you’ll need to use the **Environments Menu** to target your desired environment.

Regarding the issue you mentioned ([GitHub Issue #4943](https://github.com/FlutterFlow/flutterflow-issues/issues/4943)):<br>This issue is still open and currently on the engineering team's backlog. However, the planned update will **only adjust the UI to display accurate Firebase-related information for the main branch.** It will not allow Firebase modifications directly on branches. Essentially, this change will improve how Firebase information is presented on branches but won’t alter the current functionality.

If you’d like to deploy a Cloud Function or test something in Firebase for a development environment, you can easily set it up through the **Environments Menu**.<br><br>I'll close this issue as duplicated and link internally with #4943
