### ISSUE TITLE
Bug in checking dependencies

### ISSUE THREAD

**Issue by JeanLouisPiquet78125** [FlutterFlow/flutterflow-issues#5144]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When inserting a dependency for custom widget (e.g. spinkit or Google Map), FF is issuing a warning message indicating that the dependency is outdated and needs to be upgraded. Problem is that the inserted dependency is the most recent one (see attached picture).

### Expected Behavior

No warning message

### Steps to Reproduce

1. Create a new widget either in an existing project or a new one;
2. Inserting dependency(ies) for this widget;

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40i+fl6ot2mNtF7c7qacEw+So5KWI/a+c3jMJ7aCsofePrOpkAf8/7UFtUOMznYWNAP2f8+X0X/Mr9uNjpLfddBwSVUaJyyLVxFwzNVkm7R4/QBYS3b3wlGeNRfkyO352JmxRDNsRfWnwS71OXe++9bAXdQbL6IkVEMua4XdeK2SrDX1iXc2URm05KZDPz

### Visual documentation

[
![Capture d’écran 2024-12-19 à 07 38 37](https://github.com/user-attachments/assets/cfed0d6d-9369-41bd-b8e6-a4e3473f0cc8)
](url)

### Environment

```markdown
- FlutterFlow version: FlutterFlow v5.0.0+ released December 18, 2024
Flutter version is 3.24.2
- Platform: MacOS Desktop web
- Browser name and version: Chrome Version 131.0.6778.109 (Build officiel) (x86_64)
- Operating system and version affected: MAcOS Monterey Version12.7.6
```

### Additional Information

Not really a critical issue as project is still running at least on web however might explain why it is not working well on Android (but not sure of that yet).

**Comment by Alezanello** [comment]
Hello!

It seems this is more of a warning than an actual error. FlutterFlow uses a third-party analyzer to determine the best package compatibility for the current Flutter version. In this case, it’s simply suggesting that you use a lower version. However, if your code compiles correctly and doesn’t break functionality, you can safely ignore the warning.

If this warning were appearing as an error (in the red section rather than yellow) and causing deployment or compilation issues in your FlutterFlow project, it could potentially be a bug.

**Comment by Alezanello** [comment]
Closing this issue since we haven't heard back from you. If you are still facing the problem please submit a new issue. Thank you!
