### ISSUE TITLE
I can't cancel Web publishing of a test application in the Web Deployment section.

### ISSUE THREAD

**Issue by va9em** [FlutterFlow/flutterflow-issues#5156]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When you click Unpublish, nothing happens. The application remains published. New entries do not appear in Deployment History.

### Expected Behavior

When I click the Unpublish button, the app should be canceled, the links will stop working.

### Steps to Reproduce

1. [Click the Unpublish button. 2. Observe that the project remains published, the link works, the history does not change.

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

There is no code

### Visual documentation

![Снимок экрана 2024-12-20 210451](https://github.com/user-attachments/assets/850c776d-7426-4487-8bfb-a790df6e1deb)

### Environment

```markdown
- FlutterFlow version: 5.0.15
- Platform: Web
- Browser name and version: application
- Operating system and version affected: Windows 11 Pro
```

### Additional Information

The problem is not urgent

**Comment by rzambroni** [comment]
Hi @va9em,

I tried replicating the issue you mentioned, but it seems to be working fine on my end. Could you check if the website might be cached? You can try performing a hard refresh or accessing the URL in incognito mode to rule that out.

If the issue persists, please provide a bug-report-code (right-click on any widget in the widget tree to generate one), and we'll take a closer look at your project.

Thanks so much!

**Comment by va9em** [comment]
Hi @rzambroni, I checked the caching while standing for the first time. I launched the link not only in different browsers, but also on different devices. Try it yourself: https://zen-med.flutterflow.app/. I asked this question in a Telegram group and another person answered me, he had the same problem (https://t.me/c/2390745849/797). In general, this does not bother me now, but perhaps this problem will become relevant for many. I want to help.
![Снимок экрана 2024-12-21 155716](https://github.com/user-attachments/assets/3f59f8c0-6e97-40a9-a32d-9b44fccb6aec)

**Comment by va9em** [comment]
IT4kyfHlvYtPxc9Y7c/tbexGpDsQNUA+TL07ttYbZxUjIuPtBJh/Pcn8QBJVYOmhT2lhHGKjuEgK3NWKkeGeFOw5HySVbbU/zroJSxfxWXq8SpivEZG7OXMmOJ5Mfx2k38OJpBN+HM5sR0IA716MNe+UVjXqN5+/Zwh9f6PHaOI=

**Comment by rzambroni** [comment]
Hey @va9em,

Thank you for the additional context! I wasn't able to replicate the issue on my end, but I can see that your project is still accessible through the link you shared.

It looks like something may have gone wrong during the unpublishing process, which is why the site remains available.

If you were using the Windows app, could you try publishing the project again and then unpublishing it from the web app instead? Sometimes this resolves similar issues.

If that doesn’t work, I recommend reaching out to our support team directly so they can take a closer look at your project. You can contact them via email at **support@flutterflow.io** or through the in-app chat.

I really appreciate your patience and help with this! Let me know if you have any further questions.

Best regards,
