### ISSUE TITLE
Can get component state on a single component... can get widget states of widgets IN a component in a list of components... but can't get the component state of an individual component in a list of components??

### ISSUE THREAD

**Issue by chuggmuffinReturns** [FlutterFlow/flutterflow-issues#5157]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

https://www.tella.tv/video/accessing-component-state-in-a-list-of-components-3jnf

I can access component state in an individual component

I can access widget states inside a component in a list of components via the unique key

But I cant access the component state in a list of components via the same unique key

I am confused...

### Expected Behavior

if you can access widget state in a component in a list of components I would expect accessing the component state itself to be possible, no?

Seems like that is one step easier than accessing the widget states inside the component?

### Steps to Reproduce

create two components
one in list, one not
both have component state
try to access

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40sOX126xOscRJ15PqWuxGgmEsHGIjRLgJkNVraCosfZT2BLMcec/RVERoTsu+Y1FpPmaWkWoW0+iMiN/PVPBdISetc7Zyzbl+cQHKIUCmMrrQFJWvPGhAHehmG3alyrbYmhN+KbZqR1IZwF2EAvOXEwTvH5CxDHo0Da/LZO4=

### Visual documentation

https://www.tella.tv/video/accessing-component-state-in-a-list-of-components-3jnf

### Environment

```markdown
mac desktop latest
```

**Comment by chuggmuffinReturns** [comment]
BONUS BUG: when you delete a unique key that you used to access component state in a list the error is thrown properly in top bar but not the same pattern in the text field itself

https://www.tella.tv/video/unique-key-error-7kwu

**Comment by chuggmuffinReturns** [comment]
BONUS BONUS BUG: setting the value of an index need to go all the way to code expression to set a value as opposed to just entering a number

It works... just is counter intuitive

https://www.tella.tv/video/brians-video-dbu0

**Comment by paulperez-dev** [comment]
Hi @chuggmuffinReturns,

To select a specific item in your component list through the widget state, you can set the **SeedSelectorComponent**, possibly using the "element at index" **Access Type**.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/53df1299-6e44-4215-8df2-57c389f66a4f/b84810cd-bfc9-4670-a186-578d7ebddf30?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81M2RmMTI5OS02ZTQ0LTQyMTUtOGRmMi01N2MzODlmNjZhNGYvYjg0ODEwY2QtYmZjOS00NjcwLWExODYtNTc4ZDdlYmRkZjMwIiwiaWF0IjoxNzM0OTY3MDc4LCJleHAiOjMzMzA1NTI3MDc4fQ.O5hgTG3dpgWsVTOv-G1i9CnyqJijosfRx7BrbwDdsZg " alt="image.png" width="276" data-linear-height="429" />

If you need to set the value manually, you can delete the default expression and enter the desired value directly.

<img src="https://uploads.linear.app/3241089d-736a-4422-900b-051e72accdbe/543f1a31-7901-403b-ac1c-986cea0305db/f69040fe-be6d-42b5-9061-c58ec7997b0e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzMyNDEwODlkLTczNmEtNDQyMi05MDBiLTA1MWU3MmFjY2RiZS81NDNmMWEzMS03OTAxLTQwM2ItYWMxYy05ODZjZWEwMzA1ZGIvZjY5MDQwZmUtYmU2ZC00MmI1LTkwNjEtYzU4ZWM3OTk3YjBlIiwiaWF0IjoxNzM0OTY3MDc4LCJleHAiOjMzMzA1NTI3MDc4fQ.EHpzkMCrVb8hV3BfS7hK08Z2M5FbHRoF1O35JMvxOmM " alt="Screenshot 2024-12-23 at 11.56.23 AM.png" width="321" data-linear-height="456" />

I wanted to mention that the key issue wasn’t entirely clear to me—probably due to the awesome background music in the videos! 😄 I might have also misunderstood one of the other issues, so please double-check and let me know if this helps resolve the problem.

Also, for easier and faster triage of tickets, please file one ticket per issue. This helps us address each problem more efficiently.

Happy to assist further if needed!

**Comment by chuggmuffinReturns** [comment]
whoooooppsssssss lol!

Sorry about the music hahaha

Thanks about mentioning the deleting the default value. I missed that delete button and that works.

i am going to make another vid for the main problem one sec...

**Comment by chuggmuffinReturns** [comment]
Ok here is a quiet and hopefully clear demo of the issue I am having...

https://www.tella.tv/video/accessing-component-state-f617

**Comment by paulperez-dev** [comment]
Hi @chuggmuffinReturns,

I was able to replicate this behavior. I’ll forward it to the engineering team for further review and resolution.

**Comment by chuggmuffinReturns** [comment]
Ok cool thanks!

Hope you have a great and somewhat relaxing week!

**Comment by paulperez-dev** [comment]
Thanks! 😊

**Comment by chuggmuffinReturns** [comment]
<img width="390" alt="Screenshot 2024-12-26 at 6 11 57 PM" src="https://github.com/user-attachments/assets/ceff3a94-801a-408f-818b-c3242ab4cbcd" />


@Alezanello I am somewhat shocked this has been changed to "not planned" considering the obvious usefulness, the fact its basically already implemented, and, dare I say the literal description in the tooltip in the screenshot. 

Whats going on?

**Comment by paulperez-dev** [comment]
Hi @chuggmuffinReturns,

After checking with the team, we’ve confirmed that this isn’t a current feature of the app.

We’d love for you to submit this as a Feature Request through the app’s dedicated feature request section. This ensures it reaches the right team and can be considered for future updates. This tracker mainly handles bugs, so feature requests are best submitted that way.

Apologies for the oversight before updating the ticket status. We really appreciate your understanding and the time you took to share your feedback! 😊

**Comment by chuggmuffinReturns** [comment]
Well that's a bummer...

Submitting away!

Thanks @paulperez-dev and @Alezanello
