### ISSUE TITLE
Instant reload  button not clickable on desktop version on 5.0.16+

### ISSUE THREAD

**Issue by PhilemonChiro** [FlutterFlow/flutterflow-issues#5178]
### Can we access your project?

- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Instant reload  button not clickable on desktop version on 5.0.16+

### Expected Behavior

should  be clickable  as usual

### Steps to Reproduce

just install

### Reproducible from Blank

- [ ] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

ITFfycrluIlPxMtC7a6Jb+1WmWIvJl8cTIMziNZ+exUbfaL1Bu0DdsjRclJDTf2qaVNcDE38jkAKwNGPvYbfL/c4PUitbak6/rptEBbOe2iiVLLQOrjtOHR9M+hgG0id5LSFuxJ4AOpiSkYc7F6MGuqUQgLDFOu/Zwh9f6PHaOI=

### Visual documentation

Instant reload  button not clickable on desktop version on 5.0.16+

### Environment

```markdown
- FlutterFlow version: 5.0.16+
- Platform: desktop (windows)
- Browser name and version:
- Operating system and version affected: win10
```

**Comment by Alezanello** [comment]
Hello!

I wasn’t able to replicate the issue on my end. Sometimes, changes made in the code can cause the app to break or require a full restart, especially if they affect core functionality. In such cases, the instant reload might not work as expected because it doesn’t fully restart the app—it only applies incremental changes.

To resolve this, I recommend restarting the local run entirely. After the restart, try making a small change and then using instant reload to see if the issue persists. Let me know how it goes or if you need further assistance!

**Comment by PhilemonChiro** [comment]
thanks
