### ISSUE TITLE
Unable to change app version number for mobile deployment

### ISSUE THREAD

**Issue by kicsijohn** [FlutterFlow/flutterflow-issues#523]
## Expected behavior (required)
I want to change the app version number

## Current behavior (required)

https://user-images.githubusercontent.com/45784821/220997517-376b4b5b-ebb8-41da-926e-2b0db8e57f00.mp4

## To Reproduce (required)
1. Go to Settings - mobile deployment
2. Try to change the app version number
3. Observe that strange behavior 

## Your environment
* Version of FlutterFlow used:  v3.1 Flutter 3.7.3
* Platform (e.g. Web, MacOS Desktop): web, Mac app also
* Browser name and version: chrome, arc, brave
* Operating system and version (desktop or mobile): macOs

**Comment by WellDunDun** [comment]
My friend had a similar issue and this is how he said he resolved it:

"My cache in the browser, although I basically cleared it a lot of times, but I had to literally close my browser and deploy again with the newer version
Because of my browser, it kept showing the aab file with the first version number I wrote which was lower than the original one I uploaded before"

I hope this helps!

**Comment by kicsijohn** [comment]
I tried to type 1.01 but it didn't work but it works with 1.0.1

**Comment by abdrzq16** [comment]
It didn't work with me too.

**Comment by bulgariamitko** [comment]
I am pretty sure you need to have 3 numbers as it says in the info button. So I don't think this is a bug
