### ISSUE TITLE
Project size limit and I can't do anything and it won't save

### ISSUE THREAD

**Issue by zer151** [FlutterFlow/flutterflow-issues#524]
I have try to chat with support and I always got the same answer that optimize my project.

1.I removed some big image instead it can be application asset and upload to firestore.
2.I have made the customs component and re use it as much as I can
3.Try to remove unnecessary page 

support can't help, I build like 128 page and 50 customs component 

thank you

**Comment by bulgariamitko** [comment]
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
 
 If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
 
 Thank you for your contribution!
