### ISSUE TITLE
Page from template

### ISSUE THREAD

**Issue by blondie63** [FlutterFlow/flutterflow-issues#525]
I've save a page as template and i see it (screenshot) but i can't create a new one from this saved template !
When i click over template thumb img nothing happen !
Tested with FF MacOS v1.1.44 and FF web 3.1 Flutter 3.7.3

I'm wrong or is it a bug ?

<img width="357" alt="FFv1 1 44-page-from-template" src="https://user-images.githubusercontent.com/1261851/221172371-3ba4a464-c6b7-4115-be29-bbee16f3dc3a.png">

**Comment by blondie63** [comment]
In this docs page: https://docs.flutterflow.io/widgets-and-components/widgets-ui-elements#save-as-template
FF team say how to save a page as template but NOT how to use it later.. :(

**Comment by blondie63** [comment]
FF v1.1.45 has same problem

**Comment by blondie63** [comment]
> Hi @blondie63 - Thanks for reporting this issue. I can re-produce the issue.
> 
> Note - Please update the issue details as per standard issue template.

When i've created this issue there are not template like if create a new one now and if i edit this issue i can't see the issue template.. so how can i do ?

**Comment by blondie63** [comment]
Where is FF Team ???

**Comment by blondie63** [comment]
Yesterday March 13th you announced the new version that had actually already been released a few days before but the worst thing is that you didn't insert the fixes for the bugs reported by me and that you closed here on Gitbub as fixed. I honestly don't understand this absurd behavior, do you want your customers to leave FlutterFlow ?

**Comment by agreaves** [comment]
Hi @blondie63, apologies for the delay in addressing this issue. In order to use a template that you created, you don't click on it but instead drag it into the Page canvas (as you would another widget). Apologies for not answering sooner. Please try this again by creating a new template and dragging, and please feel free to create a new issue or respond here if you are still encountering an issue.

Regarding the new FlutterFlow versions, not all updates are full updates (including all recent changes, such as bug fixes). Some are specific cherry picked or highly important updates, so not all FF updates will fix all issues that have been recently fixed on our end.
