### ISSUE TITLE
PageView Current Index always 0

### ISSUE THREAD

**Issue by ross-anibles** [FlutterFlow/flutterflow-issues#538]
## Expected behavior
I expect that when I change pages within a PageView (e.g. swipe to the next page) that the Page View Current Index variable within the WidgetState will reflect the index of the page I have switched to.

## Current behavior
The index is always zero.

## To Reproduce
1. Create new page
2. Add PageView with pages
3. Add a Text and populate it using Page View Current Index within Widget State
4. Run the project
5. Observe that the Text is always 0

### Bug Report Code
Text:
IT4ozMrl8ZRJochE1q6JK+9ajSQsQmU1Rp0r0cpOEC0jF7KuBqQAfs/eSBRpXcDmaVNcH02bmkY1w+zNiOzpFMA5EwWdbKZR+ZF+VRb2KTbkEuzyT+3IHDUHZbsSXTTm

PageView:
IT4ozMrl8ZRJochE1q6JK+9ajSQsQmU1Rp0r0cpBZykgGL7yCLMqY8mnP1dCUumgdwhiImamp14CwtbNjuDhLsIEHASWR75Bz852VhXyYEeWRcTfU/HUACkbeacOQSj6

## Context (required)
I need to figure out when the user has finished the PageView, but cannot.
I would like to show progress through the Pages in the PageView, but cannot.

## Your environment

* Version of FlutterFlow used: 3.1 (Flutter 3.7.3)
* Platform (e.g. Web, MacOS Desktop): Web on MacOS
* Browser name and version: Chrome 109.0.5414.87 (Official Build) (x86_64)
* Operating system and version (desktop or mobile): Desktop - MacOS 13.0 (22A380)

**Comment by hariprasadms** [comment]
Hi @mravani2 - Can you you please look at this issue? Thanks

**Comment by mravani2** [comment]
Hi, @ross-anibles; thanks for reporting this issue. I have successfully reproduced the behavior you mentioned and have already addressed it to the team.

As soon as we have any updates about this matter, you'll be notified here with a comment or a label change 😉

**Comment by abdrzq16** [comment]
Well, allow me to add something to this issue.
When I make text to display the page view index the app doesn't work at all.

**Comment by mravani2** [comment]
> Well, allow me to add something to this issue. When I make text to display the page view index, the app doesn't work at all.

Thanks for sharing this, @abdrzq16. I noticed the same behavior when I tried to load the Page View Index value inside or below the Page View widget. By now, the only way to do this is to put the Text Widget below the Page View widget. Otherwise, the system will try to get the value before the Page View widget is rendered, and the project won't compile.

The team is also notified about this matter 😉

**Comment by nicmohr25** [comment]
Is there an update to this problem?

**Comment by agreaves** [comment]
Hi @nicmohr25, thanks for the bug report! This is happening because the page is not being updated when the user swipes (there is currently no such action for that). In order to fix these, we're adding and "On Page Swipe" action, as well as a setting to "Update Page on Swipe", either of which can be used to fix the issue. This will be available in an upcoming release 🙂

**Comment by abdrzq16** [comment]
Thanks Alex.

I hope you add an option to reverse in pageview as well. Regards.

**Comment by abdrzq16** [comment]
Thanks Alex.

I hope you add an option to reverse in pageview as well. Regards.
