### ISSUE TITLE
ChoiceChips widget state getting mixed when turned to custom component

### ISSUE THREAD

**Issue by KamyMouss** [FlutterFlow/flutterflow-issues#579]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

When choice chips are converted to custom components, the internal selected state of 2 distinct ChoiceChips are mixed together if they are displayed in the same location (such as in form with conditional branches, where the next option is in the same location)

### Expected Behavior

ChoiceChips that are custom components should each have their own state (as with choice chips that _aren't_ custom components)

### Steps To Reproduce

1. Create a custom component with a choice chip widget that has 2 buttons
2. Create 3 of these custom component choice chips where A B C, where Choice B is conditionally shown when Button 1 in A is selected, and Choice C is conditionally shown when Button 2 is selected.

<img width="304" alt="image" src="https://user-images.githubusercontent.com/32441857/223279056-a6e1f76e-f13f-4572-8ab0-145fe78d89c3.png">

4. To repro the bug:
- Select choice Button 1 in Choice Chips A
- Select choice Button 1 in Choice Chips B
<img width="345" alt="image" src="https://user-images.githubusercontent.com/32441857/223279304-d2801885-71e6-4b6b-8746-8a1b9c202b20.png">

- Select choice Button 2 in Choice Chips A
- Select choice Button 2 in Choice Chips C
<img width="357" alt="image" src="https://user-images.githubusercontent.com/32441857/223279332-d62a33f8-11d4-454c-9fdb-7d02957f042b.png">

BUG: Notice that the index of Choice Chip B is being modified to Button 2 when choosing Button 2 in Choice Chip C.

### Bug Report Code

IT4skvLluI9OvuZE1qrucu1B/TsXOUh8RpI0scpCbw4bIYj2P4lzY876PxNWZMOnTwlEJGe2p14d06HqjuzXO/ICAEmtRb44/rlcagrMLUyVWpuTF7WST2h6L9phfGah0cOzhCYmHPZpSmwa1DuxNeu+QnHbQL70NWo8Sq/LZO4=

### Context

I'm trying to create a conditional form based on custom components with choice chips inside of them. This breaks the flow if a user goes back on the form and selects a different option in a previous question.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome
- Operating system and version affected: Windows
```

**Comment by organicnz** [comment]
Hi, @KamyMouss. Thanks, Kamy for adding this issue 🙂

Could you pls share screenshots of the configured conditions? :)

Here's my set-up. Are those different from yours? :)
![image](https://user-images.githubusercontent.com/4765090/224329423-b492ee7f-7092-42e8-ae4e-7f90ed7224c8.png)

![image](https://user-images.githubusercontent.com/4765090/224330680-8940312f-91b2-4cb6-b9e5-1908479ca082.png)

**Comment by victoriahuang1** [comment]
Hi @KamyMouss , thanks for the report. The issue you are facing is due to Flutter thinking it's smarter than it actually is! Essentially what is happening is: the B/C components look exactly the same to Flutter, since they 1) are the same component, 2) appear in the same spot in the widget tree, and 3) neither of them show up at the same time.

Unfortunately, fixing these types of issues requires a lot of thinking to make sure it doesn't break existing behavior. We are working on it though, so this may work out of the box in the future!

For now, there _is_ an easy workaround. You can simply add an empty container (no height / width, so that it will be like it doesn't exist) in between your B/C components. This way, they will show up in different positions in the widget tree, and Flutter will no longer be confused.
