### ISSUE TITLE
Facebook Login not working on Deployed Web Apps

### ISSUE THREAD

**Issue by SameerShahzad99** [FlutterFlow/flutterflow-issues#602]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The facebook login functionality is not working on the app that has been deployed through FlutterFlow, but interestingly if i try to test facebook login on android studio on a local host, it works fine.
On web app, it does not show anything in the console tab and networks tab while clicking on facebook login button.

### Expected Behavior

I have configured facebook according to the steps in the documentation but facebook login is not working on web

### Steps To Reproduce

1. Complete the steps for Facebook Login in Flutterflow Documentation
2. Use Facebook Login action on a button

### Bug Report Code

IT4whfLluIhOsdhE17Xyb8JvmjoRMjt5arhM1Ox+eCs8GZT0B4kcYs+kfklUOfW4TwhDeWK0pD4X/MmOvYbhL8YDPROVbqJcyMxIagqWQk27RpuaO4S3b398DcFRN0PEyMKg2BVSJbd2LEZk3WD3GtzKHwLcQ+e3OUgjPOa4XdeK2SrDX1iXc2URm05KZDPz

### Context

I have been trying to accomplish facebook login on all major platforms, it works fine on android and ios but it does nothing on web

### Additional info

https://drive.google.com/file/d/11aLWAYNlpUgyc9AprcadooVe6lyWUJ14/view?usp=share_link

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: Web
- Browser name and version: Chrome 106.0.5249.119
- Operating system and version affected: macOS Ventura 13.0
```

**Comment by hariprasadms** [comment]
Hi @SameerShahzad99 - Facebook Sign-In can not be tested in Run/web Mode. Instead, you will need to test Facebook authentication on a real device/emulator.

This note is already mentioned at end of the facebook login document page. Refer point 7 - https://docs.flutterflow.io/data-and-backend/firebase/authentication/facebook-sign-in

**Comment by helloheesu** [comment]
Hi, does this mean I can't use FB login even on live-deployed web app either?

> Facebook Sign-In can not be tested in Run/web Mode. Instead, you will need to test Facebook authentication on a real device/emulator.

I have tried some steps and can't use FB login. The button is not responding and Facebook says URL `flutterflow.app` is malicious.

Here's what I've posted on community forum and it includes what I've tried:
https://community.flutterflow.io/ask-the-community/post/facebook-login-with-firebase-auth-E3sh8VGIGA1C3Oh

1. I have deployed my FF app to an URL: `https://example.flutterflow.app/` (it's not my actual URL, I've used my real one for sure.)
2. I have created Firebase project and registered above URL into Firebase Auth's allowed domain.
3. I have created a Facebook app, following this [docs](https://docs.flutterflow.io/integrations/authentication/firebase/facebook/).
  a. One problem is, I couldn't add "web" platform.
  b. The documentation is adding Android but I'm using only web.
  c. When I try to add my URL, it says the URL is malicious.
  d. " We can't review this website because the content doesn't meet our Community Standards. If you think this is a mistake, please let us know. "
4. I found one stackoverflow article saying I should add "flutterflow.app" in App Domains to solve this malicious URL problem, so I tried it, but nothing solves, still saying it's malicious.
