### ISSUE TITLE
Conditional Value for textfields

### ISSUE THREAD

**Issue by ISHA7782** [FlutterFlow/flutterflow-issues#613]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

We want to use basic functionality where if data is null, hint text should be set for textfield. 

For example, an api call returning address of the client, if address is null, we want to add hint text "Enter your address" 

We don`t have this functionality yet for the cases where data is coming api calls. We are able to have the same behaviour if the data is set from page parameters rather than api call. 

null is getting displayed as string null, instead of hint text. 

### Expected Behavior

If the data is null, text field should show the hint text/empty if hint text is not set. 

### Steps To Reproduce

1. Create a text field with initial value set to json path from api call response. 
2. If json path is null, the value is displayed as null string. 
[
<img width="428" alt="Screen Shot 2023-03-14 at 10 26 05 PM" src="https://user-images.githubusercontent.com/17334006/225215469-f2112a9a-4aca-4b05-b2f8-ddd08e9796c6.png">

### Bug Report Code

ITEek/H15c9NtbxI+qn2bsFFmQMwHVgjbJ0vpe5+dwsjCeP0EOwMZ+PRM1RpWOqHe356O1WapHIz+NWOuOLlUfICYBCZfapZ+c9TUxDgc3ygbL7SPKqOfmt5EfFmJkilyru7qiR/NrR2WWRh3TuqIOSAb3qCf9qOYwx5e6fDbOY=

### Context

Productivity loss.
Product release. 

### Environment

```markdown
- FlutterFlow version: 3.7.3
- Platform: desktop
- Browser name and version:CHROME Version 108.0.5359.124 (Official Build) (arm64)
- Operating system and version affected: MAC Version 12.5
```

**Comment by ISHA7782** [comment]
This works for variable which is null, but not work for json objects.

**Comment by agreaves** [comment]
Hi @ISHA7782, thanks for the report! In this case, it's because we need to interpret the JSON path as a String, so if it is `null` then it gets converted into the "null" string unfortunately. There's not an easy solution to this, so in the meantime I suggest either what you are currently doing (a conditional value based on whether it is null) or, more easily, add a default value to this variable (empty string or ' '). Hope this helps!

As a small tip, you can always set the "Else" in a conditional to `Constants -> Empty String`, which may be helpful.
