### ISSUE TITLE
my organization, team design library, choose tree view, freezes.

### ISSUE THREAD

**Issue by CGAlei** [FlutterFlow/flutterflow-issues#645]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

when go to team dsign library, and choose a project, then choose tree view, the ui gets freezed, no actions are allowed.

### Expected Behavior

i shoud be able to see the tree view

### Steps To Reproduce

![chrome-capture-2023-2-20](https://user-images.githubusercontent.com/78834609/226497649-cd2fae39-4c94-400f-b816-22c38c665651.gif)

### Bug Report Code

IT48z8jc5YZIvuEA0aXyLMBsnmUQKUM7bZJIlNZETkw8J5zKB+wAYvf7P1FWTL3hYEFXMVqjgnozxvfqiN7xLOw6AxWbRtlx+pN+ewLgeHmtbr2YDM+VfW1STNxYCBGD4KSFhx0lBO9hckY82l2EP96vHnfDGJDPPlYvJP2lKdeK2SrDX1iXc2URm05KZDPz

### Context

trying to make my own cross project assets

### Additional info

![chrome-capture-2023-2-20](https://user-images.githubusercontent.com/78834609/226497649-cd2fae39-4c94-400f-b816-22c38c665651.gif)

### Environment

```markdown
- FlutterFlow version: march 20
- Platform:windows
- Browser name and version:chrome
- Operating system and version affected: windows
```

**Comment by CGAlei** [comment]
i made all my designs and cannot get acces to them, need help

**Comment by bulgariamitko** [comment]
This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io for further assistance.
 
 If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
 
 Thank you for your contribution!

**Comment by CGAlei** [comment]
thanks
