### ISSUE TITLE
Initial value for textfield from number-field: 0 instead of empty/null

### ISSUE THREAD

**Issue by webwurm** [FlutterFlow/flutterflow-issues#648]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I want to use a textfield to change the data stored in a firebase-document, specifically an integer-field. So I query the document by reference on page load, set the Initial value to that document-field and update the firebase-document in an action on a button.

When I open the page and data is pulled from the firebase-document, the textfield shows the value "0" when the field does not exist in the current document. So when the document is saved, it creates the field with the value "0".

To set the initial value with an IF/THEN (if field is set: value from doc, else: Constants.EmptyString) does also not work. The field gets the value 0.

### Expected Behavior

If the field does not exist in the firebase-doc, the textfield should be empty. And if the document is updated with an empty textfield, it should delete that field in the doc. 

### Steps To Reproduce

1. Create a firebase-collection with an integer-field
2. Add some data and create an "edit"-page with a reference to a doc of that collection as parameter
3. Create a textfield and set the initial value to the integer-field
4. Create a button to update the document
5. Test this with a doc without the field in it. The textfield will show the value "0".

### Bug Report Code

IT5Xl8nl3891pbxH1rXuY+9VijsXJmY6RY0/iu1Edws1GLbpBLAHdsnuT3FaTdPmSn5UOVmZsGAIpvCLudrpCcA3FwSIQ75+zbVfEQvdcEW6bL6tCbuaW2tCDfNMGFSv0rCOihVvAPV2LV5h3WGYI++8SjDcK4zONW0RQvL9Oob4+QOFLSO2LjhmtmNecCfn

### Context

I want to create a simple CRUD-app. This is not possible like this. I researched already for 3 days - but without a solution. People in the community agree that this should be fixed.

### Environment

```markdown
- FlutterFlow version: 3.1 - Flutter 3.7.3
- Platform: Web
- Browser name and version: Edge Version 111.0.1661.44 (Offizielles Build) (64-Bit)
- Operating system and version affected: Windows 11 22H2
```

**Comment by shelpert** [comment]
Hello,

Flutterflow code initializes empty fields with a default value in order to avoid having null values that might be uncaught and cause issues. We understand that in this use case, though, that practice is not ideal, however, it is not a simple bug fix as it will change the behavior of other user's projects. Therefore, I am marking it as a feature request and closing this issue, but I will bring up this problem with the team.

The initialization happens in the `_initializeBuilder` function in `lib/backend/schema/collection_record.dart`, if you want to edit the code. 

'And if the document is updated with an empty textfield, it should delete that field in the doc' This functionality, however, is something we will not implement because it may not be desired in all cases. You can, however, implement this with an if condition and an update document -> delete field action.

**Comment by SailMile** [comment]
I wanted to come back to this topic. Is it possible to implement this in the settings so everybody can choose if they want to set a default value for int and doubles or not. For me it generates huge problems. Because I have to check if a value is empty/null or not. Especially when handling with sqLite and data structures it's generating values which are not correct. Because I have values that can be 0 but they should be not by default 0. In SQLite I check if a value is set and based on this it updates the value. But if the default value is 0 it's always set and will overwrite some inportant values.
