### ISSUE TITLE
Refresh Database Request Action Fails with Algolia Search Backend

### ISSUE THREAD

**Issue by ibm777p2** [FlutterFlow/flutterflow-issues#669]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [x] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The Refresh Database Request Action is not functioning properly when Algolia search is set as the backend of the list, this is leading to inaccurate search results and reduced efficiency.

### Expected Behavior

The search result should refresh successfully when the firebase is updated.

### Steps To Reproduce

1. Set Algolia search as the backend of the list.
2. Update database Request Action.
3. Search the database again with Algolia as backend of the list.
4. Search results doesn't get updated data

### Bug Report Code

IT4olfLluJZ1ofVY7c/QdcBv9CQWJVg2RLgZkspBZzAaIrb1CLMqY8mnP0hoTf28TEFYIGGcp140pqnmjuOXFfQ4AzGdRbZgwpYJSg3gIXKhMJeTF7rtXndABelWf3615MOvsxR5OsZeWl4k1znzCOu9YHfUK737DWowSq/LZO4=

### Context

Not able to get the updated data breaks the app.

### Environment

```markdown
- FlutterFlow version: v3.1 (released Feb 27, 2023)
- Platform: mobile
- Browser name and version:Chrome 107.0.5304.110
- Operating system and version affected: macOS Monterey 12.2.1
```

**Comment by moraemoncom** [comment]
I am facing the same problem.
Please fix it as soon as possible.

**Comment by shelpert** [comment]
Hi,

The default action added when you 'Enable Pull to Refresh' is a 'Pull to Refresh' action on the widget containing the list, for example, pull to refresh on a listview. If you want the results to update automatically when a new search term is entered, you need to add a 'Refresh Database Request' action to the TextField widget.

I'm closing this issue because I have tested this and it works properly. Please feel free to reopen this issue and elaborate on your use case if I have misinterpreted it.
