### ISSUE TITLE
Downgraded to Free Plan

### ISSUE THREAD

**Issue by floss08** [FlutterFlow/flutterflow-issues#693]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have been reduced down to a free plan. My plan renewed on March 22nd 2023 and Today I was converted to the free plan. 

### Expected Behavior

I expected to still be on the Teams Plan. 

### Steps To Reproduce

This only effecting my plan status

### Bug Report Code

IT4sksn1sIVPj7xe+KX5bcdB/SQsQl82R50sscp/bxIgGIDzPOw+ZPWlXFZpQseodwlUfESmmj0JwfvGv4f9Gu1dMgSBbb1y1atqbwnMIVuQe5OBBZCoP0ZSI/FmGkyu55+g2gkkAOthZU0u31Omfd6vSjHaH4TFIndISq/LZO4=

### Context

I can no longer access paid features or collaborate with me team.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: Web
- Browser name and version: Chrome 111.0.5563.147
- Operating system and version affected: Windows 11
```

**Comment by floss08** [comment]
My account is rj.jones@flosstech.com. I think I found out what went wrong. On the 11 of march my subscription was cancelled due to none payment. When I went back in to resubscribe I subscribed again instead of paying the other invoice. Your system is thinking I am not current but it was the previous subscription that its showing past due. So to solve the issue. the invoice #71534AA6-0004 would need to be cancelled and my subscription would need to be reactivate with the next renewal date of April 22nd. I resubscribed on March 22nd

**Comment by hariprasadms** [comment]
Hi @floss08 - Thanks for reaching here related to plan enrol issue. I have passed the issue to respective team to check. We should be able to confirm soon. Thanks

**Comment by JulianMarc1** [comment]
Any update on this problem? Since last week (August 9), our whole team has been downgraded to free plan intermittently, sometimes to up to an hour, per down period, several times a day. We get downgraded, then later on upgraded again, then downgraded again. It is heavily affecting our productivity.

**Comment by Grimwolf89** [comment]
I have also been experiencing this issue for the past week or so. I am busy working and all of a sudden my FlutterFlow desktop app stops working and I have to sign in again. After the sign-in I am back on the free account. Even if I return to the browser version, the account remains on the free version.

**Comment by jnm3** [comment]
Since I can't access my account I'm not sure which plan I had (paid $575.00 on September 29,2025) and I use flutter off and on. Went to use it yesterday  Feb. 27, 2026 and I couldn't get passed the you have to upgrade screen. I went back to the login screen and tried the forgot my password option to see if I had an account at all and it never sent me a reset link. I confirmed with my wife that the payment was paid on the 29th so now I am waiting for someone at flutter flow to respond. Looks like it will take some time Has anyone been contacted from flutter flow on these matters? This is the downside of subscription based software. Software as a Service until it goes away!

**Comment by jnm3** [comment]
It's interesting! I submitted an email to support and didn't get any feedback at all that they received the email. Any idea as to the number of lock outs? Interesting too that some are downgraded and as for myself I can't get past the upgrade screen.

**Comment by jnm3** [comment]
So here is my take on what happened. From my point of view (The client/customer/user) Stated above (paid client/customer/user) the popup screen when I went to login talked about down grading or upgrading to a growth plan but that is not made clear on the presented screen. Support was MIA for the three days nothing! Then at 12:02 around midnight I get this email 
"This is Danny from the Support Team.

I hope you're having a great day, and thank you for reaching out to us!

My sincere apologies for the delayed response over the weekend — I truly appreciate your patience.

I’ve checked your account on our end, and I can confirm that it is still active. I just wanted to follow up and see if you’re experiencing any specific difficulties.

Could you please let me know exactly what’s happening on your side? The more details you can share, the better I’ll be able to assist you.
I’m here to help and looking forward to your reply.

Warm regards,
Danny
Support Team"
I sent the screenshot and what I did. If you are an active paying customer and get this message "Users with a free personal plan can have... Now what is going on??? I went to the browser and to flutterflow.io and logged in and got the same thing. 
To me it looks like my paid account is gone! Now here is why I say that - I then went back and instead of logging in I entered forgot password to see if I still had an account! and no reset password email.   
Then just boldly go forward still confused and frustrated which programmer know that is not a good combination (mistakes are in that frame of mind) I don't know what plan I was on but now I on a much high costing plan with team that doesn't work until you pay for other seats???? Anyway Thanks Danny! But in the future reach out to me or others to see if the popup screen makes sense to the customer I sure it made perfect sense to the person that wrote it but, Understand as a programmer the first thing I think about is what I can loose if I click on that button only two will be converted to team! What! What about all the other projects! See that's what comes to my mind. I lost development time. Yes I am retired however time is more valuable now then ever. This statement will make sense when you realize it. Poorly worded interfaces are never a good thing. I will let it go here hope this helps someone going forward.       Yes I did get access to the rest of my projects.
But think about this next year when I go to renew my account payment will be $960 I paid $575 last Sept. and can't use the team feature the way I understand it now! (again maybe poorly word, don't know) but I will have to see what else I will lose if I downgrade?  I like FF very much and have high hopes for it! But much more is needed that sadly I am not able to express here. 
Regards
