### ISSUE TITLE
API from Heroku does not work on FF web version

### ISSUE THREAD

**Issue by olinoleum** [FlutterFlow/flutterflow-issues#700]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have API (get data from OpenAI). API is on Heroku, and when I use it in Test Mode - it works. When using in Web version it does not work. Below img from chrome inspector
![image](https://user-images.githubusercontent.com/11770806/229168803-7b94288d-3d4f-4f92-b3d1-0c90e408ff36.png)

### Expected Behavior

That API works also in Web version - you submit URL in bottom sheet and it retunrs summarisation

### Steps To Reproduce

1. open https://readablet.com/ in chrome
2. click + icon in navbar
3. submit link to any article in bottom sheet' textField
4. click 'Summarise' button
5. check code inspect in chrome

### Bug Report Code

IT4khvHlz5R1ocdD7qXpbcBsiikWG0glTLJEoetxc0gbfe/4PJYLd8nOVExpTb2zaH1cOFqbkn0JwNrWj+LxIPYEaBOuf7Z9yIdqbhPPbHKmMpSrC7rhf3FTPNxUFWqg0LeFkBJRCNpZV1oNwU2mNt6Uaz6Cf9qOYwx5e6fDbOY=

### Context

Want to build app for web articles summarising using OpenAi

### Additional info

project: https://app.flutterflow.io/project/readablet-rqrr0c

### Environment

```markdown
- FlutterFlow version: v3.1. (released Mar 31, 2023)
- Platform: Web
- Browser name and version: Chrome Version 111.0.5563.110 (Official Build) (arm64)
- Operating system and version affected: Ventura 13.2.1
```

**Comment by olinoleum** [comment]
Asking API hosted on Google Cloud cause same problem, like this API
https://testapi-382321.uk.r.appspot.com/hello

i.e. this one worked well with FF https://rapidapi.com/gaurmanojkumar530/api/text-analysis12

we say only about web version. on mobile app all APIs works well

**Comment by olinoleum** [comment]
are you alive?

**Comment by agreaves** [comment]
Hi @olinoleum, thanks for the report! This is because the Heroku server you have configured does not allow Cross Access Resource Sharing (CORS). In the API Advanced Settings, it is configured to use a Proxy for Run/Test mode, which is why it succeeds there. However, in order to make it work in production on Web, you will need to do one of the following (in my recommended order):
- Configure the Heroku app to allow CORS (e.g. add a header for `header("Access-Control-Allow-Origin", "*")`).
- Deploy the API as a Private API in FlutterFlow using Firebase
- Configure a Proxy similar to the one we provide for Run/Test mode ([see details here](https://elements.heroku.com/buildpacks/rob--w/cors-anywhere))

Hopefully one of these options will work for you. I'm closing this issue in the meantime as it's not directly a FlutterFlow bug but please feel free to respond if you have any further questions. Thanks!
