### ISSUE TITLE
APK constantly crashes

### ISSUE THREAD

**Issue by iqyu-tip** [FlutterFlow/flutterflow-issues#754]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I have downloaded my APK from flutterflow and installed it on my Samsung Note 10+ which uses Android 12 with all the  latest updates.
My app is simple.  It does not use any custom widgets or custom code.  It only uses flutterflow widgets.  Also, I do not use any logic or databases in my app.  I am very disappointed because I have spent the last few months  building my app, but it constantly crashes  on my phone.  It crashes so much  that it  is actually unusable as it is! :(
My project has no warnings or errors and the run view in the chrome browser works fine and never crashes.  Only the  APK version crashes.

### Expected Behavior

I  am expected the app  not to crash on my phone.

### Steps to Reproduce

download apk and try to run on your android device.

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code

ITFThuXhuI9PruEB+Kr9KcdaimURI0MBX+Y3iuxvGBE3fYj3EO0Uds7UaXddX8uWS25mIFGLvE0d+vDJht/PEvkqCzCuf71607hAbQ7wWlm7RbXRCJDpXnB5GZ9VIHK9y7SC3SJDPbJsSXwC70+Lcq3qNleeY8aSfxBlZ7vfcPo=

### Context

I am trying to create a usable android app.  I have not been successful.

### Visual documentation

nothing visual to report.  The app suddenly closes for no apparent reason.  There are no warnings or error codes.  The  app never hangs.  It just immediately closes without warning.  It happens randomly.  Sometimes it closes when no actions have even been performed.  Sometimes it closes right after any random action is performed on the app.

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: android 12 with latest updates
- Browser name and version: chrome Version 112.0.5615.49 (Official Build) (64-bit)
- Operating system and version affected: windows 10 pro
```

**Comment by hariprasadms** [comment]
Hi @iqyu-tip - I just tested the app Apk in a latest android emulator. It crashed 2 times out of 5 trials. Below the app log when it was crashed. 

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/17435678/231700775-292ed64b-0d04-440a-be31-2faca2e7b557.png">

Crash happened mostly while navigating to below page. 

<img width="364" alt="image" src="https://user-images.githubusercontent.com/17435678/231702362-057a3c39-f50f-4fe4-a310-7a691089b70e.png">

I see this out of memory exception. In general, there are several factors for app crashes while moving between pages. I believe animation may be the issue in your case. I see that most of your pages have animations. When disposing of the widgets, all of those animation controls should be closed otherwise it can cause memory leak. However, this is just my guess and not really sure what could be the issue at this point. 

I suggest downloading multiple ( more than 2 ) apk files and running them on devices. Analyze the consistency of app crashes and update the issue with app crash information. From this point, we can look into this issue. 

<img width="1523" alt="image" src="https://user-images.githubusercontent.com/17435678/231703817-e68097bd-fe25-42ca-b3c3-6e4fc44a573b.png">

**Comment by iqyu-tip** [comment]
Thanks for this information.
How do I do what you suggest on flutterflow to fix the issue?
Do you have docs or a wiki on this issue?

**Comment by shelpert** [comment]
Hello,

I'm fairly certain that the issue is not with animations in the app but instead the fact that this page has many widgets that use a lot of memory. The `VideoPlayer` and `PdfViewer` widgets are very memory intensive and this page has 10 `VideoPlayer` and 5 `PdfViewer` widgets. I would recommend replacing these with `Image` widgets that show a thumbnail or gif, and then adding on tap navigation to a page where you use the `VideoPlayer` or `PdfViewer` widget to show the actual file.

Since this issue seems to be project specific, this is classified as a support request and will be closed. Please use chat support or contact support [at] flutterflow.io

**Comment by iqyu-tip** [comment]
Thanks for this information!

**Comment by iqyu-tip** [comment]
Hi Shelpert,
I am trying to run project iqyu_web in flutter, but  I am getting the
following errors in vs code:

$ flutter run
Launching lib/main.dart on Chrome in debug mode...
../../.pub-cache/hosted/pub.dev/go_router-3.1.0/lib/src/go_router.dart:22:44:
Error: The class 'NavigatorObserver' can't be used as a mixin because it
isn't a mixin
class nor a mixin.
class GoRouter extends ChangeNotifier with NavigatorObserver {
                                           ^
lib/flutter_flow/nav/nav.dart:41:13: Error: Method not found: 'HomeWidget'.
          : HomeWidget(),
            ^^^^^^^^^^
lib/flutter_flow/nav/nav.dart:59:17: Error: Method not found: 'HomeWidget'.
              : HomeWidget(),
                ^^^^^^^^^^
lib/flutter_flow/nav/nav.dart:64:45: Error: Method not found: 'HomeWidget'.
              builder: (context, params) => HomeWidget(),
                                            ^^^^^^^^^^
lib/flutter_flow/nav/nav.dart:69:45: Error: Method not found: 'AboutWidget'.
              builder: (context, params) => AboutWidget(),
                                            ^^^^^^^^^^^
lib/flutter_flow/nav/nav.dart:74:45: Error: Method not found: 'TermsWidget'.
              builder: (context, params) => TermsWidget(),
                                            ^^^^^^^^^^^
Waiting for connection from debug service on Chrome...             21.0s
Failed to compile application.

I am not sure where to go from here.  I tried what your help docs said,
which was ....
I'm having issues running the downloaded code inside of Android Studio/VS
Code.

Make sure to run the following commands in the terminal:

flutter pub get
flutter packages pub run build_runner build --delete-conflicting-outputs

But this did not resolve this issue. Also, when trying to execute that
second command line, I get the following message: Deprecated. Use `dart
run` instead.
Could not find package "build_runner". Did you forget to add a dependency?

How do I overcome these errors?

Thanks,

Steven

**Comment by iqyu-tip** [comment]
Please study this thread and let me know how  I can overcome this issue:

https://community.flutterflow.io/c/discuss-and-get-help/compiling-project-in-flutter

Thank you!

**Comment by shelpert** [comment]
Hello,
Can you try downloading your code again? I just did it and did run into any issues, except that your nav bar has too many items on it. You can either reduce the number of items on your nav bar or try a different style, I'm not sure what the limits are on the other packages but `FloatingNavBar` can only have 5 items.

**Comment by iqyu-tip** [comment]
You are looking at the wrong project.  I have no navbar on the project  I
am talking about.
The  project  is called iqyu_web.  Please check again.
Thank you!

**Comment by iqyu-tip** [comment]
Good news.  Finally got it  to compile using FLUTTER  v3.7.12

**Comment by iqyu-tip** [comment]
Hello!
I  am trying to use the flutterflow cli to  export  my  r5_iqyu  project.
I keep getting the error "project not found"  Do you know why?   I am
following all  these instructions...

FlutterFlow CLI  <https://pub.dev/packages/flutterflow_cli#flutterflow-cli>

FlutterFlow CLI client. Currently it only allows exporting code from
FlutterFlow.
API Token  <https://pub.dev/packages/flutterflow_cli#api-token>

API access is available only to users with active subscriptions. Visit
https://app.flutterflow.io/account to generate your API token.
Installation  <https://pub.dev/packages/flutterflow_cli#installation>

dart pub global activate flutterflow_cli
Usage  <https://pub.dev/packages/flutterflow_cli#usage>

flutterflow export-code --project <project id> --dest <output folder>
--[no-]include-assets --token <token>

Alternatively, instead of passing --token you can set
FLUTTERFLOW_API_TOKEN environment
variable.

**Comment by iqyu-tip** [comment]
I finally figured out that the PROJECT ID is nowhere to  be found on your
site.

**Comment by iqyu-tip** [comment]
Thank you.
A new user would spend a  LONG time, like I have, to figure that  out about
both pieces of information.  PLEASE place it in a PROMINANT place on
flutterflow.io that is obvious to users such as at the top of the site
where it would read:   PROJECT-ID:   88fjx822
as an example, perhaps RIGHT NEXT TO the  PROJECT NAME.   Also, please
NOTIFY USERS DURING THE DOWNLOAD CODE ACTION of your WEBSITE, that
the DOWNLOADED CODE WILL ONLY WORK WITH THE PUBLISHED VERSION OF FLUTTER
THAT IS ALSO POSTED AT THE TOP OF YOUR SITE.
Thank you!
