### ISSUE TITLE
Navbar "Back" button doesn't work any longer

### ISSUE THREAD

**Issue by ExPrLtd** [FlutterFlow/flutterflow-issues#799]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

clicking/tapping the back button on a new, blank default page no longer works

### Expected Behavior

Tapping/clicking on the "back" icon redirects to previous page

### Steps to Reproduce

1. Create a new page
2. Navigate to new page
3. Tap/click "back" icon

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT40kPLqy4hJpbxD7arqcvlahio5KVh9bLg7j+1BaCgoF5jpD7MAdvXsYlhoXemmY1FIMESmmjsdp/DShvDpM8AnOSyWGYhzwqV2Sgvyczite5OBCZOKVHNfEd1MJnKw0p6JhRNSNvVoSF4G2lOQN9yRdBTaQpDUImdISq/LZO4=

### Context

Go to previous page in an app

### Visual documentation

<img width="418" alt="image" src="https://user-images.githubusercontent.com/118094992/233696270-fdd95b01-33ef-49f7-9caf-e6bffcf5f8d0.png">

### Environment

```markdown
- FlutterFlow version: 3.1
- Platform: iOS
- Browser name and version: Brave Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (arm64)
- Operating system and version affected: MacOS Ventura 13.3
```

**Comment by hariprasadms** [comment]
Hi, @ExPrLtd - I have tested it and it works fine. I do not see you have set up a blank project with showing the issue and details. The above given bug report code is from actual project and we are not sure in which page you are seeing issue. I suggest setup a blank project with re-producing the issue in the project and share bug report code of the same project.  Considering the the feature working fine I am closing the issue with not able to re-produce.

**Comment by wednesdei** [comment]
I would like to confirm that this issue is affecting me in a blank project as well.

Here is the bug code, but I would suspect that it will still work fine for you:

IT40lsn1z4pNj7xH15CBaPlVgmA5JkAibJEW09ZRaCosfZT2BLMcec/RVERpZN+qTHNDPmKWr2oW0vzuufOeO/FePTqVQaI4zJB+URbzUki6SoyQFJWvP0dBO8RQC1Se1MKFhhMkLbN1ZVY/w3GuC+u9bB3YNITtPFgSD6/LZO4=

Are you guys running latest, or prod, when you are testing these issues, like, what's your current configuration if its all working correctly? Do you use a separate browser dedicated only to testing, where your credentials are the same as a normal subscriber, and your browser session is the same thing a normal subscriber would have, with the same access permissions of a normal subscriber, so that you are running the exact same environment that we are running when you attempt to reproduce? 

- FlutterFlow version: ?
- Platform: ?
- Browser name and version: ?
- Operating system and version affected: ?
