### ISSUE TITLE
because [appname] depends on intl 0.18.0, version solving failed

### ISSUE THREAD

**Issue by rossrossp** [FlutterFlow/flutterflow-issues#892]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

I am trying to run/build my code with Xcode.
When running `flutter pub get` or `flutter run`, I see the following error:

```
Because [appname] depends on flutter_localizations from sdk which depends on intl 0.18.0, intl 0.18.0 is required.
So, because [appname] depends on intl 0.17.0, version solving failed.
```

I have tried editing the pubspec to upgrade intl to 0.18.0, but then I see the following error:

```
Because wildya depends on firebase_auth_web 5.2.0 which depends on intl ^0.17.0, intl ^0.17.0 is required.
So, because wildya depends on intl 0.18.0, version solving failed.
```

Note, I have just downloaded the code and tried to run it, and have made no custom code or configuration changes.

### Expected Behavior

I would expect these commands to complete successfully and my code to run.

### Steps to Reproduce

1. Download code
2. Navigate to root folder of code
3. Run flutter pub get

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4ozMrl8ZRJochE1q6JK+9ajSQsQmU1Rp0r0cpBZywgfZzzBLN/fPfQPxZBUu7mYXNpeWKmp14f0/vIvtnQFfAnCz6tRYBb+s1iaQ//WliiMqWTF7m8ZXElJ9pWGX6FyKWvuxIlVchpSmQk2mC6e++UYATsJLrsPUQ4Sq/LZO4=

### Context

I cannot build my code to deploy to the app store

### Visual documentation

![image](https://github.com/FlutterFlow/flutterflow-issues/assets/6325131/e46d1b25-08b0-420d-9dfa-7ee459211de3)

### Environment

```markdown
- FlutterFlow version: 3.1 - Flutter 3.7.12
- Platform: iOS/Android
- Browser name and version: N/A
- Operating system and version affected: macOS 13.0 (22A380)
```

**Comment by hariprasadms** [comment]
Hi @rossrossp - Thanks for submitting the issue. Could you please confirm, can this project build in both test and run mode? and did you try deploying through FF mobile deployment? Please confirm these details. 

It is quite hard to explore the issue because you are attempting to build the project outside of the FF editor. Package versions that comes with project code have been thoroughly tested and confirmed for compatibility with all of FlutterFlow's features and widgets. Therefore, the issue that you are experiencing locally may also be caused by your local Flutter version. Therefore, So I would suggest double check your local Flutter version and try to build again. I hope this can help you to solve the error you are facing. Thanks

**Comment by rossrossp** [comment]
Hello @hariprasadms,

Yes, the project can be built in both test and run mode.
I haven't tried deploying through FF mobile deployment, as it requires the next subscription tier.

I just tried upgrading my flutter via `flutter upgrade`, (it was 3.0.x, it's now 3.10.1), but I still see the same issue.
FlutterFlow lists the flutter version as 3.7.12, but as it's not worked on two local flutter versions, I doubt it's that.

I hear you that it's difficult to pin down as I'm building outside of the editor, but all I've done is download the code and try to run it. It seems like there is a dependency conflict which is beyond my control.

**Comment by bozau** [comment]
I'm also having this issue, my Flutter SDK is 3.10, I'm entirely unable to resolve the issue, will happen with a completely new project pushed to a GitHub repo and attempt to build.

**Comment by bozau** [comment]
> Hi @rossrossp @bozau Can you please try below combination version and try how it works.
> 
> Flutter 3.7.10 • channel stable • https://github.com/flutter/flutter.git Tools • Dart 2.19.6 • DevTools 2.20.1

Hi @hariprasadms ,

So just to make sure you've got as much visibility into environment setup, I'm using Flutter 3.7.10 via Flutter Version Manager (FVM) (because I don't enjoy dealing with env var's).

Output from FVM for the app;
```
Flutter 3.7.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 4b12645012 (6 weeks ago) • 2023-04-03 17:46:48 -0700
Engine • revision ec975089ac
Tools • Dart 2.19.6 • DevTools 2.20.1
```

And setting the FVM for the project to use 3.7.10 and executing `fvm flutter run` does execute the application within the flutter emulator for android.

So it appears to be **working** as it should for a new project from GitHub, might be a good idea to add the use of FVM (or similar) to doco's, as I expect some developers may not be using FlutterFlow for some projects (pre-existing etc) and use 3.10.1, as it is on the stable channel now.

I noticed that a number of packages are older (not that that's a specific issue at at this time), but if we wanted to add some additional custom code for example that required newer package features (e.g. go_router functions that we might want for some reason), would we need to put in a request for upgrading it?

Cheers.

Boz.

**Comment by hariprasadms** [comment]
Hi @bozau - Sorry for the delayed reply to your last comment. Since we keep package versions that take into account all FF platform functionality, it is currently not possible to update specific packages. We have plan to automate package update process soon. I appreciate your advice. We definitely take into account your points.
