### ISSUE TITLE
Google Play Store Deployment

### ISSUE THREAD

**Issue by Muth80** [FlutterFlow/flutterflow-issues#927]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

Build failed :|
Step 7 script `Build AAB with Flutter` exited with status code 1
![StudyPalz-FlutterFlow](https://github.com/FlutterFlow/flutterflow-issues/assets/117746069/a7579183-ae6a-45cd-bc31-11d37455a559)

### Expected Behavior

To deploy my app to Google Play Store

### Steps to Reproduce

1. Deploy to Play Store
2. Upload KeyStore
3. Upload service account credentials
4. Download AAB
5. Deploy to Play Store

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

https://app.flutterflow.io/project/study-palz-i8gowb

### Context

Am deploying app to Google Play Store 

### Visual documentation

![StudyPalz-FlutterFlow](https://github.com/FlutterFlow/flutterflow-issues/assets/117746069/55c1daea-aa26-4b3e-9727-19cb2d6152e8)

### Environment

```markdown
- FlutterFlow version: v3.1
- Platform:Web
- Browser name and version: Version 113.0.5672.93 (Official Build) (64-bit)
- Operating system and version affected: 19045.2965 
Windows 10 Pro
```

**Comment by Muth80** [comment]
Kindly help

**Comment by hariprasadms** [comment]
Hi @Muth80 - Can you try to deploy one more time and see what error you would get please ?. When App store deployment failing, try to deploy more than once and see the consistence of failures please. Failure can happen due to network issues or services  down at the time of your deployment and etc. Thanks

**Comment by Muth80** [comment]
Let redeploy

**Comment by Muth80** [comment]
This is what i got ![StudyPalz-FlutterFlow (1)](https://github.com/FlutterFlow/flutterflow-issues/assets/117746069/eeeaa4ca-2868-4712-a515-8a8cc12bcaa4)

**Comment by Muth80** [comment]
have redeployed and got this 
![StudyPalz-FlutterFlow (2)](https://github.com/FlutterFlow/flutterflow-issues/assets/117746069/9d30734d-34fb-49b2-8637-215a7cc50e82)

**Comment by hariprasadms** [comment]
Sure we will look into it. Thanks

**Comment by Muth80** [comment]
Hey! An updates?

**Comment by agreaves** [comment]
Hi @Muth80, apologies in the delay for triaging this issue.

This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project and the steps are not reproducible, this type of issue is generally classified as a support request. Please use chat support or contact support [at] flutterflow.io for further assistance, we are more than happy to help you out with it there!

I'm sorry you've been waiting four days already though, so please mention to support that Alex requested we prioritize this issue 🙂

If you do find a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.

Thank you for your contribution!

**Comment by Muth80** [comment]
Will do thanks
