### ISSUE TITLE
Change Column to scrollable crashes FF

### ISSUE THREAD

**Issue by yellowsnowagency** [FlutterFlow/flutterflow-issues#93]
Issue tracker is **ONLY** used for reporting bugs. New feature suggestions and questions should be discussed on Community or submitted through our user feedback form.

Your issue may already be reported! Please search in the [issue tracker](../) before creating one.

Please **thumbs up** this issue if you have also experienced it. You may also add more information if there is something relevant that was not mentioned. However, please refrain from comments that are not constructive, like "I have this problem too", etc.

## To Reproduce (required)

1. page with column with multiple elements (see video)
2. change column to scrollable
3. crash notification
4. workaround -> remove all elements, set column to scrollable, add first sub column and then the second part whihc is a container 

## Screenshots / recordings

https://www.loom.com/share/2a9bd2739f22495d946998df222f6742

## Your environment

* **Bug Report Code:**
* Version of FlutterFlow used: 3.3.4
* Platform (e.g. Web, MacOS Desktop):  Blisk browser & also tried Mac Desktop
* Browser name and version: 
* Operating system and version (desktop or mobile):  MacOS 13

**Comment by agreaves** [comment]
Hi @yellowsnowagency, thanks for the bug report. This is, however, the expected behavior.

This issue occurs when the Column contains a child that is marked as Expanded. Without going into too much detail, Expanded means "take up as much space as is available", but when a Column is scrollable it has infinite space available. This causes the layout to try to render an infinitely sized widget, thus causing a crash.

FlutterFlow detects this crash, and leaves a (only sometimes helpful) note explaining what went wrong. I'm closing this issue for now, but I hope this helps!
