### ISSUE TITLE
Show SnackBar on component

### ISSUE THREAD

**Issue by JosephStalion** [FlutterFlow/flutterflow-issues#946]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

On the following project https://app.flutterflow.io/project/naverny-borshchu-r41q9y, I have a component for rating a restaurant, when the component opens there's a possibility of uploading Pics, which I've activated the "Show Snackbar". 

When I try to upload a picture the snackbar doesn't appear in front of the component, but behind it which means that the user is not able to see if the picture is being uploaded or not 

### Expected Behavior

When uploading a picture through a component the snackbar should be appearing in front of the component and not behind it, so the user can understand if the picture is being uploaded or not

### Steps to Reproduce

1. Create a component with picture uploads
2. Activate the "Show Snackbar" on the picture upload
3. Call the component through a button 
4. Upload a picture
5. See that the snackbar doesn't appear

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

IT4CivLq05NPm7gF+Kryb8Bsgj8sQ2J+RY000sJxZE0cHZPND+x/esnRQFJuZ9OrdghUJUyWjmAJw6yKm9z2UsdeNQ2dc4RJ/rgAEg/iQkWnR8WuBoeWZmpEGshXf0iO4cKzvBRBNsFoLUIR1ziXOPOtQhDfK7rWDmo/MvyHBITXmAfuQ0SLb3kNh1JWeC/v

### Context

This issue is not a critical issue, but it affects because if a user is uploading a pic that is bigger than usual the user has no feedback or is not capable of understanding if the PIC is being uploaded or not

### Visual documentation

https://github.com/FlutterFlow/flutterflow-issues/assets/44088583/4747a73a-6db1-4825-b930-8d33e6770360

### Environment

```markdown
- FlutterFlow version: 3.7.12
- Platform: iOS/Android
- Browser name and version: Microsoft Edge
- Operating system and version affected:
```

**Comment by hariprasadms** [comment]
Hi @JosephStalion - Thanks for supporting. I can reproduce the steps. I can mark this as bug. There is a workaround for this. You can dismiss the bottom-sheet before showing snack-bar. Let if that can help you. Thanks

**Comment by victoriahuang1** [comment]
Hi @JosephStalion , thanks for the report. This issue should be resolved upon the next deploy.

**Comment by diegoserranobst** [comment]
@victoriahuang1 Hi, the bug steel occurring

**Comment by JosephStalion** [comment]
@victoriahuang1 unfortunately the bug is still occurring

**Comment by victoriahuang1** [comment]
Looks like the fix was incompatible with the new Flutter version. Getting it to work will require a lot more work, so we will not be addressing this issue just yet. But it will be on our list of things to do.

**Comment by JosephStalion** [comment]
@victoriahuang1, can you provide a work around of some sort?

Appreciate your effort 💙💛

**Comment by victoriahuang1** [comment]
@JosephStalion there isn't an easy work around. But there are 2 things you can try -- either:
1. make a custom action to replace the snackbar action
2. modify the generated code (off-platform)

Essentially, the issue is there is a `Scaffold` for each page, and the snackbar is getting tied to that `Scaffold`. Bottom sheets (which is where components appear in this case) appear on top of the page, which means the `Scaffold` and the snackbars tied to said `Scaffold` will appear underneath the bottom sheet. You will need to wrap the bottom sheet or component inside of another `Scaffold`, so that the snackbar will get tied to that one instead. If there is a package out there that can do this out of the box, that would be the easiest solution.

**Comment by nev-21** [comment]
Same problem here, please help

**Comment by nev-21** [comment]
Should this issue be reopened?

**Comment by victoriahuang1** [comment]
No, this issue will not be reopened, as this is a non-trivial feature request related to Flutter issues and not a bug.

**Comment by nev-21** [comment]
Ok, thank you for your effort, we'll be waiting for the solution.

**Comment by Krystian95** [comment]
Same of https://github.com/FlutterFlow/flutterflow-issues/issues/563

**Comment by Golicraft** [comment]
That's not an ideal solution. I use bottom sheet for Auth login/register and when an error accours within Firebase it shows a snackbar below the bottom sheet. I'm surprised this hasn't been working more on ... What about when a snackbar comes it moves the bottom sheet up so the snackbar is below? Just a thought.

**Comment by Golicraft** [comment]
Or for example a custom action could be sent when Firebase "fail" it close the bottom sheet? When I think about I might do that myself: Make it so when they click "login/register" it close the bottom sheet so if an error accours it will be shown, otherwise they will be redirected.

**Comment by hamza151081** [comment]
I suggest adding a custom loading widget with a visibility condition based on the "is Data Loading" state. If "is Data Loading" is true, display the loading widget; otherwise, show the initial view of your component. Here a code for a custom loading widget it may help: 

// Automatic FlutterFlow imports
import '/backend/schema/enums/enums.dart';
import '/backend/supabase/supabase.dart';
import '/flutter_flow/flutter_flow_theme.dart';
import '/flutter_flow/flutter_flow_util.dart';
import '/custom_code/widgets/index.dart'; // Imports other custom widgets
import '/custom_code/actions/index.dart'; // Imports custom actions
import '/flutter_flow/custom_functions.dart'; // Imports custom functions
import 'package:flutter/material.dart';
// Begin custom widget code
// DO NOT REMOVE OR MODIFY THE CODE ABOVE!

class CircularLoadingCustome extends StatefulWidget {
  const CircularLoadingCustome({
    super.key,
    this.width,
    this.height,
  });

  final double? width;
  final double? height;

  @override
  State<CircularLoadingCustome> createState() =>
      _CircularLoadingCustomeState();
}

class _CircularLoadingCustomeState
    extends State<CircularLoadingCustome> {
  @override
  Widget build(BuildContext context) {
    return Container(
        width: widget.width,
        height: widget.height,
        child: CircularProgressIndicator(
          valueColor: AlwaysStoppedAnimation<Color>(Color(0xFF017751)),
        ));
  }
}
