### ISSUE TITLE
GoRouter 3.1.0 incompatible with latest stable release of Flutter

### ISSUE THREAD

**Issue by quillifyai** [FlutterFlow/flutterflow-issues#958]
### Has your issue been reported?

- [X] I have searched the existing issues and confirm it has not been reported.
- [X] I give permission for members of the FlutterFlow team to access and test my project for the sole purpose of investigating this issue.

### Current Behavior

The latest stable release of flutter requires intl: 0.18.0, which does not support go_router: 3.1.0. Since FlutterFlow relies on this version of go_router, using the latest stable release of flutter sdk is impossible.

### Expected Behavior

I'd of course expect to use FF on the stable version of the flutter sdk

### Steps to Reproduce

Update your flutter sdk and try to run any FF application that has page navigation

### Reproducible from Blank

- [X] The steps to reproduce above start from a blank project.

### Bug Report Code (Required)

N/A

### Context

I can't use the latest Flutter sdk

### Visual documentation

N/A

### Environment

```markdown
- FlutterFlow version: as of 6/2/2023
- Platform: Any
- Browser name and version: Any
- Operating system and version affected: Every
```

**Comment by hariprasadms** [comment]
Hi @quillifyai - Thanks to you brining this up. Instead of using the most recent Flutter version, we advise you to keep the FlutterFlow compatible version. The recommended Flutter version is tested against all of the packages used in FlutterFlow. We will, however, soon update the FlutterFlow supported Flutter version to the most recent Flutter version. 

Unfortunately, as this is not a bug, we will not be looking into it. I'm making this issue as not a bug. Thanks

**Comment by quillifyai** [comment]
That's what I'll have to do in the meantime, although if FF is not keeping up with the stable version of Flutter, then it shouldn't be advertised that FF is compatible with the stable version of Flutter

**Comment by ahmedtanjim** [comment]
As a developer, I'm very uncomfortable with it. Every time I work on a flatter flow project I have to downgrade the flutter version.
