### ISSUE TITLE
Crashing, Flickering, Rendering Issues Lagging - What's going on?

### ISSUE THREAD

**Issue by cleanspacedev** [FlutterFlow/flutterflow-issues#96]
## Expected behavior (required)
The ability to run the app on iOS, web, and android without crashing, or widgets/rows half rendering and without random screen flickering.

## Current behavior (required)
When clicking on page tabs, or switching in between tabs, the app crashes, and it looks like the screen refreshes but when it does it gets worse with screen flickering, rows and FlutterFlow widgets half rendering.

## To Reproduce (required)
1. Login on web
2.  Click on the tabs to the left and switch between pages
3. Click on the tabs to left and switch pages again
4. Go to the home page and click on the tabs
5. By now your screen should be flickering the app has already crashed and restarted. 

## Context (required)
We are trying to build an app that does not crash and is easy to use. If you go back to last month's builds the app does not crash. Something that has been added/updated/changed is affecting this and causing this behavior. 

## Screenshots / recordings
Here's a video: https://loom.com/share/4f16f4ff510a4b54b78e7ba906b6944a

## Your environment
* Version of FlutterFlow used: Whatever FlutterFlow is using
* Platform Web, iOS, Android
* Browser name and version:  Chrome, Latest version
* Operating system and version Both, Latest version

![Screenshot 2022-11-04 135638](https://user-images.githubusercontent.com/107013961/200044042-44a44409-2aa9-4712-9755-7ed6e39e7a2b.png)

![Screenshot 2022-11-04 134547](https://user-images.githubusercontent.com/107013961/200044083-2597e431-f76d-4ff1-9336-74ea8b9ce3cc.png)

![Screenshot 2022-11-04 134547](https://user-images.githubusercontent.com/107013961/200044177-f3486d74-5a94-41d6-b9de-dd773ad5d620.png)

https://user-images.githubusercontent.com/107013961/200047318-2b07d016-db3c-4555-abcb-036004c0f9eb.mp4

**Comment by katherineqian** [comment]
Hi @cleanspacedev,

Can you please share a bug report code with us to help triage this issue? You can generate this by going to the widget tree, right clicking, and selecting “Generate Bug Report Code”.

**Comment by cleanspacedev** [comment]
@katherineqian I edited the video and added it.

**Comment by katherineqian** [comment]
Hi @cleanspacedev, 

While I can reproduce this behavior on web and agree that this is an error, it appears that this is not a general bug that is applicable to all users and is specific to your project. 

This issue tracker is intended for general bugs that are applicable to all users. Because this error appears to be specific to your project, this is classified as a support request and will be closed. Please use chat support or contact support [at] [flutterflow.io](http://flutterflow.io/) for further assistance. This will be the best way to get your issue resolved.

If you do end up finding a specific reason for the issues you are encountering in your project, please don’t hesitate to open a new bug report with the relevant steps to reproduce.
Thank you for your contribution!

If you are another user who is experiencing the same issue, please leave a comment, and we will be happy to re-open the issue and re-investigate.

**Comment by davidflutterflow** [comment]
We talked about this in support and found the cause.
@cleanspacedev Will explain in a more extended version.
The short version is: the issue was the navigation actions and the "allow back navigation" option, simply we were keeping all pages in the memory.
